### ISSUE TITLE
2.15.00 beta Preview for Fixed File Size Has Wrong Bitrate

### ISSUE THREAD

**Issue by kphipps** [RandomEngy/VidCoder#10]
On the 'Video' tab, when I use 'Target Size', it seems that it is trying to make the 10-second preview hit the target size specified for the entire video. For example, if I set 340MB for the target size, the preview clip will have a bitrate of 247817, so the quality of the preview isn't representing what the end result for the whole file will be.

I believe this was happening in the last couple of beta releases as well.

**Comment by RandomEngy** [comment]
Fixed in 2.16 Beta.
