### ISSUE TITLE
webm preset

### ISSUE THREAD

**Issue by nwgat** [RandomEngy/VidCoder#100]
would been nice if there was a webm preset that included vp9/opus and what type of encoding settings do vp9 use? is it --best or is it -deadline? or is it --realtime?

atm webm mux is missing :(
it can be crazy simple to add as webm is just a subset of the matroska spec
http://www.webmproject.org/docs/container/

currently there is no opus in handbrake/vidcoder so you can default to vorbis instead until opus is ready

and webrtt in webm would been neat https://w3c.github.io/webvtt/

**Comment by RandomEngy** [comment]
If webm muxing is added, it will be by the HandBrake team that owns the core encoder that VidCoder uses.
