### ISSUE TITLE
Burning subtitle problem "Apply filters before rendering subtitles"

### ISSUE THREAD

**Issue by baiguke2019** [RandomEngy/VidCoder#1007]
The 1920x800 resolution video is filled with black borders. How to customize the subtitle position when burning subtitles? Make subtitles burn in black border
![123](https://user-images.githubusercontent.com/44437213/160340287-1151c46e-9c43-4cb7-9770-c01104e835fd.png)

**Comment by RandomEngy** [comment]
There isn't any way you can customize where the subtitles are rendered; it's not an option in the HandBrake API that VidCoder uses.

When you say that there is a black border in the video, did you mean during playback or actually part of the video picture? You might be able to disable cropping or add some padding and try and convince it to render subtitles below the picture.

**Comment by baiguke2019** [comment]
> There isn't any way you can customize where the subtitles are rendered; it's not an option in the HandBrake API that VidCoder uses.
> 
> When you say that there is a black border in the video, did you mean during playback or actually part of the video picture? You might be able to disable cropping or add some padding and try and convince it to render subtitles below the picture.

Video fills with black border so that subtitles burn in black border

**Comment by RandomEngy** [comment]
I don't know what you mean by that.

**Comment by baiguke2019** [comment]
Thank you for your answer
