### ISSUE TITLE
Vidcoder margin "smarter"

### ISSUE THREAD

**Issue by joschi642** [RandomEngy/VidCoder#1009]
### Feature details

Some films have the station logo above the actual film. Vidcoder then cuts off the bottom margin, but the logo remains at the top. I would like to have an option that copies the larger margin to up (or down). The logo is then cut away without having to set it manually.

Bad English? Google translator ... ;-)

**Comment by RandomEngy** [comment]
I can see how that would be useful to you but I think it would be a little bit too specialized to add it in as a feature for everyone.
