### ISSUE TITLE
No supported DVD player?

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#101]
With a DVD open in v2.30 beta x64 and a title selected, the Preview player gives me the message "A supported DVD player could not be found. Install VLC or MPC-HC to use this feature" when I hover over the (greyed out) Play Source button. I do have VLC 2.2.4 installed and it is selected in options/general/Preferred DVD player. My VLC does play DVDs on its own. I don't have MPC-HC installed.
![vc dvd player error](https://cloud.githubusercontent.com/assets/16139156/16354892/69a1643e-3ae9-11e6-9344-02091644eb5a.jpg)

**Comment by iamjaydear** [comment]
I just d/l'd MPC-HC and installed it. Selected it in the VC options. Same outcome.

**Comment by RandomEngy** [comment]
VidCoder looks for a registry key to see if it's installed:

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VideoLAN\VLC`

I just installed VLC through the default Windows installer and VidCoder picks it up without any issues. Do you have that registry key? Are you running 32 bit or 64 bit? Did you do a portable install of VLC?

**Comment by iamjaydear** [comment]
Turns out I don't have that key! VLC was installed in the standard way as a normal 64 bit program. Anyway, I added it in Regedit with a bit of guesswork for what the data might be by looking at other prog's in that area. I used "C:\Program Files\VideoLAN\VLC\vlc.exe" and it worked *yay*. The MPC-HC prog also has no key, but I didn't push my luck. I realise that I could have just uninstalled and re-installed VLC, but I hate losing my settings, and since MPC-HC installed without putting an entry in there I figured that something must be blocking them (what, I don't know?). Weird. I'll probably just get rid of MPC-HC.

**Comment by RandomEngy** [comment]
Ahh, looks like VLC has a 64-bit version now. Will have to update to detect that as well.

**Comment by iamjaydear** [comment]
OK, I get it! There's MPC-HC x64 too. Just note that neither of them had put entries in that key on my PC and they were normal 64 bit version installs, not portable. The only thing I could point to as a possible stuff-up on my part might be that my firewall s/w (Windows 10 Firewall Control) blocks installers and I have to 'enable all' during the install unless I remember to 'allow all' before I start. The 'enable all' pause usually only causes a few seconds delay during an install and there's usually no error notifications afterwards - but who knows?

**Comment by RandomEngy** [comment]
Also found that MPC-HC also changed its registry key location. Tricksy hobbitses. VidCoder 2.31 Beta should detect both VLC and MPC-HC now.
