### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by remedy78** [RandomEngy/VidCoder#1010]
### Feature details

Hello,
The program is not in Croatian.
I can try to translate it.
Please write how to do it.

Best regards,
Mario

**Comment by RandomEngy** [comment]
I just added the Croatian language in the Crowdin project: https://crowdin.com/project/vidcoder/hr . You should be able to translate there.

**Comment by remedy78** [comment]
The Croatian translation is finished.


Best regards,
Mario


Shutterstock Portfolio
<https://www.shutterstock.com/g/Mario+Toth?rid=170667580&utm_medium=email&utm_source=ctrbreferral-link>

______________________

Napomena:
Ova elektronička poruka i njeni prilozi mogu sadržavati povjerljive i/ili
povlaštene informacije, a namijenjena je isključivo za upotrebu naznačenog
primatelja. Ako ste ovu poruku primili greškom, molimo Vas da o tome bez
odlaganja obavijestite pošiljatelja, da uništite izvornu poruku i njene
priloge i bez odlaganja poruku i njene priloge izbrišete iz Vašeg sistema.
Neovlaštena uporaba, distribucija, otkrivanje, umnožavanje ili izmjena ove
poruke je zabranjena.

Disclaimer:
This e-mail message and any attachment may contain confidental and/or
privileged information and is intended for use by the indicated addressee
only. If you have received this message in error, please notify the sender
immediately, destroy the original message and any attachment and delete
this message and any attachment from your system. Unauthorized use,
distribution, disclosure, reproduction, or alteration of this e-mail
message is forbidden.


sri, 27. tra 2022. u 04:57 David Rickard ***@***.***> napisao
je:

**Comment by RandomEngy** [comment]
The Croatian translation has been added to version 7.15.
