### ISSUE TITLE
2.31 Beta Intel QSV

### ISSUE THREAD

**Issue by sharer777** [RandomEngy/VidCoder#102]
Latest beta (2.31) doesn't allow Intel QSV encoding...forced to download old version (2.30).

**Comment by RandomEngy** [comment]
I don't have hardware that supports QSV encoding. Can you try and see if the latest HandBrake nightly works for you? It's likely an issue with some recent HandBrake changes.

**Comment by sharer777** [comment]
Yep...you are right...latest HandBrake Nightly crash as soon as I hit the encode button. I confirm that Vid Coder 2.30 Beta works fine.

**Comment by RandomEngy** [comment]
Cool, you should open an issue on the HandBrake GitHub site about that and include a log for them.

**Comment by sharer777** [comment]
Thanks for your attention but I will stick with 2.30 version until problem fix is reported in the release notes of the nextt versions. Just thought you wanted be aware of the "problem".

Thanks again for your time.

**Comment by RandomEngy** [comment]
They might not know about it or be fixing it yet; I don't see any issue like that on their tracker. Would be the most helpful to file the bug if you'd like it to be fixed.
