### ISSUE TITLE
[7.15] Picker path recursive crash

### ISSUE THREAD

**Issue by Asterchades** [RandomEngy/VidCoder#1027]
### Problem Description

The Picker is allowing invalid paths to be set. When this invalid filename includes a drive letter but no colon (eg "T\") this causes VidCoder to crash - without presenting an error - after adding such an invalid entry to the job list. Due to the job list being maintained between sessions this prevents VidCoder from being used again unless the settings file is removed, restored to an older backup (if you have one), or edited via 3rd party tool to remove the job queue.

Other invalid path configurations, such as adding an extra colon, using other invalid characters (*, |, ?, ", etc), or removing the drive letter (with or without the colon remaining) are also permitted, however they will be added without issue to the job list and simply result in "Output path is not valid" dialogues or errors in the encoding window rather than a recursive crash. Attempting to enter invalid filenames in the Picker will be permitted but sanitised in the output filename.

### What version of VidCoder are you running?

7.15

**Comment by Asterchades** [comment]
Okay, I've been able to narrow it down further. It's a lot more specific than my late-night testing had suggested it was but still easy enough to accidentally trigger with a simple typo.

In order to get it to queue the invalid filename you have to either drag-and-drop more than one file, or use either of the multiple Enqueue features (even with only one file). These three methods will bypass the individual checks and simply add invalid paths to the job list.

Two specific conditions must then be met:

Firstly the Picker must contain a path without a colon. Any other invalid path will be silently added but cause no issues (until you try to run the encode, at which point an error is give) but missing that colon will allow the recursive crash. I've been able to reproduce it with "T", "T\", T*\", "T\Temp\", and "T\Temp\123456789\".

Secondly the file name also needs to be of a minimum length - if a subdirectory is specified (eg: T\Temp\) the file name (not including extension) needs to be at least 23 characters long, while if no subdirectory is specified it must be at least 29 characters long. Deeper paths do not change the file name length requirement (eg: T\Temp\123456789\ still requires 23 character filenames).

Those extra characters don't need to be in the source file name - so long as the output name is of the correct minimum. You can manually assign a name with the Output name format section to be of the appropriate length. In other words, setting the name format to "12345678901234567890123456789" (29 characters in length) will cause any file added to trigger the crash so long as the colon is absent.

Obviously no sane person would set that as their name format but the possibility of appropriately long input names exists allowing the {source} flag to pass it through on its own (eg "12. The Beast from the Belly of a Boeing.mp4" at 40 characters, which is season 1, episode 12 of The A-Team) or by way of extra notation either manually specified or from other flags.

**Comment by RandomEngy** [comment]
Should be fixed in 8.3 Beta.
