### ISSUE TITLE
Allow VidCoderCLI to send folders to VidCoder.exe

### ISSUE THREAD

**Issue by DebugDax** [RandomEngy/VidCoder#1031]
### Feature details

Currently if you pass a directory to VidCoderCLI.exe, it will open VidCoder.exe and try to import but it does not work. If you drag a folder onto VidCoder.exe it will recursively scan the folder and import everything, then when encoding it will create the folder structure.

`VidCoderCLI.exe encode -s "D:\Pending\TVShows" -preset "H.265 QSV 1080p" -picker "CustomAuto"`

Can you add support so that VidCoderCLI can accept directories with the -s flag and send them recursively to VidCoder.exe to create folder structure on output?

**Comment by RandomEngy** [comment]
I'll add this support in the next Beta release.

It was a nice refactor where I got to delete some mostly-duplicate code. :)

**Comment by RandomEngy** [comment]
Added in 8.3 Beta.
