### ISSUE TITLE
app in Windows Store is not updated

### ISSUE THREAD

**Issue by Marciuz180990** [RandomEngy/VidCoder#1033]
### What were you doing when VidCoder crashed?

Hello, the versions in the windows store no longer open, at least the beta one, while the stable one is not updated

### Crash details

```text
Hello, the versions in the windows store no longer open, at least the beta one, while the stable one is not updated
```

**Comment by RandomEngy** [comment]
The Windows Store version is no longer supported. I was unable to get help for Desktop Bridge to work with .NET 5. The new installer versions have easy updates though.

**Comment by Stephan-P** [comment]
In order to prevent confusion, I suggest that you withdraw VidCoder from the Microsoft Store then

**Comment by RandomEngy** [comment]
Good call. I thought I had done that already but apparently not. They are taken down now.
