### ISSUE TITLE
Scanner Freezes when importing multiple ISO files

### ISSUE THREAD

**Issue by kanjieater** [RandomEngy/VidCoder#1034]
### Problem Description

When using the "enqueue multiple files" and selecting more than one, the Scanning window shows, shows progress, then freezes - effectively making it so that you can't add multiple files, as they work one by one.

### What version of VidCoder are you running?

8.3 Beta and 7.15 stable

### Encode Log

```text
https://www.dropbox.com/s/xoexoy7gbtgdpsz/Logs.zip?dl=0
```

**Comment by RandomEngy** [comment]
I made a change a while back to make the batch queuing faster by re-using the same scan process. It looks like maybe that could cause an issue in certain cases. I'm able to enqueue multiple ISO files without issue, so there might be something special about those particular ones.

When I get some time I could add an option to disable the scan process re-use, which would make this more stable. Or possibly debug the hang if I could reproduce with the ISO files.

**Comment by kanjieater** [comment]
> I made a change a while back to make the batch queuing faster by re-using the same scan process. It looks like maybe that could cause an issue in certain cases. I'm able to enqueue multiple ISO files without issue, so there might be something special about those particular ones.
> 
> When I get some time I could add an option to disable the scan process re-use, which would make this more stable. Or possibly debug the hang if I could reproduce with the ISO files.

Thanks for the reply. Do you expect this is a regression that I could use another version to get around? 
Do you need me to send you some of the problematic files or do you think you can try to reproduce first on your end?

**Comment by RandomEngy** [comment]
Having the problematic files would help address the root cause. In theory it should not hang at all when re-using a scan process. You may be able to work around it by going to Global Options -> Process and unchecking "Use worker process to encode".

**Comment by RandomEngy** [comment]
I made a fix in 10.2 Beta that resolves a problem where the batch scan would stall if there was a crash in the worker process. This might resolve your issue, or at least let the batch scan complete and report the errors at the end.

Let me know if this works for you.
