### ISSUE TITLE
Encoding failure solution suggestion

### ISSUE THREAD

**Issue by h45251880** [RandomEngy/VidCoder#1037]
### Feature details

I found that if the video encoding fails in vidcoder, upload it to this [this website](https://video-converter.com) to re-encode the original video, and the re-encode video can be successfully converted to other encodings by vidcoder.

Is it possible to use an automatic process similar to this method to deal with some videos that fail to convert in vidcoder?

**Comment by RandomEngy** [comment]
There's a few issues with that approach:
* The quality degrades further when encoding twice
* These sites usually don't like bypassing the website and will try to block you and break your program.
* The sites can disappear without warning, causing maintenance headaches. The only thing that's really stable is a paid API.

The best option here would be to report the failed scan to the HandBrake team and ask them to fix. That way the video is directly encoded quickly and with good quality.
