### ISSUE TITLE
Malwarebytes Anti-Ransomware

### ISSUE THREAD

**Issue by GT40Wins** [RandomEngy/VidCoder#105]
Not sure if it has been reported but Malwarebytes Anti-Ransomware has identified VidCoder-Beta as Ransomware.  Tried to upload screen shot but it failed twice.  In any case it flagged two versions.  One installed on about 5/12/16 and the other a week ago, but flagged today.

**Comment by RandomEngy** [comment]
Did you get the installer from vidcoder.net or the GitHub site? Could also be a false positive.

**Comment by GT40Wins** [comment]
I had 2.30 then after the last round of HandBrake corrections I went to Help in VidCoder clicked Automatic updates and then Check Now where it auto downloaded 2.31 and then installed.  It's been on for a week and was RansomWare flagged a couple days ago. Have 3.31 back on and no alerts at this time.  Remember it alerted on May 12 for probably version 2.28. Anti-Ransomware is a Beta 0.9.15.416 version as well.
