### ISSUE TITLE
EED12 decomb very s-ll-ooo-wwww

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#106]
Version 2.31 Beta x64 is working very well for me thanks, except... I wanted to try out the EED12 decombing and it is very slow. Worker.exe is running at about 0.12% of CPU most of the time, peaking briefly now and then to about 26%. I did some 30 sec preview clips which were also very slow, but the results looked better than 'decomb' or 'yadiff', so I'd like to give EED12 a good tryout if you can speed it up.

I d/l'd and installed HB 0.10.5-1 but it doesn't seem to have EED12, so I can't say if it's HB or VC to blame for the slowness.

**Comment by RandomEngy** [comment]
VidCoder is set up to expose new decomb choices as soon as they're added to the HandBrake core. Looks like it's expected to be slow: http://forum.doom9.org/showthread.php?p=744308

**Comment by iamjaydear** [comment]
I understood a bit of that (really old) thread. Thing is, the processor is on a leisurely holiday when this method is selected.
Reason I tried EED12 is because decomb doesn't seem to be giving as good a result as it used to, but maybe I'm just getting pickier. However, the broadcasters here **are** compressing everything to death these days. Lots of jaggies and compression artifacts to get rid of and I guess they're using interlaced output when they can to further reduce bandwidth.
