### ISSUE TITLE
Brightness changed after converting DVD

### ISSUE THREAD

**Issue by KiriTheGreat** [RandomEngy/VidCoder#1066]
### Problem Description

Hello, i am trying to create a digital copy of a DVD. My problem ist that the brightness is not the same as in the original DVD. The file created by vidcoder seems to have a darker screen. I play both, file and DVD with VLC media player with same settings. The DVD is an old movie in black/white.

This is the file created by Vidcover:
![VidCoder sample mp4file h264](https://user-images.githubusercontent.com/115872395/195980774-d186e6f1-8b90-42fb-9498-9e7dc5810cea.JPG)

This is the same screen running the original DVD
![VidCoder sample original DVD](https://user-images.githubusercontent.com/115872395/195980796-c911356b-bb90-429d-bb37-4e3253459c41.JPG)

The original DVD video files are mpeg-2 codec. The files I convert it with vidcover is mp4 with h.264 codec. Here are some screenshots of my VidCoder settings.
![VidCoder Settings](https://user-images.githubusercontent.com/115872395/195981014-641ef962-f018-464d-8b6a-8a91d0dc12cf.jpg)

I tried several codecs with VidCoder and also different levels of video quality but its always the same. The video created by VidCover is darker than the original DVD. Anyone got any clues how can I fix that?

Many thanks.

### What version of VidCoder are you running?

7.15

**Comment by RandomEngy** [comment]
This would be handled by the HandBrake engine which does the actual encoding. You could ask them for help.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)
