### ISSUE TITLE
Dicky mpeg2 kills VC

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#107]
A faulty mpeg2 file crashed VC ver.2.31beta x64 today. At the problem part of the file VC dropped from 100fps to 10fps and vidcoderworker.exe dropped from 85% to about 0.2% of CPU. I tried to stop the job and got the "Are you sure..?" message to which I clicked Yes, but VC did not stop, tried again, same. Tried clicking Close (top rhs X) which made VC non-responsive to any further interaction, yet the encode kept rolling at 10fps! Eventually resorted to killing VC and restarting Windows. Tried again with same file, same thing happened, but this time I got an exception error and saved a dump file. Just thought you'd be interested that a faulty mpeg2 file could basically kill all control of VC. Incidentally, the resulting 50MB mp4 was unplayable in VLC and PotPlayer. You'll notice in the dump file there's mention of "D:\docs\projects\VidCoder\VidCoder\etc". I did have a USB D: drive in at the time, but that folder tree does not exist there. There was a D: partition on my main drive when I installed VC ages ago, but I got rid of it when I changed the drive to an SSD a few months ago. I've checked the original drive and there is no such folder there either. Curious.
[VC_Exception_160724.txt](https://github.com/RandomEngy/VidCoder/files/380043/VC_Exception_160724.txt)

**Comment by RandomEngy** [comment]
Added protection against this crash in VidCoder 2.32 Beta.
