### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by CryptoFeelinara** [RandomEngy/VidCoder#1074]
### Feature details

I would like a function that man can also insert different soundtracks from a file.

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://github.com/HandBrake/HandBrake/issues/new/choose) to add it.

However, HandBrake's stated scope is to be a transcoder and not a video editor.
