### ISSUE TITLE
Is it possible to let VidCoder pick up more than one external soft subtitle automatically? 

### ISSUE THREAD

**Issue by mpek** [RandomEngy/VidCoder#1075]
### Feature details

When you add soft subtitles manually, they are being added to final file and just play fine. 

Example: 

Add a MKV file to VidCoder:

Testserie (Testseries) S01x01 Der Titel (The Title).mkv

and add external subtitles from the same directory: 

Testserie (Testseries) S01x01 Der Titel (The Title).deu.srt
Testserie (Testseries) S01x01 Der Titel (The Title).eng.srt

(The subtitles are called similiar to video file)

Now, a soft subtitle recognition for batch encoding would be helpful. What do you think?

**Comment by RandomEngy** [comment]
Such a feature would need to automatically determine the language from the sub-extension there. Is it common to have the three-letter ISO abbreviation there?

**Comment by mpek** [comment]
Thank you for considering. 
Three-letter ISO abbreviation would be preferable!

**Comment by mpek** [comment]
@AlexJCarstensen had this idea [here](https://github.com/HandBrake/HandBrake/issues/719) already. 

It's a real PITA having to encode hundreds of files with two soft subtitles when only one ss is being recognized, but I understand if it is a struggle to implement that. Thanks for looking into it.

**Comment by RandomEngy** [comment]
I added this capability in v11.0 Beta. If the language code is recognized, it will pull in the myVideo.lng.ext subtitle file.

**Comment by mpek** [comment]
Great improvement! Thank you very much.

**Comment by mpek** [comment]
I dream of a watchfolder process where you could throw in a series of files and let VidCoder do the rest. Without intervention of the user after setting up the preset and settings in VidCoder. 

If you could add a recognition for forced subs, similar to this, that would let VidCoder set a forced sub to be burned in while importing. 

I simply add a "forced" to the filename like this to the subtitles filenames: 

myVideo.lng-forced.ext

You coud add it as a third option in Picker settings at Subtitles > Burn in > None / First / Forced

If there are two or more "forced" subs available from the video a preferred language should be set somewhere.

**Comment by RandomEngy** [comment]
Is the "-forced" modifier a common standard, or just one that you use?

**Comment by mpek** [comment]
I'm not sure there is a standard yet at all for naming forced subtitles. I just use it to distinguish, as it makes sense to me. What do you think?

**Comment by RandomEngy** [comment]
I think whatever I write should be flexible enough to be useful to any user of VidCoder. If I write it to expect a non-standard format, it be a very useful feature.

**Comment by mpek** [comment]
And what is your suggestion naming forced subtitles then?

**Comment by RandomEngy** [comment]
I don't have a specific suggestion. But I do have standards for what features I would accept into VidCoder, and standards for what I would spend my time on developing. Hard-coding something that picks up a file format that only you use doesn't meet either of those bars.

**Comment by mpek** [comment]
Okay, well the standard is what is commonly used. How do people distinguish the normal from the hearing impaired and forced subtitles? I add "nothing" for normal, "-sdh" for hearing impaired and "-forced" for forced subtitles to the filenames. 
I don't know what ohters use, but perhaps they will let us know in the future in this topic. 
Sadly, that leaves us by not being able to use VidCoder's watchfolder feature with subtitles. 
Anyway, I'm very happy with your solution to be able to add external subtitles automatically!

**Comment by mpek** [comment]
Hey, wanted to let you know that i've found a naming of forced and sdh subtitle files that VidCoder will pick up without changing anything. 

That way you can distinguish them not only by language. 

Still, VidCoder won't tag them as a "forced" or "sdh" subtitle and won't give it that custom name being a "forced" or "sdh" subtitle, but at least it will include them all in batch conversion, separated by language! 


For forced subtitles:

videofilename.forced.deu.srt

For hearing impaired:

videofilename.sdh.deu.srt


**Thanks again for making external subtitles to work with VidCoder.** 


Not sure if this is related to Handbrake core, but will let you know my thoughts on this: 

1. To tag these external subtitles as "forced", "sdh" or "normal" would be nice for playback software or TVs, because in there, you can set the preferred subtitle behavior and make sure which subtitle to show by default or along with which audio language. 

2. To give them even a name in encoded file as "forced", "sdh" or "normal", a user would see directly which subtitle to choose! If there is no name set, language will be shown only. 

These two functions are something you could think about, it would certainly round up the subtitle topic. 

If tagged, a video player software or TV will pick that up and show if set to show forced or sdh preferrably over "normal" subtitles. A "normal" subtitle would be without additional Sounddescription.

**Comment by RandomEngy** [comment]
One more limitation is that the HandBrake core API that VidCoder uses doesn't have the ability to tag subtitle tracks as "forced" or "sdh". There's an option to pick "forced only" out of a subtitle track where some of the subtitles are set as forced, but there's no way to tag the output subtitle with that information.

**Comment by mpek** [comment]
Thank you for further investigating this and explaining the disabilities of the Handbrake API with subtitles.
