### ISSUE TITLE
NVEnc并没有正确的被使用

### ISSUE THREAD

**Issue by StarryNe** [RandomEngy/VidCoder#1096]
### Problem Description

![image](https://user-images.githubusercontent.com/108735960/210177858-e45da6be-c295-40bd-8562-6caf81316bcb.png)
很奇怪，我选择的视频编码器是[H.265(NVEnc]但是我的GPU并没有被软件调用，只有CPU被软件调用。

### What version of VidCoder are you running?

7.15 SquirrelInstaller

**Comment by RandomEngy** [comment]
It's expected that the CPU is still used during the encode. The filters, audio encoding and muxing are still done by the CPU; the GPU handles only the video encoding portion. I'm not sure why it's not showing any activity for your GPU; but an encode log might show something.
