### ISSUE TITLE
Picker vs Preset

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#11]
I'm picking a preset with the picker, but it's not changing in the Preset box under "Encoding", thus the settings in the "Settings" window aren't changing. Am I missing something here?

![picker-vs-preset](https://cloud.githubusercontent.com/assets/16139156/11912792/9a33374e-a6a1-11e5-99f2-b3049c61843f.jpg)

**Comment by RandomEngy** [comment]
I think I may need to rework this a bit. Currently choosing a preset on the picker will apply that preset when adding files in bulk but doesn't affect the preset chosen by the UI currently.

**Comment by iamjaydear** [comment]
It's potentially a very good feature, and one I'm keen to use.

**Comment by RandomEngy** [comment]
Added something to handle this situation better in 2.16 Beta. It now locks the preset on the main UI when set by the Picker.

**Comment by iamjaydear** [comment]
Yes, that's an improvement. 

Could you consider moving the Picker functionality into the Encoding / Preset button? Just seeing all the things that are affected in one place (currently the Picker's window) is very effective, but it is a duplication which must make the coding more difficult. Just selecting an Encoding Preset should be enough to also select *all* the other things such as Destination, Audio, Subtitles, etc. It just means we'd have a list of Presets instead of a list of Presets and a list of Pickers. Just my 2 cents' worth.

**Comment by RandomEngy** [comment]
I have presets and pickers separated for a reason. Pickers control what gets encoded and where to put it, and presets control how to encode it. You can share presets without having to worry about output information or subtitle picking coming along. You can also share a preset among several different pickers so an edit affects all of them.

You can have the preset and picker windows both open side-by-side.

**Comment by iamjaydear** [comment]
Fair enough, I guess I wasn't seeing the bigger picture, eg. sharing a
preset across pickers. Hope you can get it working soon. Regards, jaydear.
