### ISSUE TITLE
Crash on scanning file

### ISSUE THREAD

**Issue by Kennbo82** [RandomEngy/VidCoder#110]
Hi,

since updating to Win10 Anniversary I have some issues with Vidcoder, no matter which version I start I always get a program crash if try to open a file/folder/disc (Scanning).

Crash Dump is in german, does it maybe help anyway? But seems it's my PC only so any rights are not correct anymore...

Code: 0xC0000005
Info: Der Thread hat versucht, von einer virtuellen Adresse, für die er nicht über die entsprechenden Zugriffsrechte verfügt, zu lesen oder in diese Adresse zu schreiben.

OS: 10.0.14393
CLR: 4.6.1586.0

Best regards

**Comment by RandomEngy** [comment]
If you're using VidCoder Beta, check and see if the same happens on the latest HandBrake nightly. If you're on the stable version, check on the stable HandBrake. The problem might be in the HandBrake encoding engine.

**Comment by Kennbo82** [comment]
Please forget my above issue, I tried several Windows repairs, also SFC and DISM, used the .NET Repair 1.3 but still had the problem, then downloaded the Windows 10 ISO and reinstalled with keep all files+settings, after that it's working again so was a Windows error, seems with the Anniversary Upgrade something went wrong before.

Thanks anyway. :-)
