### ISSUE TITLE
There was a mistake while scanning

### ISSUE THREAD

**Issue by itsBlovu** [RandomEngy/VidCoder#1104]
### Problem Description

[
![Screenshot (80)](https://user-images.githubusercontent.com/122927614/212995473-04459a02-51b3-467b-91fb-48b255e4e5a8.png)
](url)
I want to ripp exactly five Blu-Ray-Discs because I want to digitalise them, but all of them show this report when I open them in VidCoder

### What version of VidCoder are you running?

8.21 SquirrelInstaller

**Comment by RandomEngy** [comment]
Do the discs have copy protection?

**Comment by itsBlovu** [comment]
aacs
![Screenshot (81)](https://user-images.githubusercontent.com/122927614/213002288-cdc50d35-ced0-42eb-8f35-8781c8cd6c40.png)

**Comment by RandomEngy** [comment]
It won't work unless you have a tool to remove the copy protection.

**Comment by itsBlovu** [comment]
Ok thank you. I thought it would work automatically.
