### ISSUE TITLE
Add subtitle size to track list

### ISSUE THREAD

**Issue by Neipas09** [RandomEngy/VidCoder#1107]
### Feature details

Can you add the size of the subtitles so it's easier to tell if it's FULL subs or FORCED subs?

I ran into an annoying issue where I have no clue wihich of these subtitles is the FORCED subs without extracting the subs first and seeing what their size is.
![image](https://user-images.githubusercontent.com/58871039/213773496-fb1ebb02-a40f-406b-b592-28508bff08ef.png)

**Comment by RandomEngy** [comment]
That's a good thought, but the subtitle size is not exposed on the HandBrake API that VidCoder uses. You'd need to ask the HandBrake team to expose that.

**Comment by Neipas09** [comment]
Submitted request to Handbrake github.
https://github.com/HandBrake/HandBrake/issues/4853
