### ISSUE TITLE
[FEATURE REQUEST] Combining queue into ONE single file?

### ISSUE THREAD

**Issue by ollie007** [RandomEngy/VidCoder#111]
[FEATURE REQUEST] Combining queue into ONE single file?

Sorry if inappropriate request here, but can this feature be added as an option, please. So instead of queuing up for individual file encodes, maybe the program can join them all into single output file...

**Comment by RandomEngy** [comment]
That functionality would need to be added to the HandBrake core. I don't think they are planning it any  time soon.
