### ISSUE TITLE
Add a sizing model which is no resolution limit

### ISSUE THREAD

**Issue by yumiaomaio** [RandomEngy/VidCoder#1110]
### Feature details

Whether in manual or automatic mode, the max hight seems to be only 4608 pixel（Portrait 8k video is not supported）
I noticed that handbrake has the option of no resolution limit and no limit on the max height in the custom settings
I don't want to manually adjust the resolution limit every time I adjust the preset, I just want the resolution to be the same as the source

![VidCoder_8SsJUqeqJs](https://user-images.githubusercontent.com/119026102/213936430-169c187e-7529-4108-a064-17943f6254a5.png)
![HandBrake_sRYl4lbGyK](https://user-images.githubusercontent.com/119026102/213936605-c6f0edbe-8b7b-4e4b-9074-90166e6d05d5.png)
![HandBrake_zSMxihTJTe](https://user-images.githubusercontent.com/119026102/213936606-24385e82-067a-4df6-ae59-f9adc0d572e9.png)

**Comment by RandomEngy** [comment]
Delete the number there and it will remove the limit. I'll also increase the max number allowed here in the next release.

**Comment by RandomEngy** [comment]
Increased the max allowed number here in v8.22.
