### ISSUE TITLE
Wrong or incomplete title listing

### ISSUE THREAD

**Issue by ocanav** [RandomEngy/VidCoder#1113]
### Problem Description

Helllo,
Vidcoder does not show me the good title list. A a result I can not see the film title on my DVD image.
For example:
![image](https://user-images.githubusercontent.com/47249963/215864700-378a2f23-da9f-493f-b3dd-ec09dd380ed4.png)
Whereas VLC shows:
![image](https://user-images.githubusercontent.com/47249963/215864839-b3397134-f8c6-425f-b23d-0119dd36548e.png)
I tested with DVD images that I had already ripped with vidcoder for which I did not have the problem, now the problem occurs.

Do you know where it can come from?
Regards,
Olivier

### What version of VidCoder are you running?

8.23 SquirrelInstaller

**Comment by RandomEngy** [comment]
One thing to check is Global Options -> Advanced -> Enable LibDVDNav. If that's not enabled, you can try enabling it.

If you're still having issues, you will have to ask the HandBrake team for help; they own the core logic that is reading the DVD titles.

**Comment by ocanav** [comment]
Hello, I confirm there is a bug on Hanbrake.
The problem occurs with 1.6.1. and not with 1.5.1 version.
I posted an issue on the Handbrake github.
