### ISSUE TITLE
New releases not found by winget? 

### ISSUE THREAD

**Issue by Stephan-P** [RandomEngy/VidCoder#1114]
### Problem Description

I've ben using WingetUI for some weeks and i noticed that Vidcoder releases 8.21 and 8.22 were not discovered as possible updates.
Consequently i had to resort to updating VidCoder mannually. 

Could there be a reason at Vidcoder's side that winget is missing these latest releases or is Winget at fault? 

### What version of VidCoder are you running?

8.22

**Comment by RandomEngy** [comment]
I'm not sure how WinGet works exactly. VidCoder is available as an auto-updating installer that works pretty smoothly.
