### ISSUE TITLE
Video no encoding / pass through option

### ISSUE THREAD

**Issue by WolfganP** [RandomEngy/VidCoder#112]
FOA, thanks for sharing this wonderful app. 

While testing some conversions, I wonder if is there any way to have an option in the Video section codec selection for copying the video stream without any re-encoding (or maybe create a No Encoding profile) where Vidcoder just remux the files copying the video and audio streams, and include chapter markers as well if selected.
Thx in advance.

**Comment by RandomEngy** [comment]
VidCoder uses HandBrake for the encoding engine and that's sadly a feature that they've said they will not implement.

**Comment by WolfganP** [comment]
Ohh, sad to hear that. Thx for the reply anyways.
