### ISSUE TITLE
Add Setting to Turn Off Autorename When Adjusting Start/End Points

### ISSUE THREAD

**Issue by UnrealDrumpf** [RandomEngy/VidCoder#1120]
### Feature details

This may be a Windows 11 thing, it may be something else.

On an older machine, under Windows 10 running version 8.25, if I import barfoo.avi to convert it to mp4, and decide to chop off the last 30 seconds because they're camera artifacts, actually editing the end time (or start time) does NOT change the destination filename. On a brand-new Windows 11 machine (same setup, all options manually set identically), it does -- it appends the run-segment into the destination filename ("barfoo 0:00:00-1:22:17.mp4").

I've been unable to find a setting to deal with this. I'd like the option of NOT having the machine "decide for me" what the destination filename should be.

**Comment by RandomEngy** [comment]
You can change the file name format in the Picker window.
