### ISSUE TITLE
Destination Folder Won't Change in Windows 11

### ISSUE THREAD

**Issue by UnrealDrumpf** [RandomEngy/VidCoder#1121]
### Problem Description

Windows 10 machine properly has the destination folder set to a default that is NOT the "Videos" folder. (It's a subfolder.)

Windows 11 (22H2) machine does not. No matter how many times I change the destination filename/folder when running conversions, and whether or not the "remember folders" box is checked, the destination folder remains pointed at the "Videos" folder. (The default source folder DOES get remembered, however.) I DO clear the "completed" folder when all jobs are finished; is this perhaps wiping the "remember folders" memory?

I suspect that there's a deep, dark bug buried somewhere here. I'm not sure whether this is a VidCoder bug or a Windows 11 bug, or just a poorly documented thing that works differently between Windows 10 and Windows 11. The workaround would be to provide actual options in the Global Settings area for default source and destination folders, instead of relying on the "remember" function that seems to be running into Windows Alzheimer's (or inadequate caffeine in some office in Redmond). 

### What version of VidCoder are you running?

8.25

**Comment by RandomEngy** [comment]
Have you changed the folder in the Picker window?

**Comment by UnrealDrumpf** [comment]
I had not, because the name "picker" does not say "includes stuff relating only to destinations" to me. I have no recollection of doing this on the Windows 10 machine -- the remember-folders function seemed to do the job.

Will try this later today, time for grocery shopping.

**Comment by RandomEngy** [comment]
It also opens it if you click on the "Automatic" button beside the destination box. I moved everything there so there would be a consistent place to automatically determine the output location.

I do still get some people like you that don't think to look there, so I may have to consider other ways to encourage people to check that window.

**Comment by UnrealDrumpf** [comment]
Suggestion:

Don't name the visible menu item "Picker". That's a very Macintosh thing, and people using Windows programs won't think that way inside a Windows program... especially those who used early versions of the Mac (back in the 3.5" floppy only days) whose experience with "Picker" is solely for selection of existing files from the GUI, before there even was a search box... 

Alternatives might include "Filenames" and "File Settings". But if you don't want to rename it, perhaps a longer, descriptive cross-reference in Global Settings would help. The key point is that "Global Settings" implies that one can get to all of the settings, so even if it's just a reference that will help -- and a "cross reference" can be just text with no additional programming required.

**Comment by RandomEngy** [comment]
It also can pick audio and subtitle tracks, specific titles off of DVDs/blu-rays, and perform actions after encoding. So just talking about file names isn't quite right.

Though linking them from Global Options and giving an explanation isn't a bad idea.

**Comment by RandomEngy** [comment]
I added a link to the Picker window from Global Settings in v9 Beta.
