### ISSUE TITLE
Automatically Add All Titles from Blu-Ray index.bdmv

### ISSUE THREAD

**Issue by kanjieater** [RandomEngy/VidCoder#1127]
### Feature details

This might already exist and I'm just missing it, but when I drag a bluray folder onto VidCoder Queue, if I want all the episodes ripped individually, I have to edit it, then select Add To Queue, Select Multiple Titles, Select all of them and then add them.

I was wondering if there was a way to just add all of the titles automatically?

**Comment by RandomEngy** [comment]
There is a feature to pick all titles within a duration range in the Picker window.

**Comment by kanjieater** [comment]
Thank you. So when I tried using that option VidCoder added around 25 titles. However MakeMkv only shows there are 4 titles, which is correct - there are only 4 episodes on this disk.
![image](https://user-images.githubusercontent.com/32607317/227923030-b40d4a12-beb2-45a1-b35b-7a9f03649d3d.png)
![image](https://user-images.githubusercontent.com/32607317/227923096-1c8ff6bc-437d-47fe-9286-44ca41a09f82.png)
It says the titles are equal, so it doesn't add them. Is this something I can replicated in VidCoder? Thank you!

**Comment by RandomEngy** [comment]
VidCoder uses the HandBrake engine to read the title list and do the encoding. You could ask them to add the de-duplication feature that MakeMKV has.
