### ISSUE TITLE
Cannot enter custom 'Denoise' value

### ISSUE THREAD

**Issue by KevinInSeattle** [RandomEngy/VidCoder#113]
Description:
If you select the 'Custom' Denoise option, for either 'hqdn3d' or 'NL-Means', the text entry box does not show up. This means you cannot enter a value such as "3:1:3:3".  This is reported on VidCoder v2.32 Beta (x64) on Windows 10 64-bit.

Repro:
1. Press Settings
2. Select Video Filters tab
3. Select either 'hqdn3d' or 'NL-Means' under Denoise
4. Select 'Custom' Preset
5. Try and locate the custom denoise text input box

Expected Results:
The 'Tune' drop-down menu is replaced with a custom text entry box.

Actual Results:
The 'Tune' drop-down menu does not disappear, and the text entry box does not show up.

Note:
This is working correctly in Handbrake version 0.10.5.0.

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
This should be fixed in 2.33 Beta.
