### ISSUE TITLE
Encode files with specific resolution

### ISSUE THREAD

**Issue by redrules70** [RandomEngy/VidCoder#1139]
### Feature details

Hello,RandomEngy and everyone!!!

I have a weird (probably) request...
Since all my problems with watch-folder (watcher) have been resolved,i would like to request a feature (if possible)..

When adding  A LOT files/directories,with drag/drop or watcher,is it possible to NOT encode videos with lower (or higher) resolution..
For example,drag&drop or watcher,a folder with videos....i want NOT encode flies with SD resolution (lower than 720p)...I don't want to delete them (remain on disk),just NOT encode them.Is it possible/doable by you,or i have to request it from handbrake developers??

Thank you,so much in advance,for your efforts/answers!!!!

**Comment by RandomEngy** [comment]
I started looking into the code to tell you how hard it would be, but then I discovered it would actually be pretty easy to implement. I added a feature to the Picker window to filter titles based on width and height. It's in 9.7 Beta.

**Comment by redrules70** [comment]
OMG!!!
That's exactly what i wanted!!! Thank you SO MUCH !!!!!
