### ISSUE TITLE
Shutdown fales

### ISSUE THREAD

**Issue by joschi642** [RandomEngy/VidCoder#1142]
### Problem Description

Energy is expensive, so my computer switches to saving mode very soon. Mostly VidCoder needs some time. If I set VidCoder to shut down after work is done, the energy saving mode is started before the shutdown-countdown of VidCoder starts. The computer does not switch off. So VidCoder would have to prevent sleep mode until the shutdown-command is actually executed.

### What version of VidCoder are you running?

8.25 Portable

**Comment by RandomEngy** [comment]
Thanks for the report. This should be fixed in 9.8 Beta.
