### ISSUE TITLE
detected framerate is wrong

### ISSUE THREAD

**Issue by sky-62** [RandomEngy/VidCoder#1147]
### Problem Description

I have the problem, that vidcoder always reads the framerate to 23.976. 

On several DVDs with video in 25 fps (PAL) vidcoder reads the framerate as 23.976.

I also have a Blu Ray with 25 fps and here vidcoder also reports the framerate as 23.976.

Maybe this is a bug?

In v. 8.25 (latest stable) the problem doesn't occur. Here the framerate ist correct.

The problem started with the beta versions 9.x. Currently in 9.8 same behaviour.

### What version of VidCoder are you running?

9.8

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by sky-62** [comment]
I tested it with the latest Handbrake and indeed Handbrake reads the wrong framerate.

23.7 instead of the correct 25 fps. 

Thanks for your help!!
