### ISSUE TITLE
add restart PC after task finish

### ISSUE THREAD

**Issue by 3xploiton3** [RandomEngy/VidCoder#1149]
### Feature details

![image](https://github.com/RandomEngy/VidCoder/assets/19517680/482bae01-9bb1-460d-a83d-e09edaeae836)

**Comment by RandomEngy** [comment]
Would this be to apply a Windows update or something?

**Comment by 3xploiton3** [comment]
> Would this be to apply a Windows update or something?

yea, how you know sir? and some software updating
because encode or convert video take to long, we need to leave our computer,

**Comment by RandomEngy** [comment]
Added restart on queue complete option in 9.9 Beta.
