### ISSUE TITLE
Opus support

### ISSUE THREAD

**Issue by Djfe** [RandomEngy/VidCoder#115]
Hi,

You might already know about it: the latest handbrake nightly now ships with opus :)
(In-case you didn't know)
Would be amazing if the next beta of vidcoder would support it, too.

Looking forward to it.

Regards,
Djfe 

EDIT: ups totally forgot the link
 HandBrake/HandBrake#243

**Comment by RandomEngy** [comment]
Just got it integrated. Should have a new version out pretty soon.

**Comment by RandomEngy** [comment]
It's in 2.33 Beta.

**Comment by Djfe** [comment]
Thx a lot :)
