### ISSUE TITLE
Request: Don't disable Default subtitle checkbox when Burn In selected for different subtitle

### ISSUE THREAD

**Issue by JNavas2** [RandomEngy/VidCoder#1152]
### Feature details

Vidcoder 8.25 on Windows 10 Pro x64
With a source video containing Forced, Normal, and SDH subtitles, when Burn In is selected for Forced, Default checkboxes for other subtitles are disabled. 
When Forced subtitles are _not_ contained within Normal or SDH, I want to Burn In Forced, and have Default set for the Normal subtitle, but to make that happen, I have to extract Normal and add it manually, a hassle.
Please make it possible to set Default with Burn In.
Thank you! And thank you for VidCoder!

<img width="455" alt="6NqKfslk83" src="https://github.com/RandomEngy/VidCoder/assets/14850792/6fc1538b-69b0-4f9e-870f-639a4843b81e">

**Comment by RandomEngy** [comment]
So, some sources require multiple tracks to be displayed at once to cover the whole movie? Both the Forced and the Normal subtitles?

**Comment by JNavas2** [comment]
Yes, some MKV sources have embedded subtitles where the Forced (translated foreign language) content is not included in the Normal (or SDH) subtitles, which means standard players will only show one or the other, not both at the same time.

One solution is to merge the Forced subtitles into the Normal subtitles, but that means manually extracting both of them (SDH as well), merging them, and then adding them as external subtitles.

The quick and easy solution would be to burn in Forced subtitles, and for those who need/want subtitles, set the Default flag for Normal (or SDH) subtitles.

Hence my request for the ability to flag Normal as Default when Bruning in Forced.

Thank you.

**Comment by RandomEngy** [comment]
I removed the restriction in 9.9 Beta, so you can select both a burned in track and a default track.

**Comment by JNavas2** [comment]
> I removed the restriction in 9.9 Beta, so you can select both a burned in track and a default track.

Thank you!
