### ISSUE TITLE
Watcher still processes watched folders after reboot even if disabled

### ISSUE THREAD

**Issue by mschumacher69** [RandomEngy/VidCoder#1153]
### Problem Description

When I reboot my PC, Watcher still processes new files in watched folders even though I have disabled it.

### What version of VidCoder are you running?

8.25

**Comment by RandomEngy** [comment]
Thanks for letting me know. To work around this, enable the Watcher, uncheck "Run when VidCoder is closed" and then disable the Watcher again.

**Comment by mschumacher69** [comment]
Thanks.

**Comment by RandomEngy** [comment]
Fixed in 9.9 Beta.
