### ISSUE TITLE
9.9 Beta stopped responding when trying to drag the Settings window while encoding

### ISSUE THREAD

**Issue by JNavas2** [RandomEngy/VidCoder#1156]
### Problem Description

I was encoding a job in a long queue with 9.9 Beta when I tried to drag the Settings window with a mouse.
VidCoder stopped responding and stopped updating the main window.
The encoding job did run to completion, but still had .part appended,
and the next job in the queue was not started.
I had to force Close VidCoder to recover.
I've never seen this problem with 8.25 Stable.
<img width="932" alt="dwm_71UhgvnQDI" src="https://github.com/RandomEngy/VidCoder/assets/14850792/74c0d025-1b3d-442b-8b47-1115c8763c29">
<img width="750" alt="Taskmgr_AtXCeBfneo" src="https://github.com/RandomEngy/VidCoder/assets/14850792/2e573f49-11d9-4a87-8f0d-94a72baf35a9">

### What version of VidCoder are you running?

9.9 Beta SquirrelInstaller

**Comment by RandomEngy** [comment]
Next time this happens you can open Task Manager, find VidCoder.exe, right click and choose "Create dump file". I can examine that and find where it's hung.

I also have a fix ready that *might* work that I've added based on some other hangs that have been reported. This one I haven't been able to reproduce though.

**Comment by JNavas2** [comment]
> Next time this happens you can open Task Manager, find VidCoder.exe, right click and choose "Create dump file". I can examine that and find where it's hung.
> 
> I also have a fix ready that _might_ work that I've added based on some other hangs that have been reported. This one I haven't been able to reproduce though.

Thank you.
I should have thought of that. My bad.
