### ISSUE TITLE
"Open Containing Folder" failing with long paths

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#116]
This is no biggie, but sometimes when right-clicking on files in the Completed tab and selecting "Open Containing Folder" I only get deposited at the "This PC" root, instead of in the destination directory with the selected file highlighted. A typical path length where this happens is about 120 characters or so, which I believe is only about half the maximum legal path length in Windows 7/8/8.1. Windows itself seems to have no problem managing these files and VC creates them with no obvious problem/s.

Here's an example: 
D:\Off-Air\DirectoryNameCouldBeThisLong\FileNameCouldBeThisLongAndWrittenInCamelCaseWithNoSpaces,ButSome-(123)&-Stuff.ext

**Comment by iamjaydear** [comment]
Oh, yeah, and I forgot to mention that double-clicking any file in the Completed tab always opens the correct file, never fails, no matter how long the path name.

**Comment by RandomEngy** [comment]
Does your path have a space in it?

**Comment by RandomEngy** [comment]
Hmm nevermind. For some reason it has this limitation when run through Process.Start() ... will see if there is a workaround.

**Comment by iamjaydear** [comment]
I've had the problem in the distant past of a file with a (very) long name causing an error message when an attempt was made to copy it to a deeper folder. I didn't realise the path was included in back then. Re: spaces... I always avoid them and instead use CamelCase to delineate words. I do use commas a fair bit.

**Comment by RandomEngy** [comment]
Okay I fixed in 2.33 Beta. Had to PInvoke into a native Windows method.
