### ISSUE TITLE
Select no audio and no subtitles on dropping a file in the Vidcoder window.

### ISSUE THREAD

**Issue by im4aratu** [RandomEngy/VidCoder#1160]
### Feature details

It would be great if the automatic selection of audio and subtitle streams on opening an mkv file could be turned off. Useful for when you want to encode only the video and encode the audio in  a different program and mux later.

Maybe add a "No audio" option here?

 
![Clipboard01](https://github.com/RandomEngy/VidCoder/assets/94698128/5ca77fe1-fa52-459b-9e69-7ecea4032ecc)

**Comment by RandomEngy** [comment]
Added the ability to select "None" for audio tracks in 9.10 Beta.
