### ISSUE TITLE
GUI Becomes A Little Distorted

### ISSUE THREAD

**Issue by Blaster-Master** [RandomEngy/VidCoder#1167]
I don't think this is a bug, but using VC 9.10b, when I increase the font size in settings of my Win11 to over 124%, the VC GUI becomes a little distorted.  Mainly the top menu words bleed down and only show half the words.  In the encoding tabs it doesn't do it as much unless I increase font size more than 130%.  Doesn't happen in Handbrake or other progs.

**Comment by RandomEngy** [comment]
This is a problem with the Fluent Ribbon library that VidCoder uses: https://github.com/fluentribbon/Fluent.Ribbon/issues/774

**Comment by Blaster-Master** [comment]
Ok, I understand.  Not a huge deal.  Thanks for the link and info!
