### ISSUE TITLE
Encoding Settings "Restored From Queue" After Edit Is Annoying

### ISSUE THREAD

**Issue by UnrealDrumpf** [RandomEngy/VidCoder#1181]
### Feature details

This is sort of halfway between a "bug" and an "enhancement request."

Most-obvious way to reproduce:  Use the "Open Source | Enqueue Multiple Files..." option to, well, enqueue multiple files. Discover that they're all being sent to the wrong folder (and/or have the wrong filename, such as one with an esszet instead of "ss" on a primarily-English-language system). Right-click on the offending file to edit that folder/name, and the Encoding Settings shows only "Restored From Queue", and not **what** was "restored from queue."

Better would be to state the encoding settings that are being "restored from queue," especially a named preset (whether customized or shipped-with). If it's really, really, really necessary to flag that it's been "restored," add that as a text flag in front ("RfQ"), or italicize, or something, to **add** that information without hiding the, well, actual settings being applied. Or maybe a color change (although that's potentially problematic for other reasons), or a font change (ditto).

**Comment by RandomEngy** [comment]
I think I see what you're getting at. In the next Beta release it will read as "Original preset name - Restored from Queue" rather than just "Restored from Queue".

**Comment by RandomEngy** [comment]
Fixed in 9.12 Beta.
