### ISSUE TITLE
Bitrate viewer

### ISSUE THREAD

**Issue by Ghastor** [RandomEngy/VidCoder#1185]
### Feature details

Hi !
Can you add bitrate used near % on the progress bar ? At the bottom and in batch mode for every video
It'a very usefull especially in crf mode!

Thanks !

**Comment by RandomEngy** [comment]
Bitrate used? You mean like current file size?

**Comment by Ghastor** [comment]
I mean, the real-time value of the bitrate used during encoding visible in the green progress bar next to the progress percentage.

**Comment by RandomEngy** [comment]
This is the information I get back from the HandBrake API about the encode progress:

<img width="455" alt="image" src="https://github.com/RandomEngy/VidCoder/assets/9450861/f315d62d-fbcb-4bdd-8c77-950c596b7d02">

The Rate and RateAvg here is framerate. The current bitrate is not exposed, I could add it to the Encode Details window if I had it. You can ask the HandBrake team for this.

**Comment by Ghastor** [comment]
ok, thanks for your reply @RandomEngy.
I will ask for it to handbrake team.

Thanks again
