### ISSUE TITLE
Idle priority for worker process

### ISSUE THREAD

**Issue by FCrane** [RandomEngy/VidCoder#1186]
### Feature details

Hi!

It would be nice if the priority of the worker process could be set to "idle", not just "low", so that all other processes would not be slowed down and encoding could really run in background only using idle CPU time.

It's done with the "SetPriorityClass" API function and IDLE_PRIORITY_CLASS parameter.

Thanks!

**Comment by RandomEngy** [comment]
Do you have processes running at Low priority that you need to not be slowed down?

**Comment by FCrane** [comment]
Probably, because when the encoding process is running, the whole system gets less responsive and sluggish. Especially everything with disk access of graphics gets slow - e.g. 4K video playback stutters, etc. I'm hoping that setting the priority to idle could fix that, so that if anything else needs the CPU, encoding is halted. Not sure if that would solve the issue, but theoretically idle priority should be better than low for this case...

**Comment by RandomEngy** [comment]
https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities

> The system assigns time slices in a round-robin fashion to all threads with the highest priority. If none of these threads are ready to run, the system assigns time slices in a round-robin fashion to all threads with the next highest priority.

So moving something from Low to Idle priority would only help processes that were marked Low.

There is a feature in VidCoder that can automatically pause when it sees a certain process running. So you could put your media player in the list, and VidCoder would pause when it starts up and resume when it closes.

**Comment by FCrane** [comment]
Thanks - the process pause feature does help! 

BTW: the (very long) process list should be sorted alphabetically so that I can find the respective process easier... Or some kind of filter...

Still I think setting a process priority to idle could help improving system responsiveness - maybe worth a try?

**Comment by RandomEngy** [comment]
Based on documented behavior, I don't believe it has any chance of helping your situation. Media players, apps and games pretty much never run on Low priority.

**Comment by FCrane** [comment]
The process pausing suddenly has stopped working! Even if I remove the video player from the process list in VidCoder and re-add it, the encoding will still not be paused. It used to work a few times, but not it doesn't anymore. What's going on?

Also, it'd be much better if the process list simply was an edit box where I can enter parts of the process path instead of just the process name! This way, I could e.g. quickly disable the pausing by just adding any extra character to the program name, etc. Removing and re-adding a process would also be a simple cut & paste operation instead of the tedious searching in a long unsorted list of processes...

**Comment by RandomEngy** [comment]
You can check the "General" log tab and it should have messages about the auto-pause behavior. If you have that log, and the name entered in the auto-pause list, and the process name, I might be able to tell you something more about what's happening.

**Comment by FCrane** [comment]
When it's working, the general log contains lines like:

VC [08:55:15] Automatically pausing, process detected: IsoPlayer
VC [08:56:25] Automatically resuming, processes are gone.

When it's not working, there are no lines containing anything about process detection, pausing, resuming, etc.

It did start to work again after restarting VidCoder, so it seems something that can "break" during runtime and will be restored after a restart.

Please do consider my suggestion for choosing and entering the processes, because the long unsorted list of processes is uncomfortable to work with - especially if I need to frequently add or remove my player (for HD playback, VidCoder should run, for UHD playback, it should not). A checkbox to quickly enable / disable the process pausing feature would also help a lot (like with battery and disk space)! 

Still ideally, there would be a way to remotely pause and unpause VidCoder from another app (e.g. by command line parameter, which should be easy to implement).

Thanks!

**Comment by RandomEngy** [comment]
In 9.12 I added a couple features:
* A checkbox to enable or disable process auto-pause
* A `pause` and `resume` command for `VidCoderCLI.exe`.

**Comment by FCrane** [comment]
Great!!! Thank you! Am I correct that this is not working with the portable version? Also, if I run the GUI version, will the command line pause and resume this as well? I'.ve never tried VidCoderCLI because I'm using the protable version...

**Comment by RandomEngy** [comment]
You are correct! The automation host isn't started up in the Portable version so even if you found the temporary copy of VidCoderCLI.exe it wouldn't successfully connect to the main process.

It works on the installer version. (And the updates there are painless, as well)

**Comment by JNavas2** [comment]
PMJI:
- From my experience in Windows task scheduling I would say that VidCoder at Low process priority would only have a measurable impact on another Low process priority task, which should only be an issue with a _misbehaving_ application.
- I run VidCoder at Low process priority (instead of Below Normal) and I've _never_ seen a significant impact on other applications.
- For video playback I use and recommend [MPC-HC](https://github.com/clsid2/mpc-hc).
- All that said, making it possible to set process priority to Idle is not necessarily a bad idea.

**Comment by JNavas2** [comment]
PMJI:
- From my experience in Windows task scheduling I would say that VidCoder at Low process priority would only have a measurable impact on another Low process priority task, which should only be an issue with a _misbehaving_ application.
- A likely work-around is to Limit the Number of Allowed Cores to at least 1 less than maximum.
- I run VidCoder at Low process priority (instead of Below Normal) and I've _never_ seen a significant impact on other applications.
- For video playback I use and recommend [MPC-HC](https://github.com/clsid2/mpc-hc).
- All that said, making it possible to set process priority to Idle is not necessarily a bad idea.
