### ISSUE TITLE
Conservative Cropping not working correctly

### ISSUE THREAD

**Issue by FCrane** [RandomEngy/VidCoder#1187]
### Problem Description

"Conservative Cropping" is my preferred auto cropping mode, with "Minimum 2" and "Constrain to one axis". Works fine, but very often it will crop 1 line of image data (not black) from either the top or bottom of the video (respectively left or right for the other axis). E.g. it selects 138 for top (correctly leaving 1 black line because video starts at 139) and 140 for bottom (incorrectly cropping 1 line of the actual video, which starts at 139). Sometimes it's cropping a line from the top, sometimes from the bottom.

Why does it do that? It clearly crops 1 line of actual video data from either side, when it should "conservatively" better leave a black line on both sides. I really prefer having some black lines around the video instead of losing video lines...

### What version of VidCoder are you running?

9.11 Beta Portable

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by FCrane** [comment]
Yes, Handbrake seems to have the same issue. I'll post it in their bug tracker...
