### ISSUE TITLE
I want a new feature.

### ISSUE THREAD

**Issue by asdyjd** [RandomEngy/VidCoder#119]
I have a lot of movies,I want to transform them into H265.
But I found a problem.If the bitrate of a movie is very high,just like 8000kbps in h264.It need only 3500 kbps to keep the same quality.But if the bitrate is low just like 600kbps.It need 450kbps to keep the same quality.So the new bitrate is not constant.It's dynamic.
I figure out a  approximate formula to describe the new bitrate:
(0.7 - 0.6/pi*atan(0.0000007*(-1300000 + 1000*bitrate)))*bitrate
Can you make this a new feature to this software?Thank you!

**Comment by RandomEngy** [comment]
I'd recommend using Constant Quality for this. See http://vidcoder.net/Documentation/VideoQualityOptions.html

**Comment by asdyjd** [comment]
I tried.But it doesn't help.
I set the CEF to 20. It convert a video from 1000kbps to 500kbps.It's great.But another from 5700kbps to 6000kbps.
It doesn't work sometimes.
What to do?

**Comment by asdyjd** [comment]
I tried.But it doesn't help.
I set the CEF to 20. It convert a video from 1000kbps to 500kbps.It's great.But another from 5700kbps to 6000kbps.I want it 3000kbps.
It doesn't work sometimes.
What to do?

**Comment by RandomEngy** [comment]
That's because it targets a constant picture quality, not a specific bitrate. Some sources require more data to make them look good. If you think the files are too large, try tweaking the quality target, maybe to 22, and see if you are OK with the space/quality tradeoff.
