### ISSUE TITLE
When Toggling between presets with different Denoise MAIN options selected, The Preset doesn't Bind properly

### ISSUE THREAD

**Issue by mrlenny** [RandomEngy/VidCoder#1195]
### Problem Description

This problem doesn't appear to affect the encode, that all works properly but when I'm tried to build a preset, it would be helpful if the dropdowns would bind properly so I can review the changes I'm making.

Problem is reproducible when toggling between two custom presets that both have denoise options selected, but they differ.
![image](https://github.com/RandomEngy/VidCoder/assets/778155/428add45-f78b-45bf-96fa-93ab8587d258)

### What version of VidCoder are you running?

8.26 SquirrelInstaller

**Comment by RandomEngy** [comment]
It works when I try switching between two encoding presets with different Denoise presets. Can you share your %appdata%\VidCoder\VidCoder.sqlite file and some specific steps to reproduce it?

**Comment by mrlenny** [comment]
[VidCoder.zip](https://github.com/RandomEngy/VidCoder/files/13650560/VidCoder.zip)

Steps:

Open preset window with with a preset Denoise of NLMeans and Light selected (shows correctly)
![image](https://github.com/RandomEngy/VidCoder/assets/778155/2392c340-b580-4b2c-b179-ebd5977044a9)

Then switch to a different preset with a preset denoise of hq3dn and ultra-light and the ultra-light isn't bound to the dropdown
![image](https://github.com/RandomEngy/VidCoder/assets/778155/024b150a-c9f6-4159-89fe-45006060d7c5)

Closing and re-opening the window causes the ultra-light to bind:
![image](https://github.com/RandomEngy/VidCoder/assets/778155/64d1945e-9f5b-40d2-a114-eb662466984e)
but I notice none of the "Offs" are binding either...

**Comment by RandomEngy** [comment]
Thanks, it was easy to reproduce from that file. It should be fixed in 9.16 Beta, which I just released.
