### ISSUE TITLE
Movie

### ISSUE THREAD

**Issue by 2nidtat** [RandomEngy/VidCoder#1199]
### Problem Description

Bluray the creator don't show french audio track.
Had to isolate track as file to see it.

### What version of VidCoder are you running?

9.13 Bêta SquirrelInstaller

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)
