### ISSUE TITLE
Can't select burn-in in picker

### ISSUE THREAD

**Issue by Ruriko** [RandomEngy/VidCoder#12]
I can't checkbox the burn-in box in the picker it just won't let me

**Comment by RandomEngy** [comment]
Some subtitle/container combinations limit if you are allowed to burn or specify that you must burn. What container and subtitle type are you trying, and do you want it to burn or not burn in?

**Comment by Ruriko** [comment]
It was a mkv container and the subtitle type is ass. I want to burn in subtitles

**Comment by RandomEngy** [comment]
I see what you mean now. I'm in the middle of overhauling that area; will fix as part of it.

**Comment by RandomEngy** [comment]
Fixed in 2.16 Beta.
