### ISSUE TITLE
BUG: VidCoder keeps changing the Windows Installed date

### ISSUE THREAD

**Issue by JNavas2** [RandomEngy/VidCoder#1200]
### Problem Description

SUMMARY: VidCoder keeps updating the Windows installed date.
DETAILS:
I have Automatic updates enabled with "Prompt to apply right away."
<img width="325" alt="VidCoder_xih4KqNXEy" src="https://github.com/RandomEngy/VidCoder/assets/14850792/7bc1de4e-7f39-479a-9332-9fd6c9785a08">
VidCoder 8.26 was installed on 8/8/2023 (in ...\AppData\Local\VidCoder.Stable), and has not been updated since then, yet it keeps changing the installed date in Windows; e.g.,
<img width="632" alt="UmE9gLlgqv" src="https://github.com/RandomEngy/VidCoder/assets/14850792/17e77e19-9f3d-47c7-b294-78cc50f14066">
My guess is that the automatic update logic is running something that causes this (mis)behavior.
p.s. Thank you for an otherwise invaluable application!

### What version of VidCoder are you running?

8.26 SquirrelInstaller
OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
System Type	x64-based PC

**Comment by RandomEngy** [comment]
You're right, I see that too. It's likely an issue with the Squirrel installer framework that VidCoder uses. I've opened https://github.com/clowd/Clowd.Squirrel/issues/197 to track.

**Comment by RandomEngy** [comment]
I updated the installer to Velopack for 10.1 Beta. Going to check if it is still changing the install date when running.

**Comment by JNavas2** [comment]
Should I wait on you, or would you like me to try the beta?

**Comment by RandomEngy** [comment]
Go for it. You can install the beta side-by-side with the Stable version.

**Comment by JNavas2** [comment]
Works as expected!
