### ISSUE TITLE
Convert subtitles to SRT format

### ISSUE THREAD

**Issue by cja000** [RandomEngy/VidCoder#1204]
### Feature details

It would be nice to be able to convert subtitles to other formats than the original ones.
I'm particulary interested in convert to SRT and include those subtitles in the MKV files.

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://github.com/HandBrake/HandBrake/issues/new/choose) to add it.
