### ISSUE TITLE
thumbnail not showing

### ISSUE THREAD

**Issue by THRobinson75** [RandomEngy/VidCoder#1211]
### Problem Description

Always been an issue for me, I load a video on the main VidCoder window and nothing, load it a 2nd time and I get the small video thumbnail next to time range. I just reinstalled my PC software, installed VidCoder and now I can't get that small thumbanil to appear at all. 

### What version of VidCoder are you running?

9.17 SquirrelInstaller

**Comment by RandomEngy** [comment]
Thanks for the report. I think I just overlooked this since I usually keep the preview window open at all times. This should be fixed in 9.18.
