### ISSUE TITLE
Vidcoder Crashes whenever multiple titles selected.

### ISSUE THREAD

**Issue by yahknow1** [RandomEngy/VidCoder#122]
I've tried everything I possibly can think of to fix this. Uninstalled and reinstall with latest version.  I can usually encode 1 title and be successful, but as soon as I try it with more, it crashes. 

Handbrake has no problem with any of the titles that Vidcoder chokes on? Where do I find the log to attach, is it:

C:........\AppData\Roaming\VidCoder\Logs ?

**Comment by RandomEngy** [comment]
This is one I've had a hard time reproducing or fixing. But yes that's where you'd find the logs.

**Comment by yahknow1** [comment]
Well here’s the log 

 

Thanks for trying

**Comment by RandomEngy** [comment]
Give 2.39 Beta a try. I've moved batch scans to a worker process; it might be more stable for you now.

**Comment by iamjaydear** [comment]
I just had a thought (well, it's Christmas)... What is VC looking for when it scans videos? If it's looking for problems in files, such as e.g. discontinuous timecode, what is it supposed to do? I've only experienced two scenarios... 1. The file/s scan in OK and encoding proceeds to a successful conclusion -or- 2. VC crashes during the scanning. Maybe VC is not able to 'drop' a file without crashing?? Anyway, as I say, just a thought.

**Comment by iamjaydear** [comment]
I've noticed when dragging and dropping that VC locks the source window until it is finished scanning. Other apps I have don't do that, so maybe there is an undesirable interaction if the source app tries to update it's window whilst VC is trying to keep it locked? Just another thought (1st one this year).

**Comment by RandomEngy** [comment]
Ahh you're right, it does lock the window. That's a pretty simple fix; it will be in 2.45.

**Comment by iamjaydear** [comment]
I haven't had a 'scanning crash' since!
