### ISSUE TITLE
Hardcode subtitle and logo removal

### ISSUE THREAD

**Issue by sirjohn771103** [RandomEngy/VidCoder#1220]
### Feature details

Hello, can you make this hardcode subtitle and logo removal option built-in to your software? 
https://forum.videohelp.com/threads/358181-How-to-remove-hard-coded-subtitles-HELP-PLEASE#post2481785

Thank you: Zsolt

**Comment by RandomEngy** [comment]
Not in scope. VidCoder is a transcoder, not a video editor.
