### ISSUE TITLE
Estimating the size of an encoding job

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#1223]
### Feature details

This might be rather useful, and simple to implement:

When performing a preview, get the size of the resultant "preview.mkv" and use a simple calculation to guesstimate the overall size of the corresponding finished job and show this somewhere on the preview window.

(Total duration to be encoded/Chosen preview duration) × size of "preview.mkv" = estimated size of completed job

Obviously there are caveats based on the content etc. (and a longer preview is more likely to give a better estimate), but better than nothing.

**Comment by RandomEngy** [comment]
I have some reservations about this one. In the ideal case you are doing quality targeting, and a preview will likely be systematically wrong as the credits typically need far less data to encode.

Typically I like to try and dispel the idea that you need to care deeply about exactly how big the final video is. Find an acceptable quality target, and let the encoder give you a good quality video and save space where it can. Some videos may be smaller than others, and that's OK.

I'm not rejecting the feature, but there would need to be some major caveats.

**Comment by im4aratu** [comment]
Or do a 2-pass encode. Then You will know for sure what the resulting filesize will be.

**Comment by Plutocratic** [comment]
> Or do a 2-pass encode. Then You will know for sure what the resulting filesize will be.

I fear you have rather missed the point. I have no interest in **knowing** what the size will be, merely that a **quick and dirty approximation** might sometimes be useful.

FWIW, I have been doing some tests on this approach and the worst case error, when I deliberately picked a short sample that was unrepresentative of the bulk of the content, was about ±15%. The typical result was ±10%.

RE: provided you clearly state that the figure is a guesstimate (by whatever words you choose), I really don't see what harm could be done.

**Comment by im4aratu** [comment]
I had to google "FWIW" :)))) If you're ok with a +-15% guess...timation yeah sure :)). I've always always looked for the best quality and I'm a long time user of Vidcoder/Handbrake. My constraint was always space so I aimed for the best quality at a given bitrate. I apologize for not not understanding your POV.

**Comment by Plutocratic** [comment]
FWIW (!) Another use of this function would be to assist in comparing subtle variations within a particular codec. For instance, should I opt for RF35 Slow or RF30 Medium? Some indication of the size of the test output might be a useful factor in helping such decisions. As I said earlier, provided it is made clear that this is only a first-order estimate (i.e. to be taken with a pinch of salt), what harm could such a feature do?

**Comment by RandomEngy** [comment]
I coded this feature up and created a bunch of different 10 second preview clips during the movie (not the credits). The estimated final size ranged from 590MB to 1.9GB for the same file, and I got everything in between. The final video was 1.01 GB. The variance is too high for me to include it.

It is kind of interesting though, how much the required data changes just from scene to scene.

**Comment by Plutocratic** [comment]
> a bunch of different 10 second preview clips

It's your call David; I believe you've dismissed it too readily. If you only
allowed the feature to be used with a preview of 60 seconds or greater, I
think you'd find the results to be a lot more consistent, more in line with
what I mentioned earlier.

I have never done a rough and ready calculation based on a preview this short;
perhaps I should have mentioned this in my earlier posts.

Regards, Paul O.

**Comment by RandomEngy** [comment]
10 seconds is the default preview length and what most people would have when they see these size estimates.
