### ISSUE TITLE
SUGGESTION: Make Low the default process priority instead of Below Normal

### ISSUE THREAD

**Issue by JNavas2** [RandomEngy/VidCoder#1227]
### Feature details

My own experience running VidCoder is that overall system performance is better using Low rather than Below Normal process priority, without significant encoding degradation, so I think Low might be a better default for most users. Those who want the best encoding performance will likely need/want higher than Below Normal process priority in any event.
Thank you for VidCoder!

**Comment by RandomEngy** [comment]
What processes marked as Low/Below Normal do you see VidCoder contending with? I assume processes that need responsiveness will be set to at least Normal.

**Comment by JNavas2** [comment]
Here's a partial process snapshot with my system (quad core CPU) under load.
VidCoder is running at Low priority consuming most of the processor power.
MPC-HC is playing a Full HD video with no glitches using very little processor time.
Microsoft Edge browser is running with many tabs open, most of which are at Low priority.
There is no apparent impact on use of the system from VidCoder.
You can see that responsive processes run at Normal or higher priority.
Only the Power Manager is running Below Normal.

When I run VidCoder at Below Normal priority I do get occasional sluggishness or even short freezes from other tasks.

Hope that helps! Let me know if there's anything more you need or want.

<img width="619" alt="mq7XoEvf6x" src="https://github.com/RandomEngy/VidCoder/assets/14850792/a9987edf-e67f-4002-97fb-1423440d5127">

**Comment by RandomEngy** [comment]
I don't know the internal workings of Edge enough to know what would be affected. In this case, most of the Edge processes are running at Normal priority. But generally, apps that need to be responsive tend to use Normal priority. I think Below Normal is a fine default for VidCoder, and am glad that you have found a different setting that works well for you.
