### ISSUE TITLE
Adding Folder or Multiple Files to running encoding queue fails/bombs

### ISSUE THREAD

**Issue by tester2011** [RandomEngy/VidCoder#1234]
### Problem Description

When adding addition files to a currently running encoding session ("Open Source > Enqueue Folder of Videos Files" or Open Source > Enqueue Multiple Files"), the progress-bar will stop before all files are added - sometimes after one file, sometimes after 5 or 6. The current encoding jobs still continue and I can close the progress window for the added files, however there are multiple Windows Memory Dump files created, suggesting the process the adds additional files has bombed-out. I CAN add individual files to the currently running encoding queue without issue though ("Open Source > Open Video File, Add To Queue:). 

### What version of VidCoder are you running?

9.20 Zip

**Comment by RandomEngy** [comment]
I made a fix in 10.2 Beta that resolves a problem where the batch scan would stall if there was a crash in the worker process. This might resolve your issue, or at least let the batch scan complete and report the errors at the end.

Let me know if this works for you.
