### ISSUE TITLE
MakeMKV LibMMBD Support should be mentioned on the website.

### ISSUE THREAD

**Issue by Fighterbuilder** [RandomEngy/VidCoder#1236]
### Feature details

MakeMKV has a feature called LibMMBD which allows other software to directly use it as a decryption engine, which would bypass the step of having to dump the contents of the disk using MakeMKV before running VidCoder on said dump. Having support for this feature would greatly cut down on the time and storage space required to back up my physical media.
![image](https://github.com/RandomEngy/VidCoder/assets/33814663/721f2b85-6225-40c2-a7bf-fc69dcf15d78)

**Comment by RandomEngy** [comment]
I wrote this a while ago and it looks like it's in need of an update. Does MakeMKV have pretty good support for most discs?

**Comment by RandomEngy** [comment]
I updated the documentation for MakeMKV to reflect this.
