### ISSUE TITLE
Bug with your Handbrake core and" about vidcoder" windows and year

### ISSUE THREAD

**Issue by Mister-XY** [RandomEngy/VidCoder#1239]
### Problem Description

Hello please use a new Handbrake core version. with yours, you have the problem with the 2 pass and AV1.
https://github.com/HandBrake/HandBrake/commit/47050897ac225ee342dab9c787745abaa9042b36
In the same breath, you might also want to change the “About Vidcoder” window, as the year 2022 is still listed there.
![Screenshot 2024-05-20 163728](https://github.com/RandomEngy/VidCoder/assets/10309056/14f64846-9bb4-4582-88c1-124d4c388f45)

### What version of VidCoder are you running?

10.3

**Comment by RandomEngy** [comment]
I released 10.4 Beta with an updated Handbrake core that should have that commit, and updated the copyright year.
