### ISSUE TITLE
Trojan:Win32/PswStealer detected

### ISSUE THREAD

**Issue by valkryie999** [RandomEngy/VidCoder#1240]
### Problem Description

https://www.virustotal.com/gui/file/8cd76f549441cc774d0da426007040fe39b26d7edc22514c6ecab2615363d660

### What version of VidCoder are you running?

10.5

**Comment by RandomEngy** [comment]
Thanks for the report. This is a false positive.

It looks like VidCoder was clean on 56/57 of engines. I don't have the time to babysit the 50+ AV engines, install them and submit false positive reports, but you are welcome to.

VidCoder releases are already digitally signed so as long as you're downloading from GitHub or vidcoder.net (Or you check the digital signature when downloaded elsewhere) you should be OK.
