### ISSUE TITLE
Wow, what a greast software!

### ISSUE THREAD

**Issue by davidtri1** [RandomEngy/VidCoder#1242]
### Feature details

I would like to know how VidCoder converts closed captioning to text-based srt.  Using ffmpeg I can convert CC to srt only when the video is 1080P.  If the video is 720P or 480P, I get the error: data ignored due to columns exceeding sreen width; output file is empty

ffmpeg -f lavfi -i "movie=input.ts[out0+subcc]" -c:s text "output.srt"

How does VidCoder handle Closed Captioning?  I would appreciate seeing the codes/commands for the process.  Thank you.

**Comment by RandomEngy** [comment]
This would be a better question to ask directly of the HandBrake team. VidCoder uses the HandBrake engine to do the actual encoding work, which handles the specifics around subtitles and integration with the ffmpeg library.
