### ISSUE TITLE
Same Watch Folder with different Encoding Preset

### ISSUE THREAD

**Issue by bdlegend** [RandomEngy/VidCoder#1246]
My video file in one folder and I want to encode with 1080p and 720p preset. I have already add watch folder with 1080p preset but when I try to add 720p preset with same watch folder it does not work.

How do I add same watch folder with 2 different Encoding Preset ?

**Comment by RandomEngy** [comment]
I changed 10.8 Beta to allow specifying the same folder twice. This only works correctly when you use the System folder watcher method (this is the default).
