### ISSUE TITLE
Encoding and Final output Folder

### ISSUE THREAD

**Issue by bdlegend** [RandomEngy/VidCoder#1248]
### Feature details

Is there have any settings like when encoding runs video file is in one folder and final files will transfer to other folders. That means before final output encoding will be done in one folder and after completing it goes to other folder.

**Comment by RandomEngy** [comment]
That's not a native functionality of VidCoder. But you can specify post-encode actions in the Picker that can do that.

**Comment by bdlegend** [comment]
> That's not a native functionality of VidCoder. But you can specify post-encode actions in the Picker that can do that.

Can U explain how post-encode actions works and how I set this ?

**Comment by RandomEngy** [comment]
Look at the bottom of the Picker window to find the post-encode action. You can enable it and it will run a command-line action, and it supports some placeholders. You should be able to put in a "move" command by using the `{file}` placeholder, but you'd need to figure out how to do it from the command line first.

**Comment by bdlegend** [comment]
If I want to move another folder or drive after encoding what command or argument do I use ?
please help me regarding this issue.

**Comment by RandomEngy** [comment]
I would recommend typing in "windows move file command" into a search engine or chat GPT as a start.
