### ISSUE TITLE
Subtitles - Add external subtitle files with same name as input video file

### ISSUE THREAD

**Issue by mpek** [RandomEngy/VidCoder#1256]
### Problem Description

Language: German (Deutsch)

I understand this is a feature to import subtitles automatically, right? 

What are the naming conventions for external subtitle files for adding external subtitles based on same name as input video file?

Atvthe moment, external subtitles (SRT UTF-8) won't be added automatically when input video file is loaded. 

I'm using these naming conventions to differentiate different language, but they don't get recognized: 

videofilename.deu.srt for german subtitles
videofilename.eng.srt for english subtitles

What are the prerequisites to use this feature as expected? 

### What version of VidCoder are you running?

10.9

**Comment by RandomEngy** [comment]
This is already requested under https://github.com/RandomEngy/VidCoder/issues/1075

VidCoder will pull in subtitles with the exact same name as the file name, but it doesn't pull in the language variants yet. I haven't had time to implement the feature and nobody has submitted a pull request.

**Comment by mpek** [comment]
Upps, so i just came across the same need...thank you for answering. 

I would like to encode a series of over hundred files with all additional subtitles, but as you can consider this is very heavy and stupid when adding them manually. 

Would it be quickly implementable to be able to add all subtitles in one step when adding them manually? Atm, you have to pick one by one.

**Comment by RandomEngy** [comment]
We can track with https://github.com/RandomEngy/VidCoder/issues/1075
