### ISSUE TITLE
Videocoder beta 10.10 Encoding/ Decoding with Intel Quick Sync Video crash

### ISSUE THREAD

**Issue by zakimimit** [RandomEngy/VidCoder#1257]
### What were you doing when VidCoder crashed?

Hello ;

Videocoder beta 10.10 Encoding/ Decoding with Intel Quick Sync Video crash

When activate QSV Decoding the the app crash  

There no log generated.

My best regards 

### Crash details

```text
When activate QSV Decoding the the app crash  without any logs
```

**Comment by RandomEngy** [comment]
Thanks for the report. This should be fixed in 11.1 Beta and 10.13 Stable.

**Comment by zakimimit** [comment]
Thank you, you are the best

**Comment by zakimimit** [comment]
Thank you, you are the best
