### ISSUE TITLE
Videocoder not support or detect files and folder in long path

### ISSUE THREAD

**Issue by zakimimit** [RandomEngy/VidCoder#1258]
### Feature details

Videocoder not support or detect files and folder in long path

Add detect files and folder in long path (and nested sub folders)

even the long path activate on windows 

the Videocoder  not be able to detect files with long title and long path

My best regards

**Comment by RandomEngy** [comment]
I tried enabling this by updating the manifest, but it appears there are a number of issues:

1) You can't enter a long path in the Explorer UI for Open File, as Explorer does not support long paths.
2) You can't drag and drop: it gives a COM error.
3) The HandBrake core does not appear to work with long paths. You get an error: "scan: unrecognized file type"

Once some more pieces fall into place, at the minimum HandBrake support, then I can turn it on.

**Comment by RandomEngy** [comment]
It is possible to create short paths for files, which could possibly be run during "intake" of file paths. In what situations are you going over the max path limit? The watcher? do you have really deep folder directories, or just really long file names?

**Comment by zakimimit** [comment]
I have a deep folder directories,
And i can track it because there are multiple missing files that not converted because the path is too long
