### ISSUE TITLE
CRF sometimes does 2-pass, sometimes not

### ISSUE THREAD

**Issue by kasim1r** [RandomEngy/VidCoder#126]
Hi,

according to [this ](http://vidcoder.net/Documentation/VideoQualityOptions.html) page, CRF is a one-pass process. I wanted to ask if this is "set", or if there are cases when CRF would still do a 2-passs encode? I've ssen it do this with different sources. Oh, this seems to happen in release as well as in beta, the current ones and backwards.

**Comment by RandomEngy** [comment]
If you have foreign audio search enabled it can do a scan pass, but that's only to determine which subtitle track to include.

**Comment by kasim1r** [comment]
Ah okay, great, that's probably the reason then, cos I always have that activated.
