### ISSUE TITLE
Add new options to" When file already exists (Batch):"

### ISSUE THREAD

**Issue by zakimimit** [RandomEngy/VidCoder#1266]
### Feature details

Hello 
I hope you are doing well,

Can you add more options to :
When file already exists (Batch) or single file:

Add pass

So if the file exists there no need to redo the conversion.

(If you can , add a system to check if the file has the same length or if the existing file is valid) 

My best regards

**Comment by RandomEngy** [comment]
Added this option in v11.3 Beta.

**Comment by RandomEngy** [comment]
It doesn't check if the file is valid. VidCoder by default will not write anything to the final output location unless the encode succeeded.
