### ISSUE TITLE
Vidcoder Beta - preset association

### ISSUE THREAD

**Issue by THRobinson75** [RandomEngy/VidCoder#1267]
### Problem Description

When I was using Vidcoder, whenever I shrank a series I would export the preset file to the series folder so next season I could use the same settings. I would double click the *.vjpreset file and it would show up in my encoding settings list.

With Beta, it doesn't. The file has an icon for vidcoder but doesn't open up into anything. I manually associated it with vicoder.exe but still nothing.

Last night, I formatted my C:\ and reinstalled everything, including Vidcoder Beta, and same thing happening... last time I uninstalled Vidcoder and installed beta, so thought maybe it was looking for the old version.

### What version of VidCoder are you running?

11.1 Beta

**Comment by RandomEngy** [comment]
Thanks. Looks like this broke when switching to the Velopack installer. This should be fixed in the 11.2 Beta.
