### ISSUE TITLE
EEDI2 Bob deinterlace filter

### ISSUE THREAD

**Issue by surlias** [RandomEngy/VidCoder#127]
This isn't really an issue, more of a feature request:

Is there any way you could implement a full deinterlacing filter with a quality level comparable to the EEDI2 Bob decomb filter? Decomb is great, but sometimes it just doesn't do a good enough job, especially in things like animation, or with small fast-moving objects in video (hands, mouths, etc).

Thanks so much for all your hard work on VidCoder! It's such a great program, I'd be lost without it.

**Comment by RandomEngy** [comment]
Thanks! You should ask the HandBrake devs about that; they write the filters; VidCoder is the UI.

**Comment by surlias** [comment]
I just compared the VidCoder filters options to the latest Handbrake build 0.10.5, and the filters options in Handbrake were different and more limited. For deinterlace the options are: Off, Custom, Fast, Slow, Slower, Bob.  For decomb the options are: Off, Custom, Default, Fast, Bob.

So in Handbrake, the deinterlace options are slightly more granular than VidCoder, but still maxing out at Bob for quality so they're roughly equivalent.

But for decomb there's no comparison! Your VidCoder UI has waaay more (and more advanced) decomb options. Am I comparing it with the wrong build of Handbrake?

**Comment by RandomEngy** [comment]
If you're using VidCoder Beta, the thing to compare it with would be a nightly build of HandBrake. VidCoder stable is roughly equivalent to HandBrake 0.10.5.

**Comment by surlias** [comment]
Ah, gotcha. Yeah, there's way too much awesome in the beta builds to bother with stable.

**Comment by surlias** [comment]
I posted on the HandBrake forum, and apparently this is already present in the Nightly builds! (and therefore your beta builds as well)

If you are interested, here's the full thread:

https://forum.handbrake.fr/viewtopic.php?f=26&t=35210
