### ISSUE TITLE
Doubled audio tracks with Track selection: Language(s)

### ISSUE THREAD

**Issue by mpek** [RandomEngy/VidCoder#1274]
### Problem Description

Hello, to encode quicker I set the audio track selection in picker settings to "Language(s)", but somehow all audio tracks are being added twice, if I leave them selected as is, the written file has them all doubled inside!

Vidcoder shows the tracks with desired languages,but doubled and you need to untick them to not encode them twice, but with a different Track selection setting they don't show doubled, but then you need to untick other languages that you don't want.

Picker settings:

Track selection: Language(s)
German
English
French
Unknown
Ticked: All tracks for these languages

I guess you could recreate this with different languages set and get the same result. If you want I can show you a screenshot....

### What version of VidCoder are you running?

Beta 11.3

**Comment by RandomEngy** [comment]
Hmm, I can't reproduce this. Can you share a sample video that this happens on, and a screenshot of the Audio section of the Picker?

**Comment by mpek** [comment]
I have installed version 11.4 now, and it seems to work as expected. Thank you for checking. Will let you know here, when it occurs again.
