### ISSUE TITLE
No subtitles found on blu-ray

### ISSUE THREAD

**Issue by Schtief** [RandomEngy/VidCoder#1279]
### Problem Description

Recently I have problems with newer Blu-ray releases and subtitles. VidCoder cannot find any, but I know there must be. The log does say nothing about it (no warnings or errors) and simply ignores them. But when I copy the video with MakeMKV there do exist subtitle streams (PGS). So this is my current workaround with MakeMKV, but I hope there is a future fix in VidCoder. How can I help further to investigate the issue?

### What version of VidCoder are you running?

10.14 VelopackInstaller

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by Schtief** [comment]
Same with HandBrake... I will put the issue to them.

**Comment by Schtief** [comment]
HandBrake issue
