### ISSUE TITLE
Ask where you are allowed to install!

### ISSUE THREAD

**Issue by miramanee** [RandomEngy/VidCoder#1285]
### Feature details

**Hello!**

I would like to use VidCoder. Unfortunately I can't start any portable, every version crashes under Win10. The attempt to install the program is aborted with a directory error message. According to my security log, the installation program apparently tries to install itself into the Windows user directory without being asked. So without asking where it should be placed. This directory is protected by my security software. Nobody installs programs there! That's what the "C:\Program Files" area is for.

What's all this nonsense? I mean, when you come to visit me, you hopefully you also ask where the toilet is and don't shit all over my apartment in comparison to the installation program.

Best regards, Janisha.

**Comment by RandomEngy** [comment]
I'd recommend looking over all of the [installation options](https://vidcoder.net/Documentation/Installation.html). There are ways where you can install to wherever you like.
