### ISSUE TITLE
Suggestion: Keep metadata.

### ISSUE THREAD

**Issue by CrunchyHotDogs** [RandomEngy/VidCoder#131]
Hey, so far I've found this software really easy to use, and everything with my encodes are going great. But I was just wondering if it is possible to keep the metadata for tracks within a mkv.

For example, the video and audio track names.

**Comment by RandomEngy** [comment]
The functionality would need to be present in the HandBrake engine before I can expose it with VidCoder.

**Comment by gordielachance** [comment]
https://github.com/HandBrake/HandBrake/issues/51

**Comment by RandomEngy** [comment]
@gordielachance That HandBrake issue is asking about preserving file creation and modification times (which VidCoder can already do). This issue is asking about preserving track metadata (names).

**Comment by gordielachance** [comment]
oups, sorry ! thanks.

> which VidCoder can already do

AMAZING !
