### ISSUE TITLE
hope can remove built-in preset list

### ISSUE THREAD

**Issue by wheyu** [RandomEngy/VidCoder#1311]
### Feature details

- A little bit of personal obsessive-compulsive disorder
- After adding custom presets, the built-in presets are a bit redundant

**thanks**

**Comment by RandomEngy** [comment]
You can collapse the folder so it doesn't take up a lot of room. Allowing users to change the built-in presets opens up a can of worms for app upgrades and corner cases like "what if the user deletes their last custom preset"? This will probably be low on the priority list.

**Comment by wheyu** [comment]
ok，thank you very much

**Comment by wheyu** [comment]
ok，thank you very much
