### ISSUE TITLE
3D support (HSBS etc) like BD3D2MK3D

### ISSUE THREAD

**Issue by anodynos** [RandomEngy/VidCoder#1318]
### Feature details

It would be great if VidCoder could support 3D (HSBS etc) like [BD3D2MK3D](https://forum.doom9.org/showthread.php?t=170828) does. 

I know 3D is rare these days, you can't even buy a 3D TV anymore, when almost all TVs were 3D enabled just ~10 years ago. 

But almost all mid-range projectors and above have 3D support, and there are many amazing 3D movies, worth watching again and again just for the spectacular 3D.

Also people have a lot of 50GB isos that could become 4-5GB without significant loss as and then shared, so it would be great to preserve this abandoned (by the big gangs) medium & art form.

Ideally it should support all different 3D methods: 
- Half-side by side (HSBS) 
- Half-top & bottom (aka Over/Under or HOU), 
- Full-SBS or Full-T&B (i.e double the resolution in 1 dimension, instead of 1920 x 1080, get a 1920 x 2160 with both frames for left/right eye.
- Frame Sequential 3D (double frame rate, each frame interleaved left/right eye)

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://github.com/HandBrake/HandBrake/issues/new/choose) to add it.

**Comment by anodynos** [comment]
Ok thanks, it's already open, but they aren't doing it.... https://github.com/HandBrake/HandBrake/issues/4547
