### ISSUE TITLE
Beta: 2.34 audio fallback bug

### ISSUE THREAD

**Issue by osexpert** [RandomEngy/VidCoder#132]
Notice some encoded movies were missing audio.

Log show the problem:
[00:54:25] Auto Passthru: no valid fallback specified
[00:54:25] Auto Passthru: passthru not possible and no valid fallback specified, dropping track 1

Very scary bug as it is dropping audio.

Repro:
Take High Profile. Change to MKV. In Audio remove everything, add new encoding:
Codec: Passthru
Type: Auto
Allow passthru for: all except TrueHD, DTS, DTS-DH, FLAC. Is probably doesn't matter what you check of here to reproduce the bug.
Fallback: AAC (avcodec)

Save as new profile.

Export profile: notice vjpreset file contains
"AudioEncoderFallback": null

PS: Not sure if important, but this profile was originally saved as copy of High Profile in VidCoder 1.5.34.  Then I installed the Beta and this profile came along. In the Beta I changed the profile further with the audio settings descibed above.

**Comment by osexpert** [comment]
I found a workaround: select something else than "AAC (avcodec)" in Fallback and then switch back to "AAC (avcodec)", then profile is updated.
Please fix.

**Comment by osexpert** [comment]
Another bug with this configuration: when i encode a file with MP2 audio and it goes to fallback it encodes AAC with 512kbps! Hansbrake works and uses 160 kbps (I see it sends -B 160,0 in cli). VidCoder gui show 160kbps for this config, so there is a probably bug in passing commands to HB when doing Passthru\Auto.

[02:25:09] Auto Passthru: fallback is AAC (avcodec)
[02:25:09] Auto Passthru: passthru not possible for track 1, using fallback
<snip>
[02:25:09]  * audio track 1
[02:25:09]    + decoder: Unknown (MPEG) (2.0 ch) (track 1, id 0x1)
[02:25:09]      + bitrate: 256 kbps, samplerate: 48000 Hz
[02:25:09]    + mixdown: Stereo
[02:25:09]    + encoder: AAC (libavcodec)
[02:25:09]      + bitrate: 512 kbps, samplerate: 48000 Hz

**Comment by osexpert** [comment]
Also missing option to not specify mixdown (eg. auto\default per HB).

**Comment by RandomEngy** [comment]
Thanks for the report with detailed repro steps! I've got a fix for the missing audio track ready for the next Beta release. As for the 512 kbps, in the latest HandBrake nightly I see it sending 512 kbps as well when it does the auto-fallback.

**Comment by osexpert** [comment]
Great.
512 in fallback if probably HB bug then. Strange that one can't set bitrate etc. for the fallback, but expected it to use same bitrate as when adding standard AAC (avcodec) encoding with auto bitrate (always see 160kbps in this case).

**Comment by RandomEngy** [comment]
Fixed the fallback in 2.35 Beta.
