### ISSUE TITLE
Crash when scanning

### ISSUE THREAD

**Issue by redratroph** [RandomEngy/VidCoder#133]
Vidcoder crash when Im scanning files here is windows crash log:

```
Podpis problemu:
  Nazwa zdarzenia problemu: APPCRASH
  Nazwa aplikacji:  VidCoder.exe
  Wersja aplikacji: 1.5.34.0
  Sygnatura czasowa aplikacji:  56cbe9d5
  Nazwa modułu z błędem: hb.dll
  Wersja modułu z błędem:    0.0.0.0
  Sygnatura czasowa modułu z błędem: 55774399
  Kod wyjątku: c0000005
  Przesunięcie wyjątku:   0000000000131d83
  Wersja systemu operacyjnego:  6.3.9600.2.0.0.272.7
  Identyfikator ustawień regionalnych: 1045
  Dodatkowe informacje 1:   555e
  Dodatkowe informacje 2:   555ef1bede80223b3ae00eb9327936f5
  Dodatkowe informacje 3:   a347
  Dodatkowe informacje 4:   a34707c29289bea9e5c2006333206f89
```

It happens many times with random files, can you please fix this? Im using windows server.

**Comment by RandomEngy** [comment]
You could try out the Beta. If that doesn't work, see if the HandBrake nighly also crashes on scanning those files.

**Comment by redratroph** [comment]
Yes, same problem with handbrake, I tested on normal and nightly build, same story.

https://github.com/HandBrake/HandBrake/issues/342

**Comment by RandomEngy** [comment]
You can report it to the HandBrake team. When they fix it, I'll pick up the update.

**Comment by redratroph** [comment]
Ok, I reported problem to them, hope they will fix this. Thanks.
