### ISSUE TITLE
Profile with Audio "Target stream: All" drops all tracks except track1

### ISSUE THREAD

**Issue by osexpert** [RandomEngy/VidCoder#134]
2.34

I have a profile with Audio
Target stream: All, Codec: PAssthru: Type: Auto
with passthru on all except TrueHD, DTS, DTS-HD and FLAC.
Fallback is AAC (avcodec).

I'm batch encoding many files via drag\drop, and i noticed:
-files with dual audio (eg. in AC3), only the first track is passed thru. track2 is dropped. Correct: both should have been passed thru.
-files with dual audio (eg. track1 DTS, track2 AC3), the first track is converted to AAC (avcodec) while track2 is dropped. Correct: track1 shoudl be converted to AAC, track2 should be passed thru.

So, "Target stream: All" in profile is misleading...in practice it works as Target stream: Track1

**Comment by RandomEngy** [comment]
What do you have in the Picker settings? It is set to include all audio tracks?

**Comment by osexpert** [comment]
Hmm..just now discovered the picker settings. It was set to default. Changing to all may fix the problem:-) I will test.
