### ISSUE TITLE
Please update address information on the Vidcoder program

### ISSUE THREAD

**Issue by loninappleton** [RandomEngy/VidCoder#14]
Hello RandomEngy,

  Since you moved I have been chasing around for a  link for email to the forum which I subscribed to daily.

  My recent update of Vidcoder (along with Handbrake)  shows that your old address is even on the program info and therefore difficult to find at Github.  My github registration is in place.  But I see nothing  but  programmer related info and not the usual forum page I had subscribed to by mail.

  I am not a programmer and am a casual user of Vidcoder.

If you could provide some instruction on how to reconnect I would be grateful.

I am lon at athenet.net and would appreciate a mail with the links requested and some detailed info 
within the program (forum link etc) for future releases..

thanks for Vidcoder

Lon

**Comment by RandomEngy** [comment]
Hey loni. The main program page is now vidcoder.net . GitHub is for source control and discussion (via issues) Not sure what you mean by "email to the forum". Do you want to get emailed when there is a new discussion or something?

**Comment by loninappleton** [comment]
On 12/26/2015 9:55 PM, RandomEngy wrote:
>
> Hey loni. The main program page is now vidcoder.net . GitHub is for 
> source control and discussion (via issues) Not sure what you mean by 
> "email to the forum". Do you want to get emailed when there is a new 
> discussion or something?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RandomEngy/VidCoder/issues/14#issuecomment-167377806>.
>


Hi RandomEngy,

   Lon here.  Yes, the email of new topics is what I was getting from 
codeplex.   Perhaps I should have said email _from_ the forum. The 
Github location is 'hard to read' for me and I don't see forum topics or 
a tab to go to it.  I'm mostly a lurker and view the topics sent in 
mail.  Most entries are more advanced than my usage.

Updating the info on the program "about Vidcoder" tab with the new 
address might help others as well.

Also the main page might have some old info.  Check to make sure DVD Fab 
hasn't been
discontinued for DRM issues.  I seem to recall that Feng Shui or 
whomever had a take down.
But confirm to make sure.  It may be just gossip.

  I have queried Doom9 for an unencumbered freeware tool to replace 
AnyDVD.  And Make MKV,  thatt came close to toasting my CPU so I used it 
maybe once.

Thanks for answering.


Lon in Appleton, WI

**Comment by RandomEngy** [comment]
The about page never had a link. I updated the links for "VidCoder homepage" and "Report a bug". Ideally there would be some separate place for non-issue discussion but GitHub doesn't have that right now, and the free hosted site runs on static content and can't have a message board. I think watching the GitHub project is your best bet right now.

DVDFab's site still seems to be up, though.

**Comment by loninappleton** [comment]
On 12/27/2015 10:22 AM, RandomEngy wrote:
>
> The about page never had a link. I updated the links for "VidCoder 
> homepage" and "Report a bug". Ideally there would be some separate 
> place for non-issue discussion but GitHub doesn't have that right now, 
> and the free hosted site runs on static content and can't have a 
> message board. I think watching the GitHub project is your best bet 
> right now.
>
> DVDFab's site still seems to be up, though.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RandomEngy/VidCoder/issues/14#issuecomment-167423123>.
>
Ok.  Yes,   Github is not real navigable for the casual user.

Here is the news on DVDFab:

http://www.ghacks.net/2014/03/11/dvdfab-domains-seized-alternatives/

mostly about shutting domains and social media supporting the product.

Code being what it is,  I'd think that a freeware alternative, no bells 
and whistles,  to do the technique
would be possible and valuable.  But due to DRM it may be  a "hot 
potato." :-)

Lon

**Comment by RandomEngy** [comment]
That story was from a year ago. It looks like it's up and running again. Does Passkey Lite not work for you? And I agree, GitHub is not great for non-programmers, but GitHub and vidcoder.net is what you're stuck with now, sorry.
