### ISSUE TITLE
2.37 Beta - Output is larger than limits defined on Sizing tab

### ISSUE THREAD

**Issue by awgiedawgie** [RandomEngy/VidCoder#141]
I just encoded my first file using 2.37 Beta, and the resulting video is 852x480, even though I have defined max width as 720, and Scaling Mode as Downscale Only.

The source is 720x480, and autocrop nips 2 pixels off the left side. So the the resulting video _should be_ 718x406, which is what every one of the previous videos in this set has come out to - all before 2.37 Beta. If I drop the max width down to 716, the predicted output size changes from 852x480 down to 716x404. 

![720](https://cloud.githubusercontent.com/assets/23329656/20088910/6135d1ea-a551-11e6-9ba1-d6a428ddc526.png)
![716](https://cloud.githubusercontent.com/assets/23329656/20088909/61334664-a551-11e6-9c17-190b864e5897.png)

**Comment by RandomEngy** [comment]
Yeah looks like something is going wrong here. Will take a look.

**Comment by RandomEngy** [comment]
Found the issue. Was determining whether to resize to the width or height based on the source aspect ratio, but was not accounting for PAR there. Will be fixed in the next Beta.

**Comment by awgiedawgie** [comment]
Great news! Will be looking forward to it. Thanks for all your work!

**Comment by RandomEngy** [comment]
Fixed in 2.38 Beta.
