### ISSUE TITLE
output file name problem

### ISSUE THREAD

**Issue by DannyND** [RandomEngy/VidCoder#143]
Hello everybody,

i have a problem with the output filename.
In my folder I have videofiles in .m2ts codec. These files have already the correct filename.
All I want is, that VidCoder encodes this filenames to .mkv and change the folder destination and overtake the filename.
For example:
ABC Filename S01E01.m2ts to 
ABC Filename S01E01.mkv

I can create this new filename with vidcoder but I'm not sure if E01 is also Title 01?
And I have many files and don't want to check every single output file.

The {source} command won't work, because my source is the complete folder...
I need something like {filename}, but I didn't found something about this.

Maybe you guys know more.
BR
Daniel

**Comment by RandomEngy** [comment]
Have you tried dragging the folder onto the VidCoder window rather than using the "Open DVD/Blu-ray Folder" option?

**Comment by DannyND** [comment]
OMG
It works! Thank you!
Didn't thought that is it that simple...
