### ISSUE TITLE
Failing on connection to worker.

### ISSUE THREAD

**Issue by twh110360** [RandomEngy/VidCoder#144]
Receiving following message attempting to encode from MKV to MP4:

# Connection to worker failed after 10 retries. Unable to find endpoint.
# Encode failed.

**Comment by RandomEngy** [comment]
There are some programs that mess with the inter-process communication VidCoder uses. You can try going to Tools -> Options -> Process and uncheck "Use worker process to encode" .

**Comment by twh110360** [comment]
Thank you.  That appears to have worked.
