### ISSUE TITLE
Setting subtitle

### ISSUE THREAD

**Issue by emmepi61** [RandomEngy/VidCoder#145]
I would like to point out that there is no way in latest version (even beta) could set a subtitle in a forced way. The check box can never be selected. This is despite the source file exists a forced subtitle.

**Comment by emmepi61** [comment]
![image](https://cloud.githubusercontent.com/assets/23417657/20237708/874931c4-a8da-11e6-9c1b-41b626d71517.png)

**Comment by RandomEngy** [comment]
Some subtitle types like UTF8 don't support a "forced" flag so it doesn't make sense to have that option enabled.

**Comment by emmepi61** [comment]
If it were as you say, because the source file is set as forced? And the player work perfectly forced subtitles. Only with VidCoder in recoding does not make them tick. It 'a limitation of the program is not a non-compatibility

**Comment by RandomEngy** [comment]
Let me explain a bit more. Some subtitles can have parts of them marked as "forced", meaning that they'll show even when the track is not selected. The "forced only" checkbox allows you to pick out only the parts that are marked that way. Not all subtitle types support marking pieces as forced. If you've got a subtitle track that doesn't support the flag, it doesn't make sense to let you ask for the "forced" ones only, because that would mean you would get *nothing* from the track.

**Comment by emmepi61** [comment]
Excuse me, but the idea that you have "forced" subtitle seems very wrong.
A trace of forced subtitles only contains phrases translated into the language in which you are listening to the film in the original film where they speak a different language
.
So this track contains ONLY the translated parts. Now of course this track can be inserted with VidCoder like a trace of the whole movie subtitles in the same language or a different language. But not having the check does not start automatically execution of the film but you must set depending on the player used. As if you could check the "Forced" box would automatically.
Now this VidCoder do not understand why not allow it ...
For me it is just a program bug.
I repeat: in the original is set to forced and automatic of course, and even if after re-encoded with the VidCoder refresher for example mkvtoolnix can automatically reset it, but it's an extra step and a hassle. All because the checkbox is grayed out ...
Thank you

**Comment by RandomEngy** [comment]
Having the subtitle track show up automatically is not controlled by the "forced only" / "solo forzati" function, it's controlled by "default" / "predefinito". Have you tried checking that checkbox instead?

"Forced only" does not control what happens to the output subtitles, it controls which subtitles are picked to be put in the output track.

**Comment by emmepi61** [comment]
Tank you
