### ISSUE TITLE
Allow Default of "Forced only" for subtitles

### ISSUE THREAD

**Issue by jdunne525** [RandomEngy/VidCoder#147]
Please add this option.  For all rips I do, I want only the forced subtitles.  I think this should be the default behavior since that is how a DVD normally plays.

**Comment by jdunne525** [comment]
Note I found that I can manually edit each video and select this option, but having it automatically set the option in the preset would be a huge time saver.

**Comment by RandomEngy** [comment]
Added in 2.39 Beta.
