### ISSUE TITLE
2.39 Not scanning files for dvd/bluray folder

### ISSUE THREAD

**Issue by crashff00** [RandomEngy/VidCoder#151]
Just updated beta to 2.39 (x64) and it will not scan/import any dvd source folders.

I rip all my dvds to HDD using AnyDVD/CloneDVD combination. this process hasnt changed in years. when I select the hdd folder for conversion, VidCoder beta is not even recognizing a folder has been selected. nothing shows in the logs. no scanning progress bar.  I can select the source DVD drive and it will detect and scan just fine.

There may be a possibility of issues due to recent security updates for windows, but Stable 1.5.34 does work using this same workflow, but I cant figure out how to get the preset from 2.3x into 1.5.34 with the same settings.

**Comment by crashff00** [comment]
I figured out the problem. I'm not sure /what/ is causing it though.   In CloneDVD, you can extract the dvd video files and put them wherever you want. You do NOT need to put them inside a Video_TS subfolder. Whatever was changed in VidCoder now refuses to even look for the content unless it is inside the Video_TS subfolder.

**Comment by RandomEngy** [comment]
Thanks for the report. This is fixed in 2.44.
