### ISSUE TITLE
Mouse and Keyboard freeze

### ISSUE THREAD

**Issue by maxshalamar** [RandomEngy/VidCoder#157]
I'm not saying Vidcoder is causing this just trying to eliminate the cause so I'm asking if anyone has experienced both mouse and keyboard freezing when using Vidcoder?

Using the latest stable version 1.5.34.0 

My mouse and keyboard drivers are all up to date so if no one else has had issues with this it's another thing I can cross off the list

**Comment by RandomEngy** [comment]
Never seen this happen. Does it happen when running an encode? Maybe it's an issue with overheating?

**Comment by maxshalamar** [comment]
Yes - always while encoding a batch of files - I'll grab a CPU diagnostics tool and run it while encoding to see if it is an overheating issue


________________________________

**Comment by maxshalamar** [comment]
Running speedfan while encoding and the temp got up to 72C so it does look like an overheating issue (seems to get hotter while encoding 1080p files) - running Vidcoder on 3 of the 4 CPU cores to try and leave some resources free for other things and see if I still get the free


Thanks for the reply


________________________________

**Comment by RandomEngy** [comment]
The beta has a CPU throttling feature that you might be interested in. It shows up in the process tab under Options. It should be in the stable release for 2.0 that will come out in a few days.

**Comment by maxshalamar** [comment]
Cool - I'll wait for the stable version


________________________________

**Comment by RandomEngy** [comment]
Okay should be in 2.43 Stable.

**Comment by maxshalamar** [comment]
thanks



________________________________
