### ISSUE TITLE
Beta 2.15.0.0 x64 "Output to source directory if possible" not working

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#16]
With "Output to source directory if possible" ticked, the files just end up in the folder specified in "Destination"

**Comment by RandomEngy** [comment]
Can you specify more specific steps to reproduce? I am seeing this work correctly. If you load in a video it should automatically change the folder listed in "Destination" to the start folder. Of course it won't apply if you manually override it. I also see it work correctly when you load in multiple videos.

Note that it won't work if your files are read-only or you don't have write access to the folder.

**Comment by iamjaydear** [comment]
I save .ts or .mpg files, sorted into folders. VidCoder is then used to make .mp4 files which are saved into the same folders, then the source files are moved elsewhere. Today it's back to normal!.  During the day I had been fiddling with the Picker, which throws a verbose error every now and then - and - my WD big external drive is a flaming nuisance because it shuts down if idle for a few minutes - but - that's where the files were being successfully read from, so it wasn't idle. I probably just had Win 8.1, VidCoder beta and the WD drive tied in knots. I did a chkdsk on the WD drive and it's OK according to that.

**Comment by RandomEngy** [comment]
Okay sounds like things are working.
