### ISSUE TITLE
decomb filter has been removed

### ISSUE THREAD

**Issue by lucabis** [RandomEngy/VidCoder#160]
Hello, because in the latest version decomb the filter has been removed?

**Comment by RandomEngy** [comment]
You want to choose "Decomb" under the "Deinterlace" option. It just got shuffled around a bit.

**Comment by lucabis** [comment]
Hello, in the 1.5.32 version, the screen video filters were present 5 options: stretch, decomb, deinterlace, denoise, deblocking. Now there are only four items: stretch, deinterlace, denoise, deblocking. Decomb is no longer present. perhaps in another window?

**Comment by RandomEngy** [comment]
As I told you, decomb is now a mode under the "deinterlace" option.
