### ISSUE TITLE
The arabic Subtitles bug

### ISSUE THREAD

**Issue by SAEED6199** [RandomEngy/VidCoder#164]
hello guys my name is Saeed I came here to tell you About a bug in VidCoder the Best Converter may be used fast easy and simple. when i Converter MKV file with Arabic subtitles to mp4  Damage the Subtitles and show some squares like this

http://www.m5zn.com/newuploads/2017/01/08/png//7d5deabd5d6cc68.png

And more than this

http://www.m5zn.com/newuploads/2017/01/08/png//0523e8f36e9a2fa.png

If you need some files like subtitles and mkv file with arabic subtitles np

https://mega.nz/#F!rRRHCLzA!z0_4D_SBYTmj7k4I-pZjiA

i don't know why but i will give you some Arabic fonts Maybe it'll help you ^^".

https://mega.nz/#!qYwCQApQ!TEkDR-sJpVuajg-aedtbIJ_jQaZkepKyq-NvAQ4sxWI

https://mega.co.nz/#!AgghmI7R!GRsIKruz2FL7G4uUba54N-Jo-UxuXMABwEChJUtyDFI

That's all I know so far, thank you for everything with happy greetings
SAEED ^^

**Comment by RandomEngy** [comment]
So you have a file with subtitles built in and some of them are lost in the conversion to mp4? This sounds like it may be a bug in the HandBrake core. I would test with HandBrake and report to them, then I can pick up the fix in VidCoder.

**Comment by SAEED6199** [comment]
i forgot to tell you every thing now is fine thank you very much
