### ISSUE TITLE
4K encode

### ISSUE THREAD

**Issue by Manojvb** [RandomEngy/VidCoder#165]
Hello,

Today i tried to encode a 4K rip... even though i mentioned width as 3840 my rips width is 1920... tried entering various values as width but output has width of 1920...

check vidcoder log here - http://pastebin.com/X5SVHB6Z

image for provided width value & auto selected value for output here - [url=https://postimg.org/image/bb7ixnywr/][img]https://s25.postimg.org/bb7ixnywr/error.png[/img][/url]

Regards
Manoj

**Comment by RandomEngy** [comment]
Your input video is 1920x1080; it wouldn't increase video quality to encode it as 4k. If you really want to encode it as 4k, choose Scaling mode: "Scale up/down to target"

**Comment by Manojvb** [comment]
Till version 1.5.35 it used to work on 1980x1080 input with downscale only setting... but after updating to latest version it does not work. I will try with scale up/down target setting & will let you know... Thanks for quick reply...

Regards
Manoj

**Comment by RandomEngy** [comment]
v2 had a breaking change on the sizing settings, so a v1.5 preset won't act exactly the same as a v2 preset. v1.5 didn't have the "scaling mode" option.
