### ISSUE TITLE
Norton AV snags v2.16 beta

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#17]
Filename: vidcoder-2.16-beta-x64.exe
Threat name: WS.Reputation.1Full Path: b:\***\vidcoder\vidcoder-2.16-beta-x64.exe

On computers as of 
12/27/2015 at 6:17:21 AM

Last Used 
12/27/2015 at 6:19:21 AM

Startup Item 
No

Launched 
No

Threat type: Insight Network Threat. There are many indications that this file is untrustworthy and therefore not safe

____________________________

vidcoder-2.16-beta-x64.exe Threat name: WS.Reputation.1
Locate

Very Few Users
Fewer than 5 users in the Norton Community have used this file.

Very New
This file was released less than 1 week  ago.

Medium
This file risk is medium.

____________________________

Source: External Media

Source File:
vidcoder-2.16-beta-x64.exe

____________________________

File Actions

Infected file: b:\***\VidCoder\ vidcoder-2.16-beta-x64.exe Repaired
____________________________

File Thumbprint - SHA:
645aa135f71c310b8d8228cba02561135b8b3dc28a235977ffab6fc8bd80ec8d
File Thumbprint - MD5:
Not available

**Comment by RandomEngy** [comment]
Whoa. They "repaired" it? I wonder what that did. I suppose I could digitally sign all the executables but I don't want to pay $170 per year for it. I'm guessing it will cool off when it gets more reports in for that exe.
