### ISSUE TITLE
VidCoder High-Contrast issues

### ISSUE THREAD

**Issue by FDinolfo** [RandomEngy/VidCoder#182]
It seems like VidCoder doesn't quite work right with Windows High-Contrast themes. Have a look at the picture below, you'll see one of the panels not respecting High-Contrast, while another does. This is with the 2.49 stable version on Windows 10.

<img width="1280" alt="example" src="https://cloud.githubusercontent.com/assets/6538286/22628060/1a7d53aa-eb9b-11e6-9b9e-a852c3793eea.png">

**Comment by RandomEngy** [comment]
Fixed High Contrast in 4.17 Beta.
