### ISSUE TITLE
No v2 release will scan a WTV file

### ISSUE THREAD

**Issue by benfodenNZ** [RandomEngy/VidCoder#184]
Finally upgraded from 1.5.35.0 (64bit) to various v2 releases from the first to the current (liking the new interface for encoding settings) but have found none of them will scan a WTV file (created by Windows Media Center TV Recorder), whether a batch of them are dropped onto the interface, or just an individual file.

Dropping WTV files onto VidCoder kicks off a VidCoderWorker process (at around 25% total CPU time) but there is no scan progress at all. With two clicks of the X, I can close the progress bar (but only for batch scanning - if scanning an individual file I am unable to Cancel it), however the Worker process continues to run - and attempting more scans will kick off more Worker processes too.

If I kill the Worker process VidCoder appears to skip to the next item in the batch with a new Worker process (and the progress bar advances). Doing that enough times that the end of the batch items is reached gives a not-very-informative error indicating the items could not be scanned.

In the end the only way I can scan and encode WTV files is to drop back down to 1.5.35.0 or older.

Hopefully a solution can be found to allow WTV files to scan and encode on v2.x

Thanks in advance!

**Comment by RandomEngy** [comment]
Hmm, not sure what's going on. Would it be possible to supply some files that reproduce the problem? http://vidcoder.net/Documentation/SubmittingBugReports.html

What happens when you go to Options -> Processes -> Uncheck "use worker process to encode"?

**Comment by benfodenNZ** [comment]
Hiya there. Thanks for the quick reply, On pCloud I'm uploading a couple of short WTV files, both of which fail on v2 (as do any longer files). I'm also uploading a few log files now that I've found them - 2 from v2 failures of WTV file scanning, plus an earlier one (Mythbusters) that was from v 1.5.35.0, which WAS successful.

I've tried turning off the Worker Process, restarted my PC after re-installing, tried many encoding profiles, changed some of the settings, but nothing is helping as yet. Sorry I don't have another PC available to test this out on at the moment.

The only difference noted is that trying to scan WTV files after turning off the Worker Process raised the CPU only to 10-15% usage.

Cheers

**Comment by RandomEngy** [comment]
Thanks for the files. This issue is in the HandBrake core. I opened this issue on them: https://github.com/HandBrake/HandBrake/issues/582 . If they fix it I can pull the fix into VidCoder.

**Comment by benfodenNZ** [comment]
Thanks for that, I'll stick with v1.x for now - if you're able to post a reply if an updated core solves this it'd be great. Fantastic product and a donation to AMF has been made. Cheers!

**Comment by RandomEngy** [comment]
Fixed in 2.50.

**Comment by benfodenNZ** [comment]
Works a treat. Many thanks for your awesome work and support.

Take care
