### ISSUE TITLE
VidCoder 2.15 & 2.16 beta Stalling on Windows 10 64-bit on Two-Pass Encodes

### ISSUE THREAD

**Issue by kphipps** [RandomEngy/VidCoder#19]
I'm using H.264 two-pass with turbo first pass. It will go through the first pass, then get about 1.5% into the encode and it just stalls. The interface doesn't freeze or lock up, but the 'percent done' display will just stay as, for example 51.5% (three different files stall at about 51.5%). If I click the 'Stop" button, it says 'Stopped Encoding', but the green progess bar stays active and stalled and the 'VidCoderWorker' process is still running, using about 30% CPU and I have to kill it in task manager.

I tried this on three different files and it does it on all.

Using fixed size without two-pass will complete successfully.

Constant Quality encoding doesn't seem to have this problem, but for some files I do need to use fixed size.

I tried encoding these same files on another machine running Windows 7 64-bit and they complete successfully.

I get the same behavior on both 2.16 beta and 2.15 beta (I haven't tried earlier betas).

The issue doesn't happen on 1.5.33.

**Comment by RandomEngy** [comment]
Hmm I remember some discussion in the HandBrake IRC channel about a 2-pass issue. Will take a look after work today.

**Comment by RandomEngy** [comment]
Should be fixed in 2.17 Beta. Took an update to the HandBrake core.
