### ISSUE TITLE
Doesn't save file until completed

### ISSUE THREAD

**Issue by LordChilde** [RandomEngy/VidCoder#192]
Earlier versions DID - this was very convenient when aborting after a  few percent simply to judge the quality.  Now it's tedious in the extreme, and wastes a great deal of time.  Restored 1.5.3

**Comment by RandomEngy** [comment]
What's wrong with using the preview function? It renders a small clip for you.

**Comment by LordChilde** [comment]
forgot about this thread. v2.50 does save aborted files now... must've been something amiss with the initial installation. Apologies.

I mainly use Vidcoder to upscale non-HD video for use in the Rift (and yes, upscaling sharpens pixels). Can't use preview function in the Rift, of course. 

Please delete thread.
