### ISSUE TITLE
Selecting alternate audio track on multiple files

### ISSUE THREAD

**Issue by kaufmanj1973** [RandomEngy/VidCoder#20]
I am trying to encode multiple video files that have several audio tracks.  Track #1 is in Russian, track #2 is in English.  I want to batch convert all the video files, but select ONLY the English audio track.  The only way I see to do this in Vidcoder is to add each file individually to the queue, selecting the audio track for each individual file.  Is there any way to tell Vidcoder to automatically select Audio Track #2 for all files?

**Comment by RandomEngy** [comment]
Yes. If you are using Stable you can find audio picking in Options, if using Beta you can find it in the Picker window. You can choose Language: English for audio and that will pick out the English track.

If the tracks aren't marked by language, you could choose to include all tracks, but make your Audio Encoding target Stream 2 rather than All.

**Comment by kaufmanj1973** [comment]
Didn't work.  It still will only let me assign the target audio stream PER FILE.  I have to add each file to the queue individually, rather than as a batch.  When I go into the profile settings, my only option is "All" for the audio stream.

**Comment by kaufmanj1973** [comment]
Didn't work. It still will only let me assign the target audio stream 
PER FILE. I have to add each file to the queue individually, rather than 
as a batch. When I go into the profile settings, my only option is "All" 
for the audio stream.

On 12/30/2015 9:53 AM, RandomEngy wrote:
>
> Yes. If you are using Stable you can find audio picking in Options, if 
> using Beta you can find it in the Picker window. You can choose 
> Language: English for audio and that will pick out the English track.
>
> If the tracks aren't marked by language, you could choose to include 
> all tracks, but make your Audio Encoding target Stream 2 rather than All.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RandomEngy/VidCoder/issues/20#issuecomment-168022999>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by RandomEngy** [comment]
You can only change to Stream 2 if you have a source loaded with two audio streams selected in the main UI.
