### ISSUE TITLE
A converting fail (solved:  source corruption)

### ISSUE THREAD

**Issue by CKDing** [RandomEngy/VidCoder#201]
Hello Admin,
I don't know much about converting video, so if I misunderstand 
something or do things wrong, I am very sorry.

VidCoder is my favorite, I have been using it for long time and have
converted hundreds video with it. Recently I was converting a video 
but always get broken image at same part. Log said no error though. 
After some trying, I found this problem seems only happened with 
VidCoder and Handbrake, not other software.

This is the problem part of that video, I cut it to 7 sec 13 MB:
[https://mega.nz/#!xnpFAB4Z!HROP3-9QEiR6xTyhTP5kYn9nP9TaCAOvysPuxiL1apc](url)

Screen capture of converting result, VidCoder and Handbrake are the same:
[https://ibb.co/hdTXD5](url)

**Comment by RandomEngy** [comment]
VidCoder uses HandBrake for the encoding engine. You can submit this problem to HandBrake and the fix will get picked up in VidCoder.

**Comment by CKDing** [comment]
After discussing in Handbrake forum, the problem has confirmed to be
a video source corruption.

Thank you admin. Your gui is best, much better than any other.
Please keep on great work.
