### ISSUE TITLE
Sorry, badly I speak English. The Windows 7 x64 + Net Framework 4.7 + VidCoder 2.51 x64 = doesn't work.

### ISSUE THREAD

**Issue by spikaspika** [RandomEngy/VidCoder#202]
Sorry, badly I speak English. The Windows 7 x64 + Net Framework 4.7 + VidCoder 2.51 x64 Portable = doesn't work. Can't find an entry point in the procedure. Handbrake too.

**Comment by spikaspika** [comment]
Sorry, badly I speak English. The Windows 7 x64 + Net Framework 4.7 + VidCoder 2.51 x64 = doesn't work. Can't find an entry point in the procedure.

**Comment by RandomEngy** [comment]
You need to install .NET Framework 4.6.2 for it to work. The .NET framework is a "side-by-side" thing, so a higher version won't necessarily make programs built on lower versions work.

https://www.microsoft.com/en-us/download/details.aspx?id=53345

The VidCoder installer automatically installs the framework as part of the install process but you need to do it manually for the portable version. The website *was* incorrectly telling you that you needed .NET 4 Client Profile, but I just updated the documentation.

**Comment by spikaspika** [comment]
Thank you very much for your answer. I'm a big fan of your program and I always try to get to the truth. In general, a little tormented, I understood what was happening and did everything the way you said. I wrote about this feature not because I did not understand it, but because you and other users knew about it. In general, the program is magnificent. Thank you for your work.
