### ISSUE TITLE
shutdown on finish does not work

### ISSUE THREAD

**Issue by w4hnsinn** [RandomEngy/VidCoder#203]
- currently using version 2.51 x64 portable
- Win 7 Pro x64
- user account has admin privileges
- also tried context menu: "run as administrator"

The issue also existed for previous (beta) versions, although I'm sure it worked on this system once in the past (may have been a year ago or longer though).

**Comment by RandomEngy** [comment]
Just tried it on my Win7 VM and it seems to work. Does it pop the dialog that warns that the system will shut down in 30 seconds?

**Comment by w4hnsinn** [comment]
Hmm. This is odd, I just tried it with a very short (3-sec) video clip, and it worked fine.

But whenever I do my regular (several hours) encodes through the night, I find the system still running in the morning (encodes complete).

Something else must be interfering then. Maybe Windows' power settings.. although they should not trigger while vidcoder is still active.. hmmm.

**Comment by RandomEngy** [comment]
So you have your computer set to go to sleep? When you come back is it awake or asleep?

**Comment by devildant** [comment]
hello,
i have same problem on windows 10, i lock my computer during encoding and after finish my computer never shutdown.

**Comment by RandomEngy** [comment]
Should be fixed in 2.59.
