### ISSUE TITLE
Quick question, about audio conversion only.

### ISSUE THREAD

**Issue by kairukun93** [RandomEngy/VidCoder#204]
I have been using vidcoder ever since i heard about it, and the most reliable video encoding software, of course it has handbrake source code, which the question is... is there a way to convert audio only without video, or do you use a CLI or Command line syntax? i recently figured out that you can convert 7.1 audio files from Blu-ray disc with atmos 7.1 which i want to convert it to 1024kb or more on Opus 7.1. so if there's a way to convert videos using CLI, let me know what are the syntax. thank you :) and have a nice day!

**Comment by RandomEngy** [comment]
There isn't a way to do just audio, and there isn't a way to preserve the video stream while converting audio. The video needs to be transcoded; that's a limitation of the HandBrake API.

VidCoder does have a command line, but it's for automatically queuing jobs and such, and doesn't expose anything more than what you can already do in the UI.
