### ISSUE TITLE
OGG Preset

### ISSUE THREAD

**Issue by wildgoosespeeder** [RandomEngy/VidCoder#208]
For MKV, I see Theora, Opus, and Vorbis encoders. Xiph.Org Foundation has a container format for these codecs, aside from MKV, OGG:

* [Container](https://www.xiph.org/ogg)
* [Codecs](https://www.xiph.org/doc)
* [Wiki](https://wiki.xiph.org)

Can this be implemented easily or is this related to issue #100 where VidCoder is dependent on HandBrake, the muxer it relies on and is restricted by it?

**Comment by RandomEngy** [comment]
You are correct, I'm reliant on the muxers provided by HandBrake.

**Comment by wildgoosespeeder** [comment]
Darn. I guess I'll have to create my own substitute then. Thanks for the reply.
