### ISSUE TITLE
Fallback audio bitrate is bonkers

### ISSUE THREAD

**Issue by osexpert** [RandomEngy/VidCoder#209]
Was encoding files with audio passthru for all supported codecs, but some had codec that had to be reencoded. I had selected mp3 as fallback codec.
Audio preview was showing 160 kbps.
After encoding I notice 32 kbps was used. I think aac and all other fallback codecs have same problem (I think aac uses 512 kbps while preview show 160 kbps).

Saw this code:
int previewBitrate = bitrate;
			if (previewBitrate == 0)
			{
				previewBitrate = HandBrakeEncoderHelpers.GetDefaultBitrate(encoder, previewSampleRate, previewMixdown);
			}

I think GetDefaultBitrate return 160 here, but this is abviously not what is used.

Main problem is there should have been a bitrate selector for the fallback codec. Could have a "Default" entry here (thou it will be wrong if using HandBrakeEncoderHelpers.GetDefaultBitrate) so I prefer not, better if VidCoder supply good defaults.

Value selected in new selector should be set in line 451 in AudioPanelViewModel.cs
bitrate = 0; //old
bitrate = bitrate from new selector; //new

JsonEncodeFactory.cs must also set this value from selector:
Line 210
if (!isPassthrough)
...
Line 223 add this
else
 audioTrack.Bitrate = bitrate from new selector;

I hardcoded 128 in code for testing, compiled and replaced VidCoderCommon.dll and it works, mp3 with 128 kbps is made instead of the bad default in Handbrake of 32 kbps. 

[07:28:26] json job:
{
  "Audio": {
    "AudioList": [
      {
        "Bitrate": 128,
        "DRC": 0.0,
        "Encoder": 1125984256,
        "Gain": 0.0,
        "Mixdown": 0,
        "NormalizeMixLevel": false,
        "Samplerate": 0,
        "Track": 0,
        "DitherMethod": 0
      }
    ],
    "CopyMask": [
      1073807360,
      1073743872,
      1090519040,
      1073750016,
      1074003968,
      1074266112
    ],
    "FallbackEncoder": 512
  },
  
  
  
  
[07:28:26]  * audio track 1
[07:28:26]    + decoder: Unknown (MPEG) (2.0 ch) (track 1, id 0xc0)
[07:28:26]      + bitrate: 200 kbps, samplerate: 44100 Hz
[07:28:26]    + mixdown: Stereo
[07:28:26]    + encoder: MP3 (libmp3lame)
[07:28:26]      + bitrate: 128 kbps, samplerate: 44100 Hz

I think Handbrake use bad defaults for all fallbacks, and HandBrakeEncoderHelpers.GetDefaultBitrate cant  be trustred.

Bitrate for fallback did not work before but works now after this was fixed:
https://github.com/HandBrake/HandBrake/issues/462

**Comment by RandomEngy** [comment]
Did you mean "After encoding I notice 32**0** kbps was used." ? I've noticed it defaults to quality 0 which ends up being a high bitrate. I assume they just want to make it as high a quality as they can, to get closest to "passthrough" quality, which seems like a reasonable thing to do.

I'm poking through the code and I see they use hb_audio_bitrate_get_best and hb_audio_quality_get_best in this case. I can update my preview code to reflect this behavior.

**Comment by osexpert** [comment]
No I mean 32. The original files had much higher bitrates, typically
222kbps mp2 audio. Sems Quality 0 means lowest possible, at least for mp3...
The solution is to send passthru bitrate to handbrake (user selectable in
vidcoder gui),anything else seems  pointless, I don't want random bitrates.

12. jun. 2017 8.12 a.m. skrev "David Rickard" <notifications@github.com>:

**Comment by RandomEngy** [comment]
Oh yeah you're right, the bitrate does affect it. Can you post the full log from your original attempt where you got 32kbps on the output?

**Comment by soundsfromsound** [comment]
Hello. I just wanted to confirm I also have this issue. No matter what options, the audio sounds underwater. 
(i.e. 32kbps insanely low quality audio) just as described above. I thought it was just my ears!

Just wanted to help!

**Comment by RandomEngy** [comment]
I've looked at it a bit more and it seems like it still pays attention to all the encoder settings set on the item, and combines it with the Fallback encoder, though the fallback is set as a global setting, and the encoder settings are on the individual audio encodings. I can add a workaround, but I'll ask the HandBrake devs if this is intentional and what's going on.

**Comment by osexpert** [comment]
I always use only passthru with fallback thus there is not encoder settings in gui at all for bitrate etc. only codec.
I tried to reproduce problem with all files getting 32kbps, but seems it is not consistent (or i was dreaming). now I seem to get approx half the original bitrate (mp2 vs mp3). weird...

**Comment by RandomEngy** [comment]
I think the quality you get just depends on what kind of junk you have left over in the bitrate/samplerate/quality/compression fields for your encoder. The UI fields to edit those are hidden because I assumed they were ignored for passthrough, but apparently they're being dredged up when the fallback happens.

**Comment by RandomEngy** [comment]
Fixed in 2.53. We now use the default bitrate when doing a fallback.
