### ISSUE TITLE
Overriding handbrake bug on temp folder locations

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#21]
I just discovered that handbrake has a major bug as described at https://forum.handbrake.fr/viewtopic.php?f=26&t=30559&p=158076#p158076

With windows, it ignore system settings for global and user temp file folder locations and forces them to the C drive. This is a terrible flaw and more so when users like me use a small SSD for the operating system.

Can you fix this since the handbrake team seems so nonchalant about addressing this?
Can you allow for user to set/point to their correct temp locations?

**Comment by RandomEngy** [comment]
HandBrake doesn't expose this, so I don't think VidCoder can override. However you can change the location of the TEMP directory in Windows, which may help: http://answers.microsoft.com/en-us/windows/forum/windows_7-files/change-location-of-temp-files-folder-to-another/19f13330-dde1-404c-aa27-a76c0b450818?auth=1

**Comment by BugMagnet** [comment]
My emp folder has long been moved from the C:\ drive SSD.  Handbrake doesn't honor the change and writes to the C: drive anyway.

**Comment by RandomEngy** [comment]
Sounds like you should talk to the HandBrake team. I can't control that at my level.
