### ISSUE TITLE
VidCoder 2.53 AAC Passthrough

### ISSUE THREAD

**Issue by JonnyThree** [RandomEngy/VidCoder#212]
Crash (Encoding Failed)
Settings: 
Audio Encoding - Codec: Passthrough - Type: AAC

Full log:

# Starting queue
## VidCoder 2.53 (x64)
# Starting job 1/1
#   Path: C:\Users\Gabriele\Desktop\Quinta puntata.mp4
#   Title: 1
#   Range: All
# Worker ready: Service state is Opened on pipe VidCoderWorker.7b804c46-ab51-463f-8916-a95d092d4955
# Connecting to process 3960 on pipe VidCoderWorker.7b804c46-ab51-463f-8916-a95d092d4955
[19:17:58] hb_init: starting libhb thread
[19:17:58] CPU: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
[19:17:58]  - logical processor count: 4
[19:17:58] Intel Quick Sync Video support: no
[19:17:58] hb_scan: path=C:\Users\Gabriele\Desktop\Quinta puntata.mp4, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:274: failed opening UDF image C:\Users\Gabriele\Desktop\Quinta puntata.mp4
src/libbluray/disc/disc.c:352: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:352: error opening file BDMV\BACKUP\index.bdmv
[19:17:58] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[19:17:58] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Gabriele\Desktop\Quinta puntata.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 02:24:26.22, start: 0.105375, bitrate: 1069 kb/s
    Stream #0:0(und): Video: h264 (High) [avc1 / 0x31637661]
      yuv420p, 768x432 [PAR 1:1 DAR 16:9], 1000 kb/s
      25 fps, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(ita): Audio: aac (HE-AAC) [mp4a / 0x6134706D]
      48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[19:17:58] scan: decoding previews for title 1
[19:17:58] scan: audio 0x1: aac, rate=48000Hz, bitrate=64000 italiano (AAC) (2.0 ch)
[19:17:58] scan: 30 previews, 768x432, 25.000 fps, autocrop = 2/0/0/0, aspect 16:9, PAR 1:1
[19:17:58] scan: supported video decoders: avcodec qsv
[19:17:58] libhb: scan thread found 1 valid title(s)
# Worker process crashed. Please report this error so it can be fixed in the future:
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in VidCoderCommon.AudioUtilities.GetDefaultSettings(SourceAudioTrack source, HBAudioEncoder encoder) in D:\docs\projects\VidCoder\VidCoderCommon\Utilities\AudioUtilities.cs:riga 18
   in VidCoderCommon.Model.JsonEncodeFactory.CreateAudio(VCJob job, SourceTitle title) in D:\docs\projects\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:riga 210
   in VidCoderCommon.Model.JsonEncodeFactory.CreateJsonObject(VCJob job, SourceTitle title, String defaultChapterNameFormat, Int32 previewNumber, Int32 previewSeconds, Int32 previewCount) in D:\docs\projects\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:riga 76
   in VidCoderWorker.HandBrakeWorker.<>c__DisplayClass9_0.<StartEncode>b__0(JsonScanObject scanObject) in D:\docs\projects\VidCoder\VidCoderWorker\HandBrakeWorker.cs:riga 166
   in VidCoderWorker.HandBrakeWorker.<>c__DisplayClass11_0.<StartEncodeInternal>b__0(Object o, EventArgs e) in D:\docs\projects\VidCoder\VidCoderWorker\HandBrakeWorker.cs:riga 213
# Encode failed.
# Job completed (Elapsed Time: 12s)
# Queue completed

**Comment by RandomEngy** [comment]
Should be fixed in 2.54.

**Comment by JonnyThree** [comment]
2.54, same crash here.

**Comment by RandomEngy** [comment]
Really? Are you sure it's exactly the same? I put some more logic in there that had a potential fix and more informative crash information.

**Comment by JonnyThree** [comment]
yes i have manually selected in audio encoding tab options
Codec: Passthrough
Type: AAC

here is the log:

## VidCoder 2.54 (x64)
# Starting scan: C:\Users\Gabriele\Desktop\Quinta puntata.mp4
[18:05:54] hb_init: starting libhb thread
[18:05:54] CPU: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
[18:05:54]  - logical processor count: 4
[18:05:54] Intel Quick Sync Video support: no
[18:05:54] hb_scan: path=C:\Users\Gabriele\Desktop\Quinta puntata.mp4, title_index=0
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:274: failed opening UDF image C:\Users\Gabriele\Desktop\Quinta puntata.mp4
src/libbluray/disc/disc.c:352: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:352: error opening file BDMV\BACKUP\index.bdmv
[18:05:54] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[18:05:54] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Gabriele\Desktop\Quinta puntata.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 02:24:26.22, start: 0.105375, bitrate: 1069 kb/s
    Stream #0:0(und): Video: h264 (High) [avc1 / 0x31637661]
      yuv420p, 768x432 [PAR 1:1 DAR 16:9], 1000 kb/s
      25 fps, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(ita): Audio: aac (HE-AAC) [mp4a / 0x6134706D]
      48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[18:05:54] scan: decoding previews for title 1
[18:05:54] scan: audio 0x1: aac, rate=48000Hz, bitrate=64000 italiano (AAC) (2.0 ch)
[18:05:55] scan: 30 previews, 768x432, 25.000 fps, autocrop = 2/0/0/0, aspect 16:9, PAR 1:1
[18:05:55] scan: supported video decoders: avcodec qsv
[18:05:55] libhb: scan thread found 1 valid title(s)
# Scan completed

# Starting queue
## VidCoder 2.54 (x64)
# Starting job 1/1
#   Path: C:\Users\Gabriele\Desktop\Quinta puntata.mp4
#   Title: 1
#   Range: All
# Worker ready: Service state is Opened on pipe VidCoderWorker.d2ecffdc-dad6-4d28-a9ab-201325e4a535
# Connecting to process 3340 on pipe VidCoderWorker.d2ecffdc-dad6-4d28-a9ab-201325e4a535
[18:06:18] hb_init: starting libhb thread
[18:06:18] CPU: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
[18:06:18]  - logical processor count: 4
[18:06:18] Intel Quick Sync Video support: no
[18:06:18] hb_scan: path=C:\Users\Gabriele\Desktop\Quinta puntata.mp4, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:274: failed opening UDF image C:\Users\Gabriele\Desktop\Quinta puntata.mp4
src/libbluray/disc/disc.c:352: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:352: error opening file BDMV\BACKUP\index.bdmv
[18:06:18] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[18:06:18] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Gabriele\Desktop\Quinta puntata.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 02:24:26.22, start: 0.105375, bitrate: 1069 kb/s
    Stream #0:0(und): Video: h264 (High) [avc1 / 0x31637661]
      yuv420p, 768x432 [PAR 1:1 DAR 16:9], 1000 kb/s
      25 fps, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(ita): Audio: aac (HE-AAC) [mp4a / 0x6134706D]
      48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[18:06:18] scan: decoding previews for title 1
[18:06:18] scan: audio 0x1: aac, rate=48000Hz, bitrate=64000 italiano (AAC) (2.0 ch)
[18:06:19] scan: 30 previews, 768x432, 25.000 fps, autocrop = 2/0/0/0, aspect 16:9, PAR 1:1
[18:06:19] scan: supported video decoders: avcodec qsv
[18:06:19] libhb: scan thread found 1 valid title(s)
# Worker process crashed. Please report this error so it can be fixed in the future:
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in VidCoderCommon.Model.JsonEncodeFactory.CreateAudio(VCJob job, SourceTitle title) in D:\docs\projects\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:riga 226
   in VidCoderCommon.Model.JsonEncodeFactory.CreateJsonObject(VCJob job, SourceTitle title, String defaultChapterNameFormat, Int32 previewNumber, Int32 previewSeconds, Int32 previewCount) in D:\docs\projects\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:riga 76
   in VidCoderWorker.HandBrakeWorker.<>c__DisplayClass9_0.<StartEncode>b__0(JsonScanObject scanObject) in D:\docs\projects\VidCoder\VidCoderWorker\HandBrakeWorker.cs:riga 166
   in VidCoderWorker.HandBrakeWorker.<>c__DisplayClass11_0.<StartEncodeInternal>b__0(Object o, EventArgs e) in D:\docs\projects\VidCoder\VidCoderWorker\HandBrakeWorker.cs:riga 213
# Encode failed.
# Job completed (Elapsed Time: 13s)
# Queue completed

**Comment by RandomEngy** [comment]
Thanks for the new log; looks like it's crashing in a different place now. Will take a look.

**Comment by RandomEngy** [comment]
Okay try 2.55, I was able to get a repro so I *think* it's really fixed now.

**Comment by JonnyThree** [comment]
yes now seems to be fixed. thanks so much for your time that you spent in this great project.
