### ISSUE TITLE
bitrate 

### ISSUE THREAD

**Issue by Ghastor** [RandomEngy/VidCoder#214]
hi !
There is a problem with vidcoder 2.54 for bitrate video and audio passthrough again.
File is bigger, bad calculation about 100kbps in bitrate tab, wrong.
With audio encoding, bitrate seems ok.
Any solution ?
Regards

**Comment by RandomEngy** [comment]
Ahh, I see the issue. I'm missing some logic in determining correct audio size when doing passthroughs and audio fallback. Will work on it in a week or so when back from vacation.

Thanks for the report.

**Comment by Ghastor** [comment]
Thanks for reply.
It's possible add a sort to final size target automatc  bitrate
 calcolatore for in queues? Fit to memory card, DVD or bluray

Il 22 Giu 2017 08:11, "David Rickard" <notifications@github.com> ha scritto:

**Comment by RandomEngy** [comment]
Should be fixed in 2.56.
