### ISSUE TITLE
excessive handles

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#22]
after running vidcoder 1.5 days processing over 200 videos, I am seeing over 60,000 handles left open and climbing. Only 5 other processes have over 1,000 handles in use and the highest is under 4,000.

[VidCoder excessive Handles problem 20151231.zip](https://github.com/RandomEngy/VidCoder/files/75836/VidCoder.excessive.Handles.problem.20151231.zip)

**Comment by RandomEngy** [comment]
I'm having trouble reproducing... The handles always hover around 1200 after videos finish. Could you try using Process Explorer to get more info?

https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

Select VidCoder.exe, make sure the lower pane listing the handles is open then choose File -> Save As.

**Comment by BugMagnet** [comment]
It is still running, uptime 37+ hours, completed 235 files.  63,392 handles

[VidCoder.exe handles bug 20151231.txt](https://github.com/RandomEngy/VidCoder/files/75841/VidCoder.exe.handles.bug.20151231.txt)

**Comment by RandomEngy** [comment]
Hmm, I think I might know what's going on. What version of VidCoder are you running?

**Comment by BugMagnet** [comment]
v1.5.33.0
handbrake v 0.10.2

After VC finished the last batch, I closed it and restarted. After 2 minutes, handles seemed to stabilize at 364. Then at 4 minutes, after opening help/about to see the version, I noticed handles had jumped to 571 where it staid even when the about pane was closed. At 9 minutes, 568 handles.
With nothing yet in queue.

Clicked the Source/Video file button and selected an .avi file but did not yet click [add to queue]: 998 handles
After [add to queue]: 995 handles
After delete from queue: 995 handles
after reloading same file again, using (Ctrl-O) without queuing: 1231 -> 1202 handles
after [Add to Queue]: 1187 handles
after delete from queue: 1199 handles
after reloading same file again, using (Ctrl-O) without queuing: 1390 handles
after [Add to Queue]: 1375 handles
After starting [Encode]: 1413 handles and vidcoderworker 980 handles
After completion:  1362 handles iow holding at 1000 more than before file was loaded and processed. Handles are not being closed or 'released' if that is the right word.

I'll test more with the latest beta now...

**Comment by BugMagnet** [comment]
well.. both v2.16 and v2.17 betas are erroring out and will not start for me, so I fall back to test more with the stable version

Added 226 files:  41,581 handles. Let the transcoding begin...

**Comment by RandomEngy** [comment]
I'll take a look at your issue with the betas. But I believe your issue should be fixed in the beta builds. Those have done refactoring where I immediately clean up the HandBrake instance rather than keep it around in the queue.

**Comment by RandomEngy** [comment]
I did some testing and 1.5.33 would build up threads while 2.17 would clean them up and stay steady.

**Comment by BugMagnet** [comment]
confirmed fixed
v2.19 took care of that other error on start issue also
