### ISSUE TITLE
File Target Size gives really random results

### ISSUE THREAD

**Issue by pizzaboyuk** [RandomEngy/VidCoder#220]
Not sure whether this is the result of 2.56 or 2.55, but my output files based on the target size now gives me a very large range of file sizes.

Prior to the update, setting the target size to 725MB gave me a file of around 735-745MB. Now, I'm getting files of around 790-900+MB.

Based on the 2.56 release notes, I'm guessing this is an issue with the newest release, so I've just rolled back to 2.55 to see if the problem still exists.

**Comment by RandomEngy** [comment]
I changed some code that estimates the size of the audio when doing size targeting. I'd need an encode log to tell you exactly what's going on.

**Comment by pizzaboyuk** [comment]
Confirmed.

2.55 is a lot more accurate when it comes to encoding using the target size (rather than specifying the bitrate).

How can I help? I just performed an encode (multiple files twice) with the attached preset using 2.56 and 2.55. [1.0 _ 720.zip](https://github.com/RandomEngy/VidCoder/files/1150846/1.0._.720.zip)

I've been using this preset for a while, so in terms of the output sizes, I can tell you with complete certainty that with at least a few versions prior to 2.56, a change is definitely affecting the output size.

**Comment by RandomEngy** [comment]
Thanks. I had an issue in detecting whether a track was passthrough eligible, but it should be fixed for the next release.

**Comment by pizzaboyuk** [comment]
Thanks a lot! Great job with the program!

**Comment by kphipps** [comment]
It seems that it is not taking the size of passthrough audio into account correctly when using Target Size encoding. I have the Target Size set to 340MB, but when using passthrough audio the file comes out over 380MB. When encoding the same file and also encoding the audio it comes out much closer to 340MB. Not sure if this is the exact same issue, but thought I'd report it here (v2.56).

**Comment by RandomEngy** [comment]
Should be fixed in 2.57.
