### ISSUE TITLE
'Target Size' encodes not hitting size target when using passthrough audio

### ISSUE THREAD

**Issue by kphipps** [RandomEngy/VidCoder#226]
I know this was supposed to be fixed in 2.57, but when encoding with passthrough audio, the file comes out too big. In this case, the source files have AAC audio. I set the target size to 340MB, but the result is file size of about 390MB. I'm assuming it is supposed adjust the video quality so that combined with the size of the source audio, it should be approximately the target file size. Maybe there's an issue with how it's detecting the size of the source audio.

**Comment by RandomEngy** [comment]
I have some diagnostics for the bitrate calculation in the logging. Can you provide an encode log to pastebin?

**Comment by kphipps** [comment]
[https://pastebin.com/AkuiuT34](url)

**Comment by RandomEngy** [comment]
Hmm, looks like it thought the audio was 0 bytes for some reason. I'll need to play around with it and see if I can get the same thing to happen.

**Comment by RandomEngy** [comment]
Okay I found the issue. HandBrake was unable to read the bitrate of the source audio track when doing the passthrough, so the audio's size could not be estimated. That's why it was off.
