### ISSUE TITLE
Can VC be configured to pass multiple audio formats?

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#23]
handbrake options:
        --audio-copy-mask   Set audio codecs that are permitted when the
                <string>    "copy" audio encoder option is specified
                            (aac/ac3/dts/dtshd/mp3, default: all).
                            Separated by commas for multiple allowed options.
        --audio-fallback    Set audio codec to use when it is not possible
                <string>    to copy an audio track without re-encoding.

I am noting in particular formats "Separated by commas for multiple allowed options"

My current project is to transcode files to be ROKU compatible. ROKU accepts AAC, AC3 and MP3 audio but not DTS or DTSHD, so support for
      --audio-copy-mask (AAC,AC3,MP3)
      --audio-fallback (AAC)
 would be useful.

If I understand current design, if AAC is selected, only AAC will be get a passthrough while AC3, MP3 and all others will be transcoded, right?

**Comment by RandomEngy** [comment]
That's right, it AAC is selected it would only accept AAC. I'll put it on the backlog.

**Comment by BugMagnet** [comment]
This appears to be working fine now in v2.20
thank you for the prompt attention to supporting this feature.
