### ISSUE TITLE
denoise filters problems

### ISSUE THREAD

**Issue by andrewschen** [RandomEngy/VidCoder#231]
When I change to custom preset of hqdn3d/NL-Means denoise filter, the colomn box is not blank but ALWAYS shows the following setting and can't be really deleted:

cb-frame-count=2:cb-origin-tune=1.0:cb-patch-size=7:cb-prefilter=0:cb-range=3:cb-strength=6.0:y-frame-count=2:y-origin-tune=1.0:y-patch-size=7:y-prefilter=0:y-range=3:y-strength=6.0

And now both the hqdn3d/NL-Means filtes don't work as they should be.

For NL-Means filter, the build-in presets (ultralight/light/medium/strong) now stucked at the same TUNE: with each preset, you can change between different tunes, but the encoded files always have the same filesize and visual.

For hqdn3d, it doesn't have tune option but the encoded file still seems somehow different from the files encoded by the working version of vidcoder/handbrake.

The situation happens in vidcoder versions after 2.36 beta, and some earlier version of handbrake (0.10.x), vidcoder version before 2.35 beta and Handbrake 1.0.7 works correctly.

I try to delete the VidCoder.sqlite file and let the software rebuilds it everytime before testing different version of software, but it doesn't seems to be the solution.

Anybody knows how to fix this?

**Comment by RandomEngy** [comment]
I see there's an issue with how VidCoder populates the Custom field. To work around it:

1) Delete everything in the "Custom" field
2) Change to the Denoise type you want (hqdn3d/NL-Means)
3) Pick a preset like Medium
4) Go back to Custom preset

It should now be populated with settings that make sense for that filter type.

**Comment by RandomEngy** [comment]
Fixed in 2.58.
