### ISSUE TITLE
Vidcoder trying to connect to something

### ISSUE THREAD

**Issue by eurobank** [RandomEngy/VidCoder#232]
I see VidCoder tries to connect to engy.us !

Not sure why since updates are off.

Thanks

**Comment by RandomEngy** [comment]
Engy.us is my domain and the auto-update information is stored there. It's possible that the options page is checking the available updates or something. It shouldn't be downloading the actual installers though.

**Comment by eurobank** [comment]
ok, then no problem. Worried a bit to see that warning from my Comodo firewall .

Thanks
