### ISSUE TITLE
The system hangs when transcoding MKV.

### ISSUE THREAD

**Issue by spikaspika** [RandomEngy/VidCoder#238]
Version 2.57
The program hangs the system on encoding MKV files. There is no regularity. Just any MKV.
Now moved to version 2.51.
v.2.57 portable, windows 7 Pro x64.

**Comment by Thermalzombie** [comment]
Post a mediainfo text specs I use it all the time for MKV to mp4 could be the type of file you are trying to convert.  When I have had issues in the past it was the audio codec used in the MKV I think it was flak.

**Comment by RandomEngy** [comment]
Does it also hang when using HandBrake? VidCoder uses the HandBrake encoding engine.

**Comment by spikaspika** [comment]
When encoding on HANDBRAKE everything goes fine. Hangs only on Vidcoder v. 2.57; 2.56. And on all MKV files, it does not matter which audio codec is used in the source file. I tried version 2.58 - everything works fine.
