### ISSUE TITLE
Trying to Re-encode MKV Videos

### ISSUE THREAD

**Issue by Grace2354** [RandomEngy/VidCoder#240]
I'm having trouble with re-encoding mkv files with dual audio, which I'm trying to do to save space. 
The video quality is fine, nothing is wrong with it when it's done encoding, but my problem is trying to figure out how to keep the two audio tracks and the subtitles.
The finished file has only one audio track and no subtitles. I've tried adding two audio encodings, and also two audio tracks, but nothing seems to be working. Help?

**Comment by RandomEngy** [comment]
In the Picker window, have you tried selecting Audio selection: All and Subtitle selection: All? You should only need one Audio Encoding in the encoding settings window.
