### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by immerzu** [RandomEngy/VidCoder#244]
System.ServiceModel.CommunicationObjectFaultedException: Das Kommunikationsobjekt "System.ServiceModel.Channels.ServiceChannel" kann nicht zur Kommunikation verwendet werden, weil es sich im Faulted-Status befindet.

Server stack trace: 
   bei System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   bei System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   bei System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   bei System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   bei System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   bei System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   bei System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   bei VidCoderCommon.IHandBrakeWorker.StopEncode()
   bei VidCoder.RemoteEncodeProxy.StopAndWait() in D:\docs\projects\VidCoder\VidCoder\Services\HandBrakeProxy\RemoteEncodeProxy.cs:Zeile 99.
   bei VidCoder.ViewModel.MainViewModel.OnClosing() in D:\docs\projects\VidCoder\VidCoder\ViewModel\MainViewModel.cs:Zeile 769.
   bei VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated) in D:\docs\projects\VidCoder\VidCoder\Services\Windows\WindowManager.cs:Zeile 518.
   bei VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e) in D:\docs\projects\VidCoder\VidCoder\Services\Windows\WindowManager.cs:Zeile 499.
   bei System.Windows.Window.OnClosing(CancelEventArgs e)
   bei System.Windows.Window.WmClose()
   bei System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report! This should be fixed in 2.60.
