### ISSUE TITLE
Suggestion / Feature Request

### ISSUE THREAD

**Issue by BDaddyG** [RandomEngy/VidCoder#245]
Good day!

I have a suggestion / feature request:

When opening a file (either by File -->Open, Enqueue Multiple Files, or Drag-n-Drop) have all the audio tracks from the video file selected, not just the 1st track.

I use MakeMKV to rip DVDs and that is where I select which audio tracks I want (just the primary track or the primary track and the Director’s Commentary, etc).  I have the “Audio Encoding” tab under “Encoding: Settings” in my Preset already configured to work with multiple audio tracks, so I just need to make sure I select all of the audio tracks when opening.

With the current process I have to open each video file individually and manually add additional audio tracks and I can’t use the “Enqueue Multiple Files” because the additional tracks are dropped.

I understand that not all users may wish this, so maybe this could be a Preference item?

Thanks for this great program!!

**Comment by RandomEngy** [comment]
Have you tried opening the Picker window and choosing "all" under the audio tracks section?

**Comment by BDaddyG** [comment]
Ah!  You are way ahead of me!  
I missed that option in the Picker window.  That is exactly what I am looking for.
Thanks for the quick response!
