### ISSUE TITLE
Destination file name

### ISSUE THREAD

**Issue by ThomasCSR** [RandomEngy/VidCoder#246]
When I want to convert a video I first set the time range. Then I change the Destination file name.
Then I look into sizing and other video settings.
During this process the Destination file name changes back!!! I found no pattern in this behavior.

**Comment by saxonz** [comment]
I add a video to convert, next I change the destination file name. I make sure the video and audio settings are correct. During this process the destination file name changes back to what it was when first added. I have found no pattern to this behavior. Only work around is to check the sizing and other audio and video settings right after a file is added to convert and then change the destination file name.

**Comment by saxonz** [comment]
Same as ThomasCSR.

**Comment by RandomEngy** [comment]
This should be fixed in 2.60.
