### ISSUE TITLE
AAC (avcodec) Quality

### ISSUE THREAD

**Issue by LeeThompson** [RandomEngy/VidCoder#248]
This is not a VidCoder issue since it's an issue with the underlying libraries but avcodec's AAC encoding is really quite horrible.    It seems AAC-FDK is no longer available for various reason but if there's any alternate legal AAC encoders, I'd like to request that VidCoder support them (I'll be posting a similar plea with the Handbrake people but they've always been extremely "hand wavey" even with debug logs so I expect it to go nowhere.)

**Comment by RandomEngy** [comment]
I'm stuck with what HandBrake provides.

**Comment by LeeThompson** [comment]
That's what I thought, bummer.
