### ISSUE TITLE
KNLMeansCL

### ISSUE THREAD

**Issue by mrlenny** [RandomEngy/VidCoder#249]
Can you implement the KNLMeansCL filter?
https://forum.doom9.org/showthread.php?t=171379

It has the quality of the nlmeans filter but utilizes the GPU to get the job done. The end result is spectualar. Currently the only tool I've found that implemented this filter is RipBot264, but they are missing some audio options.

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://handbrake.fr/community.php) to add it.
