### ISSUE TITLE
Audio distortion (AAC avcodec) chosen as output audio codec

### ISSUE THREAD

**Issue by mha2999** [RandomEngy/VidCoder#25]

**Comment by RandomEngy** [comment]
Usually distortion is a problem with the HandBrake engine. Can you try it with HandBrake?

**Comment by mha2999** [comment]
Same problem with HandBrake

**Comment by RandomEngy** [comment]
If HandBrake has the issue, you should report it to them. If they fix it I'll pick it up when I update the engine.

**Comment by mha2999** [comment]
Will do

**Comment by wessltov** [comment]
I think the issue is bitrate. I had the same issue, and changing the bitrate solved it

**Comment by liracobopu** [comment]
I too am having issues with audio distortion with avcodec on both the stable 1.5.34.0 and the latest beta 2.30. Switching over to the LAME MP3 codec solved my problems.
