### ISSUE TITLE
Target File Size with PGS subtitles

### ISSUE THREAD

**Issue by pizzaboyuk** [RandomEngy/VidCoder#251]
Not sure if this is related to: https://github.com/RandomEngy/VidCoder/issues/220, but source files containing PGS subtitles are affecting the result target file size regardless of whether the PGS is added to the target file or not.

For my preset, I've set the target file size to 725MB, this typically results in a file size around 745MB.

With a source file containing a PGS track when not added to the result file, I get a size of around 768MB though I think this varies depending on the size of the PGS track as I get 781MB with another video. When the PGS track is added, I get a file of around 793MB.

I'm using version 2.58, but also found the problem with 2.55. Haven't paid much attention to this issue before as typically the source files I've used tend to have SRT/ASS subtitles and these tend to be rather small.

**Comment by RandomEngy** [comment]
Can you post an encode log to pastebin?

**Comment by pizzaboyuk** [comment]
Include PGS: https://pastebin.com/RiJsrKVC
Exclude PGS: https://pastebin.com/N73e7KME

**Comment by RandomEngy** [comment]
Well the logic doesn't know how to estimate the size of a PGS so it's going to set the video bitrate to the same in both cases, which is what I see from the logs.

I did notice that I have a bug in the audio size detection logic; it's not properly adding the audio overhead when "same as source" sample rate is chosen. I can fix that and it should help a bit. But it won't help with PGS subtitles; I don't have a good way to estimate the size of those.

**Comment by pizzaboyuk** [comment]
Subtitle tracks aren't read the same as audio and video tracks? *shock* =D

Thought they would have been just been copied over (as with the "Same as Source" methods)...

Oh well...

Thanks for looking into it.

**Comment by RandomEngy** [comment]
The HandBrake API doesn't expose the total size of the subtitle track.

**Comment by pizzaboyuk** [comment]
No probs! Just assumed they would have. Thanks!

**Comment by RandomEngy** [comment]
The "Same as source" sample rate bug should be fixed in 2.60.
