### ISSUE TITLE
Upmixing an audio to 5.1

### ISSUE THREAD

**Issue by DannyJobsingh** [RandomEngy/VidCoder#258]
Vidcoder is one of the best converting tools that I have used. The features are user friendly and easy to understand.There is an option to downmix or passthrough the audio as required but also it would be great if there were an option to upmix the stereo to 5.1 audio.
Kindly add this little feature in the upcoming updates so that the old videos can also be converted to 5.1 audio which would be great.
![captu](https://user-images.githubusercontent.com/33077566/31976899-bd9706fa-b957-11e7-9c70-1579b9381fee.JPG)

**Comment by RandomEngy** [comment]
You can't just upmix to 5.1; the data doesn't exist to make the extra channels meaningful. It would just be a waste of space. It's up to the receiver or playback system to make the best use of the 2-channel signal.
