### ISSUE TITLE
Dear developers! This applies to ALL source file formats!

### ISSUE THREAD

**Issue by spikaspika** [RandomEngy/VidCoder#260]
The described effect was tested on dozens of files with all possible formats of source files.
Coding with a sound gain of 10 dB.
We change alternately the encoders built into the program.
Output result:
AAC - "gurgling" sound.
AC3 - Normal amplified sound.
MP3 - " ! Failed " - But the file is created with a questionable increase in sound.
Sorry for the bad english.

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

**Comment by spikaspika** [comment]
Many thanks, now I'll try.

**Comment by spikaspika** [comment]
I apologize for not immediately trying to check everything on HandBrake.
All the coding flaws I listed are completely present in HandBrake.
I will contact the developers HandBrake.
Thanks again.
