### ISSUE TITLE
SHUTDOWN when finish doesn't work if PC lock (windows 10)

### ISSUE THREAD

**Issue by devildant** [RandomEngy/VidCoder#262]
Hello,

i create this issue because, when i activate the shutdown and when i lock my computer during encoding, after complete the computer stay ON.
i watch the log but no erreur, the word shutdown appear but vidcoder do nothing if computer is lock.

i use windows 10.

best regards

[link to](https://github.com/RandomEngy/VidCoder/issues/203)

**Comment by RandomEngy** [comment]
Thanks for the report. I found the problem: the method I was calling doesn't work when the computer is locked: https://stackoverflow.com/a/5740235/92371 

I'll have this fixed shortly.

**Comment by RandomEngy** [comment]
Thanks for the report. I found the problem: the method I was calling doesn't work when the computer is locked: https://stackoverflow.com/a/5740235/92371 

Should be fixed in 2.59.

**Comment by devildant** [comment]
hello,

thx it's work perfectly.

great job.
best regards
