### ISSUE TITLE
External Subtitles settings won't load from Queue

### ISSUE THREAD

**Issue by Nightshade929** [RandomEngy/VidCoder#263]
Overall app works great... EXCEPT when external (.srt) subtitles are concerned.  If you try to queue mutiple video files with external subtitles, all subtitle settings ignored on Encoding. If you directly encode the subtitles are applied fine.

**Comment by RandomEngy** [comment]
The issue of course is where do you load the subtitles for each video? Do the external subtitles have the same name as the input file?

**Comment by Nightshade929** [comment]
To answer your questions:
1. The subtitle files are located in the same directory as the source video file.
2. All the SRT filenames match the filename of their corresponding source video file (except the extension of course)

As I tried to explain, If I encode them directly from the settings it works fine, it only has problems if you try to Queue multiple files.  When it loads from the queue it acts as if there is no subtitle information at all.  Embedded subtitles still encode fine from the queue, SRT subtitles won't.

**Comment by Nightshade929** [comment]
Sorry, kinda new to the whole Github thing... the close was accidental

**Comment by RandomEngy** [comment]
Oh so you had the subtitle attached when you queued it, but it didn't get applied when the encode happened? I was also considering adding an option to the Picker to automatically pick up .srt files the same name as the input file.

**Comment by RandomEngy** [comment]
This has been added in VidCoder v6.
