### ISSUE TITLE
[Feature] export selector and presets

### ISSUE THREAD

**Issue by devildant** [RandomEngy/VidCoder#265]
Hello,

I open this post to propose a feature.
Currently, it is possible to export the presets.
it may be interesting to export the selector with presets because it can be linked together.
would that be possible?

thanks for this app it is awesome and the interface is convenient.
best regards

**Comment by RandomEngy** [comment]
Thanks! Do you want to export the Picker? I was considering that but thought that the pickers would be a little less "shareable" than the encoding presets. What do you want to do with the exported picker?

**Comment by devildant** [comment]
Hello,
I would like save the picker because I linked each picker with presets.
for each picker I have a different name format with a custom language choice.
the purpose of this request was to be able to export my configuration on other pc without redoing every picker on all pc.
I made this type of configuration because it saves me time, I just have to select a picker to change the configuration :)

ps: also for backups :)

**Comment by RandomEngy** [comment]
Did you try copying %appdata%\VidCoder\VidCoder.sqlite ?

**Comment by devildant** [comment]
Hello,
I don't see sql file before. :)
I searched inside registry :p

Thx

**Comment by wkearney99** [comment]
The directory %appdata%\..\Roaming will have both the VidCoder-Beta and VidCoder folders.

Mine had been running 7.8 beta and 7.9 suddenly "didn't work" and 7.12-Stable didn't have my presets.  Copying VidCoder.sqlite from the beta to the release (while it wasn't running) solved that for me.

from a cmd prompt:

rename %appdata%\..\Roaming\VidCoder\VidCoder.sqlite VidCoder.sqlite.bak
copy %appdata%\..\Roaming\VidCoder-Beta\VidCoder.sqlite   %appdata%\..\Roaming\VidCoder
