### ISSUE TITLE
[BUG]  selector link to presets + rename presets

### ISSUE THREAD

**Issue by devildant** [RandomEngy/VidCoder#266]
Hello,

i detected one bug with selector and presets, the view crash.

for reproduce steps : 
1) create preset "toto"
2) create selector "titi"
2) create selector "toto"
3) in selector "toto" => encoding => check "use the predefined parameter" => select "toto"
4) select selector "titi"
5) edit preset "toto" and rename to "tata"
6) goto selector editor and click on "toto" selector
7) app crash

i don't copied the error but after my encoding i can put here the stack if necessary

I'm sorry, I'm attracting the bugs.

best regards

**Comment by RandomEngy** [comment]
Thanks for the report! This should be fixed in 2.60.
