### ISSUE TITLE
Feature request: support for TS container with loseless copying streams

### ISSUE THREAD

**Issue by retrofan1979** [RandomEngy/VidCoder#273]
Hi, I like VidCoder very much, but I do have a feature request.
Could you please add support for TS container as well besides MKV and MP4?
It would be nice if I could copy video, audio and VOBSUB subtitle stream into TS container without encoding as my cable receiver supports TS container with subtitles. With MKV and MP4 I don't have subtitle support, only TS. Would this be possible? This way I can copy from PS to TS.
Maybe it's also possible to add support for lossless copy for MKV without encoding, like MakeMKV does?
Thanks!

**Comment by RandomEngy** [comment]
Sorry, it's not possible to copy video streams; they have to be re-encoded. I use the HandBrake engine and that's outside of the scope they want to take on.

**Comment by retrofan1979** [comment]
Okay, I understand. Thanks for the fast reply.
