### ISSUE TITLE
suggestion: view synchronized source and destination videos

### ISSUE THREAD

**Issue by RobMielcarski** [RandomEngy/VidCoder#276]
When a rip completes I like to open the source and destination in 2 instances of a player like VLC, choose some appropriate scene, fiddle to get the 2 videos synchronized, switch both to full screen, and then alt-tab between the two instances to check for adequate quality of the rip compared to the source.

It would be wonderful to have this video comparison ability built in to VidCoder. 

I've always found it odd that none of the many encoding apps I've used over the years have this feature. You might be the first to do something unique and very useful.

Thanks for a great application.

**Comment by RandomEngy** [comment]
That's actually a pretty good idea. I'll put it on the backlog. Though I have a lot of stuff I need to get through before I get there.

**Comment by saxonz** [comment]
Ditto RobMielcarski's comment. Thanks.

**Comment by RobMielcarski** [comment]
Bump.

I still think this would be an awesome and unique feature. Please try to find time to implement it.

**Comment by saxonz** [comment]
Wonder why more people didnt jump on this one...as you stated no other software (I think) has a way to view synchronized source and destination video files to compare quility gain or loss. Only way is the Preview Clip, but not really the same thing.

**Comment by RandomEngy** [comment]
It's just a feature with a lot of complications. Sometimes the source is a blu-ray with no straightforward way to play it and no way to control the playback. Sometimes it might be a source that your PC doesn't have the drivers to play. It might also be one that the built-in WPF video player doesn't play nice with. Also I noticed that the built-in player sometimes has trouble starting in a timely manner. I think in .NET framework 4.8 they are upgrading the built-in video player so I might give it another look then.

**Comment by saxonz** [comment]
Sounds good. Thanks again **RandomEngy**.

**Comment by RobMielcarski** [comment]
I would have guessed that 90% of VidCoder users transcode hard drive based video but if the majority are ripping blu-ray then I see the problem. I still think it would be a killer and very unique addition to an already excellent application. Thanks for your great work.

**Comment by RobMielcarski** [comment]
Bump. 

VidCoder is brilliant and I use it almost every day. Thank you.

The above suggestion is the only significant feature that I miss. Perhaps there is a simple implementation that might get around some of the complications you listed?

How about a button to launch the source and destination videos in paused instances of VLC? The user can be responsible for synchronizing the videos. Any errors with unsupported video formats etc. can be handled by VLC.

Thanks for considering this suggestion.

**Comment by RandomEngy** [comment]
One more problem is that HandBrake does not expose at what time the preview clips start and there is no reliable way to compute them. So any attempts at opening a video side-by-side at the same moment won't work. I already have a shortcut to open the source video, so there isn't a lot of value I could add in a "compare" feature.

Anyway I think HandBrake would need to expose something more useful before I could add much of value.

**Comment by RobMielcarski** [comment]
I think I may have been unclear and you may have misunderstood my suggestion.

I am proposing a button, perhaps next to the "X" used to remove an item from the queue, that appears after an encode has completed, and that when pressed opens both the source and destination videos in separate instances of VLC, preferably but not necessarily in a paused state. Synchronizing the two videos will be the responsibility of the user.

It's a baby step that will still be very useful for fussy encoders like myself that always check quality after an encode completes.

Perhaps some years down the road it might be possible to synchronize the videos automatically but I suggest we walk before running.

**Comment by RandomEngy** [comment]
It wouldn't be quite as much use if you need to encode the whole video to do the comparison. Still, I poked around with the VLC command line, but there's not been much help. --width, --height, --video-x and --video-y don't seem to work. --start-paused makes it show no video at all. Also don't see a "seek to X time" option.

I did take another look at my built-in player and actually it seems to have pretty good codec support now. It even played H.265 encoded clips. I could just open another window with two of them side-by-side and sync them both to the same seek bar. I think I could even do a zoom-in compare of a part of the picture if that would be helpful.

**Comment by RobMielcarski** [comment]
I find these days with the new Ryzen 7 processors that ripping is very quick. It's no big deal to repeat a rip with different settings if the quality is not good enough. Or maybe it's because I'm over 60 and no longer in a big rush. :)

I'd be more than happy to use your built-in player. 

Zoom might be useful, but having both players in full screen mode and being able to alt-tab back and forth between them is a more important priority.

Thanks for any progress on this suggestion.

**Comment by RandomEngy** [comment]
Added this feature in 6.14 Beta:

![image](https://user-images.githubusercontent.com/9450861/93010178-5620f780-f53e-11ea-8f31-e2d3279625b1.png)

**Comment by RobMielcarski** [comment]
Just tested the compare feature. It's brilliant and better than I had hoped.  

Thank you very much!  It will save me a lot of time.

I love that I can scroll anywhere within the video to find a scene suitable for careful scrutiny.  Sync seems to be good.

Two small suggestions, both of which you can ignore and I'll still be happy.

I would prefer you enable the audio or provide an option to turn it on. I like having the audio on to help my brain interpret the video, and it's also useful for confirming I did not make an error by selecting the wrong audio track for encoding. 

I would prefer spacebar was used for the more traditional play/pause function. Perhaps another key like Alt could be used to toggle between original and encode.

Thanks again.

**Comment by RandomEngy** [comment]
I had left the audio off because I thought it would distract from the visual comparison, but I can make it an option. I was also hoping to avoid including a volume control... but maybe I'll just set it to 50% and see if anyone complains. I wanted to have spacebar to play/pause because swapping would be the primary action in this window and spacebar is the easiest button to hit. But I do appreciate that we have a lot of muscle memory for play/pause.

**Comment by RobMielcarski** [comment]
Just tested 6.16. 

Perfecto! Thank you very much.

I'm happy now but I have a suggestion you might consider for attracting new users. Your compare feature is unique and makes VidCoder stand out from the competition. You might consider making it more visible rather than requiring a right click. Perhaps a button in the main toolbar, or next to the list of completed file names?
