### ISSUE TITLE
Preserve folder structure not working?

### ISSUE THREAD

**Issue by mikeatlarge** [RandomEngy/VidCoder#28]
In settings I've set a default output folder and enabled "preserve folder structure in batch encodes." When I add files either individually or with "enqueue multiple files" from various subfolders the output files are all placed directly in the output folder with no subfolders. Am I missing something or is this a bug? This is Win7 x64 and VidCoder 1.5.33.0

My hope is VidCoder will let me batch transcode a large number of camcorder files that are currently sorted in folders without having to edit a destination path for each file. Thanks for your help and VidCoder otherwise looks great so far.

**Comment by RandomEngy** [comment]
If you add the files individually it won't put them in subfolders as it won't know how far up the tree to go. It should work if you drag a folder onto the UI, as it will use that folder as the root.

**Comment by mikeatlarge** [comment]
Thank you. It now works as expected. The drag and drop wasn't working previously as I had not added ".MTS" to the recognized files list. And, I haven't figured out why (it's likely a video setting), but VidCoder is a bit faster than Handbrake while using less CPU. Handbrake often uses near 100% CPU (on a 4 core i7) and VidCoder only uses around 50% maximum. I prefer the VidCoder behavior as my PC runs cooler and quieter. Thanks again!

**Comment by RandomEngy** [comment]
Well actually I wouldn't expect VidCoder to run faster with less CPU! You can limit it to 50% CPU with VidCoder's throttling feature, but I wouldn't expect it to run faster than HandBrake in that case. The speed can depend on the x264 preset you use, a resize filter, whether or not you use QSV and a host of other things. Glad you resolve your issue!
