### ISSUE TITLE
CPU throttling not working

### ISSUE THREAD

**Issue by saxonz** [RandomEngy/VidCoder#282]
This is the version being tested:
![000](https://user-images.githubusercontent.com/24868148/33589506-b2d39760-d946-11e7-92a6-f0fce14d1026.PNG)
This is the selected settings:
![001](https://user-images.githubusercontent.com/24868148/33589505-b28d7e24-d946-11e7-93b7-983f0bca95d9.PNG)
This is the result:
![002](https://user-images.githubusercontent.com/24868148/33589507-b2f4b300-d946-11e7-989d-3c5c3d0c68c3.PNG)

**Comment by RandomEngy** [comment]
Thanks for the report. I have a fix ready for the next beta version.

**Comment by saxonz** [comment]
Thank you for the quick reply. VidCoder is great. Thank you and keep up the good work.

**Comment by RandomEngy** [comment]
Should be fixed in 3.5 Beta.
