### ISSUE TITLE
Feature Suggestion: Multiple Simultaneous Encodes

### ISSUE THREAD

**Issue by jlikens** [RandomEngy/VidCoder#283]
On high-core-count machines (i.e. on a Threadripper 1950X), a single instance of Handbrake does not even come close to utilizing all of the cores.  It would be great to have an option somewhere in the settings to select the number of simultaneous encodes to run.  

I took a look at the code and it seems to be very hardened around the idea of a single encoding session, so this feature would likely take a bit of rework.  However, I do think this would be a great enhancement to more fully take advantage of the new breed of many-core consumer-level CPUs.

**Comment by RandomEngy** [comment]
Thanks for the input. This is actually on my list of features to add. It's just behind a few others that I also want to get done.

**Comment by RandomEngy** [comment]
Added this in 4.4 Beta. Go to Global Options -> Process -> Maximum simultaneous encode jobs.
