### ISSUE TITLE
Worker process exited unexpectedly with code -1073741819

### ISSUE THREAD

**Issue by mswindowsinside** [RandomEngy/VidCoder#285]
Hi,

I'm trying to encode FRAPS uncompressed files to H264 and H265 files, but every once in a while one of the files fails to encode after reaching 100%

```
# Worker process exited unexpectedly with code -1073741819. This may be due to a HandBrake engine crash.
# Encode failed.
```

The resulting file is unplayable, I'm getting this with both H264 and H265.

[h265 VHS TDK E180 - 0.00.08-3.06.24.mp4 2017-12-10 00.51.44.txt](https://github.com/RandomEngy/VidCoder/files/1545598/h265.VHS.TDK.E180.-.0.00.08-3.06.24.mp4.2017-12-10.00.51.44.txt)

[H264 25 jarig huwelijk.mp4 2017-12-05 16.06.03.txt](https://github.com/RandomEngy/VidCoder/files/1545610/H264.25.jarig.huwelijk.mp4.2017-12-05.16.06.03.txt)

I've tried these versions, but all have the same problem:
VidCoder 2.60 (x64)
VidCoder 2.62 (x64)
VidCoder 3.3 Beta (x64)

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

**Comment by mswindowsinside** [comment]
Same deal with Handbrake, only it quits instantly and doesn't write an error to the log.
Reported it in Handbrake's github, hopefully will get an answer soon :)
