### ISSUE TITLE
[Feature Request] Direct Audio Copy

### ISSUE THREAD

**Issue by HunDev** [RandomEngy/VidCoder#290]
Copy an audio track without re-encoding

**Comment by RandomEngy** [comment]
Have you tried using the Passthrough option on the audio tab?

**Comment by HunDev** [comment]
Ahh sorry... translation for my locale is wrong...
I will use the original english interface

**Comment by RandomEngy** [comment]
I welcome you to correct the translations here: https://crowdin.com/project/vidcoder . I can make you an editor to give you control over that language.

**Comment by HunDev** [comment]
Russian is marked as 100% )
But translation of this sound copy option is sound's like "run sound in a circle"

**Comment by RandomEngy** [comment]
100% means that every string has a translation, but that doesn't mean it's any good. You can propose an alternate translation. I can also make you an editor so you could improve whatever translation you like.

**Comment by HunDev** [comment]
Ok I can help with the translation correction (Russian)
And btw here is bug when using sound copy option
Original file
Audio: AAC 48000Hz stereo 256kbps [Core Media Audio - MPEG-4 Audio (eng) (AAC, 48.0 kHz, 2 chn, 16 bit, 256.0 kbit/s)]
New file
Audio: AAC 48000Hz stereo [Stereo - MPEG-4 Audio (eng) (AAC, 48.0 kHz, 2 chn, 16 bit)]

no bitrate info (mp4)

**Comment by RandomEngy** [comment]
Thanks! What is wrong with the copying? It looks like it's exactly the same to me: 48 kHz, 2 channel, AAC.

**Comment by HunDev** [comment]
256.0 kbit/s missing in info
No bitrate info

**Comment by RandomEngy** [comment]
So it sounds like the passthrough is working correctly. It's just missing the metadata on the stream. VidCoder uses HandBrake for its encoding engine; You can ask the HandBrake team about that.
