### ISSUE TITLE
[Feature Request] Prevent Upsampling of Video Encoding Bitrate

### ISSUE THREAD

**Issue by pizzaboyuk** [RandomEngy/VidCoder#291]
So I have a video with an average video bitrate of 1200kb/s.

I want to take a 3 minute cut of the video at the best visual fidelity possible. Why does VidCoder not override my preset settings if I set a fixed bitrate? Why isn't there an option like the for the Resolution Sizing to "Downscale Only"?

At 1200kb/s my file came out at 28.5MB.
At 1800kb/s it gave me 41.3MB.
Isn't the quality of both of the files exactly the same?

**Comment by RandomEngy** [comment]
No. You *always* lose quality when you do a lossy re-encode. The bitrate/quality setting is just about how close to the original you can get. VidCoder/HandBrake doesn't have the ability to pass through video unchanged.

**Comment by pizzaboyuk** [comment]
Thanks RandomEngy, wasn't aware that was how video bitrate worked.

How do I a 1:1 quality, if I only wish to crop a section of a video then?

**Comment by RandomEngy** [comment]
Well if you don't want to lose *any* quality, you would want lossless encoding, which is RF 0. But that's going to be an incredibly huge file, I suggest picking a quality number that makes sense so you don't degrade the picture too much (for x264, you might pick 18 or 20).

**Comment by pizzaboyuk** [comment]
Using RF could potentially mean my finished file is larger than my input file (if I did a 1:1 copy of the entire thing)?

Any way to guestimate the size (quality) to approximately the same as the input file (not ruling out other apps available)?

**Comment by RandomEngy** [comment]
There's nothing that I know of that does that. Usually people are more concerned about the settings to preserve the existing picture quality and avoid further degradation from re-encoding. The quality target is going to work equally well on high bitrate sources as low ones.

**Comment by pizzaboyuk** [comment]
Thanks
