### ISSUE TITLE
Deleting source file after completion

### ISSUE THREAD

**Issue by dorianps** [RandomEngy/VidCoder#292]
First, thank you so much for Vidcoder, is does a great job in a simple elegant manner. I have chosen it to convert all my DVD collection in h.265 (hvec) format, after looking several other commercial bad alternatives.

Since I am running long batch jobs, I am trying to let the computer run the longest possible. Longer batches mean many .iso files, on top of which new .mp4 files are created. My hard disk space if quickly filled. The best solution for me would be to start with storage almost full of .iso files, then delete them one by one as Vidcoder completes the conversion. This would allow me to run the maximum number of jobs without risking to fill the HDD any more than it is at the starting point. 

Question is:
Is there a way to make Vidcoder delete the source file? I've seen an advanced option that is supposed to delete the source file, but it hasn't worked so far. Is there any other way to tell vidcoder to delete the .iso file once it's converted, while it goes through the queue?

Note that I keep the source and output files in separate folders (i.e., "\iso" and "\mp4") for compatibility reasons with my NAS storage, where all the data is synced.

Any help is appreciated.
Thank you

**Comment by RandomEngy** [comment]
There is an option to delete the source file, but that is only after manually clearing the completed items. My thought was that you would want to make sure the encode went OK before deleting the source. I could add an option to allow immediate deletion as well.

**Comment by dorianps** [comment]
That would be fantastic. It would complement well the existing "with
confirmation".

If you manage to push the new option on a nightly, please let me know. I am
currently on Vidcoder 3.3 beta.

Thank you.

**Comment by RandomEngy** [comment]
I'm not sure how it would work with the confirmation, exactly. Maybe when you start the queue and the picker is set up to delete the source...

**Comment by dorianps** [comment]
Perhaps I didn't explain well. What I need is just automatic deletion
"without confirmation". This deletion should also be done after each file
is completed, and not wait until the whole queue is done, which can be of
hundreds of files. The deletion/elimination should not be the standard
Windows thing that moves to trash, because that does not free space, but
the type of elimination that frees space.

I thought this option can be placed next to the existing one on the GUI.
And since these are mutually exclusive, they will need to be radio buttons,
or something like a mutually exclusive choice.

I hope this is not asking too much. Perhaps it will come handy to a lot of
people that are not interested at all in keeping the source files. I don't
need to check the result because I have already spent a couple of weeks to
choose the right parameters for Vidcoder, I know it will produce a good
result.

Thank you.
Dorian

**Comment by RandomEngy** [comment]
This is implemented in v7.0 Beta. You can find the options in the Picker window under the Post-encoding section.
