### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by immerzu** [RandomEngy/VidCoder#295]
System.TypeInitializationException: Der Typeninitialisierer für "VidCoder.Model.Database" hat eine Ausnahme verursacht. ---> System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\home\AppData\Roaming\VidCoder\Backups" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
   bei System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   bei VidCoder.Model.Database.FindBackupDatabaseFile() in D:\GoogleDrive\projects\VidCoder\VidCoder\Model\Database.cs:Zeile 235.
   bei VidCoder.Model.Database.HandleTooHighDatabaseVersion(Int32 databaseVersion) in D:\GoogleDrive\projects\VidCoder\VidCoder\Model\Database.cs:Zeile 112.
   bei VidCoder.Model.Database..cctor() in D:\GoogleDrive\projects\VidCoder\VidCoder\Model\Database.cs:Zeile 47.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei VidCoder.Model.Database.get_Connection()
   bei VidCoder.App.OnStartup(StartupEventArgs e) in D:\GoogleDrive\projects\VidCoder\VidCoder\App.xaml.cs:Zeile 83.
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. I'll fix this is in the next Beta version.

**Comment by RandomEngy** [comment]
Fixed in 3.6 Beta.
