### ISSUE TITLE
Encoding Movies to X265 10bit or high10

### ISSUE THREAD

**Issue by kairukun93** [RandomEngy/VidCoder#296]
It's not really an issue, just for the sake of experiment! i notice that when i encode movies with x264 and x265 in 8bit, its a little washed out in vidcoder, but when i do encoding from DVDFab 10 x64 with x265 10bit codec with Cuda Lightning-shrink, it look very saturated and it looks like the original but... it's not refined due to quick and simple encoding feature they have with DVDFab, so if there's a way to encode x265 (HEVC) 10bit encoding with vidcoder, it would be sweet, and also is there by any chance that vidcoder may support NVENC (cuda) GPU encoding in the future??

**Comment by RandomEngy** [comment]
VidCoder beta has 10-bit x265 encoding. You'll have to ask the HandBrake devs about CUDA hardware encoding.

**Comment by kairukun93** [comment]
ok, thanks!

**Comment by kairukun93** [comment]
also is there a command for high10, because i notice when i encode a video, it only goes with main10 instead of high10. If there's a option like a "--" command for profile-high10 it would be great!

**Comment by RandomEngy** [comment]
I get the list of profiles from the HandBrake core library. If they make high10 available there, it will be added to VidCoder.

**Comment by kairukun93** [comment]
so you're saying at the moment on Vidcoder beta doesn't have the high10 profile? ok I guess i'll wait till it's added! thanks for the info! :)

**Comment by saxonz** [comment]
I don't see a place in the GUI of VidCoder to select 10bit, so I will assume that you are talking about the command line version. I too await a way to encode in 10bit x265 main10 / high10.
