### ISSUE TITLE
Encoding not working when frame-based range is used with several audio streams

### ISSUE THREAD

**Issue by meganone** [RandomEngy/VidCoder#298]
Hi

I'm using the latest beta of Vidcoder (3.5).

I loaded an MKV file (made using MakeMKV from one of my blurays) to encode it. I use x265-10 bits for video and Ogg Vorbis for audio tracks.

I selected a frame range to get rid of a logo placed before the movie. I selected two audio tracks (French and English, both DTS), launched the encoding and went to bed. The next morning, nothing had been encoded.

After some testing, I noted that encoding worked fine with just one audio track selected. If you select more, Vidcoder doesn't encode the movie. Also, as soon as encoding starts, the "encode details" window immediately show a progress of 3% which remains unchanged for as long as you let Vidcoder run.

So it seems that Vidcoder cannot encode a movie if you select a frame range and multiple audio tracks.   

Thanks for your attention.

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

I tried encoding a frame range with 3 audio tracks and it worked for me, so it may be something specific to encoder settings or the source video.

**Comment by meganone** [comment]
Hi
Thanks for the advice. I'll try with Handbrake and see what happens :)

**Comment by meganone** [comment]
Hi

Here's an update: there was actually a bug in Handbrake that caused the issue that I reported. It appears to have been fixed in the latest nightlies. 

Here's the link to the fix: https://goo.gl/Gc8YiV

Hopefully, this fix will be included in the next Handbrake core and consequently in Vidcoder :)

**Comment by RandomEngy** [comment]
Updated to the latest HandBrake core in VidCoder 3.8 Beta.
