### ISSUE TITLE
Add the languages ​​to the installer based on Inno Setup

### ISSUE THREAD

**Issue by MS-PC** [RandomEngy/VidCoder#299]
You could add the translated languages ​​to the installer based on Inno Setup. And you can also download the Unofficial from: https://github.com/jrsoftware/issrc/tree/master/Files/Languages/Unofficial

**Comment by RandomEngy** [comment]
I'm looking into getting VidCoder added to the Microsoft Store, so I might not need the installer anymore (except as a way to install old versions). I'll see how this shakes out before trying to translate the installer itself.
