### ISSUE TITLE
Feature: change hardcoded subtitles font settings

### ISSUE THREAD

**Issue by tbertels** [RandomEngy/VidCoder#3]
Currently, the font settings of hardcoded subtitles can't be changed.

Suggested: add the ability to change the font type, color, size, etc.

**Comment by RandomEngy** [comment]
Can't do this in the HandBrake core I use. Ask them about it.

**Comment by HLFH** [comment]
Oh you are using the HandBrake core :( https://github.com/HandBrake/HandBrake/issues/146
