### ISSUE TITLE
add "close program" option

### ISSUE THREAD

**Issue by Fraghera** [RandomEngy/VidCoder#30]
add "close program" option to "when done" menu plz
thnx

**Comment by RandomEngy** [comment]
I'm curious, why do you want this? And would you expect the program to stay open if some of the encodes failed?

**Comment by Fraghera** [comment]
it has same answer with the other options. the answer is really obvious, why not? i just want to program close itself when encoding processes done. in fact it would be the default option which should came already selected. it is more useful that way.

**Comment by RandomEngy** [comment]
Added in 2.20 Beta.

**Comment by Fraghera** [comment]
awesome
