### ISSUE TITLE
[Beta 3.5] UI Encoding Queue 

### ISSUE THREAD

**Issue by Siox0911** [RandomEngy/VidCoder#301]
I have found an issue in the encoding queue window. The queue has 11 items, but the window says 20. I have edited the last 10 items.

![grafik](https://user-images.githubusercontent.com/6440969/34915156-3b32f1d8-f921-11e7-8644-2cd2521150af.png)

**Comment by RandomEngy** [comment]
Thanks for the report. Fixed in 3.6 Beta.
