### ISSUE TITLE
Weird Encoding Issue

### ISSUE THREAD

**Issue by LeeThompson** [RandomEngy/VidCoder#302]
This is probably a Handbrake bug but I ran into the strangest encoding issue, it's a specific MKV source (For.a.Few.Dollars.More.1965.720p.BluRay.x264-SSF.mkv).   The MKV plays fine, previews fine, but the resulting MP4 (regardless of baseline/advanced settings) has very strange blocking issues.

VidCoder 2.62 (x64)

[mediainfo for source file](https://github.com/RandomEngy/VidCoder/files/1629822/mediainfo_source.txt)

[mediainfo for encoded file](https://github.com/RandomEngy/VidCoder/files/1629823/mediainfo_vidcoder_encoded.txt)

![for a few dollars more 1965 720p bluray x264-ssf mp4-00_39_16](https://user-images.githubusercontent.com/1982261/34920695-5c6def60-f92b-11e7-849b-fb7a7f72e323.png)

**Comment by RandomEngy** [comment]
Yes, this is a HandBrake issue.
