### ISSUE TITLE
Request for the ability to encode in 10bit

### ISSUE THREAD

**Issue by saxonz** [RandomEngy/VidCoder#304]
A simple request for the ability to encode in 10bit x265.
I think this would make your already great VidCoder even better.

Thanks for the hard work.

**Comment by RandomEngy** [comment]
You can already do that with the Beta version.

**Comment by saxonz** [comment]
I can output a video in 10bit HEVC in the beta version? How? I'm using VidCoder version 3.7 Beta (x64).
Thanks boss!

**Comment by RandomEngy** [comment]
In the Video Encoding tab:

![image](https://user-images.githubusercontent.com/9450861/34969682-d877f3c2-fa24-11e7-8233-ae6d114df235.png)

**Comment by saxonz** [comment]
Not sure what was wrong with my current version, if anything. To get the menu in the video encoding tab to show up like above I had to remove both the Beta and the regular version of VidCoder, and restart (Win7 Ent. x64). 10bit x265 is now working in the Beta as you said.
Keep up the awesome work and thank you for the help boss!
