### ISSUE TITLE
Remux option please

### ISSUE THREAD

**Issue by spikemixture** [RandomEngy/VidCoder#305]
Great program and have been using it for years. If only there was a **remux** option.

I don't want to fully re-encode mkv to make them mp4's. 

Give me a **remux** option and I will need no other software!

**Comment by RandomEngy** [comment]
VidCoder uses the HandBrake API to do its encoding. Unfortunately the HandBrake team has said that remuxing/direct video copy is not something they intend to add. You could always [ask them to add it](https://handbrake.fr/community.php).
