### ISSUE TITLE
Vidcoder x64/x64 Beta only utilize around 75-80% of my Ryzen CPU

### ISSUE THREAD

**Issue by kairukun93** [RandomEngy/VidCoder#310]
My CPU is AMD Ryzen 1700x OC @ 3.9Ghz (Stable)

I have been doing some research, and found somewhat of an answer, which is that the Handbrake core only supports up to 6 cores of CPU, which some how i don't believe that's true, because when it comes to Multi-threading, it's pretty much possible to utilize 95-100% of CPU resource. I have tried both x264 and x265, they both operate the same CPU utilization Average of 75-80%! anyways if i'm using x265 codec, is there a way to override the amount cores and threads that i want to use to encode videos? a command line option would be an example! I did read the x265 documentation, some of them like here https://x265.readthedocs.io/en/default/cli.html#performance-options . and tried some command options but some works, some don't like thread option! if anybody knows how to override core/thread count, it would be nice! by the way Ryzen 1700x has 8 cores / 16 threads!

**Comment by RandomEngy** [comment]
There's an item on my backlog to allow multiple encodes to happen at the same time, so you could get through your queue more quickly. I don't know of any setting that would get it to 100% utilization.

**Comment by RandomEngy** [comment]
Added this in 4.4 Beta. Go to Global Options -> Process -> Maximum simultaneous encode jobs.
