### ISSUE TITLE
Latest betas & trojan warning

### ISSUE THREAD

**Issue by Gingernut1978** [RandomEngy/VidCoder#312]
3.6 beta portable & 3.7 Beta portable are marked by Windows Defender to have a trojan.

win32/Azden
win32/Fuerboos

2.63 portable is clean

**Comment by RandomEngy** [comment]
Which one, the installer or portable? Can you update your definitions, right click on them and select "Scan with Windows Defender"? I ran special scans on them and it didn't come up with any threats.

**Comment by jlikens** [comment]
Confirmed that 3.7 portable is blocked by Windows Defender:

Trojan:Win32/Azden.A!cl

**Comment by RandomEngy** [comment]
I found the form to submit a file for a false positive, but I'm not able to reproduce it when I try. Can you let me know your windows version and the virus definition version used that detected it?

**Comment by Gingernut1978** [comment]
Windows 10 64bit

Defender's virus definition version: 1.261.291.0

Last updated 26/01/2018

Just tried a virus definition update, redownloaded v3.7 beta portable from here: https://github.com/RandomEngy/VidCoder/releases/download/v3.7-beta/VidCoder-3.7-Beta-Portable.exe

When the download reaches 100% it gets eliminated because of a detected virus.

Sorry if I can't be of more help. 

Amazing program btw, thanks.

**Comment by RandomEngy** [comment]
Thanks. I submitted the details and the file has been classified as "not malware" according to their system. They say it passes under definition 1.261.301.0 .
