### ISSUE TITLE
drag and drop not working 

### ISSUE THREAD

**Issue by mikelly1673** [RandomEngy/VidCoder#314]
Hi the drag and drop area is not working  version 2.63 (x64). I am using windows 10 pro (x64).
tried dragging and dropping video files from several different areas on my computer and they will no transfer. get a little black circle with slash thru it?

**Comment by RandomEngy** [comment]
What window are you dragging them onto?

**Comment by mikelly1673** [comment]
To the area that says drag video files or folders here

**Comment by mikelly1673** [comment]
Nevermind i figured it out. i was running vidcoder as admin. and for 
some reason it wont let ya drag and drop when you are. i switched it 
back to normal and its working.

**Comment by RandomEngy** [comment]
Glad you got it working. Thanks for the update.
