### ISSUE TITLE
Encode fails at the start

### ISSUE THREAD

**Issue by sparkinstx** [RandomEngy/VidCoder#319]
I just installed the 3.8 Beta on my laptop, and was ready to convert a .wtv file to .mp4 at VeryFast480p30.  When I hit Encode, the encoding failed.  I see this in the logs:

System.ComponentModel.Win32Exception: The token supplied to the function is invalid

From what I can find on the Web, it sounds like some kind of certificate error.

Any help is appreciated.  The log file is at the link below:

[Mannix_MeTV_2017_04_15_00_58_00.mp4 2018-02-11 15.21.15.txt](https://github.com/RandomEngy/VidCoder/files/1714877/Mannix_MeTV_2017_04_15_00_58_00.mp4.2018-02-11.15.21.15.txt)

**Comment by sparkinstx** [comment]
Also, the preview fails to encode.  That log file is below:

[Mannix_MeTV_2017_04_15_00_58_00.mp4 2018-02-11 15.21.15_preview.txt](https://github.com/RandomEngy/VidCoder/files/1714901/Mannix_MeTV_2017_04_15_00_58_00.mp4.2018-02-11.15.21.15_preview.txt)

**Comment by RandomEngy** [comment]
Every so often I hear of a case where something mucked with the inter-process communication VidCoder uses to talk to the worker process. You can work around this by going to Options -> Process -> Uncheck "Use worker process to encode"

**Comment by sparkinstx** [comment]
Thanks, that resolved it.  What does unchecking the worker process do?  Does it slow down the encoding, or negatively affect it in another way?

**Comment by RandomEngy** [comment]
Normally the encode runs in a different process so if the encode crashes it doesn't take down the user interface. When you uncheck the box it runs the encode in the same process, so if the encode crashes then the whole program does.
