### ISSUE TITLE
feature request: visual timeline,frameline for editing of encoding from point a to b

### ISSUE THREAD

**Issue by kleytr6s** [RandomEngy/VidCoder#32]
this idea were rejected at the handbrake forum. this is a copy and paste from their forum.  a visual timeline,frameline for the removing of unwanted scenes. it could be incorporated into the preview window. a slider can be used that is linked to the image on the screen in the preview window. as you slide the image changes showing you where you are in the video with a frameline counter,timeline clock that increases or decreases depending on which direction you slide. an A/start button and a B/end button can be used for the points wanted. after the start and end points have been selected it's name numerically increases. a user can choose to rename the clip before sending it to the queue. also, after start and end points are selected an auto add to queue after selection points feature can be used which can be toggled on and off. if toggled on after a user selects B/end the clip is added to the queue automatically. with that feature clips are never forgotten to be added to the queue by the user after selection points.  handbrake calculates the complete time differently than media players. the difference in time between handbrake and media players makes it difficult to determine where the start and end of a wanted clip are. the current preview window is very close to having this functionality already. also the x264 time cutters/trimmers i have tried remove the subtitles,closed captions. and their are no HEVC/x265 time cutters/trimmers currently available. their also seems to be no plans from any software makers to release one anytime soon.  this would also streamline the process of removing commercials,previews,etc. from videos.

**Comment by RandomEngy** [comment]
If HandBrake doesn't support it in their API, I can't do it with VidCoder. I rely on the HandBrake engine.

**Comment by kleytr6s** [comment]
i thought vidcoder could implement features not dependent on what handbrake does? examples: 1. the pausing and resuming of an encode in your GUI  2. the combining of the preview and encode preview clip window  3. Target Size encoding   Or is it that their are things within the handbrake API that are not fully utilised that can easily be broadened or combined?

**Comment by RandomEngy** [comment]
Certain features, yes. I was able to pause/resume because for a long time the official HandBrake GUI was a CLI wrapper, while VidCoder called directly into hb.dll, which gave it access to more of the core HandBrake API. The target size calculation is just something I can do on the side before calling the HandBrake engine with a certain bitrate. But certain things you can't work around. There simply is no call I can make to get a visual at an arbitrary time in the source. HandBrake controls all the picture processing.
