### ISSUE TITLE
[Feature Request]  Select multiple files using Single File drop down menu

### ISSUE THREAD

**Issue by Charvelx04** [RandomEngy/VidCoder#323]
Was just curious.. so far, we have two options when selecting files/folders.  

When I do my episode encodes, I typically have quite a few in a given folder.  This can be anywhere from 15, to 150+.  When there is a lower amount, I use the Select folder option, and just pull in all the files at once.  However, when I have hundreds to encode, the folder option doesn't really come to bear, since I don't wish to tie up my resources until the queue of 100 or so is complete.

My question is.. using the Single file option, is there a way you can add the option, similar to Windows Explorer, where you can use the CTRL+Mouse click option, to select multiple files?  This would also include the option of using CTRL+Shift key, to select a group of files.. 

This could make it easier for some of us doing batches of files.. puts us right in the middle of selecting a single file, and an entire folder full.  
Reason I am asking.. is it gets quite tedious and extra time consuming, having to use the Single file option;  open file location, click, add to queue.. repeat.

Edit:  I have downloaded the 3.8 beta.. not sure if this has already been included.. as there's no mention in the change log.. so apologies if this has already been implemented in said version.

**Comment by RandomEngy** [comment]
Have you tried selecting the files you want in Explorer and dragging them onto the main window?

**Comment by Charvelx04** [comment]
I have not tried that yet... however, after going thru the options again.. and as blind as I was... I seen from the File menu:
"Enqueue multiple files"

Which allows me to do exactly what I was wanting!

Thanks for the reply as well... now I have more than one option to use.  :)
