### ISSUE TITLE
[Feature Request] Output filesize in completed tab

### ISSUE THREAD

**Issue by Thermalzombie** [RandomEngy/VidCoder#327]
Hi would it be possible in a future update to add a coloum to the completed tab with the output file size.

I find myself opening a folder to view the output file sizes very often and this small feature may be usefull to others there also seems to me to be enough room in the gui for this information.

Thanks for reading my request.

I was also going to ask about estimated file size while converting but don't no how much work this would be to implement.  X-Media recode has this feature but vidcoder is much better in performance and user interface sorry for mentioning a competing software but in case you wanted an example of what I was talking about.

**Comment by RandomEngy** [comment]
The output file size column is already in the Beta version.

As for estimated file size when converting, there are a number of reasons why it can't be done accurately. One is that when doing constant quality encoding you never know how the complexity of the video will change as it's being encoded. Another is that the program keeps some of the data buffered, so the detected file size lags significantly behind the actual encoded percentage. And that buffer size is going to  vary based on the encoder used and the settings for it.
