### ISSUE TITLE
[Feature Request] Bulk Edit Items in Queue

### ISSUE THREAD

**Issue by Ryushin** [RandomEngy/VidCoder#332]
It would be very nice to change a specific option for multiple jobs.  Such as selecting multiple jobs in the queue and then perhaps a right click, Edit Encoding Options for Selected Jobs.  Then being able to select the changes that will affect all of the selected jobs.  Such as Denoising, Deinterlace, Anamorphic, Encoding Options for Video and Audio, etc.

**Comment by sr55** [comment]
While it sounds useful in theory, in practice it doesn't really work.

When you think how many settings are source dependant and you consider that you can't actually assume any two sources are equal it basically prevents you from altering many of the settings that you describe.

There are all sorts of UX issues around this at well. The current UI wouldn't work at all for this kind of change.

So I'm afraid this one isn't going to happen. Sorry.

**Comment by RandomEngy** [comment]
That sounds like a good idea. Though it would be an expensive change though since every single setting would need new support for the "unchanged" state.

**Comment by sr55** [comment]
Your also forgetting many settings require context which you don't have in batch.

**Comment by RandomEngy** [comment]
Well you wouldn't be able to change any of the inputs like audio tracks, subtitles, etc. But in VidCoder you don't need to have a source open to change the encoding settings. What you pick might be invalid for some of the sources, but it would just fall back to something valid in those cases.

**Comment by mdrodge** [comment]
even changing to a different preset would be nice

**Comment by RandomEngy** [comment]
Updating the queue items to the current selected encoding settings might be doable... I'll put this on the backlog.

**Comment by RandomEngy** [comment]
In 4.19 Beta you can now select multiple items in queue and apply current encoding settings to them. You can also apply them to all queue items from the Encoding Settings window.
