### ISSUE TITLE
[Features Request] remux only option

### ISSUE THREAD

**Issue by spikemixture** [RandomEngy/VidCoder#333]
I have used vidcoder for many tears and recommended it to many.
To make it the complete converter, re-coder,  media format fixer a simple remux option would be great.
Drag in a mkv,  set option to remux and it just changes/moves the mkv to mp4.
Without re-coding! 
This process is hugely faster than a unnecessary recode when "converting" mkv to mp4
Options  to extract sub title and change audio would be a bonus.
 Cheers...

**Comment by RandomEngy** [comment]
VidCoder uses the HandBrake API to do its encoding. Unfortunately the HandBrake team has said that remuxing/direct video copy is not something they intend to add. You could always [ask them to add it](https://handbrake.fr/community.php).
