### ISSUE TITLE
Vidcoder with GPU acceleration (Nvidia Nvenc...): when?

### ISSUE THREAD

**Issue by Jemalaar** [RandomEngy/VidCoder#334]
Vidcoder based on the wellknown Handbrake is really fantastic and very stable in general.
Easy to use and with a nice interface, a lot of possibilities. But I'm waiting for a version of Vidcoder with GPU accelerator because working only with the CPU is too slow. I've tried other programs with H.264 or H.265 Nvidia Nvenc encoder: it's really much faster and the result is very good. That would be my suggestion and I'm surprised Handbrake doen't still propose encoding with Nvenc for instance. :-)

**Comment by RandomEngy** [comment]
As far as GPU acceleration I'm constrained by what the HandBrake engine provides, so you should ask them to add it. It does have Intel Quicksync encoding though.
