### ISSUE TITLE
Built-in preset/folder names should be translatable

### ISSUE THREAD

**Issue by Djfe** [RandomEngy/VidCoder#336]
it's of course just an idea, but it's possible now that built-in presets cannot be renamed/replaced anymore

**Comment by RandomEngy** [comment]
I'm getting the presets from the Handbrake API now, and they don't supply translations. I should ask them to add a string ID to the folders/presets to allow for translation...

**Comment by Djfe** [comment]
I see.
An id definitely seems like the best way to do this.
In case that doesn't work out, you could also just match the strings. The translation won't change, if the preset's name stays the same after all.

Anyways, thank you for considering my idea :)

Regards,
Djfe

**Comment by RandomEngy** [comment]
I asked in the HandBrake IRC channel and they said they didn't want to do it since many of the preset names are not translatable. I don't agree with that argument, but you can take it up with them if you like.

**Comment by Djfe** [comment]
ty for trying! :)
