### ISSUE TITLE
External Subtitles: 

### ISSUE THREAD

**Issue by aotgunrt** [RandomEngy/VidCoder#339]
When you select the [**Import .srt File...**] button the (First Time) you are taken to a default sub-directory.
It appears to be a hard coded sub-directory that can not be changed. :(

I would like to be able to set the [**Import .srt File...**] default sub-directory as an option.
**Option 1**: (default) To use the sub-directory of the source video.  
**Option 2**: A default sub-directory I can select.
**Option 3**: Drag-and-drop the subtitle file.  (Like with the source video file)

Thanks

Aotgunrt

**Comment by RandomEngy** [comment]
If you haven't disabled "remember previous files/folders" it should open the SRT picker to the last directory you picked an SRT from.

In 4.1 Beta I added the ability to drag and drop an .srt file onto the main window to add it as a subtitle.
