### ISSUE TITLE
Preview window doesn't autorefresh anymore since the last two updates

### ISSUE THREAD

**Issue by bombenbodo** [RandomEngy/VidCoder#34]
Since 2.17 or 2.18 Beta the preview windows autorefresh doesn't work anymore when doing cropping or resizing.
Temporary workaround is to close and reopen the preview windows to see the results.

Please fix this.

best,

b.

**Comment by RandomEngy** [comment]
Can you leave some exact repro steps? This seems to work just fine for me.

**Comment by bombenbodo** [comment]
Drag movie into Vidcoder
Go to Settings -> Picture and open Preview window
set "Cropping" to custom and start trimming an all ends.

Expected behaviour -> Image in Preview get trimmed respectively
Actual behaviour -> nothing happens in Preview window

I just checked it again. Sizing preview works but Cropping preview does not.

**Comment by RandomEngy** [comment]
Odd, I still can't reproduce the issue. Could you send me your %appdata%\VidCoder-Beta\VidCoder.sqlite file and tell me which preset you used?

**Comment by bombenbodo** [comment]
That's it, my own (custom) profiles doesn't seem to work anymore. When choosing a preset profile cropping works. I attached a profile of mine which  used to work fine before.

[MKV_progressive_film.vjpreset.txt](https://github.com/RandomEngy/VidCoder/files/90540/MKV_progressive_film.vjpreset.txt)

**Comment by bombenbodo** [comment]
Guess I'm gonna close this one, as it works fine now after recreating my custom profile.

**Comment by RandomEngy** [comment]
Ahh, I see. I was updating the preview when the output size changed but in the preset you sent me you have the size declared as a fixed width and height. I can fix this.

**Comment by bombenbodo** [comment]
Brilliant, thanks mate.
Keep it up! Excellent piece of software ;)

**Comment by RandomEngy** [comment]
Glad you like it! Fixed in 2.24 Beta.
