### ISSUE TITLE
Movie disappears from the queue

### ISSUE THREAD

**Issue by spikaspika** [RandomEngy/VidCoder#340]
Version 3.14
Putting the movie in the queue for encoding
Run its encoding
Click "Stop"
Movie disappears from the queue
It used to be in line for encoding and it was convenient
Is this done intentionally?
Respectfully to the author of the program

**Comment by RandomEngy** [comment]
If you only have one item in the queue and you stop, it's intentionally removed. The idea is that if you stopped you probably wanted to re-start with different settings.

**Comment by spikaspika** [comment]
Thank you. You must be right.
