### ISSUE TITLE
Windows autoplay to VidCoder messes up custom Encode settings

### ISSUE THREAD

**Issue by pizzaboyuk** [RandomEngy/VidCoder#341]
I have 2 Pickers set up. 1 for general videos and another for ISO files - both have different presets assigned to them. I have the default set to the video files picker.

When I mounted a DVD ISO file through Alcohol 120, Windows 10 asked gave me an option to send to VidCoder, so thats what I did.

Once VidCoder opened, I switched to the ISO picker and tried to change the Encoding settings. The settings opened ok, however VidCoder kept jumping from the 2 different presets I have set in the pickers. Had to hard close VidCoder from Windows to resume any kind of progress.

**Comment by pizzaboyuk** [comment]
Just tried this by directly dragging an ISO file into VidCoder - same result.

Seems like you can't edit a preset if you are using a Picker with a preset assigned to it. After hard exiting out again, I was able to alter the settings even with the Picker selected!?

**Comment by RandomEngy** [comment]
Can you give some steps to reproduce the issue, with the expected/actual behavior? It's supposed to "lock" the selected preset when it's chosen via picker. As in you should be able to make changes to the preset, but you can't switch to other presets.

**Comment by pizzaboyuk** [comment]
1. Have 2 pickers set up with different presets assigned to them.
2. Drag a file into VidCoder, the preset for the picker should automatically get picked.
3. Try assigning a different preset other than the one assigned to the picker and try changing the encoding settings.

I'm aware in most cases, the reason you would assign a preset to a picker is because you probably would  want to use that preset (almost all of the time) - but is it that much of a deal to want to have the picker settings for the drag and drop but there is a better preset suited for the task?

Cheers

**Comment by RandomEngy** [comment]
What is the expected behavior and actual behavior you're seeing after doing those steps?

**Comment by pizzaboyuk** [comment]
I was expecting VidCoder to use the settings of the Picker selected, but give me the option to change the preset other than the one set in the Picker if I wanted to, and also allow me to change encoder settings if any had to be made...

**Comment by RandomEngy** [comment]
Locking the selected preset when the picker has one set is the intended behavior. When you could have another one selected it got too confusing about which encoding preset was being edited. You could very easily be changing some other preset that had no effect on all the jobs that were going to be queued.
