### ISSUE TITLE
[Feature Request] Subtitle Title

### ISSUE THREAD

**Issue by xCryptic** [RandomEngy/VidCoder#344]
When showing the subtitle list, could you make it so it'll show the track name of the subtitles. Often times I have multiple tracks of the same language, and it will make it easier to know which one is which without having to open up mediainfo.

**Comment by RandomEngy** [comment]
Unfortunately the HandBrake API does not expose the subtitle name. Only the language and type. You can ask the HandBrake team to add it and I'll put it in VidCoder.
