### ISSUE TITLE
Sizing problems - cannot retain original sizing with file containing parts which are 4x3.

### ISSUE THREAD

**Issue by Growlertiger** [RandomEngy/VidCoder#347]
I have been trying to convert some mkv files. The source files are all 1280x720.
What is less usual about the files is that about half the time the picture is 1280x720, the other half of the time (interspersed) it is clips in old 4x3 format, with black bars each side. These are old video clips shown in the movie.

I normally leave the Sizing tab alone, with sizing set to Automatic. The bottom of that window showed:
Input: Resolution: 1280 x 720
Output: Resolution: 960 x 720
But I want the output to be 1280 x 720. The resulting file is indeed 960x720, and the wide parts are reduced in size with black bars above and below.

Next I tried changing the sizing to manual, and set the sizes to 1280 and 720. Now the bottom of the scrren showed:
Input: Resolution: 1280 x 720
Output: Resolution: 1280 x 720
so it looked like this would solve it.
The resulting file is indeed 1280x720 and the wide parts are correctly shown full screen. But now the 4x3 parts are stretched to 1280x720.

I can find no settings that allows me to retain the original sizing. Unless I'm missing something perhaps we need a third sizing option: Automatic, Manual, Don't change. Or perhaps a tick box in the Automatic sizing saying "Don't stretch parts that are smaller".

**Comment by RandomEngy** [comment]
There's no way for us to detect which parts of the video should be larger or smaller. It sounds like you want to treat those parts of the video differently, and there's also no way to do that. You'd need to use a video editing application.

**Comment by Growlertiger** [comment]
I don't think I can have explained it well enough. The whole video is 
the same encoding and the same size. It is all 1280x720. I don't want to 
treat different parts differently, I want them all treated the same. I 
don't even want the sizing changed.

Some parts of it have black bars on the left and right. In Automatic the 
program seems to detect those bars and decides the output size should be 
960x720, so it shriks the wider parts. In manual I can force the correct 
size, but it is so clever it then decides to stretch and distort the 
parts that have the black bars on the left and right.

All I am trying to do is encode it without doing anything at all to the 
size.

I hope this explains it.

**Comment by RandomEngy** [comment]
If you change the cropping to "none" that should fix it.

**Comment by Growlertiger** [comment]
Yes, that solved it. The output size immediately became the same size as the input, and the black edges on parts of the movie were left untouched.
Thank you so much, you are a genius.
