### ISSUE TITLE
Feauture Request (ass subtitle) 

### ISSUE THREAD

**Issue by RiseChaN** [RandomEngy/VidCoder#349]
As we know vidcoder have only srt subtitle but there is few people use it , the most use ass subtitles cz it have more futures with aegisub software ,
I translate anime and encode episodes from mkv to mp4 with ass subs but the subs didnt show up i tryed every thing even mixing video with subs and the subtitle didnt work , even when i select burn it  and still not working subs is missing .
when i try to import subtitles she shows me only srt , i cant select ass subtitles

My Request: i want vidcoder support ( ass ) subtile also when import
Thanks

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://handbrake.fr/community.php) to add it.

**Comment by RiseChaN** [comment]
tnx
