### ISSUE TITLE
Auto-Title Selection Issue

### ISSUE THREAD

**Issue by GT40Wins** [RandomEngy/VidCoder#35]
!!! GREAT PROGRAM !!! 

Was trans-coding DVD files (ifo & vob in a folder) into .MP4 (h264/aac) and found a couple DVD where VidCoder picked a non-existing Title or in one case a correct Title and created a MP4 of near zero size compared to the expected 1 GB. Even manually selecting the Titles did not help.  

This is not a mission critical issue but thought you should know.

**Comment by RandomEngy** [comment]
Thanks. Would need some details to track this down though. Does HandBrake have the same behavior?

**Comment by GT40Wins** [comment]
Will check HandBrake performance once I figure out how to use it.  Thank You for quick response.

**Comment by GT40Wins** [comment]
Looks like it is a Hand Brake Problem ???
![Uploading HandBrake Red_2.gif…]()

**Comment by GT40Wins** [comment]
![Uploading HandBrake Red_2.gif…]()
Failed to UpLoad (Tried .doc, .jpg, .pgn, .gif)
Will send E-Mail to david.rickard@gmail.com

**Comment by RandomEngy** [comment]
Yeah you should report this to HandBrake then as I use their encoding engine.
