### ISSUE TITLE
All tracks show as "Surround" in playback

### ISSUE THREAD

**Issue by jh20001** [RandomEngy/VidCoder#353]
I noticed that no matter how many of the original English formats of audio I preserve in the encode (5.1, 7.1 MA, etc), all programs read the audio tracks as "Surround" (ie, PowerDVD sees all tracks as "English Surround", and VLC shows as "Surround - [English]"). 

So come time to play everything back, you don't always know which one is which. 

![vidcoderaudiotracks](https://user-images.githubusercontent.com/6210275/42062842-e695fc52-7ae3-11e8-9d69-0e2570a07b86.jpg)

**Comment by RandomEngy** [comment]
You can try giving the audio tracks names (Global settings -> Advanced -> Allow settings custom names...) . Though this has limited player support. Other than that it's all up to HandBrake engine, which writes out the tracks.

**Comment by jh20001** [comment]
Doesn't seem to fix anything (doesn't allow the option of editing it)

![vidcoderaudiotracks2](https://user-images.githubusercontent.com/6210275/42075972-140f43ac-7b28-11e8-8512-cf3a84424287.jpg)

**Comment by RandomEngy** [comment]
You have to add it inside the encoding settings. Though again, it has limited player support. If you're still having trouble I suggest you ask the Handbrake team about it, since I use their library to write the file.

**Comment by jh20001** [comment]
Ok, I may have to try this. It's too bad it doesn't incorporate the information in parentheses 
parentheses. I will reach out to Handbrake about that :)

**Comment by jh20001** [comment]
It has been done. Sadly it was a pointless endeavor. Maybe I stink at explaining things. They wouldn't budge an inch at talking about it because it didn't contain a "HandBrake Activity Log", so the community was more concerned about that than reading the full text and realizing....ahh, it's a common action by the application feature-wise and not a "bug". 

All I can say at this point is that hopefully one of the developers of Handbrake will see the post and go, oh...this is what he means and maybe we can address that. Or.....we just deal with everything reading in the players as "Surround" :)

Thanks for the help RandomEngy! I guess it's about as case closed as it will get for now.
