### ISSUE TITLE
FEATURE REQUEST: (4.4-beta) Delete partially transcoded file after abort

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#355]
**PROBLEM:**
If VidCoder is in the middle of a batch encoding project and gets aborted (such as a transcoding to a network share and the the share disappears during a server reboot), it leaves the partially encoded files.  These file leftovers then need to be manually sought out and deleted. If not deleted, a re-encoding of the source file will generate a new file with a different name (-1.ext?) which creates more manual file management. 

**PROPOSED SOLUTIONS:**
1> Use temp filenames while transcoding (filename-temp.ext? filename-vidcodertemp.ext?) so they are easily identified for manual deletion.
2> Automatically delete partially transcoded failed files and prompt to put them back into the batch list. Using the logs, this would be a welcome feature on VidCoder re-run as well after an unexpected system shutdown. 
**3> When confirming file deletion of transcoded files, delete failed transcodes as well.**

**Comment by bcurran3** [comment]
![](https://www.brandignity.com/wp-content/uploads/2015/07/thank-you.jpg)

**Comment by RandomEngy** [comment]
Implemented in 4.13 Beta. It now encodes to video-name.mp4.part and renames it or deletes it at the end, depending on if the encode succeeded or not. So in normal operation it shouldn't leave behind any junk. And if the process gets killed, it will leave behind easily identified .part files.
