### ISSUE TITLE
[Issue] VidCoder hangs during scanning some files

### ISSUE THREAD

**Issue by Zbyh** [RandomEngy/VidCoder#356]
Hey!

I'm not sure if that issue is caused by my software/hardware, but I have few files originally encoded with HandBrake 0.10.2, which hangs VidCoder everytime I try to load them, during "scanning file" process.
Those files works completely fine in other apps, like Avidemux, Handbrake. I can load them there, convert them, do everything I want. But VidCoder only hangs everytime I try to load those files.

The shortest and simplest way to verify this would be sample file of course. I cut small fragment of one of those files in Avidemux, and uploaded it here:
http://s000.tinyupload.com/index.php?file_id=08442213258306576519
This small sample file still hangs my VidCoder, even after Avidemux resaved this fragment (copy video/audio stream mode).

My computer is AMD Ryzen 1600, 16 GB RAM, Windows 10 x64, VidCoder 3.15 (x64).
_BTW: Big Thank You for such great application as VidCoder :)._

**Comment by RandomEngy** [comment]
I see the same thing happen with VidCoder stable version. But it seems to load fine in the VidCoder beta version. You can use that or wait until the change makes it to Stable.
