### ISSUE TITLE
Encoder H264 and H265 with Nvidia Nvenc

### ISSUE THREAD

**Issue by Jemalaar** [RandomEngy/VidCoder#357]
The latest versions of Handbrake (nightly) include Nvenc encoders for H264 and H265. I suppose you're working on a new version of Vidcoder that will include Nvenc. It would be great!

**Comment by RandomEngy** [comment]
It's in the works. It will be tied in with a major overhaul of the source video UI. You'll probably see in the next few days.

**Comment by Jemalaar** [comment]
Thank you. Good news!

**Comment by RandomEngy** [comment]
4.6 Beta is out, and has the NVEnc changes. It's not working for me even when I use the HandBrake UI, but your mileage may vary.

**Comment by mdrodge** [comment]
looks like people with RTX cards will be all over this section soon.
nVidia is claiming the quilty is nearly as good as cpu only now.
(personally i'll wait until its better than cpu)
