### ISSUE TITLE
FEATURE REQUEST: (4.4-beta) make add single file to queue behavior same as multi-file drop

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#358]
**CURRENT BEHAVIOR:**
Dragging and dropping multiple files into the queue gets them checked and then added to the queue. Dragging a single file and dropping it into the queue gets the file checked but it isn't automatically added to the queue - you have to push the Add to Queue button. This isn't very intuitive. I actually thought for a long time that there was a bug in dragging and dropping one file when a queue existed.

**PROPOSED SOLUTION:**
When dragging and dropping a single file on the (existing?) queue, check it as normal, but then add it into the queue without having to use the Add to Queue button. IMHO: This seems more intuitive. Probably negates the need for the Add to Queue button as well.

**Comment by RandomEngy** [comment]
Right now the drag-drop action does the same thing no matter where you drop it. The way it's written right now, it's geared toward dragging an item to the source pane, where it would just open the source. But it does make sense that if you dragged it onto the queue, it would add it to the queue. I'll put it on the backlog.

**Comment by bcurran3** [comment]
Hi @RandomEngy. Thanks for the super fast replies. It's refreshing.

Right now with 4.4-beta when I drag file**s** into Queued, they show up in Queued after processing. Single files don't.

**Comment by RandomEngy** [comment]
Should be fixed in 4.8 Beta.

**Comment by bcurran3** [comment]
CONFIRMED 4.12-beta - thank you.
