### ISSUE TITLE
4.5 Beta won't start

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#361]
Tried several times, won't start for me. If I wait long enough I eventually get the error message "A new guard page for the stack cannot be created" :(

All that's in the logs is 
## VidCoder 4.4 Beta
# Version 4.5 Beta is available. Update download has started.
# Version 4.5 Beta has finished downloading and will install on exit.

**Comment by RandomEngy** [comment]
Does it hang on the splash screen? I had one other report and I'm trying to figure out what's going on. Can you try temporarily renaming %appdata%\VidCoder-Beta\VidCoder.sqlite ?

**Comment by iamjaydear** [comment]
Yes, it does. 
After renaming VidCoder.sqlite it started OK, but I haven't gone further yet.

**Comment by RandomEngy** [comment]
Can you send me the old .sqlite file that was causing the issue? That way I can reproduce the problem and fix the underlying issue.

**Comment by iamjaydear** [comment]
Here you go...
[sqlitefile.zip](https://github.com/RandomEngy/VidCoder/files/2259835/sqlitefile.zip)

**Comment by iamjaydear** [comment]
I should explain a little too - I exported settings from VC3.1x and started using VC4.xbeta, but I was having the occasional corrupt file that would not play in VLC or PotPlayer. Converting the same file in VC3.1x always worked 100%. I just put it down to Handbrake issues, didn't raise an issue and just kept using VC3.15. This new beta will get a workout soon. I'm most often converting .mpg files to .mp4's.

**Comment by Ghastor** [comment]
me too.
