### ISSUE TITLE
Another Crash

### ISSUE THREAD

**Issue by Ghastor** [RandomEngy/VidCoder#363]
Hi !
Thanks for fix about 4.5 beta.
I've found another bug to fix.
VidCoder crash when check manually update under "check now" button
this is the log

ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.InvalidOperationException: Il thread chiamante non riesce ad accedere a questo oggetto perché tale oggetto è di proprietà di un altro thread.
   in System.Windows.Threading.Dispatcher.VerifyAccess()
   in System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   in System.Windows.Controls.Primitives.ButtonBase.get_Command()
   in System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   in ReactiveUI.ReactiveCommand.OnCanExecuteChanged()
   in System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   in System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count)
   in System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnNext(T value)
   in System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.CombineLatest`3._.FirstObserver.OnNext(TFirst value)
   in System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   in System.Reactive.Observer`1.OnNext(T value)
   in System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value)
   in System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   in System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   in System.Reactive.Observer`1.OnNext(T value)
   in ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.notifyObservable[T](TSender rxObj, T item, ISubject`1 subject)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in ReactiveUI.RxApp.<>c__DisplayClass0_0.<.cctor>b__2()
   in System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   in System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Yeah the ReactiveUI library update really messed with a lot of things. I have a fix ready; will come with the next release. Thanks for the report.

**Comment by Ghastor** [comment]
thanks again !!

**Comment by RandomEngy** [comment]
Fixed in 4.8 Beta.
