### ISSUE TITLE
Sleep / Shutdown options?

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#365]
I can't see the sleep and shutdown options in 4.6beta. Is it just me?

**Comment by iamjaydear** [comment]
I've had to go back to v3.15 for now. It's not just this issue, there are quality problems in the HB version in 4.6, e.g. Yadiff is screwed <sigh>

**Comment by RandomEngy** [comment]
Hmm, I can see the sleep and shutdown options. Can you take a screenshot of what you see?

**Comment by iamjaydear** [comment]
Aha! Now I see the problem... I always have the main window about half screen height and the Sleep/Shutdown line is not coming up with the bottom of that window, i.e. it is staying way down and the bottom edge of the main window is covering it up.

**Comment by RandomEngy** [comment]
Ahh I see the problem now. I'll fix it for next release.

**Comment by jhemp01** [comment]
Hello, I'm on 4.7 beta now, and I'm missing the sleep/shutdown options too...

**Comment by RandomEngy** [comment]
Fixed in 4.8 Beta. It's still possible to have it disappear but it's much harder.
