### ISSUE TITLE
Hanging at startup screen

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#366]
4.4 was OK. **4.5 and later** hangs at startup screen on my Windows 8.1 (NET framework 4.72) machine and Windows 10 virtual machine. The Windows event log doesn't seem to contain anything useful - a fairly generic "apphang" message. Your log follows....

`## VidCoder 4.7 Beta
# Could not get update info.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 74.124.218.32:80
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidCoder.Services.Updater.<GetUpdateInfoAsync>d__24.MoveNext() in D:\git\VidCoder\VidCoder\Services\Updater.cs:line 411
# Update download failed. Unable to get update info.
`
As this appears to be related to network access, I took down the (Windows) firewall. Vidcoder beta still hung, but the corresponding log remained empty. Anything more I can do to help?

**Comment by RandomEngy** [comment]
When it's hung, can you take a process dump of VidCoder.exe via Task Manager -> Right Click -> Create Dump file? You can share via https://transfer.pcloud.com/ to david.rickard@gmail.com

**Comment by Plutocratic** [comment]
It is done. Happy hunting! Please advise if there is anything further I can do to assist on this one.

**Comment by RandomEngy** [comment]
Thanks. Do you remember how much CPU it was using when it was hung?

**Comment by RandomEngy** [comment]
Actually I think I found an open issue on this on the .NET framework:

https://developercommunity.visualstudio.com/content/problem/244615/setfinalsizemaxdiscrepancy-getting-stuck-in-an-inf.html

So it appears to be a .NET bug.

**Comment by Plutocratic** [comment]
I recall it being hung with about 15% CPU.

If it is the .NET framework problem to which you refer, thay haven't fixed it in 4.7.2

Is there anything to be achieved by attempting to isolate the problem to the particular change (between 4.4. & 4.5) that causes the issue? Once you know more about the cause of the issue, a workaround might be possible.

**Comment by RandomEngy** [comment]
I switched to .NET Framework 4.7.1 in VidCoder 4.5. I upgraded because
HandBrake.Interop also did. I'd keep an eye on that issue and stay with
Stable or an older beta until they resolve it.

**Comment by Plutocratic** [comment]
Sorry - I didn't think you were talking about 4.7.1 at the developer's end. As I said earllier, I have installed 4.7.2 user runtime NET framework and confirmed that it doesn't help. Have they updated the developer end to 4.7.2? If so, it might be worth a try.

**Comment by RandomEngy** [comment]
I believe the way it works for minor versions is that on the developer side you can target "at least 4.7.1" but the version that gets used depends on what the user has installed. So if installing 4.7.2 doesn't work on your end, requiring it from my side wouldn't help. Once a fix rolled out I could require that version.

**Comment by RandomEngy** [comment]
There was a workaround posted on the thread, I have tried applying it for 4.8 Beta; can you see if it works for this issue?

**Comment by Plutocratic** [comment]
I confirm that 4.8β gets through the startup phase and the UI appears as expected. Are there any further aspects to this bug (elsewhere in the program) that need to be specifically tested?

Anyway, congratulations and well done !!

**Comment by RandomEngy** [comment]
Thanks! Glad it worked.

**Comment by mdrodge** [comment]
i'm running the beta on a windows insider build.
it updated the build.
this build has .net 4.7.2 
VidCoder BETA won't run on .net 4.7.2
i cant even get in to export my que or my presets 
(my que is 19 days worth of work at %94 load on a 16 thread cpu)

any way of getting this going ????
please help

**Comment by RandomEngy** [comment]
I'm not sure what's going on here. There are two things you can do:

1) While it's stuck, open Task Manager, right click VidCoder.exe and create a dump file. Send it to david.rickard@gmail.com and I can see where it's stuck.
2) For the short term, uninstall that version and re-install a previous version. Just make sure not to delete your user settings when you uninstall. Your queue should come back and you can finish up encoding.

**Comment by mdrodge** [comment]
Ok I'll send you a Dropbox link now
(It'll probably get picked up by you spam filter so check your spam box)
Thanks
P.s it's for version 4.12.  i tried 4.13 but that would not make a dump
file for some reason.

**Comment by RandomEngy** [comment]
It looks like it's waiting on a dialog box. Are you sure a dialog box is not visible when opening? Can you press Ctrl+C while the dialog box is open and paste the contents here?

**Comment by mdrodge** [comment]
I think that's what you're after.

**Comment by RandomEngy** [comment]
What do you mean? I don't see any message...

**Comment by mdrodge** [comment]
Yep that's fixed it.
All running on 4.13 now.
Thanks

**Comment by mdrodge** [comment]
it opens now but has an error when i try and encode something

System.ArgumentNullException: Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at
VidCoder.Services.ProcessingService.<>c__DisplayClass191_0.<OnEncodeCompleted>b__0()
in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1619
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mdrodge** [comment]
I also tried changing it from this

<startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1"/>
  </startup>

to this

  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2"/>
  </startup>

and it gives the same error as above

i.e


System.ArgumentNullException: Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at VidCoder.Services.ProcessingService.<>c__DisplayClass191_0.<OnEncodeCompleted>b__0()
in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1619
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object
source, Delegate callback, Object args, Int32 numArgs, Delegate
catchHandler)

**Comment by RandomEngy** [comment]
I'll give that a look. That may be a different problem related to another change that was in that release.

**Comment by RandomEngy** [comment]
Yeah the ArgumentNullException was from an unrelated change. I'll fix in the next beta release. That should only happen for items queued in an old version and opened in the new.

**Comment by RandomEngy** [comment]
Fixed the ArgumentNullException in 4.14 Beta.

**Comment by mdrodge** [comment]
Sweet.
Every thing else seems fine with 4.13 now.
It's not failing anything.
😎

**Comment by LeeThompson** [comment]
Having this happen on one machine running Windows 10.0.19041.1165.   Still investigating.
