### ISSUE TITLE
Preview window issues

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#369]
1. The 'corners' function seems to cause an exception most of the time. Should be easily reproducible.

2. With the preview mode set to 'fit in window', as soon as you attempt to resize the preview window, the preview appears to flip into '1:1' mode (but view dropdown indication remains unchanged). Only by cycling through another mode can 'fit in window' be resumed and it seems OK thereafter.

**Comment by Plutocratic** [comment]
>Corners crash should be fixed in **4.10 Beta**
Agreed

>I'm not able to reproduce the "fit in window" issue. Does it happen with all sources?
As far as I can tell, yes. Three things to note –
1. I am using a high DPI screen. This may be relevant as the issue is possibly related to miscalculation of pixel size/shape/number
2. The issue only occurs **when the preview window is initially opened.** Provided the preview window remains established, the problem is not apparent. Only when the preview window is closed and subsequently re-opened does it happen again.
3. This is a small issue and, IMHO, possibly not worth worrying about at this point!

**Comment by RandomEngy** [comment]
Thanks for the details. This will be fixed in the next beta release.

**Comment by RandomEngy** [comment]
Fixed in 4.11 Beta.
