### ISSUE TITLE
Preview window - another thing....

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#375]
... that might be relevant so some of the crash reports.

I noticed that on one particular video (_possibly_ the one I uploaded to your PCloud a couple of days ago – not certain) neither of the preview windows (neither the small one within the main window nor the dedicated one) show anything ("no video source"). I also noticed that, within the sizing tab, this source file produced a (green) output dimensions display in which the pixel aspect ratio and display resolution have –ve values (impossible!) so something here needs looking at. Thanks.

**Comment by RandomEngy** [comment]
I checked my email and I don't see the video files you sent to me. Are you sure they went to the right address?

**Comment by Plutocratic** [comment]
File re-sent, just in case.

**Comment by RandomEngy** [comment]
Ahh I got it this time. Looks like a large PAR value is causing an integer overflow when we calculate the final size. I'll fix this in the next beta release.

**Comment by Plutocratic** [comment]
Excellent. You're getting there.

**Comment by RandomEngy** [comment]
Fixed in 4.11 Beta.
