### ISSUE TITLE
5.11 – so far so good

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#378]
**4.11**, not 5.11 as per heading

A few brief tests indicate that you have gripped all the problems I have experienced since you updated the .NET stuff. In an hour of testing various video files, 4.11 remained stable and delivered no surprises. Well done :)

NOW – are you interested in a feature suggestion which might be tricky but, if implemented well, has the power to turn Vidcoder into a world-beater?

**Comment by RandomEngy** [comment]
Always willing to hear suggestions. No guarantee on implementation though.
