### ISSUE TITLE
frame size altered

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#38]
Watching, I never would have noticed, but as I experimented and examined the files, I am seeing a slight alteration of frame size. (testing w v2.20)

I used a DVD as source (720x480) and the conversion to MP4 was 720x482 w display resolution 720x478

I had a MOV source file that was 1280x738 (display res: 1280x720) and the MP4 conversion was to 1280x718

In each case, it seems the conversion is 2 lines less than the source.

Is this to be expected? or might their be a minor bug in the conversion math?

**Comment by RandomEngy** [comment]
Could you provide the encode logs via pastebin?

**Comment by BugMagnet** [comment]
I did the transcode again and noticed this in the log:

[12:15:54]      + Crop and Scale (720:478:2:0:0:0)
[12:15:54]        + source: 720 * 480, crop (2/0/0/0): 720 * 478, scale: 720 * 478

When I looked at settings, I found Cropping was set to Auto.  Is that the default? If so what is the purpose of clipping 2 lines?

http://pastebin.com/b7nCLhD2

**Comment by RandomEngy** [comment]
Yeah that would be why. Cropping is set to Auto by default so it cuts off black bars from sources. It must have found there was a bit of black at the top and removed it. It's more useful when sources come along with lots of black at the top and bottom (like some early DVDs that didn't do Anamorphic correctly).
