### ISSUE TITLE
[Feature Request] Audio Normalizer

### ISSUE THREAD

**Issue by plasmavideo** [RandomEngy/VidCoder#381]
It would be handy to have a feature that would allow you to automatically normalize audio tracks to a preset level in addition to the manual volume settings. That would be very handy for batch processing without having to individually check levels outside of the application and manually applying gain changes.

Thanks.

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://handbrake.fr/community.php) to add it.
