### ISSUE TITLE
How to remove recent files?

### ISSUE THREAD

**Issue by bulrush15** [RandomEngy/VidCoder#384]
On the main Vidcoder screen for v3.1.5 (x64) there are 2 Recent Files, and below those 2 files it says "(Or drag video files or folders here)". How do I remove those recent files? I did a right click on the recent files and got no menu. I checked through all the options and I don't see an option to remove Recent Files.

**Comment by RandomEngy** [comment]
Try Options -> Advanced Options -> Uncheck "Remember previously used files and folders"

When you apply that it should clear the list.

**Comment by bulrush15** [comment]
Ok, I had to restart the program, then it worked. Thank you.
