### ISSUE TITLE
[Feature Request] Picker: select Audio and Subtitle streams by number

### ISSUE THREAD

**Issue by Zaaacharias** [RandomEngy/VidCoder#388]
I have a feature request for the Picker that would make it even more powerful imho.
It would be great to be able to select audio and video streams by number.

Eg. select the first and third audio stream and make the third one default.
select the third and fourth subtitle stream and make the third one default.

Would love to see this feature in the future!

**Comment by RandomEngy** [comment]
Sounds handy. I'll put the feature on the backlog.

**Comment by Zaaacharias** [comment]
Cool. Thanks a lot mate!

**Comment by RandomEngy** [comment]
Added in 4.22 Beta.
