### ISSUE TITLE
Clearing 'Recent' file name

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#389]
I'd like to be able to clear the 'Recent' file name. Just a blue 'x' next to it would do. Why? Well, I usually drag & drop several files at a time, but occasionally open a single one which then "haunts" me for days or even weeks. If you're unreceptive to having an 'x' to clear it, how about clearing it automatically when a bunch of  files are dragged & dropped?

**Comment by iamjaydear** [comment]
... or just retain the name of the last file d&d'd?

**Comment by RandomEngy** [comment]
It sounds like you don't really use that feature. Have you tried Global Options -> Advanced -> Uncheck "Remember previously used files and folders"?

**Comment by iamjaydear** [comment]
Thanks for v4.12 beta :)

**Comment by RandomEngy** [comment]
Do they open in the latest HandBrake nightly? I also updated the HandBrake core in 4.12.

**Comment by iamjaydear** [comment]
Yes. Nightly dated 2018090901

**Comment by RandomEngy** [comment]
Then you can report the issue to them and they can fix the issue.

**Comment by iamjaydear** [comment]
OK, weird time now... VC beta IS opening file now that I've d/l'd and run latest HB nightly. I tried several times before that and no go. The only clue I can offer is that VC beta's scan was instantaneous and encode attempt completed in a millisecond with a 0 byte file. Sorry for scaring you.

**Comment by RandomEngy** [comment]
Can you send the file or a sample of a file that doesn't open? https://transfer.pcloud.com/ david.rickard@gmail.com

**Comment by RandomEngy** [comment]
Okay, good to hear that it's working now.

**Comment by iamjaydear** [comment]
Yes, thanks heaps.
