### ISSUE TITLE
Can VC convert to TS?

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#39]
Can VidCoder transcode to .ts format for streaming? I am using a program that has chatrooms in which MP3 audio and TS video can be streamed

can VidCoder do the equivalent of this:

Low Bitrate Video, 40 KB/s stream:
ffmpeg -i input.avi -c:v libx264 -b:v 384k -bufsize 384k -c:a libmp3lame -b:a 16k output.ts

Better Quality Video, 120 KB/s stream:
ffmpeg -i input.avi -c:v libx264 -b:v 768k -c:a libmp3lame -b:a 32k ouput.ts

It appears to me this is converting to h/x264 video with AC3/MP3 audio. But I only see output options for MP4 or MKV on the current VidCoder.  Is or could .TS format be supported?

**Comment by RandomEngy** [comment]
You'd need to ask HandBrake to support .TS .
