### ISSUE TITLE
BUG: (?) 4.12-beta - appears to only use one thread (on start)

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#390]
4.11 crashed after a network problem (and throwing a hundred messages - need to write up something about that issue). Re-ran. 4.12 installed. Drag and dropped a bunch of files. Only one file converting/thread running. Checked settings, set for 3.

**Comment by bcurran3** [comment]
Follow up - hour later. Once the first file finished transcoding, three started up.

Intentional delay?
Bug?
Dunno - close at will.

**Comment by RandomEngy** [comment]
Don't have enough to go on here. Need to be able to reproduce it or have some error message.
