### ISSUE TITLE
AMD VCE works not proberly (4.12 Beta and all other Betas)

### ISSUE THREAD

**Issue by widfek** [RandomEngy/VidCoder#395]
think it's great that Vidcoder now has VCE too, it does not work properly. CPU usage continues at 100 & and the FPS is very slow. Other programs with VCE work better there. Would be great if you could check it out, I love VidCoder and have used it for years. Many Thanks
Best regards

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

**Comment by widfek** [comment]
Hello RandomEngine,

Thank you for your answer. it does not work in HandBrake either. I reported it as a bug. In other programs VCE works very well. Let's wait
Best regards
