### ISSUE TITLE
BUG: 4.13-beta crash

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#400]
![image](https://user-images.githubusercontent.com/14026600/45723625-18638100-bb67-11e8-8534-b1220946f18d.png)

> ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> DryIoc.ContainerException: Unable to resolve String as parameter "baseFileName"
>   in singleton VidCoder.Services.AppLogger: VidCoderCommon.Services.ILogger #32
>   from container
> Where no service registrations found
>   and no dynamic registrations found in 0 Rules.DynamicServiceProviders
>   and nothing in 0 Rules.UnknownServiceResolvers
>    at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3)
>    at DryIoc.Container.TryThrowUnableToResolve(Request request)
>    at DryIoc.Container.DryIoc.IContainer.ResolveFactory(Request request)
>    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
>    at DryIoc.Factory.GetExpressionOrDefault(Request request)
>    at DryIoc.Factory.GetDelegateOrDefault(Request request)
>    at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
>    at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
>    at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
>    at VidCoder.FileUtilities.OpenFolderAndSelectItem(String folderPath, String file) in D:\git\VidCoder\VidCoder\Utilities\FileUtilities.cs:line 46
>    at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
>    at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
>    at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
>    --- End of inner exception stack trace ---
>    at ReactiveUI.RxApp.<>c__DisplayClass0_0.<.cctor>b__2()
>    at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
>    at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I brought VidCoder to the forefront. Resized it. Clicked completed. Right clicked a failed file to open its location and delete the failed file....BOOM!

p.s. I noticed it doesn't show the output file any longer in the queue columns. I didn't read the release notes, not sure if this is intentional or not. Advise if you want an issue or not.

**Comment by RandomEngy** [comment]
Fixed in 4.14 Beta.
