### ISSUE TITLE
ENHANCEMENT: Don't stack "Scanning..." windows on top of each other (pretty please)

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#406]
When dragging and dropping files into the queue I sometimes drop 50+ files at a time and repeat about 5 times while VidCoder scans the files. Across multiple 3.x and 4.x versions it always stacks the new "Scanning..." window on top of the previous one. It makes it hard to know what's going on as I'm waiting for the scans to finish in a lot of cases before I can hit the Encode button. (I've adapted, I'll drop 2-3 files, hit encode, and THEN drop my large bunches of files and walk away!) I routinely click and drag the Scanning... windows to new locations so I can watch the progress on all of them simultaneously.

PROPOSAL:
Instead of stacking multiple...
![image](https://user-images.githubusercontent.com/14026600/45950384-6d165a00-bfb4-11e8-8920-8466d41e4914.png)
on top of each other when adding to the queue, consider opening subsequent Scanning... windows below the last existing one. I'm GUESSING this is pretty easy for you to implement.

LONG TERM GOAL:
Would be to have one Scanning... status window open that resizes with multiple status bars in it instead of multiple Scanning... windows. This probably requires a lot more code changes than the first proposal. :)

**Comment by RandomEngy** [comment]
Yeah that is weird. I'd probably handle this by adding the dropped files to the end of the scan queue on the existing scan dialog window. Will put it on the backlog.

**Comment by RandomEngy** [comment]
Fixed in 4.20 beta. The additional dropped files get added to the scan queue rather than stacking multiple windows.
