### ISSUE TITLE
ENHANCEMENT: Help/Updates/Check Now download LATEST version

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#408]
I've been running 4.12-beta on one machine. I knew from various Issues that 4.14-beta had been released.

On my machine running 4.12 I wanted to update to 4.14. Help/Updates/Check Now button found 4.13 and then ghosted the Check Now button or VC had download 4.13 and had ghosted the Check Now button. Either way 4.14 was available but VC was unaware of it at the 4.12 version level.  Appears as if it only checks subsequent sequential version numbers or possibly only checks once and then locks in that answer without the ability to check again for a yet newer upgrade version allowing it to skip versions.
(Yes, my queues are up to 2 weeks long and I hate stopping 4x transcodings that take 5-8 hours each!)

Would be nice if VC could skip right to the latest release for upgrades.

**Comment by bcurran3** [comment]
4.16 - successfully checked, found, downloaded, and installed 4.18-beta

**Comment by RandomEngy** [comment]
4.20 Beta adds code to ignore an earlier, out of date installer if a newer one is found.
