### ISSUE TITLE
ENHANCEMENT: append/prepend "failed" to the log file names 

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#410]
I'm exception based. If things work right, well, that's what I expect and I don't really care about the details. I, personally, don't need the log files of files that transcoded correctly. I'd like to routinely delete them. It would be helpful if failed transcodings were flagged and more obvious to see without actually having to look through thousands of log files. Smarts are already built into the log file naming convention, It would be nice if "-failed" (and possibly also "-success!") could be included into the naming smarts. Not sure if it should be a prepend or an append. My goal would be to do a del *failed*.txt.

Pros to prepend:
- fast easy visual when looking at a folder in Windows (assuming view is set to details/list name) all failures would be at the top of the list with all successes below (again, assuming alpha sort a-z). 
- easy to highlight and delete in Windows based on the division of successes and failures
- del failed*.txt or del success*.txt easy from CLI

Cons to prepend:
- slightly harder to find (in Windows) by those looking for a specific file name (probably have to use search function); i.e. no hitting "C" to jump to filenames beginning with "C."

Pros to append:
- can easily del *-failed.txt or del *-success.txt from CLI (Good use of DropIt here!)

Cons to append:
- harder to sort by failed/success in Windows (probably have to use search function)

**Comment by RandomEngy** [comment]
Did you know you can right click a completed item an open its log file?

**Comment by bcurran3** [comment]
No, didn't know that!

But...(will edit this in a minute)

**Comment by RandomEngy** [comment]
Added affix to log file in 4.16 Beta.
