### ISSUE TITLE
BUG: VidCoder 4.14-beta freezes on right click to add failed files back into the queue

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#413]
RE: https://github.com/RandomEngy/VidCoder/issues/383

![untitled](https://user-images.githubusercontent.com/14026600/46187884-b90a1d00-c29a-11e8-9dc0-a31e90949d11.png)

I noticed a large amount (thousands) of failures. I remembered the new right click to add failed files back into the queue feature for the first time. I tried it. VidCoder went unresponsive. 11-12 hours later (now) it's still unresponsive. 

Not a slow system:
![untitled](https://user-images.githubusercontent.com/14026600/46188164-5154d180-c29c-11e8-84bc-aaded012b060.png)

I killed the VidCoder task via Task Manager. Re-ran VidCoder. It popped up the splash screen and the normal program window but has been unresponsive now for 5 minutes showing "Not responding" in Task Manager as well. I'm going to let it sit a bit and check back on it later. Will update.

**Comment by bcurran3** [comment]
UPDATE: 2 hours later and it's looks like it's loaded up the failed files - YAY!

**Comment by RandomEngy** [comment]
Try it on 4.16 Beta. I made some changes that might make this go faster.
