### ISSUE TITLE
Sound dropped mid video

### ISSUE THREAD

**Issue by jard9911** [RandomEngy/VidCoder#414]
I used Applian Replay Media Splitter software to cut out some scenes in a video.
When I encode the video I am left with no sound immediate after my last cut. 
On inspection of the above resulting input video to VidCoder, I can hear a 1 second audio silence and can see the 1 second flat line gap in the sound track after the last cut. 
Apparently VidCoder  determines there is no sound, and drops the sound for the remainder of the video. 
Is there a way to keep VidCoder from dropping the sound for the rest of the video after a sound gap?

See attached input and output videos of VidCoder.
Input video to Vidcoder, showing sound gap:
![image](https://user-images.githubusercontent.com/17124877/46212134-dd95e180-c2fa-11e8-8123-93ea8fbbe5bd.png)
Output video from Vidcoder showing no sound for the remainder of the video:
![image](https://user-images.githubusercontent.com/17124877/46211745-e9cd6f00-c2f9-11e8-9b72-9c36e8d3b469.png)

Thanks,
Ron
jard9911r@shawra.com

**Comment by RandomEngy** [comment]
VidCoder uses the HandBrake engine to do the encoding. You could try it with HandBrake and ask them to get it fixed. Make sure to post an encode log for them.

**Comment by jard9911** [comment]
Found a temp fix by converting the file.
