### ISSUE TITLE
ENHANCEMENT: please implement auto-recycling of log files

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#417]
![image](https://user-images.githubusercontent.com/14026600/46328899-dacb1300-c5be-11e8-84c7-1dbb57133141.png)

I'm not sure what a good default # would be to keep, it's going to vary a lot depending on use. Maybe a configurable option in setup? ;i.e. Keep xxx logs.  xxx could default to 1,000 or so.

**Comment by RandomEngy** [comment]
There's code that should be deleting logs older than 30 days. Is this too long to keep them for you?

**Comment by bcurran3** [comment]
Excellent. 30 day seems very reasonable.

I've had VidCoder running constantly for three months. I should have checked the dates of my log files before deleting. I guess I've done 30k+ transcodes on this machine in the last 30 days!
