### ISSUE TITLE
Could not copy log file to output directory...

### ISSUE THREAD

**Issue by saxonz** [RandomEngy/VidCoder#421]
START # Could not copy log file to output directory: System.IO.FileNotFoundException: Could not find file 'C:\Users\Administrator\AppData\Roaming\VidCoder-Beta\Logs\2018-10-08 14.55.22 Tai.Chi.1080p.x265.mkv.txt'.
File name: 'C:\Users\Administrator\AppData\Roaming\VidCoder-Beta\Logs\2018-10-08 14.55.22 Tai.Chi.1080p.x265.mkv.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at VidCoder.Services.ProcessingService.<>c__DisplayClass180_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1833
END
All the paths above are correct except D:\git\VidCoder\VidCoder\Services\ (My system has no D:\ drive)
(Win7 ENT x64 SP1 up to date)
(VidCoder Beta version 4.16)

**Comment by RandomEngy** [comment]
So that log file does exist on disk? But it threw a FileNotFoundException when trying to copy it? Does this happen often?

**Comment by saxonz** [comment]
Yes the log does indeed exist on disk. It is almost like it threw the error when VidCoder Beta v4.16 was in the middle of renaming the file to Tai.Chi.1080p.x265.mkv-succeeded.txt but it just never copied the log to the output folder. Yes it happens often and never has be able to copy the log/txt file to the file output destination folder in this version. Hope that helps out. 
![000](https://user-images.githubusercontent.com/24868148/46717020-28392700-cc34-11e8-8af7-f3c80e31f68a.png)

**Comment by RandomEngy** [comment]
Thanks for the report. Fixed in 4.17 Beta.
