### ISSUE TITLE
ENHANCEMENT: Clear Completed list after clicking Confirm delete

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#422]
CURRENT SCENARIO:
When clicking the X to delete the Completed files, the list is cleared then user is prompted to Confirm delete (if enabled) of the source file(s)/folder(s).

SUGGESTED ORDER:
When clicking the X to delete the Completed files, prompt to Confirm delete (if enabled) of the source file(s)/folder(s), then clear the list. This allows the user to see and visual confirm what he/she is agreeing to.

**Comment by RandomEngy** [comment]
I changed this to a Yes/No/Cancel box in 4.18 Beta. It won't clear out the list until you respond, and also you can now cancel and review the list of files affected.
