### ISSUE TITLE
Batch conversion do not retain settings

### ISSUE THREAD

**Issue by pstrg** [RandomEngy/VidCoder#425]
20 movies in which
- audio stream 1 is Russian and
- audio stream 2 French.
Wanted to remove Russian.

If I select just one file at a time, Russian is removed (as it should) and only French remains.
However, if I try batch processing, stream 2 is removed instead, so that only Russian remain.

Double checked and French is correctly set as the sole audio to remain.

**Comment by RandomEngy** [comment]
Have you tried selecting the audio stream by language in the Picker window?

**Comment by pstrg** [comment]
_Initially I did not use Picker:_
Selected File > Enqueue multiple files
Language selected in the main window (did not use the picker button):
Audio: 2 Francais (AC3) (2.0 ch)
Instead of Français, Russian resulted and no French

_Given your question, I used this time the Picker button too:_
Audio selection Language French (Francais)
All tracks for this language
_Instead of French, both tracks were eliminated in the output._

(Sorry for the delay - expected an e-mail but didn't receive one)

**Comment by RandomEngy** [comment]
Can you share the file you're having trouble with, or a small section of it?

http://vidcoder.net/Documentation/SubmittingBugReports.html

**Comment by pstrg** [comment]
Hi,

Just sent (WeSendit) to the long email address.
It's one of twenty files.
Audio 1 is Russian over French.
Audio 2 is French.

Want to suppress Audio 1 and keep Audio 2 only.
Works fine one by one but doesn't as a batch.

**Comment by pstrg** [comment]
WeSendit-Info

    
        table {
            padding:0;
            margin:0;
        }
    




    
        
            
                
                    
                        
                            
                                
                                    
                                    
                                
                            
                        
                    
                
                
                    
                            
                                
                                        
                                             
                                        
                                        
                                            Files are ready for download.
                                        
                                        
                                             
                                        
                                        
                                            
                                                    
                                                        
                                                         
                                                        pastraga@gmail.com
                                                            has sent you a file through WeSendit.
                                                    
                                                
                                        
                                        
                                             
                                        
                                        
                                            
                                                    
                                                        
                                                         
																													The files will be deleted on 
                                                            24. October 2018 deleted.
														                                                    
                                                
                                        
                                        
                                             
                                        
                                        
                                            
                                                    
                                                        Files(406 MB total) 
                                                        01 Zeus ou La conquête du pouvoir.mkv
                                                    
                                                
                                        
                                                                                
                                            
                                                    
                                                        Message
                                                        One of original files (20 total).
Audio 1 is Russian over French.
Audio 2 is French
                                                    
                                                
                                        
                                                                                
                                             
                                        
                                        
                                            You cannot see the download button?
                                        
                                        
                                             
                                        
                                        
                                            
                                                
                                                    
                                                        Download link
                                                        https://wsi.li/N0sj15mMhp9Ehh/1225964
                                                    
                                                
                                            
                                        
                                        
                                             
                                        

                                        
                                             
                                        
                                    
                            
                        
                

                
                    
                            
                                
                            
                        
                    
                
                
                    
                            
                                
                                    
                                        
                                        By activating the download link, you thereby confirm that you have read the terms & conditions and privacy policy of WeSendit GmbH. If you want to read these before downloading, please click on this link                                        link

**Comment by pstrg** [comment]
WeSendit-Info

    
        table {
            padding:0;
            margin:0;
        }
    




    
        
            
                
                    
                        
                            
                                
                                    
                                
                            
                        
                    
                
                
                    
                            
                                
                                        
                                             
                                        
                                        
                                            Hello reply@reply.github.com

Thank you for trusting WeSendit.com and for starting your download!

This will be finished in a few seconds or minutes.

Did you know that WeSendit.com is a Swiss company with Swiss headquarters and a Swiss data center?

With WeSendit.com, you can send data to your business partners and friends quickly, easily and, most importantly, securely!

Just give it a try

Plus you’ll get lots of other functions and be able to send larger amounts of data when you register free of charge for a free account!

All the best,

Team WeSendit

                                        

                                        
                                             
                                        
                                        
                                             
                                        
                                        
                                             
                                        
                                    
                            
                        
                
                
                    
                            
                                
                            
                        
                    
                
                
                    
                            
                                
                                    
                                    Judicial subjects on www.wesendit.info

**Comment by pstrg** [comment]
Thank you very much - working as it should.
The last phrase solved the issue.

May I comment that the necessity to define settings *before *adding the
files seems a bit counter-intuitive?
If the GUI allows the user to change settings while a file list already
exists (without any warning), shouldn't the user understand the new
settings have been accepted?

Have a nice weekend.
Paulo Braga

**Comment by RandomEngy** [comment]
There's no perfect answer. Someone might need to use different settings for different files. In that case they would queue some files, change the settings then queue some more files. They wouldn't want the setting change to apply to the previously queued files because they *want* the files to have different settings. Maybe I need to have some button that pops up that applies new settings to existing queue items.
