### ISSUE TITLE
Padding color

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#427]
The padding color shown in the lower-left corner of the "sizing" tab remains black, regardless of the color actually chosen. Other aspects of the padding color picker appear to work correctly.

**Comment by RandomEngy** [comment]
Fixed in 4.17 Beta.

**Comment by Plutocratic** [comment]
This one appears NOT to have been fixed! The swatch showing the padding color on 4.17 shows constant red, but the actual padding color (as seen in the preview window) is correct.
