### ISSUE TITLE
You just saved my life, thanks.

### ISSUE THREAD

**Issue by gordielachance** [RandomEngy/VidCoder#428]
Hi !
I'm using Handbrake since a few years but this time it was refusing to do what I needed.
And I needed it quick: 24 files to transcode for a very big client before 6PM (it's 4PM here)... 
He was getting quite nervous.
Hopefully I found out VidCoder.
Thanks, you just saved my ass !

https://github.com/HandBrake/HandBrake/issues/1633

**Comment by RandomEngy** [comment]
I'm really glad to hear it!
