### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bogolha** [RandomEngy/VidCoder#43]
System.Reflection.TargetInvocationException: O destino de uma invocação accionou uma excepção. ---> System.Reflection.TargetInvocationException: O destino de uma invocação accionou uma excepção. ---> System.Reflection.TargetInvocationException: O destino de uma invocação accionou uma excepção. ---> System.Reflection.TargetInvocationException: O destino de uma invocação accionou uma excepção. ---> System.IO.IOException: O processo não pode aceder ao ficheiro 'C:\Users\Ricardo Santos\AppData\Roaming\VidCoder\Logs\2016-01-21 20.04.54.txt' porque está a ser utilizado por outro processo.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   em System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   em System.IO.StreamWriter..ctor(String path)
   em VidCoder.Services.Logger..ctor(ILogger parent, String baseFileName) em d:\docs\projects\VidCoder\VidCoder\Services\Logger.cs:line 57
   em VidCoder.Services.Logger..ctor() em d:\docs\projects\VidCoder\VidCoder\Services\Logger.cs:line 29
   --- Fim do rastreio da pilha de excepção interna ---
   em System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   em System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em GalaSoft.MvvmLight.Ioc.SimpleIoc.MakeInstance[TClass]()
   --- Fim do rastreio da pilha de excepção interna ---
   em System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   em System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   em System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.Delegate.DynamicInvokeImpl(Object[] args)
   em GalaSoft.MvvmLight.Ioc.SimpleIoc.DoGetService(Type serviceType, String key)
   em GalaSoft.MvvmLight.Ioc.SimpleIoc.GetInstance[TService]()
   em VidCoder.Services.Updater..ctor() em d:\docs\projects\VidCoder\VidCoder\Services\Updater.cs:line 58
   --- Fim do rastreio da pilha de excepção interna ---
   em System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   em System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em GalaSoft.MvvmLight.Ioc.SimpleIoc.MakeInstance[TClass]()
   --- Fim do rastreio da pilha de excepção interna ---
   em System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   em System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   em System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.Delegate.DynamicInvokeImpl(Object[] args)
   em GalaSoft.MvvmLight.Ioc.SimpleIoc.DoGetService(Type serviceType, String key)
   em GalaSoft.MvvmLight.Ioc.SimpleIoc.GetInstance[TService]()
   em VidCoder.App.OnStartup(StartupEventArgs e) em d:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 118
   em System.Windows.Application.<.ctor>b__1(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Fixed in 2.25 Beta
