### ISSUE TITLE
Padding color swatch

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#430]
This one appears NOT to have been fixed! The swatch showing the padding color on 4.17 shows constant red, but the actual padding color (as seen in the preview window) is correct.

In other words, much as before but now it's red instead of black.

**Comment by RandomEngy** [comment]
Shoot, I had it all fixed then I went and changed it from a Grid to a Border without testing. Will be fixed in next Beta.

**Comment by Plutocratic** [comment]
Don't worry - mistakes happen.

You're doing a good job :-)

**Comment by RandomEngy** [comment]
Fixed in 4.18 Beta.
