### ISSUE TITLE
vidcoder 4.17 crash on load

### ISSUE THREAD

**Issue by Ghastor** [RandomEngy/VidCoder#432]
as title, crash on load after update...

System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in VidCoder.Services.AppThemeService.GetWindowsTheme() in D:\git\VidCoder\VidCoder\Services\AppThemeService.cs:riga 95
   in VidCoder.Services.AppThemeService..ctor() in D:\git\VidCoder\VidCoder\Services\AppThemeService.cs:riga 83
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   in System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   in System.Activator.CreateInstance(Type type, Boolean nonPublic)
   in System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   in System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   in System.Activator.CreateInstance(Type type, Object[] args)
   in DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   in DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   in DryIoc.ReflectionFactory.CreateServiceExpression(MemberInfo ctorOrMember, ExpressionInfo factoryExpr, ExpressionInfo[] paramExprs, Request request)
   in DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   in DryIoc.Factory.GetExpressionOrDefault(Request request)
   in DryIoc.Factory.GetDelegateOrDefault(Request request)
   in DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   in DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   in DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   in VidCoder.App.OnStartup(StartupEventArgs e) in D:\git\VidCoder\VidCoder\App.xaml.cs:riga 146
   in System.Windows.Application.<.ctor>b__1_0(Object unused)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Fixed in 4.18 Beta.
