### ISSUE TITLE
Add option to 'When Done' behavior

### ISSUE THREAD

**Issue by kphipps** [RandomEngy/VidCoder#433]
Could you add an option so that the 'When Done' behavior resets to 'Do Nothing' each time after it executes? Many times I encode overnight and have the computer hibernate when done. Then the next day I wake the machine and at some point will do another encode forgetting it will hibernate when done, leave the machine and come back and it's hibernating. Many times I will have other things happening such as downloads, which get killed by this.

**Comment by dnitzer** [comment]
Is there an option (as in Handbrake) to call a batch file or external script when the conversion is complete? eg to send a notification, or a call to another program?

**Comment by RandomEngy** [comment]
Sure, I'll put the change in the next Beta release.

**Comment by RandomEngy** [comment]
As of Beta 4.18, the "When done" behavior resets to "Do nothing" after it's triggered.

**Comment by RandomEngy** [comment]
@dnitzer yes, under Picker -> Post-encoding. Though this feature is not on the Windows Store version since it's impossible to invoke outside processes for trusted store apps.
