### ISSUE TITLE
Que order not working, and request for black theme switch on/off...

### ISSUE THREAD

**Issue by saxonz** [RandomEngy/VidCoder#436]
Using VidCoder v4.18 Beta on Windoze 7 ENT x64.
When I add say three files to the que to be (re)encoded and then drag and drop the qued items in the order I want them encoded VidCoder-4.18-Beta starts with the file I added first. It was doing that in version 4.17 also.
You have done a good job with the black theme however for those of us on a PC without themes enabled it is of no use. Can we have a "switch to black theme" tick box or something like that?

Thanks!

**Comment by RandomEngy** [comment]
I don't understand what you're asking about the queue order. Can you list the exact steps to reproduce the problem, the expected behavior and the actual behavior you saw?

**Comment by saxonz** [comment]
Okay so I add a file to encode with the name of 03.avi and then I add another file 02.avi and then I add another file 01.avi and then I see oh crap the que is messed up I should have added them in the order I wanted to encode. So I go to the que to correct the order by dragging the 01.avi to the top of the que and then dragging file 02.avi to be encoded next and finally file 03.avi at the bottem of the que, I hit encode and the program encodes 03.avi, 02.avi and then 01.avi   ...I hope that helps for now the fix is simple, I will just add the vids to encode inthe order I want them encoded, no big deal. Black theme tick box would be great.
Cheers!

**Comment by RandomEngy** [comment]
The drag/drop bug I had in earlier versions but I fixed it in 4.18. Are you sure that's the version you were testing on?

I've put the theme toggle feature on the backlog.

**Comment by saxonz** [comment]
Yes I am testing on v4.18 Beta. Just to make sure I will uninstall, clean up, reboot and reinstall VidCoder v4.18 Beta. The theme toggle feature on the backlog sounds good.

**Comment by saxonz** [comment]
I'm closing this issue. After reinstall everything is working. Thanks for your help.

**Comment by RandomEngy** [comment]
Added manual theme switch in 4.19 Beta.

**Comment by saxonz** [comment]
Thanks, can't wait to see it in action.
