### ISSUE TITLE
wrong progress bar time

### ISSUE THREAD

**Issue by Mister-XY** [RandomEngy/VidCoder#437]
Hello and indeed I noticed that for some time the progress bar and the estimated time calculation are completely wrong. So I am shown a time that is far away from the one still needed. This is particularly noticeable when I add some new movies to the queue.
For a einizige film it is true, but as soon as I add films as I said before and then, then the estimated time calculation goes back further and further.
Suppose the first movie takes 3 hours to convert, and I add the next after 2.5 hours, then the new time is 8 hours and the progress bar goes up to 30% instead of 40-45%.
Thus one can estimate at the end no more how long the 2nd or third film still needed.
I use Vidcoder 4.18 beta
![progress bar](https://user-images.githubusercontent.com/10309056/47453059-01e6c000-d7cc-11e8-99a5-3f22c16998f7.png)

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next Beta.

**Comment by RandomEngy** [comment]
Fixed in 4.19 Beta.
