### ISSUE TITLE
Beta 4.18-19 Update Button did not work

### ISSUE THREAD

**Issue by Mister-XY** [RandomEngy/VidCoder#439]
Hello, i have the problem in vidcoder, that the update button did not work.
I press the button but nothing happens.

**Comment by RandomEngy** [comment]
After you press the button, what does it say under Status?

**Comment by Mister-XY** [comment]
nothing.

**Comment by RandomEngy** [comment]
You don't have a special Debug build installed, do you? Also does anything show up in the Log window when you check for updates?
