### ISSUE TITLE
Feature Request: Video Passthrough

### ISSUE THREAD

**Issue by trickfilmjunkie** [RandomEngy/VidCoder#44]
It might sound silly, but I would like to ask for a feature at VidCoder "Video Passthrough". The similar feature exist for Audio, why not for the video information as well. Basicly I would like to convert some x264 MKV-Files to MP4 without reencoding and I didn't find any easy to use and/or relieable freeware-solution. 

Once again: Sounds silly but why not asking. The least you can say is "no".

P.S. Thank you for VidCoder. Its a very nice piece of software.

**Comment by RandomEngy** [comment]
Thanks! Unfortunately HandBrake has no plans to implement this and has said it is lot of scope. I rely on the HandBrake engine so my hands are tied. Sorry!
