### ISSUE TITLE
Wrong output (sizing)

### ISSUE THREAD

**Issue by Mister-XY** [RandomEngy/VidCoder#440]
Hello, I often have a small but nice mistake here. If I change in sizing, the crop from automatically to custom, then I sometimes get an incorrect resolution. So he changes me to a completely different one but shows that he has taken 0 pixel away. But under output there is something completely different.
I change then z.b. a value, then a part is changed correctly, then I change a different value, then he is properly corrected.
value, then he is properly corrected.
That's why I've made 3 pictures for that, which should clarify that.
From Automatic to Custom
![wrong output](https://user-images.githubusercontent.com/10309056/47926432-d5fcc600-dec0-11e8-8609-264b061cf24d.png)

First value change
![wrong output2](https://user-images.githubusercontent.com/10309056/47926434-d6955c80-dec0-11e8-9724-84d496dedc57.png)

second value change
![wrong output 3](https://user-images.githubusercontent.com/10309056/47926431-d5fcc600-dec0-11e8-862b-63d8bdd0da50.png)

**Comment by RandomEngy** [comment]
Thanks for the report. It does look like  there's something going wrong there, but I can't reproduce the issue. Can you share your %appdata%\VidCoder-Beta\VidCoder.sqlite file?

**Comment by Mister-XY** [comment]
I have uploaded it. I found out, that there are old sources in the sqlite file.
[VidCoder.zip](https://github.com/RandomEngy/VidCoder/files/2545581/VidCoder.zip)

**Comment by RandomEngy** [comment]
Hmm. It doesn't see it as a valid .sqlite file, which makes me think something went wrong in the file upload (since you can open it). Tried downloading and extracting twice.

> Checksum information
> Name: VidCoder.sqlite
> Size: 133691 bytes (0 MB)
> 
> CRC32: 17E4AF7D
> CRC64: AE003562A8754A39
> SHA256: BF135D96C0798419FF1E1F0CDE10CF5F295861120128FE00F1AE09D33F44EE0D
> SHA1: 99C4D6462F5DB3FBFFCDAF9D6839F714AFC2630B
> BLAKE2sp: 4F7D1007F7E7B76086ED010B4F2914B3207F2D84BECB51814E10CE786399E82B
> 
> SQLite error (11): database corruption at line 63851 of [c7ee083322]
> SQLite error (11): database corruption at line 63892 of [c7ee083322]
> SQLite error (11): statement aborts at 4: [SELECT value FROM settings WHERE name = 'Version'] database disk image is malformed

Can you try re-uploading?

**Comment by Mister-XY** [comment]
Ok, have you extracted the file?

**Comment by RandomEngy** [comment]
Yes, I extracted it.

**Comment by Mister-XY** [comment]
Twice

[VidCoder.zip](https://github.com/RandomEngy/VidCoder/files/2545986/VidCoder.zip)

**Comment by Mister-XY** [comment]
Nice to hear that. i have also seen, you have made a change for fdk-aac? What is there the change?

**Comment by RandomEngy** [comment]
It looks like you've used a special build of hb.dll to support fdk_aac. I updated it so that if it finds fdk_aac in a preset and you open it with a version of hb.dll that doesn't support it, it will gracefully fall back to av_aac rather than crash.

**Comment by Mister-XY** [comment]
Ok, thats good. I use the hb.dll with fdk-aac support since 1 week, the crop error is longer there.

**Comment by RandomEngy** [comment]
Fixed in 4.20 Beta.

**Comment by napouser** [comment]
@Mister-XY 

hi
sorry to hijack the thread but i am using this program alot and its amazing but it doesnt have the fdk-aac encoder option
i am in the process of reencoding about 2500 movies and its sad to use an inferior codec
if u have an upgraded version of hb.dll can u share it?
thanks

**Comment by Mister-XY** [comment]
I have a self compiled version from handbrake with enabled fdk-aac. I think, it isn't allowed to share it.

**Comment by napouser** [comment]
well my email is dieksodo@gmail.com
i wont tell anyone 
plz u will save me... 2500 movies!

**Comment by Mister-XY** [comment]
This version is for the beta of vidcoder.

**Comment by napouser** [comment]
i am using the stadard but i wanna switch to the beta at some point for the dark theme

**Comment by Mister-XY** [comment]
with beta, you have also an good aac encoder. it's use the ffmpeg aac. In the "stabel" Vidcoder/Handbrake. it's use the Libav/avconv. That can only 2.0 Stereo aac sound.

**Comment by napouser** [comment]
i heard that fdk-aac is better than the stadard codec from ffmpeg
