### ISSUE TITLE
Not deleting source video file after conversion

### ISSUE THREAD

**Issue by matrixebiz** [RandomEngy/VidCoder#441]
Hello, I have the Advanced option turned on to delete the source video (AVI) after successful video conversion (MP4) but it is not deleting the source when complete. Can you please fix that. Thank you

**Comment by RandomEngy** [comment]
Does a dialog open when you clear the completed files? It only deletes the files after doing that.

**Comment by matrixebiz** [comment]
Hello, after that job is complete, I just exit the program. How do I clear
the completed files to get the dialog box? Thanks

**Comment by matrixebiz** [comment]
No, it didn't ask me.

**Comment by matrixebiz** [comment]
Hi David, my issues was number 5. I still had the source loaded. Thanks
