### ISSUE TITLE
Crash after change the preset

### ISSUE THREAD

**Issue by Mister-XY** [RandomEngy/VidCoder#442]
If i change my preset in encoder setting, vidcoder give me an error message.
I actually use the Beta. 

![error vidcoder](https://user-images.githubusercontent.com/10309056/47962521-4bca7400-e01e-11e8-85fa-ec11a4b2f672.png)

**Comment by RandomEngy** [comment]
Does this happen regularly? If so, can you send me your %appdata%\VidCoder-Beta\VidCoder.sqlite file, and list of steps for how to get it to happen?

**Comment by Mister-XY** [comment]
You have my sqlite file ;-).

**Comment by Mister-XY** [comment]
Here look 
https://github.com/RandomEngy/VidCoder/issues/440

**Comment by RandomEngy** [comment]
Great. Does it happen regularly? Do you have a list of steps that can cause it to happen?

**Comment by RandomEngy** [comment]
Actually, nevermind, I got it to reproduce. Will look at fixing.

**Comment by Mister-XY** [comment]
Ok, you have seen also this error, thats great for me.

**Comment by RandomEngy** [comment]
Fixed in 4.21 Beta.
