### ISSUE TITLE
ENHANCEMENT: Stop - Stop after current tasks

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#443]
I typically have 4 transcodings going on at a time. (Thanks VidCoder v4.x!)

Many times I find myself staring at the progress bars wishing to stop encoding for some reason (needed reboot) but would prefer not to waste the sometimes HOURS put into the current progress as well as not waste more time starting transcodes that I'm going to end up cancelling/stopping.

A useful feature, to me, would be an additional Stop option for stopping new transcodings from starting but allowing the current ones to finish.

**Comment by RandomEngy** [comment]
Implemented in 4.23 Beta.
