### ISSUE TITLE
BUG: (4.19-4.21) Adding to queue doesn't check for duplicates

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#446]
I believe I found the root cause of https://github.com/RandomEngy/VidCoder/issues/435

When adding to the queue (manually or via right click to retry failed), files are not checked for duplicates and are just added. Duplicates of the exact same file name and path should not be re-added to the queue.

**Comment by RandomEngy** [comment]
I assume you are talking about duplicate source paths. What if someone is queuing up a few different copies to try out different settings? Or they want to have different encodings for different purposes?

As for #435, please just give me the logs.

**Comment by bcurran3** [comment]
The issue is duplicates of the exact same path and file getting duplicated into the queue, I'm not suggesting checking only the file name.

**Comment by RandomEngy** [comment]
Sorry, what are you concerned about duplicating? The source path or the destination path? You're referring to "file names" a lot but I'm not sure which one you mean each time you bring it up.

I'm just bringing up some legitimate reasons people might want to have the same source file in the queue twice.

As for logs for the % >100 issue, email david.rickard@gmail.com . I can search through them and find what I need.

**Comment by bcurran3** [comment]
I'm not sure how to word it differently.

You can drag and drop the same file into the queue.

It doesn't make sense. (Maybe it's my setup - overwrite) VidCoder would hit the file and transcode it and then hit the file and transcode it again.... two passes, one same result.

**Comment by bcurran3** [comment]
Logs sent.

**Comment by bcurran3** [comment]
PRIORITY: HIGH

This problem has creeped up many times but I'm looking at it again today..

What I'm seeing: The exact same 4 files replicated in the queue over and over again possibly a few thousand times. I'm confidently guessing that transcodes failed due to a network share going offline and VC then repeatedly attempted to transcode them, failed, and put them back into the queue.

I already cleared my completed so I can't see the exact numbers, but where there should be up to a few hundred files in the queue I believe now there are 38,000+. This is where my enhancement request https://github.com/RandomEngy/VidCoder/issues/416 would come in handy. <snicker> :)

**Comment by bcurran3** [comment]
Screencap and logs sent via e-mail. Done.

**Comment by RandomEngy** [comment]
Do they duplicate on their own or are you using the "retry failed" feature?

**Comment by bcurran3** [comment]
I think both. I KNOW I didn't do retry failed a hundred times, possibly once or twice.

**Comment by RandomEngy** [comment]
I think I figured it out. Fix should be in the next Beta.

**Comment by bcurran3** [comment]
Unfortunately, not yet.

Log files sent.

**Comment by RandomEngy** [comment]
The issue with it creating duplicates should be fixed in 4.22 Beta.

**Comment by hl2guide** [comment]
Seems to me like this could be appearing in version 5.10 Beta.
Maybe an advanced setting could be something like a checkbox for "Keep queue sources unique".

**Comment by RandomEngy** [comment]
I think you are thinking of a different problem. The original issue was with the "retry failed" adding back two jobs instead of one. It wasn't asking to skip over sources that were already in the queue. Could you create a new issue for that?

**Comment by bcurran3** [comment]
Maybe this needs a new issue? Scroll up a little and you'll see that exact duplicates can be put in the queue directly be dragging and dropping them.  Look at the path of the files in the image below:

https://user-images.githubusercontent.com/14026600/48667311-d338ce00-ea87-11e8-8978-ebbfc87f4db3.png

This shouldn't be allowed as who purposely wants to re-encode the same file the same way a 2nd time?

I have not tried a VC release in months so I'm not sure if this bug is still there or not.
