### ISSUE TITLE
ENHANCEMENT: Different name (extension) for log files

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#449]
Program specific and transcoding file specific log files exist as .TXT files.

It would be nice if the VidCoder log files (as opposed to the file specific log files) had a different extension. maybe .LOG for program specific and keep .TXT for file specific?

Would help in quick sorting of log files when submitting for debugging purposes.

**Comment by RandomEngy** [comment]
The extension is supposed to describe what's in the file and what programs can open them. I don't think it would be appropriate to have a different extension for each one, as there's no reason a user would want to use a different program to open each one.

**Comment by bcurran3** [comment]
Maybe pre-pend "vidcoder" to the program log files for easier sorting? Seems a good compromise.

PRIORITY: Low

**Comment by RandomEngy** [comment]
Threw it in 4.21 Beta. It's not prepended because I want the log files in chronological order but you should be able to run a search to get all the app ones.

**Comment by bcurran3** [comment]
Thanks. Anything to help in those instances that I have over 100,000 log files!

**Comment by bcurran3** [comment]
Unfortunately "Application" at the end (4.21) doesn't really help since there's no way for File Explorer to sort by it. It would require a pre-pend or a different extension.

**Comment by RandomEngy** [comment]
Search in file explorer:
vidcoderapplication
-vidcoderapplication
To get the app log files, and everything but the app log files, respectively.

**Comment by bcurran3** [comment]
I know how to do that, but that's COUNTER to what I want..... to delete all the OTHER files easily and leave these so I can email them to you!

You want logs in chronological order? Sure. DIR /OD or use the File Explorer details tab and click Date Modified.

Sorting by name or extension is much easier and intuitive as the methods have already been created to do it easily by default.

**Comment by RandomEngy** [comment]
-vidcoderapplication will show you all the other files so you can delete them.
You can also search "vidcoderapplication" and copy those files to another folder, or even directly add them to a zip file.

**Comment by bcurran3** [comment]
I completely get it, still requires more work then sorting by filename for easy distinction.
