### ISSUE TITLE
Beta 2.21.0.0

### ISSUE THREAD

**Issue by rumred85** [RandomEngy/VidCoder#45]
Since installing beta 2.21.0.0 I am unable to encode videos.  It gets to between 1.6 and 1.7% and just stops.  It doesn't even write a file to the output directory.  I have tried it with quicksync on and off.  While i am not certain it is the beta causing the problem I can tell you that I use vidcoder almost everyday and have used it several times this week with no problems.

I have tried rebooting and installing the previous beta.  It will encode with the stable version.

**Comment by RandomEngy** [comment]
Does the latest HandBrake nightly have the same behavior?

**Comment by rumred85** [comment]
I apologize for my ignorance but are you asking me to install the handbrake nightly build and encode there or are you asking me to do something else?

**Comment by RandomEngy** [comment]
Yeah that's what I'm asking.

**Comment by rumred85** [comment]
Ok, I downloaded and installed nightly build HandBrake-f363762_x86_64-Win_GUI.exe.  I set all the settings as close as I could to my Vidcoder settings.  It encoded fine.

**Comment by RandomEngy** [comment]
I haven't picked up this change in HandBrake yet: https://trac.handbrake.fr/changeset/2eef7441c3bf670d4392c3cbcf887c77a0354aef Do you have a "foreign audio search" subtitle track?

**Comment by rumred85** [comment]
Yes

Is that it?

**Comment by rumred85** [comment]
I like to burn in foreign audio so I don’t have to turn on subtitles when I am using plex.  That way it just shows them

**Comment by RandomEngy** [comment]
Okay so it looks like your issue will be fixed when I pick up the latest HandBrake core.

**Comment by rumred85** [comment]
Thank you for your help.

**Comment by RandomEngy** [comment]
Fixed in 2.23 Beta.
