### ISSUE TITLE
BUG (4.x?-4.21) VidCoder can run more worker tasks then configured under circumstances

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#453]
I think I've reported this before but can't find it. It might have been along with something else similarly related. Sorry for not finding it.

Sometimes I've experienced VidCoder starting more transcoding tasks then I have it configured to do. Below there is a screenshot of VidCoder running 5 worker tasks. I am configured for 4. I'm pretty sure I've seen 6 in the past and never had a clue as to why it happened.

Tonight I have a clue. I was dragging and dropping files in the queue to group like files together. I was also moving small groups of similar files to the top of the queue as well as the bottom of the queue. While doing this I noticed my Completed (1) tab appeared. I believe that moving files (possible and probably to the top of the queue) at the same time as a file being finished transcoded causes the issue.

I'm going to assume logs would help. Will try to send tomorrow.

![image](https://user-images.githubusercontent.com/14026600/49421055-2460e700-f743-11e8-926d-9c64871a53c4.png)

Also of note, VidCoder shows SEVEN files being transcoded!

![image](https://user-images.githubusercontent.com/14026600/49421308-28d9cf80-f744-11e8-9e24-d521695add46.png)

**Comment by bcurran3** [comment]
I just noticed a similar problem on another machine when moving a few files to the top of the queue at apparently the same time as a file finished transcoding.

Slightly different results though. Task Manager has now lost track of some of the worker threads and I have 5 worker processes going on even though I'm configured for 4.

![image](https://user-images.githubusercontent.com/14026600/49421526-33489900-f745-11e8-9736-ba32f6f0d996.png)


![image](https://user-images.githubusercontent.com/14026600/49421545-40fe1e80-f745-11e8-8169-0691e69dd224.png)

**Comment by RandomEngy** [comment]
Thanks for the report. The "Move to Top" functionality was broken and moving the items too far up in the queue. Will be fixed in next beta.

**Comment by RandomEngy** [comment]
Fixed in 4.23 Beta.

**Comment by bcurran3** [comment]
About to try 4.23, confirmed still problem in 4.22

![image](https://user-images.githubusercontent.com/14026600/49896429-2d6b4b80-fe08-11e8-8ad9-a897c3915f3b.png)
