### ISSUE TITLE
change: make update message persistent

### ISSUE THREAD

**Issue by starkebn** [RandomEngy/VidCoder#454]
Please make the message that there is an update available persistent, so that if I don't notice it on loading I can still decide to update before starting some encoding

**Comment by RandomEngy** [comment]
I don't think I'd like to make it persistent. How would you feel about an option to pop a dialog box on program start rather than exiting?

**Comment by starkebn** [comment]
sounds good

**Comment by RandomEngy** [comment]
Added option in 4.24 Beta.
