### ISSUE TITLE
Error when adding certain discs

### ISSUE THREAD

**Issue by meetloaf13** [RandomEngy/VidCoder#46]
Hello,

I've been using VidCoder for years.  I use it in conjunction with AnyDVDHD and have had zero issues.  Just yesterday I was trying to rip a few videos using the latest version of VidCoder.  When I add these two particular movies I get an error that says "An error occurred while scanning".  

As some background, the videos I'm trying to rip are "edited" movies, so they have already had DRM stripped and whatnot.  

I have attached the log file.
[2016-01-21 23.01.25.txt](https://github.com/RandomEngy/VidCoder/files/101629/2016-01-21.23.01.25.txt)

Thank you for your help

**Comment by RandomEngy** [comment]
Looks like the HandBrake core failed to scan it. Can you see if it replicates on the latest HandBrake nightly? If so you can report the issue to them.

**Comment by meetloaf13** [comment]
Certainly, I may not get a chance to remote into that machine until the morning, but I'll update.  If seeing the source ISO helps, I can link that too

**Comment by meetloaf13** [comment]
no dice, heres the log
[2016-01-22 20.50.58.txt](https://github.com/RandomEngy/VidCoder/files/101712/2016-01-22.20.50.58.txt)

**Comment by RandomEngy** [comment]
Ahh, sorry. I meant to try and see if it happens with the official HandBrake GUI, so I can tell if it's a HandBrake or VidCoder issue.

**Comment by meetloaf13** [comment]
Got it.

**Comment by meetloaf13** [comment]
Looks like it's a handbrake issue, I'll hit the forums over there. Thanks!
