### ISSUE TITLE
Click & Drag Videos Not Working After 4.27 Beta

### ISSUE THREAD

**Issue by Cornbane** [RandomEngy/VidCoder#467]
The ability to drag a video into the program has stopped working after updating the beta version to 4,27 from 4.26. The cursor turns into the cross-out symbol when hovering with a dragged video.

**Comment by RandomEngy** [comment]
What version are you using? Portable or installer?

**Comment by Cornbane** [comment]
Installed version.

**Comment by RandomEngy** [comment]
Hmm. I can't reproduce the issue. I haven't changed anything related to drag+drop between those two versions. Can you try uninstalling and reinstalling? If it's still broken, can you tell me your Windows version?

**Comment by Cornbane** [comment]
Windows 10.

I just uninstalled and install 4.26, which the drag and drop works. Updated to 4.27 via the in-program updater and now the drag and drop doesn't work. I'm dragging to the same spot as I did with the 4.26 test - where the it says "(Or drag video files or folders here)".

**Comment by Cornbane** [comment]
Ah ha. Installing 4.27 directly from the .exe works, but updating from the internal updater doesn't.

**Comment by Cornbane** [comment]
Everything seems to be working fine with the 5.00 Beta and 4.28 release when updating via updater.
