### ISSUE TITLE
VidCoder 4.27 Beta (Portable) wont' start

### ISSUE THREAD

**Issue by padi543** [RandomEngy/VidCoder#468]
Launching the portable version of “VidCoder 4.27 Beta” I get the error message defined by 'DataTooOldRunVidCoderVersion':

`<value>Your data is too old to upgrade. Run VidCoder {3.15} once to upgrade it to a compatible version, then try this version again.</value>`

However version 3.15 (and 3.16) are running fine, but the error message above keeps showing up …

I had _installed_ nearly every Vidcoder version since v1.x but have ALWAYS used the portable packages by simply extracting the content of the EXE-file to a new folder.

What's the proper way to migrate to the new settings-format?
Will this be backward-compatible with version 3.16?
… would be nice if the migration feature would be integrated into Vidcoder itself, not some part of the installer.

**Comment by RandomEngy** [comment]
I'm not familiar with the practice of extracting files out of the portable installer; I've never installed anything that way. In any event, where is your VidCoder.sqlite file kept? This can be beside the portable .exe or can be in %appdata%\VidCoder or %appdata%\VidCoder-Beta .

The upgrade code is actually part of VidCoder, though the trouble is that running the Stable version looks at a different .sqlite file and doesn't upgrade the beta .sqlite file.

**Comment by padi543** [comment]
Thanks!

0. Portable executables can often be extracted simply by using 7-Zip,
1. My Settings are under appdata ... I had both: _VidCoder_ and _VidCoder-Beta_
2. Just tried 4.28 (non beta) ... the program starts-up fine!

=> Guess v4.27 was only accessing/testing my _Beta_ settings which are probably quite outdated...

Problem solved, 
thanks again!
