### ISSUE TITLE
Vidcoder 4.28 Portable don't start - with errors

### ISSUE THREAD

**Issue by emaen** [RandomEngy/VidCoder#469]
Hello !
I use vidcoder portable version from years now (stables , not betas).
Today, downloaded new 4.28 portable version and run it, make Vidcoder crash with this log : 

System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.Baml2006.Baml2006Reader.Process_PropertyWithConverter()
   à System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   à System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   à System.Windows.Baml2006.Baml2006Reader.Read()
   à System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à VidCoder.View.Main..ctor() dans D:\git\VidCoder\VidCoder\View\Main.xaml.cs:ligne 76
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, Boolean nonPublic)
   à System.Activator.CreateInstance(Type type)
   à VidCoder.Services.Windows.WindowManager.CreateWindow(Type viewModelType) dans D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:ligne 673
   à VidCoder.Services.Windows.WindowManager.PrepareWindowForOpen(Object viewModel, Object ownerViewModel, Boolean userInitiated, Boolean isDialog) dans D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:ligne 430
   à VidCoder.Services.Windows.WindowManager.OpenWindow(Object viewModel, Object ownerViewModel, Boolean userInitiated) dans D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:ligne 162
   à VidCoder.App.OnStartup(StartupEventArgs e) dans D:\git\VidCoder\VidCoder\App.xaml.cs:ligne 169
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Hope that it can help.
Thank you for all !

Emaen.

**Comment by RandomEngy** [comment]
Last time I saw this someone was running an old Windows 10 version that did not have .NET framework 4.7.1 installed. Can you let me know what your Windows version is? Also if you have .NET Framework 4.7.1 installed?

**Comment by emaen** [comment]
Hello !

I'm runnning an old Windows 7 version that works like a charm !
But was still running .NET framework v 4.6.2.
I've updated to .NET v 4.7.2 and now, Vidcoder just perfectly works !

Thank you for all.

----- Mail original -----
De: "David Rickard" <notifications@github.com>
À: "RandomEngy/VidCoder" <VidCoder@noreply.github.com>
Cc: "emaen" <emmanuelbilleaud@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 13 Janvier 2019 01:39:54
Objet: Re: [RandomEngy/VidCoder] Vidcoder 4.28 Portable don't start - with errors (#469)



Last time I saw this someone was running an old Windows 10 version that did not have .NET framework 4.7.1 installed. Can you let me know what your Windows version is? Also if you have .NET Framework 4.7.1 installed?
