### ISSUE TITLE
Encoding stuck at 0.4% and never continues encoding

### ISSUE THREAD

**Issue by rlewandowski23** [RandomEngy/VidCoder#47]
I setup a que of alot of videos and started to encode with VidCoder 2.20.  I can't get it to progress past 0.4%.  I have attached my que and log.  Perhaps this is a new bug?  I don't think I've actually done an encode with VidCoder in a couple versions.

[log.txt](https://github.com/RandomEngy/VidCoder/files/102638/log.txt)

[Queue.zip](https://github.com/RandomEngy/VidCoder/files/102639/Queue.zip)

**Comment by rlewandowski23** [comment]
I hoping we can figure this out quickly since in the mean time I can't get VidCoder to encode anything :(.

**Comment by RandomEngy** [comment]
Fixed in 2.23 Beta.

**Comment by rlewandowski23** [comment]
I updated to 2.23 beta and I was able to get one video to encode and now the next video in the que is hanging.  Thoughts?

[log.txt](https://github.com/RandomEngy/VidCoder/files/105526/log.txt)

![encodestatus](https://cloud.githubusercontent.com/assets/16128158/12591879/80f5fcf2-c42f-11e5-9924-c20c39b77a43.png)

**Comment by RandomEngy** [comment]
Looks like the latest HandBrake nightly is having the same issue. I opened a bug on them; https://github.com/HandBrake/HandBrake/issues/69

**Comment by rlewandowski23** [comment]
Looks like they fixed it.  Let me know when you have a new beta and I'll give it a shot.

**Comment by RandomEngy** [comment]
Fix included in 2.24 Beta.
