### ISSUE TITLE
Wrong subtitle processing order in 4.28 Stable release

### ISSUE THREAD

**Issue by MYodaTheRe** [RandomEngy/VidCoder#472]
Hi,

I have spotted a wrong subtitle order in the last stable release v4.28.
If there are two (or maybe even more?) subtitles and the first is language A and the second language B (ordered in the list) then the output tracks will be changed: First: B, Second A.

I got the error with a "normal" subtitle track, which should be on position 1 and the second track should only contain the "forced" parts of the subtitle (with the help of the duplicate feature). However in the output file the tracks are changed around. This behaviour was not present in the 3.16 stable release.

Regards,
Michael

**Comment by RandomEngy** [comment]
Should be fixed in 4.29.

**Comment by MYodaTheRe** [comment]
Thanks for this quick fix, awesome work you are doing on vidcoder!

I found another little, minor bug: If you first select the subtitle tracks which to encode (and set the proper flags like forced or default) and then duplicate one track the selections will be deleted and you have to select it again.

I know this is a very minor issue, but if you handle alot of encodings a day it would be awesome if you could fix that in the next 4.30 release.

**Comment by RandomEngy** [comment]
The subtitle duplication issue should be fixed in 4.30.
