### ISSUE TITLE
V5.1 beta Full Parameter List is incomplete and intermittent 

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#480]
I'm on board to use the new Full Parameter List popup in More Settings, but I think there's problems.

1/ If I look at the encoding settings of a video in MediaInfo I can see a list of parameters which I assume to be the **full** list used by HandBrake. In the revamped More Settings window the list that pops up is not the full list, but the few parameters that are displayed match some of what I see in MediaInfo.
2/ If I change e.g. the Constant Quality slider setting and check the More Settings window, sometimes I see a changed list in the popup, other times it's empty. In either case it's still not the full list.
3/ If I put any settings of my own in the More Settings window, that is all I see in the popup, just mine, not the full list.
4/ Once there's been an empty list displayed, it intermittently stays empty for that session.

Could I suggest that it would be simpler for you to code and us to use if you:
a/ rename the 'More Settings' window to 'Encoding Parameters',
b/ get rid of the popup and just display the full parameter list and code it so that it automatically updates when you change any setting,
c/ add a 'show/hide parameters" button to make the 'Encoding Parameters' window optional for people that don't want to see any inner workings,
d/ make it possible to copy the full parameter string so that it can be pasted into HB when checking out a problem, - edit: no don't bother, not supported by HB
e/ given what has been said in a recent thread - just get rid of the facility to add or change parameters manually.

**Comment by RandomEngy** [comment]
I made some changes in 5.2 Beta.

- It shows the options string at all times, underneath the More options text box
- Fixed a bug that caused it to stop updating after changing the encoding preset

The quality slider isn't going to affect what shows up in the parameter list.

**Comment by iamjaydear** [comment]
OK, thanks. However:
1. The end of the string disappears if it's too long, so why not put it in the box where it can wrap (and be edited)?
2. The same message "Additional advanced etc." appears for the More Settings box and the options string. Is that intentional?

**Comment by RandomEngy** [comment]
1) Yes, that was getting cut off.
2) No, was not intentional.

Both fixed in 5.3 Beta.

**Comment by iamjaydear** [comment]
I'd still like to be able to select and copy the options string... only for use in a text editor - I promise :)

**Comment by RandomEngy** [comment]
Changed to a text box in 5.4 Beta. You can select/copy/paste it now.

**Comment by iamjaydear** [comment]
Thank you very much :)
