### ISSUE TITLE
Urgent bug in V4 - audio channel shows "unknown-chan-mask"

### ISSUE THREAD

**Issue by Growlertiger** [RandomEngy/VidCoder#482]
Just updated to 4.2.9. Bug may be in all V4 versions.
Encoding to mp4 from mkv. Video is fine. Audio source E-AC3, 5.1. Tried encoding to AAC, also tried AC3 also tried Passthrough. In every case result plays OK in VLC and sounds correct.
BUT using VLC look at the codec info and it shows the Channel as "unknown-chan-mask" instead of "3F2R/LFE".
So why does this matter? If you import the file into Vegas Pro (and I imagine various other software), the sound appears as a single corrupt channel, making Vidcoder unusable.
Downloaded 3.16 and it works correctly.
Hope this helps.

**Comment by Growlertiger** [comment]
I just tried it with version 5.1 Beta and it has the same bug.

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by Growlertiger** [comment]
I just tried the latest Handbrake as requested.
I set Normal profile. That uses AAC (faacv). Set 6 channel discrete. Set 384 rate. Result was correct, VLC codec display shows Channels as 3F2R/LFE which is correct.
I'm a beginner at Handbrake, but that seems the same settings I was using in Vidcoder. And remember 3.16 works correctly.
I suggest you try it on any mkv video with 5.1 AC3 and see what Channels are reported in the encoded mp4.

**Comment by RandomEngy** [comment]
For me when I do AAC with 5.1 mixdown in VidCoder it displays as 3F2R/LFE in VLC. Also there is no "Normal" profile anymore. Can you post a pastebin link for the HandBrake and VidCoder encodes you did? That would allow me to see which encoder parameters changed. Let's compare VidCoder 4.30 stable with HandBrake 1.2.0 stable here.

**Comment by Growlertiger** [comment]
I updated Vidcoder to 4.30.
I found I had an old version of Handbrake despite it telling me there were no updates. I uninstalled and installed 1.20.
I created a one minute long file using Vidcoder 4.30, making it easy to do tests. This is an mkv file, E-AC3 5.1.
I loaded it in Handbrake 2.0. The only setting I changed was to choose a 5.1 mixdown. The resulting m4v file has the bug.
So the good news for you is that the bug is in Handbrake.
The bad news is that this bug is a real problem.
The small test file is the only file in this folder, you can encode it yourself:
https://www.universalquestions.com/test/
Will you report this to the Handbrake developers? I have no experience of Handbrake.

**Comment by RandomEngy** [comment]
Since I can't reproduce it you should report it to https://github.com/HandBrake/HandBrake/issues with the activity log.
