### ISSUE TITLE
Channel bug is fixed in latest Handbrake nightly. Version of Vidcoder with fix?

### ISSUE THREAD

**Issue by Growlertiger** [RandomEngy/VidCoder#484]
Regarding the channel bug I reported here regarding mkv files with 5.1 channels having incorrect data about the channels in the mp4 file created by Vidcoder. It proved to be a Handbrake bug and I reported it to them.
It has been fixed and Handbrake now works correctly. I tested using the latest nightly build:
Nightly 20190122165149-557a331-master (2019012301)

Please could you kindly add a comment here when Vidcoder is updated with a Handbrake release that includes the fix - in other works the next full Handbrake release beyond 1.2.0. That way I will know when it is safe to upgrade to the latest from 3.16. Thank you.

**Comment by RandomEngy** [comment]
Handbrake core is updated in Beta 5.2.
