### ISSUE TITLE
Drag & Drop Issue

### ISSUE THREAD

**Issue by Blickie** [RandomEngy/VidCoder#487]
5.x Betas & late 4.x Betas
- I have program set to check for updates on program start.  This works fine.
- Update works fine and program reopens. This works fine.
- But right after program reopens after an update, I cannot drag and drop a video file onto the program.  I have to close and reopen the program to get drag and drop feature back.  You should be able to repeat this issue following these steps.

Thanks

**Comment by RandomEngy** [comment]
I found the issue. It was running VidCoder as Administrator after updating. The next release (after today's releases) should open VidCoder as a normal user and allow drag+drop.
