### ISSUE TITLE
Multiple encodings, add trigger

### ISSUE THREAD

**Issue by MYodaTheRe** [RandomEngy/VidCoder#488]
Could you add a trigger for starting multiple encodings by adding more jobs to the job list, please?

In v4.30 (tested), if you have enabled two or more multiple encodings, they will only start as soon as one job has finished. But if only one encoding is currently running, the next added job (second parallel encode) will not start immediately after getting added to the encoding list.

**Comment by RandomEngy** [comment]
Added in 4.32.
