### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by foxdav** [RandomEngy/VidCoder#49]
Hi

Mine is a query rather than an issue.

I've been slowly using VidCoder to rip my accumulated DVD collection and save them on a hard drive instead of the space-hogging DVD boxes. All well to date. However I have a number of music DVDs / concerts that I'd like to rip with the audio in a lossless format - .flac or similar. Is this practicable with VidCoder?

**Comment by RandomEngy** [comment]
Yes, if you rip to MKV you can use FLAC.

**Comment by foxdav** [comment]
Many thanks
