### ISSUE TITLE
Intel QSV: constant quality value is not applied with media sdk 1.17

### ISSUE THREAD

**Issue by bjmi** [RandomEngy/VidCoder#50]
In the last days an update for intel graphics drivers for Windows 10 was rolled out and the media sdk version bumbed from 1.16 to 1.17 on my system.

The constant qualitiy value is set to _30_ but the output file size reached 30 GB+ for a simple DVD.
Log file states that quality value of 0 is used.
```
Intel Quick Sync Video support: yes
  - Intel Media SDK hardware: API 1.17 (minimum: 1.3)
  - H.264 encoder: yes
     - preferred implementation: hardware (any)
  - H.265 encoder: no
[...]
encqsvInit: RateControlMethod LA_ICQ ICQQuality 0 LookAheadDepth 100
```
I found an older log that has quality value 30 set.
```
Intel Quick Sync Video support: yes
  - Intel Media SDK hardware: API 1.16 (minimum: 1.3)
  - H.264 encoder: yes
     - preferred implementation: hardware (any)
[...]
encqsvInit: RateControlMethod LA_ICQ ICQQuality 30 LookAheadDepth 100
```
I don't whether it is a vidcoder or an handbrake issue.
Affected Version: 2.23 (beta)

**Comment by RandomEngy** [comment]
Very well may be a HandBrake issue. If you're using the VidCoder beta you could compare against the latest HandBrake nightly to find out.

**Comment by bjmi** [comment]
Oh I missed to state that I tested it with Vidcoder 2.23 (beta)

**Comment by bjmi** [comment]
It was a Intel HD Graphics driver issue. Current drivers work fine again.
