### ISSUE TITLE
Vidcoder 5.4 crash

### ISSUE THREAD

**Issue by valkryie999** [RandomEngy/VidCoder#500]
Vidcoder 5.4 crash after opening this video in this link https://www.dropbox.com/s/lof4u7xzf4ej6hf/%5BDragon-Releases%5D%20Heroic%20Age%20-%2001v2%20%282007%29%20%5BDual%20Audio%5D%20%5B10-bit%5D%20%5BBDRip%5D%20%5BHD%201080p%5D.mkv?dl=0

**Comment by RandomEngy** [comment]
Thanks for the report. Looks like the crash was due to bad handling of a track with 96 kHz sample rate. I'll have this fixed in the next release.

**Comment by RandomEngy** [comment]
Fixed in 5.5 Beta.
