### ISSUE TITLE
Random Close after Scanning Source

### ISSUE THREAD

**Issue by MartyrKomplx** [RandomEngy/VidCoder#503]
Windows' VidCoder 4.32 Installed (Non-Store)
Windows' VidCoder 5.4 Beta Portable
Windows' VidCoder 4.31/4.30/4.29 Portable
MakeMKV ripped source, Blu-Ray Akira 25th Anniversary ripped with Video, TrueHD x3, PGS x2, Chapters (This was ripped twice to rule out a bad copy)

VidCoder (all listed above) consistently becomes non-responsive immediately after scanning. Does not finish populating the Video/Audio/Subtitle selection subsection, [seen here](https://imgur.com/a/0iHA4Ig). Roughly 5-10 seconds of non-responsiveness ends with VidCoder closing with no error dialog. Looking at the logs (Verbose 1&2) reveal nothing out of the ordinary, no warnings or errors, with the very last entry of the log being "# Scan completed"

I've tried this with "original" source, as well as "remuxed" source (ran through MKVToolNix Gui 29.0.0 with no changes).  I've also adjusted the "Picture previews" from 25 to 10, and the preview length down to 0 seconds even.  I've turned off Autocropping. Finally, I've tried using a remuxed source with only the video and one audio included.

Latest Handbrake (1.2.0) does not have the same issue, and scans/completes without incident.

For reference, I've converted close to 200 different DVD/Blu-Ray rips with no similar incident.

[EDIT: Re-ripped the blu-ray, with Dolby Digital x3, and it scans and preps no problems ... an issue with TrueHD I guess? I don't remember if any of my other Blu-Rays used that format]

[EDIT 2: It seems Nolan's Batman Begins and The Dark Knight used TrueHD, and I was able to scan/convert that with no issue]

**Comment by RandomEngy** [comment]
When it becomes non-responsive, could you open task manager, right click on the process and select "Create dump file"? Then share the dump file with me and I can find out where it might be getting hung up. Or get me the problematic source.

**Comment by MartyrKomplx** [comment]
As requested, I've created the [dump file](https://www.mediafire.com/file/bu85mvareqp6ec7/VidCoder+DMP.7z). As for getting you the source, it's a 30GB file, and it took me half an hour just to upload this 120MB dump ... there's no way I could get you the source without just physically sending you the blu-ray and having you rip it.

**Comment by RandomEngy** [comment]
Thanks. I'll take a crack at it when I get back from vacation in a week or so.

**Comment by MartyrKomplx** [comment]
No... Thank YOU. You dont owe me, but I would love to be able to compress this audio from a lossless than a lossy source.

**Comment by iamjaydear** [comment]
There was an issue where the scanning would sometimes fail and crash VC if the file had been dragged in from a browser and the browser was closed before the scanner finished. There was no problem if the file was imported by VC's internal browser.

**Comment by MartyrKomplx** [comment]
> 
> 
> There was an issue where the scanning would sometimes fail and crash VC if the file had been dragged in from a browser and the browser was closed before the scanner finished. There was no problem if the file was imported by VC's internal browser.

I tried using the Open File, and navigating/selecting from within VidCoder. It would still force close in the same place.

**Comment by RandomEngy** [comment]
Thanks, the stack trace helped narrow down the problem but it's going to be a bit tricky to pin down. I added some additional logging in 5.5 Beta that should allow me to load up the scan JSON without needing the entire file. It would be helpful if you could check %appdata%\VidCoder-Beta\Logs and share the scan log for the problematic file.

**Comment by MartyrKomplx** [comment]
With the new update (4.33, and 5.5) it fully loads/scans the file now. It would make sense, and I would assume, that it has to do with that "high audio sample rate" issue you fixed. (The TrueHD tracks have 96kHz and 192kHz rates)

In any case, thank you. Seems the problem is solved.
