### ISSUE TITLE
quick settings for audio and video options

### ISSUE THREAD

**Issue by Woodmanananth** [RandomEngy/VidCoder#508]
In beta 5.4 I have that small icon for the settings in the main window behind the file name and can easily enter the settings. In 4.31 I think I saw this setting icon also but it´s gone (maybe I´m wrong and it was never there). I´m using the portable versio of 5.4 and 4.31/32 and cleared all data.

How do I get back that little icon in 4.31? I know I can go to the settings via "window" and so on. But I´m sure it was there in non beta version....
![vidcoder](https://user-images.githubusercontent.com/47917515/53285973-13cf7400-3768-11e9-90ba-1636257ec441.JPG)

**Comment by RandomEngy** [comment]
It was never there in v4. It's only in the v5 Betas.

**Comment by Woodmanananth** [comment]
...so I was wrong. thx anyway
