### ISSUE TITLE
Error scanning nested folders

### ISSUE THREAD

**Issue by stevefal** [RandomEngy/VidCoder#51]
I'm trying to convert MKVs on a server in a nested folder structure. Scanning a folder with only files inside works fine, but scanning a folder containing child folders fails with a non-specific error. I tried with both stable and beta versions.

**Comment by RandomEngy** [comment]
Are you trying to open it as a DVD folder? It should work when you just drag the folder onto the UI.

**Comment by RandomEngy** [comment]
That should be the fix, re-open if you're still having issues.
