### ISSUE TITLE
Resolve ambigious queue item deletion

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#512]
Please consider changing the queue's "Delete" context menu item to "Remove from Queue" with a **minus** icon.

![vidcoder - remove from queue](https://user-images.githubusercontent.com/17044982/53471622-689d2280-3ab9-11e9-9ab7-99e4525a24d0.png)

"Delete" sounds scary to new users and feels like "hey, does that delete the video too?".

**Comment by RandomEngy** [comment]
That's a good suggestion.

**Comment by RandomEngy** [comment]
Implemented in 5.6 Beta.
