### ISSUE TITLE
Clearing the queue globally

### ISSUE THREAD

**Issue by wantirna** [RandomEngy/VidCoder#515]
There is one issue with vidcoder in the area of the queue. There should be a means of clearing the queue globally and not one by one which can be very frustrating if you have a lot of videos in the queue and also the queue does not clear automatically on shut down which should be a must as i've found in version 4.34 the queue stays when you shut vidcoder down and re-open.

**Comment by RandomEngy** [comment]
You can Ctrl+A -> Right click -> Delete. But I agree it would be handy to add another context menu option.

**Comment by RandomEngy** [comment]
Added a context menu option in 5.6 Beta.
