### ISSUE TITLE
VidCoder 5.6 Beta: Log File Options

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#522]
Options for logs would be really useful:
* Create logs (checkbox)
* Open logs folder (button)
* Compress logs (button)
* Clear logs (button)

**Comment by RandomEngy** [comment]
Which ones of these would you personally use?

**Comment by hl2guide** [comment]
I'm pretty techie so I'd prefer it to list logs (and their raw text) in the GUI itself and then not have separate text files for logs at all. Consider it giving more power to the user and not leaving traces. 💃

**Comment by RandomEngy** [comment]
So it sounds like you only really want 1 and 4 then? Since opening the logs folder and compressing logs don't make sense if you don't have log files.

**Comment by RandomEngy** [comment]
Added the Clear and Open log folder buttons in 5.8 Beta.
