### ISSUE TITLE
Beta 5.7 stop encoding

### ISSUE THREAD

**Issue by SteveLevesque** [RandomEngy/VidCoder#528]
I can't figure out why it suddenly stop, but I was unable to encode anymore on beta 5.7.

Same files works great on Vidcoder 4.35, I also try to move the file, do the same.

Encoding start, but stay at 0 fps and do nothing.

**Comment by RandomEngy** [comment]
Can you send me the partial encode log when it's stuck?

**Comment by SteveLevesque** [comment]
Not sure which one you want, so I sent you all

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : David Rickard <notifications@github.com>
Envoyé : Wednesday, April 3, 2019 8:46:53 PM
À : RandomEngy/VidCoder
Cc : SteveLevesque; Author
Objet : Re: [RandomEngy/VidCoder] Beta 5.7 stop encoding (#528)


Can you send me the partial encode log when it's stuck?

**Comment by SteveLevesque** [comment]
Just see that I sent you the logs for Vidcoder 4.35, here's the one for the 5.7 beta
[2019-04-06 12.38.30 Encode Mommy.mp4.txt](https://github.com/RandomEngy/VidCoder/files/3050930/2019-04-06.12.38.30.Encode.Mommy.mp4.txt)

**Comment by RandomEngy** [comment]
Hey, been on vacation for a bit. Got another look at this. In %programfiles%\VidCoder-Beta have you customized VidCoder.exe.config or VidCoderWorker.exe.config?

They should both have an entry like this:

```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

This binding redirect should prevent the error you're seeing.

**Comment by SteveLevesque** [comment]
I didn't, it was exactly like you said.

**Comment by RandomEngy** [comment]
So they both had the binding redirect in place? What is your OS version?

**Comment by SteveLevesque** [comment]
Vidcoder 4.35 was like that: (joint file) but works

**Comment by SteveLevesque** [comment]
And I have Windows 10 v1809 (17763.437)

**Comment by RandomEngy** [comment]
I'm interested in what you are seeing on the Beta 5.7 installation. Not in the file that's working. Is the file you posted what you're using for Beta 5.7?

**Comment by SteveLevesque** [comment]
The first one was for 5.7, the one that is the smae that you ask me

**Comment by RandomEngy** [comment]
For 5.7, does VidCoderWorker.exe.config look the same way?

**Comment by SteveLevesque** [comment]
This is the 5.7 : 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<appSettings>
		
		
	</appSettings>

  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1"/>
  </startup>

  <runtime>
    
    <AppContextSwitchOverrides value="Switch.System.Windows.Controls.Grid.StarDefinitionsCanExceedAvailableSpace=true"/>

    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by RandomEngy** [comment]
Okay that looks correct. I'll need to puzzle over this one some more. I guess if all else fails I can just bump the JSON version number on the HandBrake interop assembly and remove the need for the binding redirect.

**Comment by SteveLevesque** [comment]
Seems to be sloved with 5.8 beta
