### ISSUE TITLE
VidCoder CLI problem in 5.7 Beta

### ISSUE THREAD

**Issue by atziasios** [RandomEngy/VidCoder#529]
First, I'd like to thank you for this great program!

I came upon a problem with CLI in the latest beta (5.7). When issuing this on Windows command line:
VidCoderCLI.exe encode -s "myVideo.mkv" -p "myPreset"

it yields:

args: encode -s myVideo.mkv -p myPreset
Action: 'encode'
Action length: 6
Connecting to named pipe 'VidCoderAutomationBeta' on machine '.'
Connected.
Sending Request message
{"CallId":1,"MethodName":"Encode","Parameters":["myVideo.mkv",null,"myPreset",null],"GenericArguments":[]}
Pipe has closed.

Connecting to named pipe 'VidCoderAutomationBeta' on machine '.'
...

and it continues like that and it keeps adding the same file in the VidCoder encoding queue.

In the previous beta (5.6) it gives:

args: encode -s myVideo.mkv -p myPreset
Action: 'encode'
Action length: 6
Encode started.

and it works as expected.

Could you take a look at this? Perhaps it is somehow related with the WCF named pipe change...

Thank you in advance.

**Comment by RandomEngy** [comment]
Fixed in 5.8 Beta.
