### ISSUE TITLE
Picker does not change encoding settings window

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#53]
The Picker locks the preset selector in the main window, but not to the one it has selected. Additionally it does not change to the current settings in the Encoding Settings window.

Logically, The Picker should display the current preset in the main window and that preset's settings in the encoding settings window. Those settings are NOT locked by the picker, so any changes one might make must ultimately be incorrect if the wrong ones are displayed. Are changes just ignored perhaps? I haven't had the time to test that.

**Comment by RandomEngy** [comment]
Fixed in 2.25 Beta.
