### ISSUE TITLE
New Splash Screen?

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#534]
VidCoder is awesome! Please consider making the **splash screen** smaller and more modern.

**Comment by RandomEngy** [comment]
Do you have a new image you'd like to see there?

**Comment by hl2guide** [comment]
Maybe something like:

![draft1](https://user-images.githubusercontent.com/17044982/55959248-c83c3f80-5cad-11e9-97da-f73e984f6653.png)

with the VidCoder logo in the middle, with a sheen.

Photo Sourced from: https://pixabay.com/illustrations/lens-camera-photographer-photo-490806/
_Free for commercial use
No attribution required_

**Comment by RandomEngy** [comment]
That's a good suggestion but I would like something clean, professional and simple, that incorporates VidCoder's green theme color. Something like the Office splash screen.

**Comment by hl2guide** [comment]
hmm okay, I'll see if I can mockup an example for that. Is there a high res logo available?

**Comment by RandomEngy** [comment]
I have one on my home PC but I'm out on vacation now. I can send you it in a couple of weeks.

**Comment by RandomEngy** [comment]
This is the highest-res version I have, with transparency:

https://drive.google.com/file/d/11ka6xO0XOwa1ypr3O-ezD53-FKaXmzn9/view?usp=sharing

**Comment by RandomEngy** [comment]
That looks pretty nice! What I like:
* The straight angles on the "play" button fit well with the current Windows 10 UI.
* The white text and dark background looks nice.
* The dark background lets you leave off the border, which looks clean.
* The dimensions of the triangle are good.

What could be better:
* Increase font size of "Loading" text and have equal margins from the left and bottom
* Don't include the "VC" overlay on the play icon as we already have the app name here.
* I miss the "pixels falling into place" effect of the old icon. A green triangle on its own is a very generic shape without any unique defining characteristics. I like the way you've done away with the gradient and outlines and differentiated the pixels by color, and I think it would still work if some of them were detached.
* The pixels inside the icon should be square, not rectangular.
* There should be equal margins on the top and bottom from "VidCoder" to the bottom and the icon to the top. Actually, the side margins for the main content should also match this.

If this was the new splash screen, we'd also need to update the taskbar icon. I know paint.net has a plugin that can save multi-resolution .ico files. I think we'd need 128x128 in there. For that one, we should leave off the drop shadow and have the play icon go all the way to the edge. I think the "VC" text could work here, but not a lot of apps outside of Office put letters on the icons. I think the icon could stand on its own. Notepad++ has tiny "N++" text on its icon but you can barely read it and it doesn't help distinguish the icon. If you did keep it, it would need to be bigger and bolder.

I have some variant icons that would need an update like the installer, exported preset and exported queue icons, but I could re-create those with the updated icon.

![image](https://user-images.githubusercontent.com/9450861/78398826-9c922380-75a8-11ea-9c40-59f547a69624.png)

Anyway with a few tweaks I could update the icon and splash screen.

**Comment by ArtexJay** [comment]
Alright, I'll fix the issues with the icon in the splash screen. I'll fix up the splash screen first then do the icon to how you prefer it.

**Comment by ArtexJay** [comment]
> That looks pretty nice! What I like:
> 
> * The straight angles on the "play" button fit well with the current Windows 10 UI.
> * The white text and dark background looks nice.
> * The dark background lets you leave off the border, which looks clean.
> * The dimensions of the triangle are good.
> 
> What could be better:
> 
> * Increase font size of "Loading" text and have equal margins from the left and bottom
> * Don't include the "VC" overlay on the play icon as we already have the app name here.
> * I miss the "pixels falling into place" effect of the old icon. A green triangle on its own is a very generic shape without any unique defining characteristics. I like the way you've done away with the gradient and outlines and differentiated the pixels by color, and I think it would still work if some of them were detached.
> * The pixels inside the icon should be square, not rectangular.
> * There should be equal margins on the top and bottom from "VidCoder" to the bottom and the icon to the top. Actually, the side margins for the main content should also match this.
> 
> If this was the new splash screen, we'd also need to update the taskbar icon. I know paint.net has a plugin that can save multi-resolution .ico files. I think we'd need 128x128 in there. For that one, we should leave off the drop shadow and have the play icon go all the way to the edge. I think the "VC" text could work here, but not a lot of apps outside of Office put letters on the icons. I think the icon could stand on its own. Notepad++ has tiny "N++" text on its icon but you can barely read it and it doesn't help distinguish the icon. If you did keep it, it would need to be bigger and bolder.
> 
> I have some variant icons that would need an update like the installer, exported preset and exported queue icons, but I could re-create those with the updated icon.
> 
> ![image](https://user-images.githubusercontent.com/9450861/78398826-9c922380-75a8-11ea-9c40-59f547a69624.png)
> 
> Anyway with a few tweaks, I'd happily accept this to get a nice, fresh look!

So I ended up deciding to edit and try to finish up the icon part of vidcoder first. I tried my best to keep them square shaped. And have one version where they float and other where they are a bit more broken up. I think they both came out pretty nicely though. The 2nd one for me at least I wanted/tried to make it look like that the triangle is being built up by broken pieces, all coming together to fit. Kind of a parallel to encoding where you have the video part, audio track and sub track and they come together to make a nice video. Hope this is a bit closer to what you had in mind though. I will keep altering it to your suggestion if it's not quite right.
 
![VidCoder Redisgn Broken(4)](https://user-images.githubusercontent.com/32932497/78464547-c63a7000-76b8-11ea-8bc0-eca068a57ae7.png)
![VidCoder Redisgn Broken(1)](https://user-images.githubusercontent.com/32932497/78464548-c76b9d00-76b8-11ea-8b07-5ee3808a440c.png)

**Comment by ArtexJay** [comment]
Here is a splash screen tweaked to how you wanted I think.
![Splash Screen final](https://user-images.githubusercontent.com/32932497/78510404-d4dd6180-7762-11ea-9c5f-8c5a40040d5d.png)

**Comment by RandomEngy** [comment]
Much improved! A few more thoughts on the core logo:

* I like how the pixels are coming in at angles in your second version. Gives it a bit more sense of life.
* Not a fan of them breaking up into sub-pixels. It's a little too busy. (and pixels are atomic!) In that sense I like the first one more.
* What is that extra fringe of light pieces on the upper-left? It looks like it's not even part of the triangle.
* Some of the pixels are not quite square still, like the lowermost detached one.
I was thinking you would have "full" pixels all along the left side, and "partial" pixels along the upper edge. It looks like you split up the triangle on a non-aligned grid. I would make a uniform grid, starting on the upper vertex of the triangle, like this:

![image](https://user-images.githubusercontent.com/9450861/78511050-7c9c6480-774e-11ea-94f9-0ad47239dccd.png)

Then move the pieces around. So it looks like they would assemble to form a cohesive whole. I picked a 2:1 slope, which cuts the pixels evenly and leaves fewer tiny pieces leftover. But the current colors you have look great.

Also some thoughts on the new splash screen composition:

* Give it a bit more margin on the top to balance with the bottom.
* Increase "Loading..." font size by a little bit more.
* Otherwise looks fantastic.

**Comment by ArtexJay** [comment]
I made the triangle out of small squares and triangles, for the versions I showed I divided the triangle using 3x3 squares. Which where I ended up with the "fringe end". Personally I kinda like it since it's quite different from before but still retains a bit of the original image. To me it looks very unique at the moment.

But I will try to change it up to how you'd rather have it. Thanks for the feedback.

**Comment by RandomEngy** [comment]
Maybe I'm a bit OCD about the grid alignment, but thanks for accommodating me.

**Comment by ArtexJay** [comment]
> Maybe I'm a bit OCD about the grid alignment, but thanks for accommodating me.
Here, completely squared up pixels. No fringe anymore. Full and partial pixels with the slightly rotated ones since you said you liked it.

Hopefully this one is the one!

![Final Vidcoder](https://user-images.githubusercontent.com/32932497/78961184-9e834780-7abe-11ea-977d-43150b94b6bc.png)

**Comment by RandomEngy** [comment]
That looks great, thanks!

Aside from the splash screen, Could you also supply a high-res on transparency with the drop shadow? Would be handy to use that on https://vidcoder.net/ .

**Comment by ArtexJay** [comment]
Will do, should i upload the images here? or send it to you via email or something? And what formats would you prefer?

**Comment by ArtexJay** [comment]
With transparent background with shadow:
![VidCoder Redesigne Shadow](https://user-images.githubusercontent.com/32932497/79054127-53794980-7c10-11ea-8d0e-196d0b9e0ac5.png)

Here's the Splash Banner: I tried to add more margin and I increased the font size of Loading text.
![VidCoder Redesigne Shadow](https://user-images.githubusercontent.com/32932497/79054146-79065300-7c10-11ea-923d-12b8edf2542c.png)

**Comment by RandomEngy** [comment]
Splash screen looks perfect. Integrating it now.

Are these the "masters" with the highest resolution? If you authored with vectors can you export to .svg as well? I think I'm set for the splash screen; I just want to have the best quality you've got on the logo so it looks nice when I resize to all the places it's needed.

**Comment by ArtexJay** [comment]
Here are the SVG files. Again this is my first time doing these kind of things. So hopefully they are good enough.
[Vidcoder SVG.zip](https://github.com/RandomEngy/VidCoder/files/4470260/Vidcoder.SVG.zip)

**Comment by RandomEngy** [comment]
Thanks. SVG is only useful if you authored in vector format, which it looks like you didn't. But if I've got the highest res PNGs, then that's good. Working on creating all the different versions I need now.

**Comment by ArtexJay** [comment]
well i did do it in vectored format but it didn't quite get exported correctly for some reason, so I had to export it as png format first, since it gave me the desired result.

Sorry about that.

**Comment by ArtexJay** [comment]
> Thanks. SVG is only useful if you authored in vector format, which it looks like you didn't. But if I've got the highest res PNGs, then that's good. Working on creating all the different versions I need now.

I ended up finding a slightly better process for me exporting my pictures so that they are in a vector format correctly. Also I completely didn't see small  issue in the icon part which I have corrected as well. Here they are. Apologies for posting/updating you late on this.

[Vidcoder SVG Fixed.zip](https://github.com/RandomEngy/VidCoder/files/4512649/Vidcoder.SVG.Fixed.zip)

**Comment by RandomEngy** [comment]
I must not have the "Open sans" font; this is what I get:
![image](https://user-images.githubusercontent.com/9450861/79940185-de7af080-8415-11ea-8ff2-e966e4f70887.png)

Anyhow I've already done a few tweaks and will probably keep this one:
![image](https://user-images.githubusercontent.com/9450861/79940208-f3f01a80-8415-11ea-9e5b-cd13e1dcc603.png)

But it's nice to have the main logo as a vector, thanks.

**Comment by ArtexJay** [comment]
> I must not have the "Open sans" font; this is what I get:
> ![image](https://user-images.githubusercontent.com/9450861/79940185-de7af080-8415-11ea-8ff2-e966e4f70887.png)
> 
> Anyhow I've already done a few tweaks and will probably keep this one:
> ![image](https://user-images.githubusercontent.com/9450861/79940208-f3f01a80-8415-11ea-9e5b-cd13e1dcc603.png)
> 
> But it's nice to have the main logo as a vector, thanks.

https://www.fontsquirrel.com/fonts/open-sans

Font for the text. I didn't have it installed either but it looks like it was bundled inside the vector app i use.   Open-Sans regular font fixes it, maybe I should alter the font to something that's already included in the Windows.

**Comment by ArtexJay** [comment]
> I must not have the "Open sans" font; this is what I get:
> ![image](https://user-images.githubusercontent.com/9450861/79940185-de7af080-8415-11ea-8ff2-e966e4f70887.png)
> 
> Anyhow I've already done a few tweaks and will probably keep this one:
> ![image](https://user-images.githubusercontent.com/9450861/79940208-f3f01a80-8415-11ea-9e5b-cd13e1dcc603.png)
> 
> But it's nice to have the main logo as a vector, thanks.

Just downloaded the portable version of Vidcoder beta and it looks great!
