### ISSUE TITLE
please can we have a watch folder

### ISSUE THREAD

**Issue by mdrodge** [RandomEngy/VidCoder#536]
it would be so awesome if you could use a watch folder (( or even a few watched folders ))

**Comment by spikemixture** [comment]
I use vidcoder as my backup re coder. Because the one I pay for has a watched folder option. And a remux only option would make it almost perfect...

**Comment by mdrodge** [comment]
@spikemixture i don't understand.
what are you paying for?
this doesn't help 
are you talking about adobe media encoder?

Handbrake can support a watch folder and i do have a version for unRaid that will do it but the VidCoder GUI is awesome and a watch folder would be so much nicer.

**Comment by RandomEngy** [comment]
Added a folder watcher in 8.4 Beta.
