### ISSUE TITLE
Request: KNLMeansCL: OpenCL non-local means denoising algorithm

### ISSUE THREAD

**Issue by Oberworld** [RandomEngy/VidCoder#54]
It's possible to implement KNLMeansCL denoising algorithm?

More info here: http://forum.doom9.org/showthread.php?t=171379

Thank you very much for this great tool.

Regards.

**Comment by RandomEngy** [comment]
Thanks! Ask HandBrake to add it and I'll pick up the functionality when they add it to their core library that I use.

**Comment by Oberworld** [comment]
Thank you very much for response.

I will try.

Regards.
