### ISSUE TITLE
Estimate Encode Output Filesize

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#546]
Please consider adding a check to the analysis progress bar of adding a video to the queue.

I often convert videos to HEVC format. It would be awesome if there was some logic to adding a video(s) to the queue where the expected output filesize is estimated.

The question being answered here is "Is the encode job worthwhile doing?", disk space wise.

e.g.

**ESTIMATED_OUTPUT_FILESIZE = ESTIMATEOUTPUTSIZE(VIDEO_FILENAME)**

IF(**ESTIMATED_OUTPUT_FILESIZE <= INPUT_FILESIZE**)
THEN
**ADD TO QUEUE**
ELSE
_SKIP ADDING TO QUEUE_
ENDIF

I personally would love a "If the estimated output filesize is at least 25% smaller than the input video filesize, then add it to the queue".

**Comment by RandomEngy** [comment]
In most cases you cannot accurately predict the final size of the video before you encode it. The most efficient encodings are quality-based and will vary greatly based on the content of the video.
