### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by immerzu** [RandomEngy/VidCoder#548]
5.8 beta

Text:

ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.ArgumentException: "-960*" ist kein gültiger Wert für die Eigenschaft "Width".
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   bei VidCoder.Controls.PaddingFrame.OnOutputSizeChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs eventArgs) in D:\git\VidCoder\VidCoder\Controls\PaddingFrame.xaml.cs:Zeile 74.
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   bei System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   bei System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   bei System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   bei ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args)
   bei ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName)
   bei ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj this, TRet& backingField, TRet newValue, String propertyName)
   bei VidCoder.Services.OutputSizeService.Refresh() in D:\git\VidCoder\VidCoder\Services\OutputSizeService.cs:Zeile 56.
   bei VidCoder.ViewModel.SizingPanelViewModel.RefreshOutputSize() in D:\git\VidCoder\VidCoder\ViewModel\Panels\SizingPanelViewModel.cs:Zeile 724.
   bei VidCoder.ViewModel.ProfileViewModelBase.UpdateProfileProperty[TProperty,TModel](Func`1 targetFunc, String propertyName, String raisePropertyName, TProperty value, Boolean raisePropertyChanged) in D:\git\VidCoder\VidCoder\ViewModel\ProfileViewModelBase.cs:Zeile 171.
   bei VidCoder.ViewModel.SizingPanelViewModel.<.ctor>b__3_53(Int32 padLeft) in D:\git\VidCoder\VidCoder\ViewModel\Panels\SizingPanelViewModel.cs:Zeile 343.
   bei System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   bei System.Reactive.Observer`1.OnNext(T value)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   bei System.Reactive.Observer`1.OnNext(T value)
   bei ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.NotifyObservable[T](TSender rxObj, T item, ISubject`1 subject)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   bei System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   bei System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Duplicate of https://github.com/RandomEngy/VidCoder/issues/547
