### ISSUE TITLE
add multiple titles to queue

### ISSUE THREAD

**Issue by ewittke** [RandomEngy/VidCoder#549]
When VidCoder v4.35 global settings output folder is set to 'Output to the source folder if possible',  and I drop VOB files from FolderA and I choose to Add Multiple Titles to Queue, it picks the proper folder.  While FolderA is processing, I load VOB files from FolderB and when I choose to Add Multiple Titles to Queue, The Destination shows the proper folder, but the Queued list is those destination of FolderA.  The workaround is Add to Queue one at a time.

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by RandomEngy** [comment]
Should be fixed in 5.9 Beta.
