### ISSUE TITLE
More precise "Target Size" option

### ISSUE THREAD

**Issue by 14422** [RandomEngy/VidCoder#550]
I would like to set target file size more precisely either in KB or comma addition to MB, such as 7,9MB. Even with 2-pass encoding setting for example 8MB target leads often to 8.1MB videos which go over my maximum hard limit of 8MB so I'll have to go for 7MB. This is basically for creating clips for Discord and with this limit all possible wasted filesize counts.

One workaround I have been using recently is that I set target size to both 7MB and 8MB and compare the difference between automatically calculated "Avg Bitrate (kbps)" below and I'll try to lower the result from 8MB to hit as closely to <8MB as possible. This is doable but not as handy as it could be.

**Comment by RandomEngy** [comment]
Added ability to set decimals for target size in 5.9 Beta.
