### ISSUE TITLE
The Picker still going nuts in v5.9 Beta

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#555]
1. Make sure encoding settings window is visible
2. Select a picker
3. Change the encoding preset in the picker window
4. Load a file
5. Preview the file without doing a sample encode (just checking cropping)
6. Add to queue
7. Select another picker
8. Q. "Do you want to save preset?" - A. "No"
9. You will now observe that the title of Encoding Settings window is flickering between two presets and cannot be stopped except by closing down VidCoder
10. Open VidCoder again and now the flickering is going much faster and the only way to stop it is to restart windows.
11. Restart Windows and open VC. It is now peaceful and a different preset can be chosen for next job.
12. Observe that VC wrongly thinks you've edited the **encoding** preset.
13. GOTO 7.

**Comment by RandomEngy** [comment]
I didn't reproduce exactly what you were seeing but I did find an update loop you could get into with similar repro steps. I'll fix that for the next Beta release and hope that helps.

**Comment by RandomEngy** [comment]
(Possibly) fixed in 5.10 Beta.

**Comment by iamjaydear** [comment]
Seems fixed, sorry for long trial period :)
