### ISSUE TITLE
More Items for Help Toolbar Icon?

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#556]
Please consider adding more context items for the "Help" toolbar icon.

![screen](https://user-images.githubusercontent.com/17044982/58256140-cf2c9680-7db1-11e9-9b04-18b93b80c9e3.png)

Maybe..

GitHub Repository => https://github.com/RandomEngy/VidCoder
GitHub Release Notes => https://github.com/RandomEngy/VidCoder/releases

**Comment by RandomEngy** [comment]
The repository is linked from the main VidCoder page. Is there a reason why you would want it directly accessible from that menu? As for the release notes, that's a decent idea and I could look directly to the notes for that release.
