### ISSUE TITLE
Subs don't work

### ISSUE THREAD

**Issue by Vasco1971** [RandomEngy/VidCoder#559]
Hi,

Not sure what I am doing wrong, but no matter how I set it up, the subs don't show after the programm is done. i am doing everything as i used to do with vidcoder and it always was fine. But now when i play the video, the subs just are not there.

Am i doing something wrong here? is there a good tutorial on subs some wehere, I can not find any.

**Comment by RandomEngy** [comment]
Do you burn the subtitles in? Can you provide an encode log?

**Comment by Vasco1971** [comment]
Hi,

I stopped the application and started all over and then it worked. Not sure what went wrong, maybe i didn't set it right, although i was convinced i did. Anyway, subs are there now!
