### ISSUE TITLE
Bad Italian translation - tune

### ISSUE THREAD

**Issue by Krzysiu** [RandomEngy/VidCoder#56]
Hello!

In EncodingRes.it.resx there's tune translated as "melodia". Wrong word meaning, as it's "tune" as in "tuning something", not "tune" as "melody". Thanks in advance.

I'm from Poland and I'm fixing Polish translation right now. Yet I've noted the same problem with Italian translation. As I don't speak Italian, I can't fix it.

**Comment by RandomEngy** [comment]
Please suggest corrections on the Crowdin site: https://crowdin.com/project/vidcoder . I can make you a proofreader there.
