### ISSUE TITLE
5.10 Beta - last Ecoder Settings are applied if different selected

### ISSUE THREAD

**Issue by juzzle** [RandomEngy/VidCoder#561]
It seems that if you say rip three videos on Encoder Settings 1, then add two more videos and change to Encode Settings 2, the settings that apply to the two additional videos are still Encoder Settings 1, irrespective of the encoder settings selected. Rebooting the app resolves

**Comment by RandomEngy** [comment]
This is by design, to allow applying different settings from the items in the queue. When you edit the encoding settings a button should pop up that says "Apply to queue". You can also select items in the queue and choose "Apply current encoding settings".

**Comment by juzzle** [comment]
Thanks David,

Perhaps I should have pointed out that after previous say 1.78:1 session, I clear all completed videos, add new videos (say 2.0:1) and set new encoder settings (for 2.0:1 in this case), but still the previous Encoder Setting used for the [cleared] list settings persists for the ripping.

I did discover the workaround “Apply current encoding settings”, but it still catches me out often (usually after 5 hours of ripping, only to find that the displayed settings are not being used – the inherited/echoed ones were 😐)

Regards,
Justin

**Comment by RandomEngy** [comment]
Unfortunately some people are going to get caught-out no matter what the behavior is. If I automatically applied settings changes to queued items that would mess up some people's encode queues.

I assume that the encode queue may have a bunch of deliberately set settings associated with each job and I don't want to wipe them out by default. So I've set it up to keep those settings but add some cues to let people know that the currently selected settings need to be applied to the queue.
