### ISSUE TITLE
Encoding Source Items - Context Menu

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#563]
Please consider disabling  some of the context menu items for Source items (queue) while encoding is underway (2 or more videos in queue).

I'd disable these 2:
![screen](https://user-images.githubusercontent.com/17044982/59986988-6ec49980-967c-11e9-8fc5-15dacf80e480.png)

**Comment by RandomEngy** [comment]
Sure. Will be fixed in next Beta.

**Comment by RandomEngy** [comment]
Fixed in 5.11 Beta.
