### ISSUE TITLE
Got an exception when trying to encode - Beta 5.10

### ISSUE THREAD

**Issue by 1024mb** [RandomEngy/VidCoder#566]
I got this error when trying to convert one GIFs to H265 in MKV container.
I successfully converted GIF to video before with Handbrake.
<details>
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.InvalidOperationException: Invalid length '00:00:00' on job Y:\1 - file 1.mkv
   en VidCoder.ViewModel.EncodeJobViewModel.CalculateWork() en D:\git\VidCoder\VidCoder\ViewModel\DataModels\EncodeJobViewModel.cs:línea 268
   en VidCoder.Services.ProcessingService.<>c.<StartEncodeQueue>b__192_1(EncodeJobViewModel job) en D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:línea 1477
   en System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   en VidCoder.Services.QueueWorkTracker.ReportEncodeStart(IEnumerable`1 initialWork) en D:\git\VidCoder\VidCoder\Services\QueueWorkTracker.cs:línea 85
   en VidCoder.Services.ProcessingService.StartEncodeQueue() en D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:línea 1478
   en ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   en System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   en System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   en System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   en System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
</details>

**Comment by RandomEngy** [comment]
Thanks for the report. Can you share the GIF with me so I can test with it?

**Comment by 1024mb** [comment]
> 
> 
> Thanks for the report. Can you share the GIF with me so I can test with it?

Sure, here it is (couldn't upload to github as it's bigger than 10MB: 
https://we.tl/t-az1NZkFG03

**Comment by RandomEngy** [comment]
Thanks! Found the problem. It will be fixed with the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 5.11 Beta.
