### ISSUE TITLE
Encode Details Window - Reset Position to Main Window

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#567]
Please consider adding a button in the **Global options** window, that resets the position of **Encode Details** window to the main window.

This is an issue when multiple screen systems change to one screen and the **Encode Details** window is totally inaccessible (off screen).
Tried:
- Cascading windows
- Setting lower resolution
- WinKey+D to switch

none of the above resolved it.

**Comment by RandomEngy** [comment]
I do have code to detect when a window is totally off screen and move it back to the closest monitor. I just tested and it still seems to work for me.

I wonder if your system still thought that the monitor was present? Or maybe it's hidden behind another tool window?

In any event you should be able to rescue it by focusing the window with Windows -> Encode Details, then Alt+Space -> M, then using the arrow keys to move the window.
