### ISSUE TITLE
Keep video same but re-encode only audio 

### ISSUE THREAD

**Issue by highflyer1** [RandomEngy/VidCoder#568]
Hi,

Is it possible to have an option to re encode only audio (various formats) but keep the video same.

Thanks.

**Comment by RandomEngy** [comment]
VidCoder uses the HandBrake API to do its encoding. Unfortunately the HandBrake team has said that remuxing/direct video copy is not something they intend to add. You could always [ask them to add it](https://handbrake.fr/community.php).
