### ISSUE TITLE
VidCoder not recognizing 1 of 8 audio tracks

### ISSUE THREAD

**Issue by anarchator** [RandomEngy/VidCoder#570]
i have one blu ray iso where vidcoder is only detecting 7 auto tracks (it is showing 7 of 7 tracks). but in fact there are 8 tracks existing. When i play iso file in Kodi, it is showing 8 audio tracks. even latest beta version does not deetct that one audio track. BDInfo is showing following:
MPEG-4AVC Video
DTS-HD Master Audio
' DTS Audio
DTS Audio
Dolby Digital Audio
Dolby Digital Audio
Dolby Digital Audio
Dolby Digital Audio
" Dolby Digital Audio
English
German
Russian
Hindi
Polish
Thai
Ukrainian
English
	1080p / 23.976 fps / 16:9 / High Profile 4.1
	5.1 / 48 kHz / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
768 kbps	5.1 / 48 kHz / 768 kbps / 24-bit
768 kbps	5.1/48kHz/768kbps/24-bit
448 kbps	5.1 / 48 kHz / 448 kbps / DN -4dB
448 kbps	5.1 / 48 kHz / 448 kbps / DN -4dB
448 kbps	5.1/48 kHz/448 kbps
448 kbps	5.1 / 48 kHz / 448 kbps / DN -4dB
224 kbps	2.0 / 48 kHz / 224 kbps / DN -4dB
But the german audio track is not detected by VidCoder. Does someone have a solution for this?

**Comment by anarchator** [comment]
it seems the audio track that is not detected by VidCoder is a so called "Hidden Track". How can i get VidCoder to show/process that track?

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by anarchator** [comment]
thank you very much. I now have made it with another software, called 'Pavtube ByteCopy' (which is not for free unfortunately). Worked fine and went really fast. But result mkv file is huge (21,7 GB) but this is okay for me. This seems to be due to the fact that this software ripps to mkv without loss of quality.
