### ISSUE TITLE
Add *.ass to file selection window

### ISSUE THREAD

**Issue by rudolphos** [RandomEngy/VidCoder#572]
VidCoder seems to support .ass subtitles when selecting file through wildcard filter, but there is only .srt +.ssa filter when selecting files now.

![image](https://user-images.githubusercontent.com/4366810/62383465-84b95a00-b558-11e9-9bca-2be9290047aa.png)

I would suggest adding *.ass too.

**Comment by RandomEngy** [comment]
Added in 5.12 Beta.
