### ISSUE TITLE
Program doesn't start

### ISSUE THREAD

**Issue by PB188** [RandomEngy/VidCoder#573]
All program versions I tried (portable 4.36, 5.11, 2.57x64 and intalled version 4.36 via Windows Apps) just show the starting splash screen (VidCoder Loading...) , then create the file "VidCoder.sqlite". Splash screen vanishes and nothing (visible) happens.
I have 64 bit Windows 10 Pro on an Intel I7-8700K with .NET 7.2
I didn't use VidCoder earlier; I never had a running version so far.
Is that an known issue and how can I solve that?
Best regards
Peter

**Comment by RandomEngy** [comment]
Do you mean you have .NET 4.7.2? What version of Windows 10 do you have? 1903?

**Comment by PB188** [comment]
I have Windows 10 Pro, 1809 built 17763.615
Update says, it's the up to date.
.NET versionis 4.7.2, checked it in registry.

**Comment by PB188** [comment]
Sorry, I just too new. I accidently closed the issue.
I can manually update to Windows 10, 1903 and I will try this now.

**Comment by RandomEngy** [comment]
1809 is pretty recent, you shouldn't be having issues on that version if you have .NET 4.7.2 installed. I don't know what is going on here.

If updating to 1903 doesn't work, can you look in the "View reliability history" window and see if there are any crash reports on VidCoder.exe?

**Comment by PB188** [comment]
Hello RandomEngy,
after updating to Windows 10, 1903, Vidcoder now starts without any problem.
Thanks a lot for you immediate reply.
No clue, what was the issue. I can now close it.
Best regards,
Peter
