### ISSUE TITLE
Feature Request/Suggestion: Delogo/Watermark removal

### ISSUE THREAD

**Issue by kleytr6s** [RandomEngy/VidCoder#577]
I have to use Avidemux to delogo each file. To delogo a file a transcode/re-encode is necessary. Which takes more time and the quality of each file drops. I cannot use Avidemux only. It does not process closed captions. I have to extract the closed captions using CCExtractor. Then add/mux the closed captions to the re-encoded file. Then re-encode the file using Vidcoder. Avidemux's setup for transcoding is not as straightforward.

**Comment by somethin9** [comment]
watermarks are there for a reason...

**Comment by RandomEngy** [comment]
Thanks for the suggestion!

However video editing, including watermark removal is not in scope for the HandBrake engine that VidCoder uses.
