### ISSUE TITLE
Errordetectiontype: for level 1

### ISSUE THREAD

**Issue by Giotto887** [RandomEngy/VidCoder#581]
Hello, I ask for your help because the versions with the new interface (from version 4.28 to 4.36) after converting a video, give me the error "Errordetectiontype: for level 1" and the videos made by these versions, are no longer reproduced from my TV.
I tried to change the profile from Main to High, I tried to change also the level from 4.1 to 3.2 but it is always "Errordetectiontype: for level 1"
This does not happen with versions 3.16 or older.
Thanks for your help
Best regards
Antimo
![1](https://user-images.githubusercontent.com/55479767/65123860-79c96480-d9f4-11e9-812c-775ef34a2f69.jpg)

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by Giotto887** [comment]
Thanks RandomEngy for your reply, but I solved it by going back to the previous version 3.16 whose interface is much nicer for me.
Regards

**Comment by Giotto887** [comment]
However also out of curiosity I tried handbrake and it gives me the same error.

**Comment by RandomEngy** [comment]
In that case you can follow up with the HandBrake team about the issue if you'd like to pursue it.

**Comment by sr55** [comment]
It's a CRC check attribute in the container. 
https://mailarchive.ietf.org/arch/msg/cellar/Z4Qgfoa2ggM87wUlcD-6wi17NG8
