### ISSUE TITLE
Vidcoder does not start after latest Windows 10 update

### ISSUE THREAD

**Issue by botmakerdvd** [RandomEngy/VidCoder#582]
Hello. After latest windows 10 update, vidcoder does not start. I have suffered it in 2 different PCs

**Comment by RandomEngy** [comment]
Are you on Windows 10 v1903?

Do you get any error details?

I had a recent report that RivaTuner was causing these crashes; do you have that running?

**Comment by botmakerdvd** [comment]
I have detected exactly the same, after latest update rivatune statistics
causes vidcoder (and other apps) to crash
