### ISSUE TITLE
Feature Request: Option to Show Track Names in VidCoder's Editor

### ISSUE THREAD

**Issue by LeeThompson** [RandomEngy/VidCoder#586]
When working with a source media file if tracks are named at all (this obviously would depend on the container of the source media) to show those names.

For example, let's say the source file is an anime MKV with several audio and several text streams.

In VidCoder in the "Audio track(s)" section would be, for an example:

```
[ ] 1 Japanese (AC3) (2.0)  448 48hHz 
[ ] 2 English (AC3) (2.0)     224 48kHz     Original Dub
[ ] 3 English (AC3) (2.0)     224 48kHz     Remaster Dub
```

Subtitle section would be similar:

```
[ ] 1 English [SSA] Full
[ ] 2 English [SSA] Signs and Songs
[ ] 3 English [SSA] Forced Only

```

If the 'show track names' option isn't enabled, supported by the source container or simply not set in the source media, it would show blank.

**Comment by RandomEngy** [comment]
VidCoder already displays all the information that we have on the track. It would need an API change from HandBrake to pull out additional information.

**Comment by LeeThompson** [comment]
Fair enough :)

**Comment by Solo177** [comment]
The relevant information appears to be available though.  For example, when I load a MKV file in 5.13 with named audio and subtitle tracks, VidCoder's layout will display as "日本語 (FLAC) (2.0 ch)" and "English [SSA] (SSA)."  However, in the relevant section of the log, it shows the following:

           "AudioList": [
                {
                    "Attributes": {
                        "AltCommentary": false,
                        "Commentary": false,
                        "Default": true,
                        "Normal": false,
                        "Secondary": false,
                        "VisuallyImpaired": false
                    },
                    "BitRate": 1,
                    "ChannelCount": 2,
                    "ChannelLayout": 3,
                    "ChannelLayoutName": "stereo",
                    "Codec": 1048576,
                    "CodecName": "flac",
                    "CodecParam": 86028,
                    "Description": "日本語 (FLAC) (2.0 ch)",
                    "LFECount": 0,
                    "Language": "日本語",
                    "LanguageCode": "jpn",
                    "Name": "Japanese 2.0",
                    "SampleRate": 48000
                }
            ],

            "SubtitleList": [
                {
                    "Attributes": {
                        "4By3": false,
                        "Children": false,
                        "ClosedCaption": false,
                        "Commentary": false,
                        "Default": true,
                        "Forced": false,
                        "Large": false,
                        "Letterbox": false,
                        "Normal": false,
                        "PanScan": false,
                        "Wide": false
                    },
                    "Format": "text",
                    "Language": "English [SSA]",
                    "LanguageCode": "eng",
                    "Name": "Full [FFF]",
                    "Source": 5,
                    "SourceName": "SSA"
                }
            ],

The 'Name' field listed for both audio and subtitle entries is the custom name set in the MKV.  Is it possible to have that display in the editor instead of the current 'Description' and 'Language'?

**Comment by RandomEngy** [comment]
Thanks for the tip; looks like we do get the track name now.

Also it appears that the audio track naming has gotten more robust in the HandBrake core. It used to be that the track names you entered would only be picked up by a handful of programs like iTunes.

I'm working on a change that will display the track name in the track list, and support automatically carrying over this track name to the output file. And allow you to overwrite that track name in settings.

**Comment by RandomEngy** [comment]
Change is in 6.0 Beta.
