### ISSUE TITLE
Feature Request: Add Multiple File Settings

### ISSUE THREAD

**Issue by LeeThompson** [RandomEngy/VidCoder#587]
It would be nice when adding multiple files if you could set VidCoder to do certain default selections/sorting.

Say I'm encoding to MP4 which does not support PGS text streams but the source media has a mix of PGS and VobSub text streams.      I'd like to tell VidCoder to deselect ALL PGS text streams (or maybe just deselect incompatible ones) and to choose the VobSub ones only.   

Currently, when selecting multiple files it will typically select a PGS track (oddly, usually the last one) for burn in even if compatible text streams are present in the source media (SRT, VobSub, etc).

**Comment by LeeThompson** [comment]
This is still an issue as of VidCoder 5.13.   Even if the source container has compatible subtitle tracks (e.g. VOBSUB, it will instead burn in one of the PGS tracks if "Enqueue Multiple Files" is used.

**Comment by RandomEngy** [comment]
But it doesn't matter if the output doesn't support PGS if you're burning it in, right? After burning in, it's part of the picture, not a specifically formatted subtitle stream.

What Picker settings are you using?

Though I can definitely see the need to add logic to filter out incompatible streams for certain settings.

**Comment by LeeThompson** [comment]
Sometimes (foreign movie in particular) I do just burn in PGS but the multiple file option always just kind of randomly picks a PGS stream *even* if there's VOBSUB streams present in the source.

My picker generally includes all audio and subtitle streams, that may be where to put in a limiter or options for the type of streams to pick?

Something like:

Subtitle Selection
(existing options)
[ ] Compatible Streams Only


(While we're at it, being able to have preferences for audio stream types would be handy too in cases like where they have DTS MA and DTS 5.1 or DTS TrueHD (all the same language) to just have it select one type.)

**Comment by RandomEngy** [comment]
Fixed picker subtitle selection to ignore incompatible (non-passthrough) subtitles when selecting multiple tracks. This change is in the 6.0 Beta.
