### ISSUE TITLE
Feature Request: Auto Subtitle Detection

### ISSUE THREAD

**Issue by ali-masoudi** [RandomEngy/VidCoder#590]
Hi there
It would be very good to add an option for automatically subtitle detection based on name matching if there is one, or name matching and language-code if there are multiple subtitles for each file.
for example:
# One Sub:
```
classes.mp4
classes.[srt,ass,...]
````
# Multiple Subs: select en and sp
```
classes.mp4
classes-en.[srt,ass,...]
classes-sp.[srt,ass,...]
classes-it.[srt,ass,...]
```

**Comment by RandomEngy** [comment]
There are a bunch of different codes for a language. Is there one in common use for subtitles? The HandBrake API uses the ISO 639-2 3-letter language codes: (eng, zho, spa, hin, ...) . So we'd need to be able to map to that one.

**Comment by RandomEngy** [comment]
This has been added in VidCoder v6, as an option in the Picker window.
