### ISSUE TITLE
4.36 Windows 10: No info or warning output from x264

### ISSUE THREAD

**Issue by albesp77** [RandomEngy/VidCoder#591]
In registry information returned as info or warning from x264 codec are blank, so is impossible to analyze the output result! tested on 2 computer with windows 10 and same vidcoder portable v4.36 build that works correctly on windows 7 machine

**Comment by RandomEngy** [comment]
What is the problem? Was there something wrong with the encoded video?

**Comment by albesp77** [comment]
the video output is good, but i cannot evaluate the avg quantizer value of output

**Comment by RandomEngy** [comment]
Are you talking about the log within VidCoder, some other log or using some external tool?

**Comment by albesp77** [comment]
the vidcoder internal registry, this is an example of wrong output:

[16:34:15] sync: framerate min 30.000 fps, max 30.000 fps, avg 30.000 fps
x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: x264 [info]: [16:34:15] mux: track 0, 643 frames, 2969201 bytes, 1103.11 kbps, fifo 1024
[16:34:15] libhb: work result = 1

as you can see all [info] from codec are empty, instead on windows 7 are correctly populated!

**Comment by RandomEngy** [comment]
Ahh, that's the encode log.

You can try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by albesp77** [comment]
Tested with handbrake stable 1.2.2, this is part of the output log:

x264 [info]: frame I:24    Avg QP:22.94  size: 24505
x264 [info]: frame P:542   Avg QP:26.10  size: 17405
x264 [info]: frame B:1477  Avg QP:27.13  size:  7852

this part is empty if you use vidcoder portable v4.36 on windows 10 x64, but populated correctly if you use windows 7 x64, i don't know why!

**Comment by albesp77** [comment]
i've do some other test, that confirm that VidCoder v4.36 is bugged:

1) Fresh install of VidCoder v4.36 - Doing the test with default profile - x264 [info] output empty
2) Fresh install of HandBrake v1.2.2 - Doing the test with default profile - x264 [info] output correct
3) Replace hb.dll from HandBrake v1.2.2 folder and replace in VidCoder v4.36 folder - Doing the test with default profile - x264 [info] output empty

So the problem is VidCoder logs output, now i'm download latest beta of VidCoder and do test on it, stay tuned!

**Comment by RandomEngy** [comment]
Thanks for investigating. Been a bit short on time lately. I noticed that when I debug it from Visual Studio I see the x264 info, but not when I run the executable standalone.

Something else is different in the way the executable is run and I need to figure out what it is.

**Comment by RandomEngy** [comment]
Finally figured this one out. That data was coming in on the "standard error" stream, and I was not redirecting that when starting up the encode worker process.

This should be fixed in 6.9 Beta.
