### ISSUE TITLE
Encoding Options Greyed Out...

### ISSUE THREAD

**Issue by Blickie** [RandomEngy/VidCoder#594]
Sometimes, the Add to Queue, Pause and Stop Icons are Grey out and cannot be selected.  Why does this happen, especially during files being encoded.

thanks

**Comment by RandomEngy** [comment]
Normally this happens when an encode is starting up: When we've sent the signal for the encode to start but have not yet heard back that it's actually encoding. If you try to pause too early, it doesn't actually work and the UI gets into an inconsistent state.

It shouldn't stay like that for more than a few seconds. How long are you seeing this happen?

**Comment by Blickie** [comment]
Indefinitely until the app is closed and restarted. It doesn't happen all the time, but it does happen.Blickie
-------- Original message --------From: David Rickard <notifications@github.com> Date: 10/23/19  1:39 PM  (GMT-05:00) To: RandomEngy/VidCoder <VidCoder@noreply.github.com> Cc: Blickie <Blickie47@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RandomEngy/VidCoder] Encoding Options Greyed Out... (#594) Normally this happens when an encode is starting up: When we've sent the signal for the encode to start but have not yet heard back that it's actually encoding. If you try to pause too early, it doesn't actually work and the UI gets into an inconsistent state.
It shouldn't stay like that for more than a few seconds. How long are you seeing this happen?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RandomEngy/VidCoder/issues/594?email_source=notifications\u0026email_token=AI2N5SYLYK3LQ253E5AJPT3QQCD4LA5CNFSM4JEESVFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECCIM2Q#issuecomment-545556074",
"url": "https://github.com/RandomEngy/VidCoder/issues/594?email_source=notifications\u0026email_token=AI2N5SYLYK3LQ253E5AJPT3QQCD4LA5CNFSM4JEESVFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECCIM2Q#issuecomment-545556074",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RandomEngy** [comment]
In Global Options -> Process, do you have "Use worker process to encode" checked?
Also, what version were you using? The v5 betas use different code to communicate with the worker process, so I'd like to know if the trouble is with the old or the new code.

**Comment by Blickie** [comment]
Hi David,

 

Yes, “Use Worker Process to Encode” is checked.

 

Also have “Maximum simultaneous encoding jobs” set to 4

 

CPU throttling is set to 75%

 

Version is 5.12 Beta

 

Thanks

**Comment by RandomEngy** [comment]
Ahh, thanks for the details. This is a part I missed when adding simultaneous encodes. It should be fixed when I release the v5 stable version in a week.

**Comment by Blickie** [comment]
Sounds good... thxBlickie
-------- Original message --------From: David Rickard <notifications@github.com> Date: 11/11/19  12:30 AM  (GMT-05:00) To: RandomEngy/VidCoder <VidCoder@noreply.github.com> Cc: Blickie <Blickie47@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RandomEngy/VidCoder] Encoding Options Greyed Out... (#594) Ahh, thanks for the details. This is a part I missed when adding simultaneous encodes. It should be fixed when I release the v5 stable version in a week.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RandomEngy/VidCoder/issues/594?email_source=notifications\u0026email_token=AI2N5SZNHZJCLYLO2VD3P5DQTDUYZA5CNFSM4JEESVFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDVWU4A#issuecomment-552299120",
"url": "https://github.com/RandomEngy/VidCoder/issues/594?email_source=notifications\u0026email_token=AI2N5SZNHZJCLYLO2VD3P5DQTDUYZA5CNFSM4JEESVFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDVWU4A#issuecomment-552299120",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Blickie** [comment]
Hi David,

 

I have an Intel i7 8-core 3770K processor with 32 Mb RAM.  These settings below typically use 6 of the 8 cores for processing in VidCoder.  Are these setting optimal for “4 simultaneous jobs” or would you recommend different settings?

 

Thanks

 

 

“Use Worker Process to Encode” is checked.

 

“Maximum simultaneous encoding jobs” set to 4

 

CPU throttling is set to 75%

 

Version is 5.12 Beta

**Comment by RandomEngy** [comment]
Should be fixed with 5.13 Stable.

**Comment by Blickie** [comment]
Ok thxBlickie
-------- Original message --------From: David Rickard <notifications@github.com> Date: 11/17/19  3:55 PM  (GMT-05:00) To: RandomEngy/VidCoder <VidCoder@noreply.github.com> Cc: Blickie <Blickie47@gmail.com>, Author <author@noreply.github.com> Subject: Re: [RandomEngy/VidCoder] Encoding Options Greyed Out... (#594) Should be fixed with 5.13 Stable.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RandomEngy/VidCoder/issues/594?email_source=notifications\u0026email_token=AI2N5S5N7GZHKLEYG5TPZH3QUGVU7A5CNFSM4JEESVFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIV2UY#issuecomment-554786131",
"url": "https://github.com/RandomEngy/VidCoder/issues/594?email_source=notifications\u0026email_token=AI2N5S5N7GZHKLEYG5TPZH3QUGVU7A5CNFSM4JEESVFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIV2UY#issuecomment-554786131",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
