### ISSUE TITLE
How do I get vidcoder to autoselect subtitles

### ISSUE THREAD

**Issue by birbob** [RandomEngy/VidCoder#606]
When I batch encode several files I have to edit each file and manually check the subtitles to ensure they get selected.  Is it possible to make selecting subtitles automatic default?  Vidcoder does this with audio why not subtitles?
Thank you

**Comment by RandomEngy** [comment]
Have you tried looking at the Picker window?

**Comment by birbob** [comment]
Well I feel stupid.  I spent my time in encoder settings and global options,  never noticed the "picker" icon before.
Thank you
