### ISSUE TITLE
How do I know vidcoder is using my GPU as well?

### ISSUE THREAD

**Issue by birbob** [RandomEngy/VidCoder#607]
Apologies if this is not the right place to ask.  I  can't find a forums for vidcoder.  This issue list is the closest I can find.
Before I only had an i7  and recently was given a hand me down Nvidia GT 720.  It's an older card but does have a GPU.  I pop it in just to give it a try.  My question is can vidcoder, in addition to my CPU, utilize this GPU?  I see an option for x264 (NVenc) and that seems fast but I get the feeling it is GPU only.  I tried x265 (NVenc) and it crashed.  While using regular x265  can vidcoder still use the GPU for extra number crunching? If so  how do I know vidcoder is actually using it?
Thanks

**Comment by RandomEngy** [comment]
The GPU encoding is only with NVenc. Sometimes you can tell if the GPU is doing the work if the CPU is mostly idle during the encode. There's probably a way to tell more directly but I don't know it offhand.

**Comment by birbob** [comment]
ok thanks
