### ISSUE TITLE
Preview: Compare options

### ISSUE THREAD

**Issue by nwgat** [RandomEngy/VidCoder#61]
would been nice if there was a compare option like [this](http://screenshotcomparison.com/comparison.php?id=150220) in the preview window, compare source with encode etc

**Comment by RandomEngy** [comment]
That's a good thought but we don't actually have the capability to see what the frame will look like after compression. The preview is more to aid with cropping/size/aspect ratio/rotation and making sure the source content is OK. Will consider if HandBrake adds ability to get encoded still pictures.
