### ISSUE TITLE
latest beta 6

### ISSUE THREAD

**Issue by Ghastor** [RandomEngy/VidCoder#611]
Hi !
I've downloaded latest beta and after install, it don't load. Stop on splash screen and never start.
Previous version 5.13, don't load anymore. The logs in roaming directory are empty :(

**Comment by RandomEngy** [comment]
Are you using Portable, Installer or Windows Store version?

**Comment by Ghastor** [comment]
I'm using installer version. Ive tried portable version too, but it fails. Now, stable versione 5.13 don't load. I've unistall the two, deleted /appdata/roaming/vidcoder/ files but don't start. Stop on splash screen

**Comment by RandomEngy** [comment]
That's weird. Can you open up Task Manger (Ctrl+Shift+Esc), right click on VidCoder.exe and select Create dump file? Then share the file with me so I can debug the hang?

**Comment by Ghastor** [comment]
https://drive.google.com/file/d/1mIS6zIDj-GF48J-cKQHM6iGLnHo3RZWb/view?usp=sharing

**Comment by Ghastor** [comment]
Hi RandomEngy,
I've rebooted my pc and reinstall vidcoder beta 6.0 again. Now works ok !
Thanks a lot for your reply.

**Comment by RandomEngy** [comment]
Thanks for the dump. It looks like Windows can get in a bad state and the call to the ManagementEventWatcher (that I use to detect drive insert/eject events) can hang indefinitely. I can update it so it doesn't block the entire app start.

**Comment by Ghastor** [comment]
Thank you for your help. Rebootin Windows, vidcoder is ok again, stable 5.13 and 6.0 beta. Inviato da Posta per Windows 10 Da: David RickardInviato: martedì 31 dicembre 2019 18:55A: RandomEngy/VidCoderCc: Ghastor; State changeOggetto: Re: [RandomEngy/VidCoder] latest beta 6 (#611) Thanks for the dump. It looks like Windows can get in a bad state and the call to the ManagementEventWatcher (that I use to detect drive insert/eject events) can hang indefinitely. I can update it so it doesn't block the entire app start.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by RandomEngy** [comment]
Okay; this shouldn't happen again in Beta 6.1.
