### ISSUE TITLE
shutdown issue in Vidcoder 6.1

### ISSUE THREAD

**Issue by Rod65** [RandomEngy/VidCoder#615]
6.1 will not shutdown after selecting (when queue is finished shutdown) from the drop-down menu in windows 7, after encoding multiple files..It does seem to work if just when only one file is being encoded and completed..I have been using that drop-down ever since it was incorporated into your application without issue..Thanks for years of use with this fine user friendly program..

**Comment by RandomEngy** [comment]
Did you have any failed encodes when it didn't shut down? In that case it won't trigger that action unless you've enabled "Trigger 'when done' action when there are failed encode jobs" in Advanced settings.

Also do you have simultaneous encodes enabled? Do you see any error messages in the General section after the queue finishes? Does the shutdown warning window pop up?

**Comment by Rod65** [comment]
Hello:  Did you have any failed encodes when it didn't shut down==>NO
          Also do you have simultaneous encodes enabled?==>NO, only 1 encode at a time
          Do you see any error messages in the General section after the queue finishes?==>NO
          Does the shutdown warning window pop up?==>NOT SURE I AM USUALLY ASLEEP WHEN ITS ENCODING..and I encoded 2 nights in a row using 6.1 with the program not shutting down my computer..And yes I check all the time to make sure it is set to shut-down after the queue is done..
          All files were completed successfully in Vidcoder 6.1 with NO errors or failed encodes
I encoded the same exact multiple files again in Vidcoder 6.0 with NO shut-down problems what so ever..
Could it be an issue with the new U.I.?, and I don’t see a core change..I have always used the portable versions with the same .sqlite in the same folder
I also run a clean updated windows 7 using Vidcoder almost every night for years with no shut-down problems until 6.1..But again I cant thank you enough for all the work you put into this and the pleasure it has given me..

**Comment by RandomEngy** [comment]
Thanks for the details. For some reason when I moved the drive event watcher to a background thread, the shutdown API I was calling just stopped working. I'll revert this in the next Beta and submit a bug report to Windows to see what they make of it.

**Comment by Rod65** [comment]
I always wondered why the When Done dropdown box never appears until you start the queued encodes,, anyway thanks so much for your timely responses to issues and the care you and the developers have showed to Vidcoder through the years..Ill be looking forward to the next beta..

**Comment by RandomEngy** [comment]
Should be fixed in 6.2 Beta.
