### ISSUE TITLE
6.2 Dark Theme, encoding setting Issue

### ISSUE THREAD

**Issue by Rod65** [RandomEngy/VidCoder#617]
In windows 7 after inputting a file using the Dark Theme,, and going to /encoding settings/sizing tab, and under cropping, the Normal Setting and the Automatic Setting are whited out and are not usable..The Custom Setting displays the crop numbers as if it was the Automatic Setting..When using the OS theme or the Light theme the behavior is normal..And thanks again for the prompt response and fixing the shutdown issue in 6.2..I put that to the test already..;)

**Comment by RandomEngy** [comment]
Thanks for the report. It looks like the TextBox has a different control template on Windows 7 that does not respect the system color overrides I set for dark mode. I'll fix this in the next Beta release by specifying a custom control template.

**Comment by Rod65** [comment]
Thanks!!

**Comment by RandomEngy** [comment]
Should be fixed in 6.3 Beta.
