### ISSUE TITLE
Encoder crashes while rotate 90 degrees

### ISSUE THREAD

**Issue by wistoha** [RandomEngy/VidCoder#619]
When I rotate a video 90 degrees and choose padding fill, the encoder crashes. See the log info.

# VidCoder 6.2 Beta
ERROR: Output padding cannot be negative: {"Top":0,"Bottom":0,"Left":157,"Right":157,"IsZero":false}
Calculated from profile: Width 720, Height 480, Padding {"Top":0,"Bottom":0,"Left":0,"Right":0,"IsZero":true}, PaddingMode Fill, SizingMode Automatic, ScalingMode DownscaleOnly, Rotation Clockwise90, PixelAspectX 1, PixelAspectY 1, UseAnamorphic True
And source title geometry: {"Height":1080,"PAR":{"Num":1,"Den":1},"Width":1920}
ERROR: Output padding cannot be negative: {"Top":0,"Bottom":0,"Left":157,"Right":157,"IsZero":false}
Calculated from profile: Width 720, Height 480, Padding {"Top":0,"Bottom":0,"Left":157,"Right":0,"IsZero":false}, PaddingMode Fill, SizingMode Automatic, ScalingMode DownscaleOnly, Rotation Clockwise90, PixelAspectX 1, PixelAspectY 1, UseAnamorphic True
And source title geometry: {"Height":1080,"PAR":{"Num":1,"Den":1},"Width":1920}
ERROR: Output padding cannot be negative: {"Top":0,"Bottom":0,"Left":157,"Right":157,"IsZero":false}
Calculated from profile: Width 720, Height 480, Padding {"Top":0,"Bottom":0,"Left":157,"Right":157,"IsZero":false}, PaddingMode Fill, SizingMode Automatic, ScalingMode DownscaleOnly, Rotation Clockwise90, PixelAspectX 1, PixelAspectY 1, UseAnamorphic True
And source title geometry: {"Height":1080,"PAR":{"Num":1,"Den":1},"Width":1920}
ERROR: Output padding cannot be negative: {"Top":0,"Bottom":0,"Left":157,"Right":157,"IsZero":false}
Calculated from profile: Width 720, Height 480, Padding {"Top":0,"Bottom":0,"Left":157,"Right":157,"IsZero":false}, PaddingMode Fill, SizingMode Automatic, ScalingMode DownscaleOnly, Rotation Clockwise90, PixelAspectX 1, PixelAspectY 1, UseAnamorphic True
And source title geometry: {"Height":1080,"PAR":{"Num":1,"Den":1},"Width":1920}
# Generating preview clip
#   Path: C:\Users\Wistoha\AppData\Local\VidCoder-Beta\preview.mp4
#   Title: 1
#   Preview #: 1
# Worker ready: Pipe 'VidCoderWorker.9a19b5bb-579e-41e9-8752-cc03550ba422' is open
# Connecting to process 7580 on pipe VidCoderWorker.9a19b5bb-579e-41e9-8752-cc03550ba422
[14:49:25] hb_init: starting libhb thread
[14:49:25] CPU: Intel(R) Pentium(R) CPU 2117U @ 1.80GHz
[14:49:25]  - Intel microarchitecture Ivy Bridge
[14:49:25]  - logical processor count: 2
[14:49:25] Intel Quick Sync Video support: yes
[14:49:25]  - Intel Media SDK hardware: API 1.11 (minimum: 1.3)
[14:49:25]  - H.264 encoder: yes
[14:49:25]     - preferred implementation: hardware (any) via D3D11
[14:49:25]     - capabilities (hardware):  vsinfo opt1 opt2+extbrc+ib_adapt+nmpslice
[14:49:25]  - H.265 encoder: no
[14:49:25] hb_scan: path=C:\Vakantie\2019-Filipijnen\Fotos\Rico\Camera\Filmpjes\MVI_9172.MOV, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:323: failed opening UDF image C:\Vakantie\2019-Filipijnen\Fotos\Rico\Camera\Filmpjes\MVI_9172.MOV
src/libbluray/disc/disc.c:424: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:424: error opening file BDMV\BACKUP\index.bdmv
src/libbluray/bluray.c:2585: nav_get_title_list(C:\Vakantie\2019-Filipijnen\Fotos\Rico\Camera\Filmpjes\MVI_9172.MOV\) failed
[14:49:25] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 6.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[14:49:25] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Vakantie\2019-Filipijnen\Fotos\Rico\Camera\Filmpjes\MVI_9172.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 537331968
    compatible_brands: qt  CAEP
    com.apple.quicktime.make: Canon
    com.apple.quicktime.model: Canon PowerShot S100
    com.apple.quicktime.rating.user: 0.000000
    creation_time   : 2019-11-30T08:24:57.000000Z
  Duration: 00:00:42.58, start: 0.000000, bitrate: 35669 kb/s
    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuvj420p(pc, bt709), 1920x1080, 34115 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 48k tbc (default)
    Metadata:
      creation_time   : 2019-11-30T08:24:57.000000Z
    Stream #0:1(eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2019-11-30T08:24:57.000000Z
[14:49:25] scan: decoding previews for title 1
[14:49:25] scan: audio 0x1: pcm_s16le, rate=48000Hz, bitrate=1536000 English (pcm_s16le) (2.0 ch) (1536 kbps)
[14:49:27] scan: 10 previews, 1920x1080, 23.976 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1
[14:49:27] scan: supported video decoders: avcodec qsv
[14:49:27] libhb: scan thread found 1 valid title(s)
ERROR: Worker process crashed. Please report this error so it can be fixed in the future:
System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij Microsoft.AnyContainer.StaticResolver.Resolve[T]()
   bij VidCoderCommon.Model.JsonEncodeFactory.GetOutputSize(VCProfile profile, SourceTitle title) in D:\git\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:regel 1479
   bij VidCoderCommon.Model.JsonEncodeFactory.CreateJsonObject(VCJob job, SourceTitle title, String defaultChapterNameFormat, Int32 previewNumber, Int32 previewSeconds, Int32 previewCount) in D:\git\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:regel 64
   bij VidCoderWorker.HandBrakeEncodeWorker.<>c__DisplayClass4_0.<StartEncode>b__0(JsonScanObject scanObject) in D:\git\VidCoder\VidCoderWorker\HandBrakeEncodeWorker.cs:regel 57
   bij VidCoderWorker.HandBrakeEncodeWorker.<>c__DisplayClass6_0.<StartEncodeInternal>b__0(Object o, EventArgs e) in D:\git\VidCoder\VidCoderWorker\HandBrakeEncodeWorker.cs:regel 104
ERROR: Operation 'Ping' failed, worker process has crashed.

**Comment by RandomEngy** [comment]
Thanks for the report. Should be fixed in 6.3 Beta. Also put out a fix for the Stable track.
