### ISSUE TITLE
Anamorphic 

### ISSUE THREAD

**Issue by stylusbum** [RandomEngy/VidCoder#620]
476/5000
The new version (5.15) changes the output resolution of the video if it is filled with black and anamorphic stripes, I liked to take out my Br Rip with stripes, since many remove them, now if I use the anamorphic option and fill for a 1920x960 for example puts me,

Storage resolution: 1920x1080
Display resolution: 1680x1080

The output resolution suck. I do not know if this was what they solved in the update, but before it did not happen, I will continue with the old versions.

**Comment by RandomEngy** [comment]
I did change the logic recently to fix another bug; I'll look at fixing this. Can you give me an encode log? And the storage/output resolution you were expecting?

**Comment by stylusbum** [comment]
> I did change the logic recently to fix another bug; I'll look at fixing this. Can you give me an encode log? And the storage/output resolution you were expecting?


I share a one minute video to try to explain better what happens to me:

The 1920x960 video source would be this:

https://drive.google.com/file/d/15oj8n9IMwG3KQwHKfry6sQEiunGfGP3W/view?usp=sharing

I want to take it out in 1920x1080, filled with black stripes up and down, for this, previous versions I selected padding: fill and it came out perfect, but now if I select that option and use anamorphic box it goes like this:

https://drive.google.com/file/d/1yccQBg-Kub1DU9FQB9FZu_0_jPMXYPoW/view?usp=sharing

With black stripes but a display resolution of 1680x1080. I do not know if it really is a bug or before the anamorphic option did not work well, I am not very expert on the subject.

Greetings.

**Comment by stylusbum** [comment]
attached encode log
[log.txt](https://github.com/RandomEngy/VidCoder/files/4080022/log.txt)

**Comment by RandomEngy** [comment]
Thanks for the feedback. This will be fixed in the next release.

**Comment by RandomEngy** [comment]
I've fixed it in the Beta 6.4 release. Planning to also port it to stable, but trying to work out a Windows Store cert issue first.

**Comment by stylusbum** [comment]
Download Beta: 6.4 and the problem does not happen, I will wait for the stable version, thank you very much :-)

**Comment by RandomEngy** [comment]
Fixed in 5.16 stable.
