### ISSUE TITLE
vidcoderbeta

### ISSUE THREAD

**Issue by leninmejia39** [RandomEngy/VidCoder#623]
You can change that when you are converting the file do not do so. if not it has termination .mkv of a single pason
![vidcoder01](https://user-images.githubusercontent.com/23637190/73231143-2525bb00-4145-11ea-8623-46fa6749895e.png)

**Comment by leninmejia39** [comment]
that becomes normal as a single mkv and s can verify during the conversion as with mediainfo .. do not wait until it is finished

**Comment by leninmejia39** [comment]
https://pastebin.pl/view/raw/fe3062f2

**Comment by RandomEngy** [comment]
Yes, it writes to a temporary location first to better handle failed encodes. Are you saying that you'd like the temporary location to also have an .mkv suffix?

**Comment by leninmejia39** [comment]
if you can and that when you are converting the file can be verified with mediainfo .. during the process

**Comment by leninmejia39** [comment]
have a suffix .mkv? yes

**Comment by RandomEngy** [comment]
Made the change in 6.7 Beta.
