### ISSUE TITLE
Vidcoder Beta themes

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#624]
In Vidcoder stable 5.16 the border of the window with focus is coloured and the Encoder Settings one is grey which matches the rest of my software. The borders change colour with focus. In Vidcoder 6.4 Beta it seems that the light theme is always overriding the OS Theme setting I have selected so I get no colour borders at all and the Encoding Settings window is always grey. It doesn't match the OS theme and it makes it hard to know what window is selected.

**Comment by RandomEngy** [comment]
I agree that the window should change more to make it more obvious which one is selected. I've changed it to alter the title bar background color and the border color when selected. It won't use the OS accent color, but I think it will still work.

Change will be in the next Beta.

**Comment by RandomEngy** [comment]
Change is in 6.5 Beta.

**Comment by iamjaydear** [comment]
Thank you :)
