### ISSUE TITLE
There is no audio pass through for TrueHD when using Apple 2160p60 4k HEVC Surround  

### ISSUE THREAD

**Issue by dtownsend** [RandomEngy/VidCoder#625]
When Using the "Apple 2160p60 4k HEVC Surround" there is no pass through option for TrueHD.  

The audio option is blank and if a user attempts to render the file no audio is present for that specified track.

Verified that this option is available in Handbrake

**Comment by RandomEngy** [comment]
TrueHD passthrough is not available using the mp4 container. I don't see it as an option in HandBrake when using an MP4 container either. What version of HandBrake are you checking on?

**Comment by dtownsend** [comment]
You are right I miss spoke.  I apologizes. Handbrake(1.3.1) lets you select the option to have TrueHD audio pass through but when it renders out it just ignores the track. It does not indicate the user can not select the option.  Unlike your UI.
