### ISSUE TITLE
Picker Title Selection not saved

### ISSUE THREAD

**Issue by bschwehn** [RandomEngy/VidCoder#627]
I want to enqueue a folder with quite a few sub folders of DVD backups, some containing series, so I want to automatically enqueue all titles in a DVD longer than 10 minutes. 

As I understand, using the Picker settings, this should be possible. 

However, in both vidcoder Beta and stable, whenever I set the checkbox in "Title Selection" - "All titles from ... minutes", save the picker, close the picker window and then reopen the picker, the checkbox is not saved. And when I enqueue a folder, only the first long title is enqueued, discading all the other episodes. 

I assume the bug is, that the "Title Selection" - "All titles from .. to .. minutes" is not saved in the picker, without providing any feedback during save why it is not saving.

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next release (Beta and Stable).

**Comment by RandomEngy** [comment]
Fixed in 6.7 Beta.
