### ISSUE TITLE
Auto subtiles select

### ISSUE THREAD

**Issue by towlerg** [RandomEngy/VidCoder#628]
In the old 32bit version 1.5.31.0 you could auto select subtitles tools/options/audio and subtitles. Where is this in 5.17? BTW Great fan, nice mix of ease of use and flexibility.

**Comment by RandomEngy** [comment]
That functionality has been expanded and moved to the "Picker" window. I have a change ready for v6 that will make this more discoverable.

**Comment by towlerg** [comment]
Hey, thanks for getting back so quick, I'll have a play with that.
