### ISSUE TITLE
Can I set the bitrate or quality for the Fallback ?

### ISSUE THREAD

**Issue by Gokou-Ruri** [RandomEngy/VidCoder#635]
I don't know how to modify this value .

![image](https://user-images.githubusercontent.com/26711804/79174856-957fd680-7e2e-11ea-9b2d-a40f3647d654.png)

**Comment by RandomEngy** [comment]
You can't, right now. It picks defaults. It would be a lot of UI to write for a corner case, so I haven't done it yet. But you can click on Add audio encoding, select the AAC codec and change settings there.

**Comment by Gokou-Ruri** [comment]
> You can't, right now. It picks defaults. It would be a lot of UI to write for a corner case, so I haven't done it yet. But you can click on Add audio encoding, select the AAC codec and change settings there.

Thank you for your reply.
