### ISSUE TITLE
Dark Mode --

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#636]
In Dark mode, within Options section, some colors need more careful consideration –

check box and radio button selections are not visible unless the mouse is hovered in the vicinity of the item in question.

Also (probably related), drop-down selections (for example, "when done" or "worker process priority"), the selection bar obliterates the text beneath it.

**Comment by RandomEngy** [comment]
What OS are you using? Is this VidCoder Beta or stable? I'm not seeing the issues you describe. Can you attach screenshots?

**Comment by Plutocratic** [comment]
The shots that follow were taken using dark mode (6.6 beta) under Windows 10 1909.

First - the "When Done" box. Note that the text near the cursor is only marginally visible. _(Don't be concerned about the "shadow" around the mouse cursor which is an anomaly of the screen capture software)._ Some of the drop-downs look like this...

![When Done](https://user-images.githubusercontent.com/42285022/79484696-f6183a80-800b-11ea-8c1c-5c8b586f1f01.jpg)
...others are OK, like this...

![This menu OK](https://user-images.githubusercontent.com/42285022/79484769-121bdc00-800c-11ea-838c-036c27e71434.jpg)

Now the "options" menus. The first three check boxes are selected - trust me :) - the check mark only becomes visible when the mouse is positioned within the target region for that item. Note also that **none** of the radio button states are visible.....

![Options 1](https://user-images.githubusercontent.com/42285022/79484908-50b19680-800c-11ea-8c55-f0bb49e0c329.jpg)

....until the mouse is moved within the appropriate target region at which point it becomes visible

![Options 2](https://user-images.githubusercontent.com/42285022/79484931-59a26800-800c-11ea-8292-757fe8bdaaf5.jpg)

No changes were made between one shot and the next; the mouse was merely moved around a bit!

**Comment by RandomEngy** [comment]
Thanks. To help me reproduce, could you tell me what Windows theme you are using?

**Comment by Plutocratic** [comment]
It's something of a mongrel, I'm afraid – but nothing too fancy. I can confirm that the stock themes do work in this respect, but the changes I have made are legitimate and reasonable.

The key difference that appears to cause the problem with my theme is the background color **internal** to the check boxes and radio buttons is, as you can see, white. In a satisfactory theme that internal background is black and the checks and buttons are white, so you can understand why they are not visible in this case.

So the answer may well be for **your** dark mode to override that aspect of the user's theme.

I can send you my theme if it will help.

**Comment by RandomEngy** [comment]
Yeah. I had to basically take over the control templates for a lot of the standard controls and put in my own colors. I had not done that yet for radio buttons or checkboxes because the built-in ones seemed fine. But looks like I'll have to give those the same treatment.

But yes, if I had your theme to test with, that would be helpful.

**Comment by Plutocratic** [comment]
Here's my theme. This ZIP contains the two files that, I believe, should be all you need except for the screen background but that shouldn't matter. Just in case it's relevant (although I don't believe so), I also use Stardock's Start10.

[Pluto theme.zip](https://github.com/RandomEngy/VidCoder/files/4515244/Pluto.theme.zip)

**Comment by RandomEngy** [comment]
Beta 6.7 has a fix for the checkboxes and radio buttons. I wasn't able to reproduce the list issue with that theme; but hopefully the app is usable for you now.
