### ISSUE TITLE
Pause - close - lose

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#64]
I have several videos in queue. I paused VC and then closed it. When I restarted it, the video that was unfinished was gone. I repeated this and same thing happened. The incomplete file is not reloaded to complete it.

**Comment by RandomEngy** [comment]
Thanks for the feedback. I'll change this in the next Beta release to keep your in-progress item in the queue when exiting the app. Though you'll need to start it at the beginning again; I can't avoid that.

**Comment by RandomEngy** [comment]
Fixed in 2.27 Beta.
