### ISSUE TITLE
Feature: Source timecode on preview

### ISSUE THREAD

**Issue by refriedfood** [RandomEngy/VidCoder#645]
I don't care where it is, it is impossible to make compares from encode to source without a strenuous effort of scrubbing through the source to the exact frame. Please add the timecode for the starting frame of the preview somewhere in the preview window or even in the tiny preview window with the chapter length, etc. I don't know how this has been looked passed. :x

**Comment by RandomEngy** [comment]
Added the preview timestamp for file sources in 6.9 Beta. It's not easy to get for DVD/Blu-ray sources right now because of the complicated way those ones are picked.

**Comment by refriedfood** [comment]
Thanks for working on adding it. I tested the beta multiple times and used mp4 vs raw source and the timecode is off by about 3-6 seconds. Also, hh:ss:frames would be the greatest. Thanks again, hope you get it going.

**Comment by RandomEngy** [comment]
They seek to a "fraction" of the file for the preview. For DVD and Blu-Ray this was wildly off but for the files I tested, it was within a second. But now I'm wondering if for some sources the "seek" code isn't quite as exact or if the reported title duration is incorrect. I don't think I'm going to get this "guess" much better, so including frames is pretty much off the table.

Is this feature of any value as it is? I think I should remove it if it's this far off.

**Comment by refriedfood** [comment]
Well, considering what your tool is used for, at least in my case, to encode quality x264/5 from DVD/BD sources. i.e. vob/m2ts. To meet quality standards for encoding you have to compare source versus encode, and the frame has to be exact. Now encoding the entire film twice just to find out you can improve its encode either by dropping the bitrate or changing the advanced settings in order to produce the best final product without being bloated, you're wasting a lot of time that could simply be determined with a preview and knowing its frame number to compare it immediately to source.
Does that make sense? If you have time, look into AvsPmod. https://www.screenshotcomparison.com/comparison/3281

**Comment by RandomEngy** [comment]
I understand the use case, certainly. But I'm limited with what the HandBrake API can do. It doesn't look like I can get down to frame-level accuracy with what I've got.

I think I'll remove the timestamp as it looks like it can be off by a fair amount.

**Comment by refriedfood** [comment]
That's a shame. If you ever get it to work, it'd be great if you added it at least as an toggle option.
