### ISSUE TITLE
Vidcoder Beta 6.8 won't "Output to the source folder if possible" any more.

### ISSUE THREAD

**Issue by ZaphodX77** [RandomEngy/VidCoder#647]
First time I've tried to use this feature in some time, and it is broken now. A default folder is required and is in place, but checking and unchecking the box for Output to Source Folder hasn't this effect. I also loaded Betas going back to 6.5, and it didn't work.
I loaded 5.19 non-Beta, and it worked correctly in this respect. However, the selected default folder stays as set and changes are never loaded at all, even if it is changed (a lot).

**Comment by RandomEngy** [comment]
In your Picker settings, do you have the box for "output to source folder" unchecked?

**Comment by ZaphodX77** [comment]
That was the source of my problem. Thank you for referring me to this.
