### ISSUE TITLE
Vidcoder FAILS if 2-pass encoding is chosen (Dell SFF 9020 i7 with Windows 10 2004, VidCoder 5.19)

### ISSUE THREAD

**Issue by dborisd** [RandomEngy/VidCoder#648]
First time since the Win10 2004 update I tried VidCoder encoding. I can choose x264 or x265, play with other settings, but as soon as I select 2-pass encoding, the encoding fails.

Please help.

[2020-05-29 22.57.46 Encode Transporter (The Series) - S01 E01 - Trojan Horsepower (720p Web-DL).mkv-failed.txt](https://github.com/RandomEngy/VidCoder/files/4704317/2020-05-29.22.57.46.Encode.Transporter.The.Series.-.S01.E01.-.Trojan.Horsepower.720p.Web-DL.mkv-failed.txt)

**Comment by dborisd** [comment]
And this is the log of the normally started encoding WITHOUT 2-pass encoding selected.

[2020-05-29 23.00.24 Encode Transporter (The Series) - S01 E01 - Trojan Horsepower (720p Web-DL).mkv-aborted.txt](https://github.com/RandomEngy/VidCoder/files/4704339/2020-05-29.23.00.24.Encode.Transporter.The.Series.-.S01.E01.-.Trojan.Horsepower.720p.Web-DL.mkv-aborted.txt)

**Comment by dborisd** [comment]
The 2-pass encoding works normally on another PC with WIn 10 2004.

**Comment by dborisd** [comment]
For now I had to roll back to Win10 1909 to get the 2-pass encoding to work.

Can somebody investigate ?

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by dborisd** [comment]
> 
> 
> Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.
> 
> Equivalent versions:
> VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
> VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

I did, same results. You think I should go to the HandBrake team ? OK.

**Comment by dborisd** [comment]
Got forgotten, don't know the background, but the user logged in (and the C:\Users\xy folder) had a "š" character in it.
Once I tried it with another user, strict non-special english named, the encoding worked.
