### ISSUE TITLE
Vidcoder audio/subtitle suggestion

### ISSUE THREAD

**Issue by ArtexJay** [RandomEngy/VidCoder#649]
Allow users to be able to name (rename) the audio fields and subtitles so that when we select the audio or subtitle it doesn't return as only "eng" or something.

**Comment by RandomEngy** [comment]
You can already name the audio tracks under Encoding settings -> Audio Encoding. I'll look at adding the ability to name subtitle tracks.

**Comment by ArtexJay** [comment]
Reason why I ask is because when i encode Vidcoder doesn't respect the original names of the audio track. So it ends up being "eng" as the name. While with ShanaEncoder it came out as "Disney and Streamline" 
Here is a screenshot of the layout. I don't see where I can name the audio track. Just where to select.
![image](https://user-images.githubusercontent.com/32932497/83357790-8b615b00-a33c-11ea-954f-fb05369d3457.png)

**Comment by RandomEngy** [comment]
Try the Beta. It has changes to respect the source audio track name.

**Comment by RandomEngy** [comment]
Made a more comprehensive fix in 6.9 Beta. It now preserves both subtitle and audio track names and those are editable from the main UI.
