### ISSUE TITLE
Intel Quick Sync Video fails with new Intel Media SDK

### ISSUE THREAD

**Issue by spec1re** [RandomEngy/VidCoder#653]
https://github.com/HandBrake/HandBrake/issues/2858

I have the exact same issue here with VidCoder:

> [12:43:51] sync: expecting 163518 video frames
> [12:43:51] hb_d3d11va_device_check: QSV adapter with id 1 has been found
> [12:43:51] qsv_hevc_make_header: MFXVideoENCODE_EncodeFrameAsync failed (-5)
> encqsvInit: qsv_hevc_make_header failed
> Failure to initialise thread 'Quick Sync Video encoder (Intel Media SDK)'

And here is the PR which fixed it in HandBreake.

https://github.com/HandBrake/HandBrake/pull/2862

**Comment by RandomEngy** [comment]
HandBrake hasn't had a successful nightly build since that checkin. Waiting on that, then I can bring the fix into VidCoder.

**Comment by spec1re** [comment]
Okay thanks! 👍

**Comment by RandomEngy** [comment]
Updated the core in VidCoder 6.9 Beta.
