### ISSUE TITLE
BitDefender reports infection with 6.9 Beta

### ISSUE THREAD

**Issue by kingstairs** [RandomEngy/VidCoder#654]
Just tried downloading 6.9 Beta (Portable EXE), and BitDefender Security reporting the following:

**The file C:\Users\Marshall\Downloads\VidCoder-6.9-Beta-Portable.exe.fdmdownload is infected with Gen:Variant.Graftor.761998 and was moved to quarantine.**

Windows 10 Pro, current BD definitions.
No issue with 6.8 Portable. Likely a false positive, but of course needs investigation.

**Comment by sed03** [comment]
It doesn't look good with virustotal https://www.virustotal.com/gui/file/b13fc30a68d27036309178f23f89eb2a8b185155711c0d64dcc87d18efc3ba24/detection

**Comment by RandomEngy** [comment]
It looks like a bunch of the engines on VirusTotal share the same definitions, which is why they all changed at once. Reported false positives to a bunch of them.

**Comment by sed03** [comment]
It's getting better. Now 9  reports, https://www.virustotal.com/gui/file/b13fc30a68d27036309178f23f89eb2a8b185155711c0d64dcc87d18efc3ba24/detection  from 17 reports.

**Comment by palopezv** [comment]
Windows Security and SmartScreen are killing the portable binary on sight too.

**Comment by sed03** [comment]
Yep. It's not a positive development for small developers and for all us that love portable apps.

**Comment by RandomEngy** [comment]
Defender doesn't flag anything for me. SmartScreen always seems to go off on the new releases for a bit until it trusts them. I could solve the SmartScreen problem by signing the code, but the required certificate would cost ~$400 per year.

**Comment by kingstairs** [comment]
Nowadays, it's probably good practice to test a new binary and/or installer with VirusTotal or a similar service, so you can submit false positive report(s) _before_ you release, or at least mention the false positives in the release notes.

In my experience, AV vendors just don't test their definitions sufficiently before releasing them - didn't Symantec (for example) have multiple incidents, where it "quarantined" Windows core DLL's?

Back to this issue, it's curious that the AV engines are reporting different results - TrendMicro and Sophos each have _two_ engines on the list, but only _one_ reporting a positive.

**Comment by palopezv** [comment]
> 
> Defender doesn't flag anything for me. SmartScreen always seems to go off on the new releases for a bit until it trusts them. I could solve the SmartScreen problem by signing the code, but the required certificate would cost ~$400 per year.

@RandomEngy check out:

https://www.codenotary.io/with-codenotary-you-never-have-to-pay-for-code-signing-certificates-again/
https://blog.aluxian.com/free-code-signing-certificate-for-open-source-software-d836270823a7
https://en.sklep.certum.pl/open-source-code-signing.html

There are others, in fact I became aware of these services throught other web siite offering free certificates for open source, but I cannot find in my bookmarks anymore.

**Comment by palopezv** [comment]
@RandomEngy FYI, the latest Windows Defender database update stopped detecting VidCoder as malware. I was able to both run tne portable version and the installer without interference.

**Comment by palopezv** [comment]
@RandomEngy I've finally found the signing service I was thinking about. I found it in the release noted for Transmission BT (see https://github.com/transmission/transmission/releases/tag/3.00). The free signing service is [SignPath.io](https://about.signpath.io/) and certificates are provided by the [SignPath Foundation](https://signpath.org/).

**Comment by RandomEngy** [comment]
That looks promising. They want you to fully integrate the build with their services so they can be sure it's used to sign the open source code only. I wonder if they would take issue with a large hb.dll being included and called without building it with their system. Will look into it.

**Comment by RandomEngy** [comment]
Sent them an email. Will see if it works out.

**Comment by RandomEngy** [comment]
https://github.com/SignPath/Website-old/blob/v2/src/drafts/oss_policy.md

Since you are re-using their cert to sign, you need to run the build on AppVeyor. Getting the Linux->Windows cross compiled hb.dll built in that way seems like a giant pain. Also I use a bunch of NuGet packages which bring in binary DLLs that the program uses, and they are asking for all of those to be signed as well. Sounds like a real bad time tracking all of this down.

I think this would be more trouble than it's worth.

**Comment by RandomEngy** [comment]
Update: I'm now digitally signing VidCoder releases. Hopefully that will reduce the suspicion AV programs have on new releases.
