### ISSUE TITLE
Deleted source files should be moved to recycle bin instead of directly removing from the disk

### ISSUE THREAD

**Issue by abdusco** [RandomEngy/VidCoder#655]
When _Delete source files after successful complete items (with confirmation)_ option is selected, source file is deleted directly from the disk (with a confirmation, of course). This is a bit unfortunate because it's really tedious, often impossible to recover the file back in case I realize I made a mistake.

https://github.com/RandomEngy/VidCoder/blob/054803e7d83eef6b23fa15c161431052ec73f110/VidCoder/Services/ProcessingService.cs#L984-L987

The app should instead move the source file to Recycle bin and let user decide when to get rid of the file completely.

https://stackoverflow.com/questions/721026/how-to-move-files-to-the-recycle-bin

**Comment by RandomEngy** [comment]
Implemented in 6.10 Beta.

**Comment by abdusco** [comment]
Thanks a lot!
