### ISSUE TITLE
CPU unused cores

### ISSUE THREAD

**Issue by fatnasa** [RandomEngy/VidCoder#656]
Hello,

currently i am running Vidcoder on Amd ryzen threadripper 3960x (24 Cores) but when running a single encode instance , vidcoder only utilizes 30% of CPU.

allowed cores setting ==== > 100%

do we have any way to fix this?

thanks in advance

**Comment by RandomEngy** [comment]
The encoders can use multiple threads but only up to a certain point. You can run multiple encodes at once with this option though:

![image](https://user-images.githubusercontent.com/9450861/84327125-756d4a80-ab33-11ea-804b-7b82c528d3ec.png)

**Comment by fatnasa** [comment]
oh ,  yeah i have already done this by splitting the files into small chapters so i can utilize the full power.

i thought i am doing something wrong and there is a better way to perform the proccess

thanks for your answer

**Comment by Vereor** [comment]
No to hijack, but I have been tempted to raise an enhancement request on the simultaneous encoding jobs.
Any chance of getting max limit increased to 8-12 jobs?
Another stupid 3970x user here. running 4 1080p with my settings gets about 80% usage.
But 720p on 4 simultaneous jobs does leave some thumb twiddling room.

**Comment by RandomEngy** [comment]
@Vereor I'll bump it to 8 on the next Beta release.

**Comment by RandomEngy** [comment]
Changed max to 8 in VidCoder Beta 6.10 .
