### ISSUE TITLE
Interlaced video incorrectly called progressive

### ISSUE THREAD

**Issue by Beater34** [RandomEngy/VidCoder#661]
I have a commercial blu-ray disk labelled as 1080i, and MediaInfo says the m2ts files are "Interleaved fields, Scan order: Top Field First". I have encoded the disk using AnyDVD and VidCoder with all video filters set to off (including deinterlace = off). The resultant MKV file is clearly interlaced (with combing), but MediaInfo says it is progressive and tsMuxer says the resolution is 1920:1080p, so my TV does not deinterlace the picture. VidCoder mislabels the output even if :tff is specified in More Settings on the Video Encoding tab (I suspect this is because VidCoder puts :tff at the start of the parameter list instead of at the end).

The problem is solved by using Handbrake instead of VidCoder: in the Filters tab set everything to off; in the Video tab set fps to "Same as source" with "Constant Framerate", and in Advanced Options add :tff or :bff (top or bottom frame first can be obtained from MediaInfo set to View/HTML).

**Comment by RandomEngy** [comment]
I am guessing that something else is causing the difference in output between VidCoder and HandBrake. Both supply the "extra options" field directly to the encoder in a separate field, so the ordering should not matter.

Can you supply the encode log from both?

**Comment by Beater34** [comment]
Thank you for looking into this. I attach the HandBrake log and MediaInfo report on the output (Interleaved fields), and the VidCoder log and MediaInfo report (Progressive) on the same encode. The file is clearly interleaved, with obvious combing.

[HandBrake_Log.txt](https://github.com/RandomEngy/VidCoder/files/4891625/HandBrake_Log.txt)
[HandBrake_MediaInfo.txt](https://github.com/RandomEngy/VidCoder/files/4891626/HandBrake_MediaInfo.txt)
[VidCoder_Log.txt](https://github.com/RandomEngy/VidCoder/files/4891627/VidCoder_Log.txt)
[VidCoder_MediaInfo.txt](https://github.com/RandomEngy/VidCoder/files/4891628/VidCoder_MediaInfo.txt)

**Comment by RandomEngy** [comment]
There are a couple of differences I noticed.

* In VidCoder you have "align A/V start" set to true, while false with HandBrake.
* Handbrake video profile is set to "high" while it is set to "auto" for VidCoder.

Can you check and see if one of those was throwing it off?

**Comment by Beater34** [comment]
Thank you. Unfortunately, the problem persists after turning off Align A/V and setting video profile to "High".

[VidCoder_UnAlign_High_MediaInfo.txt](https://github.com/RandomEngy/VidCoder/files/4894383/VidCoder_UnAlign_High_MediaInfo.txt)
[VidCoder_UnAlign_High_log.txt](https://github.com/RandomEngy/VidCoder/files/4894384/VidCoder_UnAlign_High_log.txt)

**Comment by RandomEngy** [comment]
Two more possibilities:

You could try VidCoder 5.20 which uses the HandBrake 1.3.3 core.
Try making sure the audio encoding is the same on both. It's probably not the issue but I've seen some weird effects before.

**Comment by Beater34** [comment]
Thanks again for helping. Vidcoder 5.20 crashes when I try to load this disk (see  #662). Vidcoder 5.20 portable loads the disk but still outputs a "Progressive" file (that is actually interlaced) despite the :tff option. The audio coding is the same on VidCoder and Handbrake 1.3.3. I note that HandBrake without the :tff option outputs a file labelled "Progressive", but with :tff outputs "Interleaved". VidCoder outputs "Progressive" with and without :tff.

**Comment by RandomEngy** [comment]
I did notice that you have a space at the end of the options string in the VidCoder. I'm not sure if that would make a difference, but you could try removing it.

If that doesn't help I'll try to track down an interlaced source and figure out what's going on.

**Comment by Beater34** [comment]
Thank you! That may have been the problem. I uninstalled VidCoder 5.20 (because it will not load the problem blu-ray) and re-installed VidCoder 5.19 and made sure there is no space after :tff - and the output is Interleaved. I still cannot get Vidcoder 5.20 to read the disk (see #662). Vidcoder 5.20 portable reads the disk and outputs interleaved.

**Comment by RandomEngy** [comment]
I'll fix this in the next version by automatically trimming space from the ends of the string.

**Comment by RandomEngy** [comment]
Should be fixed in 5.21.
