### ISSUE TITLE
Vidcoder 5.20 crashes after loading blu-ray disk

### ISSUE THREAD

**Issue by Beater34** [RandomEngy/VidCoder#662]
After upgrading from version 5.19 to 5.20, VidCoder crashes after opening a blu-ray disk (with AnyDVD HD). I have had to uninstall 5.20 and reinstall 5.19 (which works fine). I attach the "Combined" log file.

[VidCoder 5.20 Combined.txt](https://github.com/RandomEngy/VidCoder/files/4894618/VidCoder.5.20.Combined.txt)

**Comment by RandomEngy** [comment]
Does it also crash for you with HandBrake 1.3.3? The only thing that changed in 5.20 was the HandBrake core.

**Comment by Beater34** [comment]
Thank you. HandBrake 1.3.3 does not crash. VidCoder 5.20 portable does not crash. VidCoder on my Windows 10 x64 computer still crashes when I try to load the blu-ray disk (with AnyDVD HD). I have uninstalled it (and deleted all options), rebooted and reinstalled - and it still crashes. If the problem is mine alone, I can just use HandBrake or the portable version of VidCoder 5.20 or VidCoder 5.19 (all of which work well).

**Comment by RandomEngy** [comment]
Hmm. Does the crash make the UI disappear, or is this just a crash in the encoding process? Do you get any error dialog on the crash?

**Comment by Beater34** [comment]
While loading a file or disk the screen says scanning the input (with a progress bar), then, when it has finished loading, the main screen appears for about a second, then VidCoder completely disappears.  There is no error dialogue. This occurs only with VidCoder 5.20 installed on my Windows 10 x64 computer, and not with VidCoder 5.20 portable or with HandBrake 1.3.3 installed. I have re-installed 5.20 twice (deleting all options and profiles etc), but have had to go back to 5.19. My apologies for the hassle, and thank you for helping.

**Comment by Beater34** [comment]
I thought I had solved the problem by uninstalling VidCoder 5.20 using Revo Uninstaller in Advanced Mode, (which found a lot of registry entries and files left by the Vidcoder Uninstaller), rebooting, then reinstalling VidCoder 5.20. It then loaded the blu-ary and seemed to be OK for a couple of minutes, but when I was about change the container format from mp4 to MKV, the UI suddenly disappeared. Portable 5.20 still works fine.

**Comment by RandomEngy** [comment]
Do you see any entries under Event Viewer -> Windows Logs -> Application?

![image](https://user-images.githubusercontent.com/9450861/87082074-47852f80-c1df-11ea-9329-55907c412281.png)

**Comment by Beater34** [comment]
Yes, see attached.
[Vidcoder - Event Viewer.txt](https://github.com/RandomEngy/VidCoder/files/4900626/Vidcoder.-.Event.Viewer.txt)

**Comment by RandomEngy** [comment]
Thanks, that was very helpful. It is trying to cache preview images to disk, but is not able to due to unauthorized access to %appdata%\VidCoder\ImageCache . I've got a change ready to properly catch that exception and prevent the crash. Should be fixed in the next version.

**Comment by RandomEngy** [comment]
Should be fixed in 5.21.
