### ISSUE TITLE
Open multiple files or directory does not remember the subtitle selection from either in the file of external srt file

### ISSUE THREAD

**Issue by aotgunrt** [RandomEngy/VidCoder#663]
With "remember previous files/folders"
Open multiple files or directory does not remember subtitle selection from either in-beaded in the file of external srt file

If you drag and drop files 1 by 1 file it remembers the subtitle selection. Works Great Thanks.

Even If I add one file with srt file, English, Burn In checked, then add the rest of the files from the same directory, just does not remember the selection. :(

After multiple files are added to the Queue, there is no way to make a subtitle selection on all files in the Queue.

You must edit each individual file separately. This seems to defeat adding multiple files with subtitles selections.

It is quicker to drag and drop each file individually.

FEATURE REQUEST:
Is there a way to add a subtitle status to the Queue Columns?

Thank Your attention to this matter,

Steve

**Comment by RandomEngy** [comment]
When you drag and drop multiple files, the source subtitles are chosen based on the current Picker settings, which you can edit from the Picker window.

Right now, adding external .srt files needs to be done on a 1-at-a-time basis. Though it might be possible to try and automatically add them if they had the same file name. Is this the case for your videos?

Will put the subtitle selection queue column on the backlog.

**Comment by aotgunrt** [comment]
Thanks

Did not know about the picker window. :)

Steve

**Comment by RandomEngy** [comment]
Added subtitles as an optional queue column in 6.13 Beta.

**Comment by aotgunrt** [comment]
Thanks 😊
