### ISSUE TITLE
YADIF Bob framerate with CFR

### ISSUE THREAD

**Issue by Asterchades** [RandomEngy/VidCoder#669]
I don't know if this counts as a bug or a feature request, or if it's something which needs to be handled by the VidCoder front-end or HandBrake back-end, but here goes...

When using YADIF set to Bob (counter-intuitively, me thinks, but that's neither here nor there) the filter returns one frame per field. This results in doubling the input framerate, assuming the filter is set to parse every frame rather than deciding which frames to process (decombing). When set to VFR, this works (almost) exactly as you might expect it would. However, when set to CFR "Same as source" the resulting output drops every second frame. This behaviour is present in both 5.21 and 6.11beta.

Obviously you can manually set the appropriate framerate for the output by taking the input and doubling it, correcting for each file as it comes. But this seems like an oversight, given the "source" framerate should already been doubled by the deinterlacing operation. Even a "Source x2" option, which could be assigned to the profile, would result in a faster work flow than having to manually adjust, though that setting would very much be a feature request.

If you're wondering why I don't just use VFR, I have found that it produces visible stuttering in situations - particularly camera pans - as it seems incapable of generating truly consistent frame times even from consistent input. In the video I'm testing at the moment it's reliably yielding an average 49.898fps instead of an even 50fps, despite being sourced from a constant 25fps PAL stream, but even times when it shows the correct average it doesn't mean they all have the same frame time.

**Comment by RandomEngy** [comment]
Thanks for the report. If the same behavior is present in HandBrake, then it should be addressed by the HandBrake team.

**Comment by Asterchades** [comment]
Yep, this is a base HandBrake thing. I've reported it over there - just forgot to come back here and close this.
