### ISSUE TITLE
Proper manual syntax to enter for custom video filters

### ISSUE THREAD

**Issue by 55trucker** [RandomEngy/VidCoder#671]
Dave:

if one wants to not use the default sharpness/denoise filters (lapsharp/NL-means) as they are set up in the video filter page how does one enter a manual syntax into the advanced window/encoder settings to get a slightly different sharpness setting or denoise setting?
As well, what are those default settings entered in as a syntax?

I make use of another encoding program as well that uses filters for doing the same function, this program allows the user to make fine adjustments to allow such changes but Vidcoder is somewhat more user friendly.

**Comment by RandomEngy** [comment]
Choose the Custom preset. Mouse over the box to get the format and the list of valid keys:

![image](https://user-images.githubusercontent.com/9450861/89742453-eb683200-da4e-11ea-909a-795ceac8192b.png)

**Comment by 55trucker** [comment]
I see,
with reference to the strength of either item, when I select (for example) light....what is the syntax that is being prescribed & how do I actually see that setting to get an idea as to how I want to vary away from such setting?

**Comment by RandomEngy** [comment]
You'd need to encode some sample clips with the Preview window.

**Comment by 55trucker** [comment]
I'll try that, 
but in the meantime, could you tell me what are the program default code entry settings for both *light* sharpen & *medium* sharpen?,...... if I want to enter a custom code for a setting that somewhat stronger than light but less than medium what would I manually have to enter?

thx

**Comment by RandomEngy** [comment]
There should be a tooltip for the available parameters but I don't know that off the top of my head.
