### ISSUE TITLE
System.NotImplementedException: Unable to run any recent version, no idea last working version

### ISSUE THREAD

**Issue by clubside** [RandomEngy/VidCoder#673]
Automatic update of Beta introduced this error. Manually downloading Beta releases in reverse order unable to find working version, all report identical error during startup:

System.NotImplementedException: The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Appears that it's a bug in WPF: https://github.com/dotnet/wpf/issues/2377 . Does it happen when on remote desktop? Since you have a reliable repro they might be interested in whatever details you can give.

**Comment by clubside** [comment]
I don’t have a Remote Desktop setup. This is just a basic Windows 10,Home install. I’ve had VidCoder Beta pinned to the taskbar for over a year and blindly accept upgrade prompts on exit. In the past if a new version crashed on startup I’d just download the previous version. Unfortunately it’d been months since my last update so I have no idea what version was the last working version. I tested the previous 4 versions before giving up and posting here.

**Comment by elyoh** [comment]
This specific exception can be thrown whenever a WPF application tries set the Window.TaskbarItemInfo property (whether through xaml or code behind).  If it fails for any reason, the application will crash with the exception you have seen which is pretty fustrating for the user.  

That appears to happen here (even in the last non-beta release).
https://github.com/RandomEngy/VidCoder/blob/af9f604d732d7b04205e2f00e1da9c4961b29753/VidCoder/View/Main.xaml#L404-L406

Commenting out those lines and rebuilding the source might give a build which works on systems affected by this issue.

As for the underlying reason the code fails, I am not at all sure.

The remote desktop scenario appears to be just one reproducible way to cause the crash.  My own WPF apps detect and  workaround for that, but the crash report is still seen in telemetry, so there is certainly a problem in non-remote desktop scenarios too.

@clubside If you have any clues about your specific set up which would help someone to reproduce the crash, that might help convince the Microsoft team to investigate further and implement a fix.  For example, I wonder if some users have third party antivirus solutions which attempt to run an app in a "sandbox", preventing access to certain OS functions.

**Comment by clubside** [comment]
@elyoh other than VidCoder Beta being pinned to the Taskbar seems to be the only out-of-the ordinary aspect to my setup. This Windows 10 install is nearly 3 years old and never had issues with VidCoder Beta being pinned for over a year, but as mentioned previously I hadn’t run it in months so I don’t know the last working version.

I have no anti-virus beyond Windows Defender and while apps have come and gone no 3rd-party system-wide apps have been installed.

**Comment by RandomEngy** [comment]
That code setting the TaskbarItemInfo has been there in its current state for several years. I am wondering if some .NET or OS update has corrupted things. I'll look into trying to set this programatically under a try/catch.

**Comment by RandomEngy** [comment]
I added a workaround in 6.12 Beta. If it throws an exception the taskbar progress feature won't work, but at least it shouldn't crash.

**Comment by clubside** [comment]
@RandomEngy Thanks, this version does launch fine. If there's anything I can do to help debug please let me know. It's been a while since I haven't used the in-app update-on-close and running the installer gets the "windows doesn't want you to install this" dialog where you have to click a few things to get to "Install anyway". If that's not normal maybe it's tied to whatever OS or .NET issue is affecting the Taskbar.

Oh, one other note: before this started happening I didn't have Visual Studio 2019 Community on this machine. That's a big sys-level difference to previous environment.

**Comment by RandomEngy** [comment]
The windows warning dialog is just because I haven't coughed up the money for a code signing certificate yet, and is unrelated to this issue.
