### ISSUE TITLE
Create new folder within source folder for new encodes

### ISSUE THREAD

**Issue by ez-one** [RandomEngy/VidCoder#677]
Hi there, new to VidCoder (awesome program).  Just wondering if there is any chance of a create new folder within source folder option.  Or if this can already be done?

ie. "Big source file" is in Big Source Folder
-> new file becomes 'Big Source file in Big Source Folder/Smaller version

Not sure if this can be done within the Override folder area.

**Comment by RandomEngy** [comment]
You could do that with Override Naming Format: `Smaller\{source}` and checking "Output to the source folder if possible".

**Comment by ez-one** [comment]
Thanks, worked perfectly
