### ISSUE TITLE
BUG: Last item in queue does not get an progressbar (V6.12 beta)

### ISSUE THREAD

**Issue by MBCD2000** [RandomEngy/VidCoder#678]
Like the title says, the last item left in queue does not get a progressbar.

EDIT: This seems not to happen every time, at my last watch it worked as expected, at actual queue there is still again no progressbar for the last item that is processed. Seems not to be some kind of "constant" bug.

**Comment by RandomEngy** [comment]
Fixed in 6.13 Beta.

**Comment by MBCD2000** [comment]
Thank you very much!
