### ISSUE TITLE
Feature Request: Automatically retry failed jobs

### ISSUE THREAD

**Issue by swanknight** [RandomEngy/VidCoder#679]
I use VidCode to re-encode a lot of videos and I often get some failures, but whenever I manually retry them they always work just fine. 

I don't know why these failures happen, but it would be be nice to have an option to to auto retry _(add them back at the end of the queue)_ **X** number of times before finally giving up.

**Comment by swanknight** [comment]
Nobody?

**Comment by RandomEngy** [comment]
You want to add to the end of the queue rather than automatically retry right then?

**Comment by swanknight** [comment]
> 
> 
> You want to add to the end of the queue rather than automatically retry right then?

The way I see it, there are two ways to go about this. 

1) Automatically retry failed job and the user gets to decide the number of retries before VC gives up and continues the queue.
2) On failure, simply add the failed job back at the end of the queue.

Personally, I prefer the second one but either of them should work. What do you think?

**Comment by RandomEngy** [comment]
I would think you'd have two settings:
When to add retry jobs: Immediately or at the end of the queue
How many times to retry: 1, 2, 3, etc

Is there a reason why you would want to add the retry job to the end of the queue rather than attempting the retry immediately?

**Comment by swanknight** [comment]
> I would think you'd have two settings:
> When to add retry jobs: Immediately or at the end of the queue
> How many times to retry: 1, 2, 3, etc

Sounds perfect.

> Is there a reason why you would want to add the retry job to the end of the queue rather than attempting the retry immediately?

That's the current behavior of VC when I manually choose "Retry all failed jobs", so I thought it would be simpler to implement.
Also, delaying the "retry" could avoid deadlocks that would arise from continuing to retry a damaged file or something along those lines, but that's a rather minor scenario.

**Comment by RandomEngy** [comment]
Added ability to retry failed encode jobs in 6.29 Beta in General Options -> Advanced.
