### ISSUE TITLE
Forced Econding to 35 MB file size

### ISSUE THREAD

**Issue by Nearpeer** [RandomEngy/VidCoder#680]
I am using vidcoder to encode multiple video footage (MKV format) to the different target bit rates but it is forcefully convert/encode all of the footage to a 35 MB size irrespective of the preference I pick. Can anyone please help/guide me?

**Comment by RandomEngy** [comment]
Can you post an encode log to pastebin and mention the bitrate that you picked?

**Comment by Nearpeer** [comment]
Hey, Got the solution. i wasn't clicking on "Apply to render Qeue" before pressing save. Can you tie-in both of these functions in next release?
