### ISSUE TITLE
Feature Request: More info about automatically selected features on queue

### ISSUE THREAD

**Issue by MBCD2000** [RandomEngy/VidCoder#681]
Great Program, thanks !!!

I miss some kind of control what it outputs.
In my case I used autocrop for multiple sourcefiles.
But there is no quick way to check in queue what has been adjusted for each source.
In my case it accidently cropped 164 pixels from left, so output was not as it should have been, I had to redo it.

There is no possiblity to get a quick info about the output (what has been cropped, what tracks have been selected, ...).
So some kind of quick-info-tooltip would be nice or at least an optional column in the queue-table for a quick check.

What I got, the only way to check it, is to edit the queue-item and re-add it back to queue.
This works of course, but it is not very comfortable for lots of files.

**Comment by RandomEngy** [comment]
Added cropping, subtitles and audio tracks as optional queue columns in 6.13 Beta.

**Comment by MBCD2000** [comment]
Dont know what else to say: THANK YOU !!!!!
This become a really nice app, I am so happy to find it, it does so far a very good job! Best software of all I tried!

**Comment by RandomEngy** [comment]
That's great to hear. Glad you're enjoying it!
