### ISSUE TITLE
Ransomware warning from TrendMicro re VidCoder 6.12 Beta

### ISSUE THREAD

**Issue by juzzle** [RandomEngy/VidCoder#683]
**Here's the report**

Date/Time,Threat,From,Version,Copyright,Detected Resource or Process ID,Response
6/09/2020 11:04,C:\Users\<user>\AppData\Local\Temp\is-OPA33.tmp\VidCoder-6.12-Beta.tmp,Unknown,,,C:\Users\<user>\AppData\Local\Temp\is-OPA33.tmp\VidCoder-6.12-Beta.tmp,Terminated

Seems that three JPEGs were created (thumbs) in temp directory

**Comment by RandomEngy** [comment]
These are temporary files that Inno Setup creates to track the install progress. Pretty sure this is normal behavior.

**Comment by RandomEngy** [comment]
Could you report the file as safe to them?

**Comment by juzzle** [comment]
I could do that David, but last we spoke you were going to raise this with Trend. There comes a point where I have to ask myself "maybe there's something in this report" - I mean I can take your word for it once or twice, but ..

Regards,
Justin
________________________________

**Comment by RandomEngy** [comment]
Understandable.

I did report the file as safe to a bunch of AV providers. But most of them are not responsive, and there are so many AV providers that it would take an inordinate amount of time to do that for every release.

If you click on my GitHub profile, you can see that I work for Microsoft. They pay me well enough that it wouldn't be worth doing anything shady.

I've recently started digitally signing VidCoder releases, so hopefully this will eventually help with the virus false positives.

Has your computer ever been locked and held for ransom?

**Comment by juzzle** [comment]
Thanks for understanding David, and I feel your pain getting AV providers to listen. I guess my concern is not directed at something you’d do intentionally, but rather a PUA that your app might depend on (ie, sneak in through a back door).

Has my PC ever been locked for ransom? No, but that’s pretty much a one way ticket so I will do everything I can to fall into that trap.

Justin

**Comment by RandomEngy** [comment]
All the dependencies are open source. Not a guarantee against foul play, but it helps.

As for third party antivirus, I've always considered it malware in and of itself, based on how it bogs down the system and finds false positives.

I now have an especially dim view of it based on how it's telling so many people my software is malware. I've had people coming to me for years with many different viruses and trojans VidCoder has been mis-identified as.

Anyway, not to say your report isn't appreciated. More of a rant about the state of AV in general.

**Comment by juzzle** [comment]
I appreciate the feedback David – thank you
