### ISSUE TITLE
interpreting full Vs. limited range

### ISSUE THREAD

**Issue by davexnet** [RandomEngy/VidCoder#684]
Hello -
an intermediate clip encoded in Virtualdub using FFV1 lossless codec, 4:2:0, 8 bit,
and then encoded as H.264 in Vidcoder appears washed out.

Is Vidcoder interpreting this FFV1 source as full range?

[clip.zip](https://github.com/RandomEngy/VidCoder/files/5197605/clip.zip)

**Comment by RandomEngy** [comment]
VidCoder uses HandBrake for the core encoding engine, so you might ask them for help. I don't have detailed knowledge of how the engine handles color spaces.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by davexnet** [comment]
Thank you.  I tried it on Handbrake and it's OK.  Retraced my steps in VidCoder and it's
working fine now, after choosing one of the built in encoder settings.  Not sure what happened, 
something in my saved encoding profile?  But there's nothing about color spaces in there, 
something implied somewhere?

**Comment by RandomEngy** [comment]
There's no "color space" UI in VidCoder. It would all happen through the "extra options" string.

**Comment by davexnet** [comment]
Thanks for your help
