### ISSUE TITLE
weird bug in 6.14 beta

### ISSUE THREAD

**Issue by davexnet** [RandomEngy/VidCoder#687]
clicked on the quality slider in encoding settings, a warning about file conflict appeared,
and the slider continued by itself all the way to the right
https://i.postimg.cc/wMCgcpKx/vidcoder-bug.jpg

**Comment by RandomEngy** [comment]
Were you able to move the slider back after you closed the dialog?

**Comment by davexnet** [comment]
yes but it moved to the right again by itself.  Had to kill process in Task Manager.
Have now reverted to 6.13

**Comment by RandomEngy** [comment]
Thanks for the report. Fixed in 6.15 Beta.

**Comment by davexnet** [comment]
Thanks RE updated to latest Beta
