### ISSUE TITLE
Feature request: output path relative to source path

### ISSUE THREAD

**Issue by Senju-vilis** [RandomEngy/VidCoder#691]
For source path of D:\foo\source you could enable:
✅ set output path relative to source path

and then write in address bar:
source `\output` or source `\bar\output`

and it would yield:
`D:\foo\source\output` or `D:\foo\source\bar\output` respectively.

This would help me with batch encodings with nested source folders.

**Comment by RandomEngy** [comment]
Have you tried using this option on the Picker window?

![image](https://user-images.githubusercontent.com/9450861/94495681-3ed14380-01a7-11eb-94af-245df12d448d.png)

Also in the "custom file naming format" you can specify subdirectories if you want to, like `output\{source}`. That would put the file in D:\foo\source\output\MyVideo.mp4

**Comment by Senju-vilis** [comment]
Yeah, I requested an already present feature. Sorry for inconvenience
