### ISSUE TITLE
[Request] Add Watermark

### ISSUE THREAD

**Issue by pro100Hub** [RandomEngy/VidCoder#696]
Hello.
Please add to the functionality of the program the ability to add watermarks to the video: text and image with location and size.

Thanks for the program, very good encoder :+1: 

Regards.

**Comment by RandomEngy** [comment]
Thanks for the feature request. VidCoder uses the HandBrake encoding engine, and that project has defined their scope as being a transcoder only, not an editor. You'll need to use a video editing program to add a watermark.
