### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ThomasCSR** [RandomEngy/VidCoder#701]
System.NullReferenceException: Objektreferencen er ikke indstillet til en forekomst af et objekt.
   ved VidCoder.Services.PreviewImageServiceClient.set_PreviewIndex(Int32 value) i C:\git\VidCoder\VidCoder\Services\PreviewImageServiceClient.cs:linje 37
   ved VidCoder.Services.PreviewImageServiceClient.ShowPreviousPreview() i C:\git\VidCoder\VidCoder\Services\PreviewImageServiceClient.cs:linje 56
   ved System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   ved System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ved System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ved System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   ved System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   ved System.Windows.Input.InputManager.ProcessStagingArea()
   ved System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   ved System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   ved System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   ved System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. I'll have a fix out in the next Beta release.

**Comment by RandomEngy** [comment]
Should be fixed in 6.17 Beta.
