### ISSUE TITLE
File Joining?

### ISSUE THREAD

**Issue by UnrealDrumpf** [RandomEngy/VidCoder#702]
Does VidCoder support joining multiple input files into a single output file? (Two-part TV, especially!) 

If so, how? 

If not, can that be considered for future releases, please?

**Comment by RandomEngy** [comment]
Thanks for the feature request. VidCoder uses the HandBrake encoding engine, and that project has defined their scope as being a transcoder only, not an editor. You'll need to use a video editing program to do this.
