### ISSUE TITLE
audio encoder

### ISSUE THREAD

**Issue by Marciuz90** [RandomEngy/VidCoder#704]
Hello, there is way to integrate into lossy audio encoding: to DTS lossy (768, 1509, 1536), to E-AC3 7.1 (in this alternative increase the presence of frequencies in mhz in version 5.1 with 896 and 1024)

**Comment by 55trucker** [comment]
To the best of my knowledge there is not a free consumer based software encoder package for DD+ (E-AC3) encoding. 
There are commercial/industrial software packages but they are expensive, Minnetonka is one source & Neyrinck is another, but they are in the price range of $2000us.

**Comment by Marciuz90** [comment]
you would then be able to increase the frequencies of the E-AC3 5.1 with 896 mhz and 1024 mhz; besides maybe add among the lossy conversion codecs also to dts 5.1 768 and 1536 mhz?

**Comment by 55trucker** [comment]
Any time one is dealing with a lossy format there is nothing to be gained in trying to re-encode that lossy file to anything else than what it currently is. You cannot convert back to wav (6 or 8 independent channels) and expect to gain back the file information that was lost (such as can be done with a lossless file) when originally encoded to the lossy format. Once encoded to a lossy format that information is permanently gone.

**Comment by Marciuz90** [comment]
no, I mean I would code TrueHD, PCM, DTS-HD MA, DTS HD including DTS X and maybe the same E-AC3 7.1 896/1024 to E-AC3 5.1 (if there is no way to insert the 7.1 of the E-AC3). Maybe you could also insert lossy encoding for DTS-HD MA and DTS X

**Comment by 55trucker** [comment]
I understand what you're intent is, but there isn't a software program available to the general public at the moment that will encode to E-AC3 (Dolby Digital+).

**Comment by Marciuz90** [comment]
i'm fine vidcoder, I was just asking to implement the mhz frequencies of the E-AC3 5.1 with 896 mhz and 1024 mhz

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://handbrake.fr/community.php) to add it.
