### ISSUE TITLE
Subrip subtitles are turned to SubStationAlpha

### ISSUE THREAD

**Issue by gkalemis** [RandomEngy/VidCoder#706]
In beta version 6.17 .srt (subrip sutitles) are converted to SubStationAlpha (SSA) during the conversion

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)
