### ISSUE TITLE
A Question about Move Files in VidCoder

### ISSUE THREAD

**Issue by Pinepro** [RandomEngy/VidCoder#713]
當我移動預定編碼列表，多個檔案同時向上移動時，最下方的檔案會排列到移動後的最上方，多個檔案同時向下移動時，最下方的檔案也會排列到移動後的最上方。

When I move the predetermined code list, when multiple files move up at the same time, the bottom file will be arranged to the top after the move. When multiple files move down at the same time, the bottom file will also be arranged to the top after the move.

The above content is translated by Google

**Comment by RandomEngy** [comment]
I think something may have been lost in translation. I don't know what the "predetermined code list" is. Could you post some screenshots of what you are seeing?

**Comment by Pinepro** [comment]
![1st](https://user-images.githubusercontent.com/74996903/100256009-3024c400-2f7f-11eb-878c-f187e2e8a138.jpg)
![2nd](https://user-images.githubusercontent.com/74996903/100256051-3ca91c80-2f7f-11eb-865c-db23a3ea3af6.jpg)
![3rd](https://user-images.githubusercontent.com/74996903/100256074-4763b180-2f7f-11eb-8910-6902d7e2e374.jpg)



I selected six files. 07 08 09 10 11 12
I ordered them to move to the top.
The order after moving is wrong.12 07 08 09 10 11
Is this an error?

**Comment by RandomEngy** [comment]
Thanks for the report; this looks like a bug. I'll investigate it.

**Comment by Pinepro** [comment]
The same problem will arise when moving down again

Thanks for your reply

**Comment by RandomEngy** [comment]
I found the problem. This will be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 6.19 Beta.
