### ISSUE TITLE
show fraction number in Output PAR line

### ISSUE THREAD

**Issue by bjmi** [RandomEngy/VidCoder#72]
In Encoding Settings > Picture > Input ... Pixel Aspect Ratio: **1.07** (16/15) shows fraction number but Output ... Pixel Aspect Ratio: (16/15) does not. Could you please add the fraction number there too?

It should look like: Output ... Pixel Ascpect Ratio: 1.07 (16/15)

**Comment by RandomEngy** [comment]
Added this in 2.27 Beta.
