### ISSUE TITLE
Feature Request: "Automatic" Resolution for Input

### ISSUE THREAD

**Issue by Saijin-Naib** [RandomEngy/VidCoder#721]
I'd love the ability to have an "Automatic" or "Keep Original" option for Input file video resolution, so that a single transcode macro could be safely used against varying sources without having to worry about them having their resolution changed.

In this way, one could re-encode to HEVC at a given quality level and not worry if there are some 1080p intermixed with 720p and 2160p videos, as each would stay at their original resolution, but still be re-encoded into HEVC at the right settings.

**Comment by RandomEngy** [comment]
Set up your Sizing tab like this:

![image](https://user-images.githubusercontent.com/9450861/101536379-c7f6ba80-394e-11eb-930c-4f35295c6f68.png)

You can delete the max width and height and disable cropping to keep the original resolution.

**Comment by Saijin-Naib** [comment]
Awesome that that is there, but not very intuitive!

Thanks so much!
