### ISSUE TITLE
Mixed List

### ISSUE THREAD

**Issue by kenanunkesti** [RandomEngy/VidCoder#725]
Kuyruk listesinde klasör ve dosya yolları dikkate alınarak sıralama özelliği olmalı.
Vidcoder v5.21 dosyaları karışık şekilde kuyruğa atıyor :(

![2020-12-13_111420](https://user-images.githubusercontent.com/65110421/102015939-6e87f480-3d6f-11eb-8678-151e120c3c7c.png)

**Comment by RandomEngy** [comment]
Thanks for the report. Were these added via drag/drop?  I add them in the way that Windows hands me the drag/drop files, which is the selected order. I'll add an option to always order drag/dropped files alphabetically.

**Comment by kenanunkesti** [comment]
Hello,

Yes i added it with drag and drop.


14 Ara 2020 Pzt 19:50 tarihinde David Rickard <notifications@github.com>
şunu yazdı:

**Comment by RandomEngy** [comment]
Should be fixed in 6.20 Beta.
