### ISSUE TITLE
nlmeans filter custom settings

### ISSUE THREAD

**Issue by radusound** [RandomEngy/VidCoder#726]
Nlmeans filter custom settings don't work. What i did wrong ?

Could not recognize filter settings for 'HB_FILTER_NLMEANS' with preset '', tune '' and custom settings 'cb-frame-count=2:cb-origin-tune=1.0:cb-patch-size=7:cb-prefilter=0:cb-range=3:cb-strength=6.0:y-frame-count=2:y-origin-tune=1.0:y-patch-size=7:y-prefilter=0:y-range=3:y-strength=6.0'

**Comment by RandomEngy** [comment]
Thanks for the report. A HandBrake engine change broke this. It will be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 6.20 Beta.
