### ISSUE TITLE
Question about batch file naming.

### ISSUE THREAD

**Issue by DillFrescott** [RandomEngy/VidCoder#728]
I'm trying to batch transcode files and have them replace the original file in the source folder, retaining the folder structure.

I set the global options to name every file as {source}, so the name doesn't change, but the issue is that many of the files say:

filename (Encoded).mp4

How do I get rid of the (Encoded) at the end without having to rename every single file in the batch manually?

**Comment by RandomEngy** [comment]
Are you trying to replace the original file? Currently there is no way to automatically delete the original; I'm afraid of causing data loss on an encode that didn't go correctly.

I assume you also want to delete the original file even if the encoded name is different, in this case?

**Comment by DillFrescott** [comment]
Yes. It's okay though. Thank you for the assistance!
