### ISSUE TITLE
Latest 6.19 Beta no longer preserves File Modification/Creation Time on Conversion

### ISSUE THREAD

**Issue by FurinaxBln** [RandomEngy/VidCoder#729]

**Comment by RandomEngy** [comment]
I just tested it it and it seems to still be working and I haven't changed any code in that area lately. Do you see any errors in the Log window when the encode ends?

**Comment by FurinaxBln** [comment]
On Log-Level Standard I didn't see any errors in the logfiles.
Now it still seems to work if the container stays the same, i.e. only the codec inside the container changes (for example x264 -> x265, both inside mkv), but it no longer keeps the date/time on file format changes (for example avi -> mkv).

**Comment by RandomEngy** [comment]
I think this is an issue with .mkv. I was trying to set the Encoded date as well, but that was failing and then not trying to change the created/modified date. I added some logic to handle that error and still change the created/modified dates. Will be fixed in the next Beta release.

**Comment by FurinaxBln** [comment]
if it helps, on another try this time I got the following long chain of error messages (mp4 -> mkv):

ERROR: Could not set create/modify dates on file: Microsoft.WindowsAPICodePack.Shell.PropertySystem.PropertySystemException (0x80004005): Unable to set property. ---> System.Runtime.InteropServices.COMException (0x80030005): Access Denied. (Exception from HRESULT: 0x80030005 (STG_E_ACCESSDENIED))
   at Microsoft.WindowsAPICodePack.Shell.PropertySystem.ShellPropertyWriter.WriteProperty(PropertyKey key, Object value, Boolean allowTruncatedValue)
   at Microsoft.WindowsAPICodePack.Shell.PropertySystem.ShellPropertyWriter.WriteProperty[T](ShellProperty`1 shellProperty, T value, Boolean allowTruncatedValue)
   at Microsoft.WindowsAPICodePack.Shell.PropertySystem.ShellProperty`1.set_Value(T value)
   at VidCoder.Services.ProcessingService.<>c__DisplayClass212_0.<OnEncodeCompleted>b__0()
   
Did not change the temp. target directory or permissions of it, only had different sources for the encodes...
But always the sources were on a network drive, the target temp is local - in case that might be important.
I myself don't know enough about Windows, so the error codes can't tell me much beyond the obvious :-)

**Comment by RandomEngy** [comment]
Yeah that's what I saw as well. It can't change the "encoded date" property on .mkv files I think. But I should be able to fix it not setting created/modified dates.

**Comment by RandomEngy** [comment]
Fixed in 6.20 Beta.
