### ISSUE TITLE
Portable 2.27-beta will NOT encode any video to a different size

### ISSUE THREAD

**Issue by RappinRod** [RandomEngy/VidCoder#73]
Hello: 2.27 works fine encoding the audio part of a file but it will not change the video frame size,,its a major flaw..I have been using Vidcoder through all of its betas with no major issues,but this one is a huge problem and can not be used because of it..For instance 1280x536 will not change to 1024x576 even though I set it under the picture tab the same goes for h265 under the picture tab.the file produced is still 1280x536 no matter what frame size setting I use under the picture tab..Also after returning to the 2.26 beta,it would not restart until I deleted the VidCoder.sqlite file thus causing me to lose all my set presets,I guess I should have backed up my preset file lol..Thankfully 2.26 works fine again..Anyway Thanks for a great program and I know you will address this issue promply as 2.27 is unusable until you do...;)~

**Comment by RandomEngy** [comment]
Ahh, looks like HandBrake changed the JSON formatting of their rescale filter. Will take a look at it.

**Comment by RappinRod** [comment]
I was hoping the new Handbrake core would work properly in 2.27..You do great work on VidCoder and I know you will correct this issue.I hope you keep it going strong..I know you have no control over what Handbrake does and I am glad you spend the time making it work in your program..Once again Thanks for a great product and thanks for the quick response...

**Comment by spikaspika** [comment]
we set settings:  max width = 720
input video - width = 1024
converting
result : width video output = 1024

**Comment by RappinRod** [comment]
Thanks for replying,you just verified the issue..~

**Comment by kairukun93** [comment]
hope this will be fixed soon, because i recently checked my previous encodes, and i was like wow, didn't notice that my encodes are in the same resolution as the original DVDs, and Blu-rays! thanks for letting us know this issue! thank god I'm not the only the one!

**Comment by RappinRod** [comment]
Hello and yes I am right there when new betas are put out from VidCoder..Half my day is spent  encoding and VidCoder is my program of choice..The author of this fine user friendly GUI for Handbrake does a great job of making it work flawlessly..I’m sure he will have this issue fixed soon at least I hope so lolol..

**Comment by RandomEngy** [comment]
Fixed in 2.28.

**Comment by RappinRod** [comment]
Ahhh there is a bright spot in this dim world today hehe..2.28 64bit portable is working perfectly for me..Settings,,profiles,,resolutions,,cpu throttling,,worker process at normal uses 90% to 99% of all 8 cpu cores,,h265,,h264 encoding with subtitles as we speak seem to be working perfectly..Thanks for the energy and time you take to do this,,and thanks for correcting any problems found in VidCoders betas in a timely fashion...
