### ISSUE TITLE
Request for Documentaiton regarding what switches set for Fast, Medium, Slow

### ISSUE THREAD

**Issue by Ergonomicmike** [RandomEngy/VidCoder#730]
There is a window for Advanced Options, where users can manually add switches for encoding. But it's not clear if we are undoing (or changing) something that is already done in a Encoder Preset setting.

So a request for documentation documenting what switches are being set in Fast, Medium, Slow. (E.g. strict_gop=1)

Better yet, if the switches were automagically loaded into the Advanced Options (perhaps in blue, to show defaults) it would show users what switches are being set by VidCoder.

**Comment by RandomEngy** [comment]
Are you using an old version? The Advanced Options tab is gone.

**Comment by Ergonomicmike** [comment]
The name has been changed in VidCoder to More Settings. (Is still "Advanced Options" in Handbrake.)

https://i.postimg.cc/fWpR6xwS/Vidcoder-screen-shot-More-Settingts.jpg

**Comment by Ergonomicmike** [comment]
P.S. (Since github won't let me edit my posts) - am using VidCoder 6.19 Beta. Screen shot above shows the Settings window that I am referring to.

**Comment by RandomEngy** [comment]
H.264 (x264) has the ability to show what settings are active based on the encode preset/tune/profile. But that's not possible for other encoders. The HandBrake API that VidCoder uses does not expose that.

**Comment by Ergonomicmike** [comment]
Ah, okay. Too bad. If it ever does, please keep this request in mind.
