### ISSUE TITLE
Starting Vicoder disconnects wi-fi (Windows 10)

### ISSUE THREAD

**Issue by Krongii** [RandomEngy/VidCoder#733]

**Comment by RandomEngy** [comment]
That is extraordinarily odd. VidCoder doesn't do any fancy networking stuff. It does an update check on launch. Try the version of VidCoder in the Microsoft Store: that one doesn't do an update check.

Also if your disconnect is happening on starting an encode, try disabling "Use worker process to encode" in Global Options -> Process.

**Comment by Krongii** [comment]
On further investigation it appears to be a random thing related to the
wi-fi and not directly related to Vicoder. Please cancel/delete my post.
Apologies

Maciej
