### ISSUE TITLE
Ver 2.27 much slower

### ISSUE THREAD

**Issue by hucky291158** [RandomEngy/VidCoder#74]
For some reason 2.27 is about 6 times slower than 2.26.

I'm converting to h264 in 2-pass, average bit rate: the first pass is about 70-90 fps with 2.26, with 2.27 it dropped to 10-15.

Is it just me doing something funny after update? I'm using the same presets used with 2.26.

**Comment by RandomEngy** [comment]
The video filters are a bit messed up in 2.27, and those are sometimes bottlenecks for encoding speed. I'll fix those and hopefully this goes away.

**Comment by hucky291158** [comment]
Thanks, RandomEngy.

**Comment by RandomEngy** [comment]
Fixed in 2.28.
