### ISSUE TITLE
Suggestion:  Be Able to Rename Subtitltes...

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#741]
Since vidcoder resides on Handbrake, this option is already in handbrake.  Would be nice to have a CHECKMARK like the AUDIO.

Thanx. Regards.

**Comment by RandomEngy** [comment]
You can do this in the Beta version:

![image](https://user-images.githubusercontent.com/9450861/106485048-0c8d6680-6465-11eb-96b8-7e57718dafed.png)

**Comment by quebecman** [comment]
Thanx, I will give a try.

________________________________

**Comment by quebecman** [comment]
Hello,

 It would be nice in the BATCH MODE to be able to ENTER a CUSTOM SUBTITLE NAME to apply to all the EPISODES in a TV SHOWS.  See below for example.

[cid:6216d3dc-88cb-4e2a-a276-db3add3ebcc2]


Thanx. Regards


________________________________

**Comment by RandomEngy** [comment]
Was that supposed to be an image? It may have gotten lost in the email -> GitHub comment conversion.

**Comment by quebecman** [comment]
![2021-02-01 18_18_01-VidCoder Beta](https://user-images.githubusercontent.com/4656308/106530902-32ddf100-64bb-11eb-9b74-9cece9aa658a.png)

**Comment by quebecman** [comment]
I have tried the following but doesn't work.

  I have add all my episodes of my favorite TV SHOW in VIDCODER.
 
I have created a CUSTOM Encoding System Called TV SHOWS.

 -- Once all the episodes added to the BATCH QUEUE, I went ahead and @APPLY ENCODING SETTINGS@ in the BATCH QUEUE.

![2021-02-01 20_05_57-VidCoder Beta](https://user-images.githubusercontent.com/4656308/106538006-76d7f280-64c9-11eb-84a6-0575a2ea30b1.png)

**Comment by quebecman** [comment]
Please, can you confirm is this can be done in version BETA?    I have download the BETA version but maybe I have missed something.

Thanx. Regards

**Comment by RandomEngy** [comment]
Beta doesn't have this functionality. I'll put it on the feature backlog.

**Comment by quebecman** [comment]
Thanx. Regards.

________________________________

**Comment by RandomEngy** [comment]
Added Picker option in 6.24 Beta.
