### ISSUE TITLE
Suggestion for Batch: New Column for information such as PASS # and FPS in real time

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#742]
It would be nice to get a column in the BATCH MODE when running with FPS in real time and the PASS NUMBER (example: 1 of 2...)

In the completed TAB I would add Average FPS.  (If I change my CPU, this is neet informations.)

Keep it up, it's really good software.  I think I will switch from Handbrake since handbrake has lots of issues and limitation on the BATCH SIDE.

**Comment by RandomEngy** [comment]
Have you tried Window -> Encoding Details?

**Comment by quebecman** [comment]
Nope, sorry.  Didn't knew it was there.  I will give a try next time.  Sincerly, this is minor to me but it would be nice to get under the COMPLETED TAB the information like handbrake gives when completed:


![image](https://user-images.githubusercontent.com/4656308/106538486-4e042d00-64ca-11eb-88e9-172bd80e001b.png)

**Comment by RandomEngy** [comment]
You can right-click -> Customize columns to get some of the details for the encode queue. The "completed" tab doesn't have that yet. I have debated going to the way HandBrake is handling it but I do like the option to be able to see information for every queue item, not just one at a time.

Would adding customizable columns for the completed tab help?

**Comment by quebecman** [comment]
LOL! I should of THOUGHT about the customization column.  This is great!

Would adding customizable columns for the completed tab help?  -- **YES BIG TIME!  I would ADD ERRORS too**!.

Well, I have switched over vidcoder.  VIDCoder have some major enhancement over HANDBRAKE, especially on the BATCH QUEUE side.

**Comment by RandomEngy** [comment]
I'll put the customizable columns for the completed items on the backlog.

As for writing my own encoding engine: Not going to happen, sorry. I've got other projects I'd rather work on.

**Comment by quebecman** [comment]
You can go ahead and close this thread.  This was my BAD when I began.  I didn't noticed it was there.

  But, please, do not forget to add the column to the output folder.

**Comment by RandomEngy** [comment]
You can also close your own issues, by the way. I do have the completed jobs columns on the backlock.

**Comment by quebecman** [comment]
Asked as a request.
