### ISSUE TITLE
Enhancement: BATCH QUEUE Replace Name by...

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#745]
Hello,

 I do understand this is not really part of VIDCODER but it's related.  It would be nice in the PICKER or Global Option to have some sort of AUTO RENAME option.

As per example, REPLACE in the name of a TV SHOW something like below:

Source Name: Dcs.Legends.Of.Tomorrow.S03E01.**FRENCH.1080p.BluRay.x264-FRATERNiTY**

by

End Name: Dcs.Legends.Of.Tomorrow.S03E01.**FRENCH.BRRip.264-TORRiD**

I have to use manually an utility called BULK RENAME UTILITY, but this is a long process.  If it could be done during the conversion, it would be nice.

Thanx. 
Regards.

**Comment by RandomEngy** [comment]
I would try to use the "Post-encoding" option at the bottom of the Picker window. You can run another command on it after the encode completes. Auto-rename utilities can get quite complicated so I'm not sure I'd want to try and build a full-fledged one into VidCoder.

**Comment by quebecman** [comment]
Since this will not be implemented.  You can go ahead and close this thread.

Thanx.
Regards.
