### ISSUE TITLE
Enhancement for BATCH QUEUE: Apply to all Audio Name Tag

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#746]

**Comment by quebecman** [comment]
Same as suggestion #741.  Meaning to have the same thing as the subtitles, to be able to apply to ALL the same Audio Name Tag.

Thanx. 
Regards.

**Comment by quebecman** [comment]
Can you confirm if this can be added in the enhancements to the PICKER option?  Would save a lot of time.

**Comment by RandomEngy** [comment]
It's on the backlog.

**Comment by RandomEngy** [comment]
Added Picker option in 6.24 Beta.
