### ISSUE TITLE
Minor Tweaks to add to Batch Queue

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#747]
Hello,
 
 Here is a list of things in Handbrake midnight that I think should be included in VIDCoder.

 - Change Case to Title Case; (nice to have feature)
 - Minimize to system tray; (good to have)
 - Replace space in the name with "." dots; (nice to have feature)
 - Name output files based on folder name. (this one is not in handbrake)

Thanx. Regards.

**Comment by RandomEngy** [comment]
Minimize to system tray is in Global Options -> General
![image](https://user-images.githubusercontent.com/9450861/107122698-168cdc00-684e-11eb-9d3d-aa4ede4e7d88.png)

Replacing space with "." - I didn't see this option in HandBrake but I have planned out options for much more configurable source transforms, to allow word breaking by specified characters and replacing with space, dot or underscore. In addition to having the Title Case option applied to more than just disc sources.

I was thinking of adding an option to pick out the "true" source name via regex. Let me know if that would be handy.

As for naming output files based on folder name, you can already do that in VidCoder. Use `{parent}` in the naming format.

**Comment by quebecman** [comment]
Wow... where were u all these years.  I think this should be awesome.  It's more than a nice to have but a must have.  Ok, well, I do understand that people that does this once in a while, it's not really useful... but when doing lots, it a big save of amount of time.

Thanx. Regards.

________________________________

**Comment by RandomEngy** [comment]
Added options in the Picker to change title case for all sources and to change the word break character in 6.22 Beta.
