### ISSUE TITLE
Subtitles: ASS vs SRT

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#751]
I do understand that VIDCoder is based on Handbrake but is there anything that we can do about the subtitles.  In other terms, HANDBRAKE does convert to ASS the subtitles.  I tink SRT (UTF-8) should be kept and not converted.

**Comment by RandomEngy** [comment]
I'm not sure what format they get converted to under the hood. But that's HandBrake functionality that the encoding engine owns.

**Comment by quebecman** [comment]
Hello David,

  They are converting it in a ASS subtitle instead of SRT (utf-8).  I have already asked the support but they closed the ticket without any explanation.

Thanx. Regards.

________________________________

**Comment by RandomEngy** [comment]
I don't own that code so that's not something I can help with. Sorry.

**Comment by quebecman** [comment]
No worries. I was wondering what are usually the Time frame for updates and néw enhancements of vidcoder?

Thanx. Regards.

Envoyé de mon iPhone

Le 8 févr. 2021 à 10:32, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


I don't own that code so that's not something I can help with. Sorry.

**Comment by RandomEngy** [comment]
It's when I get time to work on it. I have a full time job and a family and other projects. But usually I work on it at least once a month. Been working on adding better word break/separator/capitalization options to the Picker recently.

**Comment by quebecman** [comment]
No problem...was just curions on upcoming notes of thé fractures released

Envoyé de mon iPhone

Le 8 févr. 2021 à 11:02, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


It's when I get time to work on it. I have a full time job and a family and other projects. But usually I work on it at least once a month. Been working on adding better word break/separator/capitalization options to the Picker recently.

**Comment by quebecman** [comment]
Mat i know what is word break and seperator

Are thèse boomerang true or false?

Envoyé de mon iPhone

Le 8 févr. 2021 à 11:02, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


It's when I get time to work on it. I have a full time job and a family and other projects. But usually I work on it at least once a month. Been working on adding better word break/separator/capitalization options to the Picker recently.

**Comment by RandomEngy** [comment]
This sentence uses spaces to break words. This_sentence_uses_underscores_to_break_words.

Not sure what you mean by "boomerang".

**Comment by quebecman** [comment]
Sorry, my corrector. i meant boolean.

Merci.
Bonne journee.

Envoyé de mon iPhone

Le 8 févr. 2021 à 11:45, Richard Desormiers <rdesormiers@hotmail.com<mailto:rdesormiers@hotmail.com>> a écrit :

Mat i know what is word break and seperator

Are thèse boomerang true or false?

Envoyé de mon iPhone

Le 8 févr. 2021 à 11:02, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


It's when I get time to work on it. I have a full time job and a family and other projects. But usually I work on it at least once a month. Been working on adding better word break/separator/capitalization options to the Picker recently.

**Comment by quebecman** [comment]
Boolean for stuff like Caps case, replace spaces with . Or _ , etc...

Thanx. Regards

Envoyé de mon iPhone

Le 8 févr. 2021 à 14:09, Richard Desormiers <rdesormiers@hotmail.com<mailto:rdesormiers@hotmail.com>> a écrit :

Sorry, my corrector. i meant boolean.

Merci.
Bonne journee.

Envoyé de mon iPhone

Le 8 févr. 2021 à 11:45, Richard Desormiers <rdesormiers@hotmail.com<mailto:rdesormiers@hotmail.com>> a écrit :

Mat i know what is word break and seperator

Are thèse boomerang true or false?

Envoyé de mon iPhone

Le 8 févr. 2021 à 11:02, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


It's when I get time to work on it. I have a full time job and a family and other projects. But usually I work on it at least once a month. Been working on adding better word break/separator/capitalization options to the Picker recently.

**Comment by RandomEngy** [comment]
Here's a sneak preview:

![image](https://user-images.githubusercontent.com/9450861/107280233-e8092f80-6a0c-11eb-9b53-7005d7702c6d.png)

**Comment by quebecman** [comment]
That seems Nice.

In thé change word seperator. What are thé options? Space, dot, underscore...

Change capitalisation? Can you and option for only thé first letter of thé word



Envoyé de mon iPhone

Le 8 févr. 2021 à 15:55, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


Here's a sneak preview:

[image]<https://user-images.githubusercontent.com/9450861/107280233-e8092f80-6a0c-11eb-9b53-7005d7702c6d.png>

**Comment by quebecman** [comment]
You can go ahead and close this thread since it was implemented.
