### ISSUE TITLE
Source Name Cleanup (good job!)

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#755]
I have tried all the scenarios with the name cleanup and nothing to add.  I already talked about this but if we could be able to MIX with a AUTO-RENAME, it would be awesome.  Finally, almost a DRAG DROP and CLICK ENCODE...

I think the only thing would be to add the BATCH Audio et Subtitle RENAME (apply to all).

 I love the PREVIEW!  (Perfect)

I have notice just a small thing.  The first Word of the Title, The capital W gets to small w.  I would leave it like that since it's the first word.

Lasty, I know you already talked about this but if you could be able to create a new project to keep this GUI with FFMPEG as the engine... it would be awesome.  You would take all the market.  (Yes, I know, handbrake use FFMPEG but there are some stuff I don't like about handbrake)

  -- Handbrake converts UTF-8 to ASS (sucks) (Would be nice to let an option to keep
  -- Some usefull information are not available with MEDIAINFO when encoding with Handbrake (by example, subtitles).
 

Thanx. Regards.

**Comment by RandomEngy** [comment]
You can mix the title cleanup with the custom file name format. It just changes what is inserted in for {source}.

As for your "W" issue, can you tell me what the exact source name is? I can't reproduce it.

About the batch subtitle/audio rename, it's on the backlog.

And again, nope, not going to change the encoding core. I still don't have the time. You need to ask HandBrake about that stuff.

**Comment by quebecman** [comment]
As for your "W" issue, can you tell me what the exact source name is? I can't reproduce it.

  Hmmm... strange, I can't reproduce it anymore. Well, nevermind.

Well, handbrake developpers are stict and never answers in the forum.  Like the subtitle stuff, I am shure it would be just as easy as saying DO NOT CONVERT subtitle to ASS and leave it as is (UTF-8 by example wich is commonly used since every).
There just in their tower and not listening.

Anyway, keep it up.

Thanx. Regards.

**Comment by RandomEngy** [comment]
There are sometimes technical limitations with different containers and formats, so something that seems easy can in practice be really difficult when you get into the details. Also open source software is often just people adding stuff that they find useful for themselves and not adding features for others. They might accept a pull request that adds what you need though!

I did find their aversion to batch processing is a bit odd, so I'm glad you agree with VidCoder's approach here and are finding it useful.

**Comment by quebecman** [comment]
Since this was fullfilled, you can go ahead and close this thread.

Thanx.
Regards.
