### ISSUE TITLE
Is there any way to apply a new folder FOLDER DESTINATION when in BATCH MODE?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#757]
-- I mean after that you already have drag and drop the folder, I can't find anyway to change the FOLDER DESTINATION.

 I do understand that you have this in the PICKER, but you always have to change it there... or there might be something that I am missing.

**Comment by RandomEngy** [comment]
After you've already queued all the files up? No, there isn't a way to do that. You need to re-queue them with the right picker settings.

**Comment by quebecman** [comment]
Ok thanx.  Would be nice to be able to OVERRIDE this PICKER for the destination folder.
 
 Example: I would like to encode Season 1 wich is in folder:

D:\season 1
D:\season 2
...

**Comment by RandomEngy** [comment]
Yes, you change the destination folder in the picker. You can leave the Picker window open beside the main window for easy access.

**Comment by quebecman** [comment]
You can go ahead and close this thread.  Would be nice to overwrite the OUTPUT directory in the BATCH QUEUE... but not really a assel, just a nice to have.
