### ISSUE TITLE
Editing a file already in the BATCH QUEUE issue or behavior?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#759]
I do not know if this is a bug but there is something really strange in the behavior about editing a file already in the batch queue.

  When you edit a file to change anything ... could be only the subtitles, when clicking on ADD TO QUEUE, it's asking if you would like to overwrite.  I click OVERWRITE but it's creating a DOUBLE ENTRY.

![image](https://user-images.githubusercontent.com/4656308/108135568-55106b00-7086-11eb-9d2e-f44e4b2619ab.png)

![image](https://user-images.githubusercontent.com/4656308/108131748-c567be00-707f-11eb-8557-1649878df429.png)

 Is this a bug?

Personally, when editing, I would put kind of an AUTO-SAVE and or a SAVED BUTTON when edition is completed, or maybe a third option would be literally remove from the BATCH QUEUE the file and re-inserted when click ADD TO QUEUE.

More likely, when adding twice the same folder, it duplicates everything.

**Comment by RandomEngy** [comment]
It's saying that you would be overwriting the output of another job on the queue if you added it. I assume you want to instead replace the old job in the queue with your new job?

**Comment by quebecman** [comment]
> I assume you want to instead replace the old job in the queue with your new job?

Answer: I am a bit confused.  Let me give you an example.  Let say I have to change an ENCODER SETTING and or just a SUBTITLE NAME, how can I add back to the QUEUE?

**Comment by RandomEngy** [comment]
I'll change the "Overwrite" option to a "Replace job" option that will remove the old job from the queue and add the new one. After all, it doesn't make sense to go through with the earlier encode if it's just going to be overwritten by the later one. It also makes it behave better when simultaneous encodes are enabled.

**Comment by quebecman** [comment]
Well lets give it a try and see what it does.


Envoyé de mon iPhone

Le 16 févr. 2021 à 21:32, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


I'll change the "Overwrite" option to a "Replace job" option that will remove the old job from the queue and add the new one. After all, it doesn't make sense to go through with the earlier encode if it's just going to be overwritten by the later one. It also makes it behave better when simultaneous encodes are enabled.

**Comment by RandomEngy** [comment]
Added the "Replace job" option in 6.26 Beta.
