### ISSUE TITLE
Worker.exe only throttling up to 33%

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#76]
I'm using v2.27.0.0.beta x64 and cannot get worker.exe to work very hard! Previously with the stable version and all the betas up to now it was running about 95 to 97%, so what has suddenly changed? I haven't had time to install older versions as a test, sorry.

It does not seem to matter where the throttle is set, it runs at 33%, even if set to, say, 20% or 100%. The CPU is sitting on about 65 degrees, but used to go up to over 80 degrees when the throttling was actually running up over 90%. Priority is at 'below normal', but changing to 'high' or 'low' makes no difference. External HDD's are usb3.0 and heaps fast enough to keep up. CPU idle process is at about 66 to 69%

Encodes are taking way too long, I need to get it working hard again. Using Win8.1 x64, i7, 16GB RAM.

**Comment by RandomEngy** [comment]
The video filters are a bit messed up in 2.27, and those are sometimes bottlenecks for encoding speed. I'll fix those and hopefully this goes away.

**Comment by iamjaydear** [comment]
OK, thanks. I do have hqdn3d preset on light, I'll disable it and let you know if it accelerates. Decomb / default has to stay on though. They're the only filters I use.

**Comment by iamjaydear** [comment]
Just confirming - disabling hqdn3d has maxed out the i7 :) Yay!

**Comment by RandomEngy** [comment]
Fixed in 2.28.
