### ISSUE TITLE
ОШИБКА

### ISSUE THREAD

**Issue by Arfei81** [RandomEngy/VidCoder#760]
[Новый текстовый документ.txt](https://github.com/RandomEngy/VidCoder/files/5992304/default.txt)

**Comment by RandomEngy** [comment]
Looks like it couldn't communicate with the worker process. When this happens do you see a VidCoderWorker.exe process still running? You can also disable the worker process in Global Options -> Process if it's giving you problems.

**Comment by Arfei81** [comment]
Я не понимаю !!программа что просто зависло!?

**Comment by RandomEngy** [comment]
Did you try disabling the worker process?

**Comment by Arfei81** [comment]
А что это значит ))

**Comment by Arfei81** [comment]
Вы имеете виду в общи
![TeamViewer_W6ObAVolo9](https://user-images.githubusercontent.com/79176053/108141782-7c177d00-7118-11eb-8466-a0afea731c62.png)
х настройках

**Comment by RandomEngy** [comment]
Yes.

**Comment by Arfei81** [comment]
Я сейчас установил портативную версию и отключил в ней рабочий процесс.Посмотрим как она себя поведёт.

**Comment by Arfei81** [comment]
Всё ОК.

**Comment by Arfei81** [comment]
Почему в калибровка убираем черные полосы с верху с низу в конечном файле они всё-равно остаются !
![explorer_QftNdJguIV](https://user-images.githubusercontent.com/79176053/169486728-f4664c15-33e7-4e0c-8767-bff7ee969ffe.png)
?

**Comment by RandomEngy** [comment]
It looks like those settings should be cropping. Can you provide an encode log?

**Comment by Arfei81** [comment]
Нет не могу ,это просто пример.

**Comment by RandomEngy** [comment]
Anyway, cropping does remove the black bars. You might still see them if you are playing on a monitor with a different aspect ratio.

**Comment by Arfei81** [comment]
То-есть монитор должен быть минимум 1920х1080.
А если его разрешение будет больше чем 1920х1080 ,чёрные полосы появятся !?

**Comment by RandomEngy** [comment]
If the aspect ratio of your monitor is different than the aspect ratio of the video, you'll get black bars, even if there are no black bars in the actual video itself.
