### ISSUE TITLE
BATCH Queue duplicates behavior?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#763]
As shown below, I was just curious if adding many times the same name files was a normal behavior?  The only explanation I can find was if you want muliple different encoding settings for the same file.

![image](https://user-images.githubusercontent.com/4656308/108246400-63f72c00-711f-11eb-8c65-c1125caf5c77.png)

Why doesn't rename the file automatically?

Would there be nice to get a POPUP message to ask to OVERWRITE?  (something such as:  A file with the same name already exist. Would you like to OVERWRITE or AUTO-RENAME.

**Comment by RandomEngy** [comment]
As I posted earlier I'm looking into fixing this behavior.

**Comment by quebecman** [comment]
I mean when you add for the first time a FILE, i think it's good to keep it this way.  I explain:

  Let say you copy over a 1080p, you want to create 720p and a SD file, it's good since you have the same source.  

The thing I was writing is that when you edit the file and try to put it back to the queue are 2 different thing.

**Comment by RandomEngy** [comment]
Yeah I know, and I've got a plan to fix this behavior.

**Comment by RandomEngy** [comment]
Added the "Replace job" option in 6.26 Beta.
