### ISSUE TITLE
Enhancement: Real-time behavior for CPU Throttling, PROCESS PRIORITY and Maximum simultaneous job.. behavior problem

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#764]
I do not know if this is possible but it would be neet when modifying the GLOBAL OPTION for PROCESS PRIORITY and CPU throttling , that can apply modification in realtime.

 In other terms, if lowering the PRIORITY during a job and or modifying CPU throttle, it would do it realtime. 

This is really useful if using your computer and you need more extra power.  Unfortunately, I do not have enough money to buy few dedicated computers to render video.

Keep it up, light is at the end of the tunnel.

Thanx. Regards.

**Comment by quebecman** [comment]
I do not know if this is controlled by HANDBRAKE and or VIDCODER development.

**Comment by RandomEngy** [comment]
This would be a VidCoder feature. I'll look into adding this.

**Comment by quebecman** [comment]
I just wanted to make some clarification here:

  -- CPU THROTTLING and Worker process priority doesn't seems to be working for now.  Even when one of the job completed, it doesn't restart with the new settings

I would like to clarify the simultaneous job control;
  
  -- This works when going up by one job. So by example, if you where at 1 job encoding and put 2, you need to wait for the job to end before it will create a NEW ONE.  This is in my personnal opinion not good.  Should be in real time.

  But, if you go from let say 2 to 1 encode, I think it should wait the end of the job but maybe with a displayed message telling the user.

Thanx. Regards.

**Comment by RandomEngy** [comment]
CPU throttling and process priority changes apply to already-encoding jobs in 6.29 Beta.
