### ISSUE TITLE
Suggestion for Batch Queue: In the PICKER, do not import files under x megs in Picker Filter

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#765]
This would be an awesome nice to have to not import VIDEO FILES under x AMOUNT OF MEGS. 
 
 -- This would be an excellent nice to have when you have the presence of SAMPLES wich gets imported in batch queue.

Thanx. Regards.

**Comment by RandomEngy** [comment]
Added feature in 6.31 Beta.
