### ISSUE TITLE
Behavior and or bug with FOREIGN LANGAGE in the PICKER

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#766]
Please, can you add a TICK BOX besides the ADD foreign langage to not put in DEFAULT?

![image](https://user-images.githubusercontent.com/4656308/108735514-a98c6e00-74fe-11eb-84f5-b68ec2608114.png)

Please note to that when adding a new video with the PICKER, there is 2 default tracks.  Once you removed the FOREIGN manually, you can't put it back since only one can be selected.

![image](https://user-images.githubusercontent.com/4656308/108735200-40a4f600-74fe-11eb-87d1-f9655c85f06c.png)

 I am not shure if this is a normal behavior.

Thanx. Regards.

**Comment by RandomEngy** [comment]
Yeah this shouldn't be marked as default. I'll change this.

**Comment by quebecman** [comment]
Glad that I was able to help just little in your project.
________________________________

**Comment by RandomEngy** [comment]
Fixed in 6.26 Beta.
