### ISSUE TITLE
Bug Report: Default doesn't apply on subtitle when selecting BY INDEX in the PICKER.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#770]
![image](https://user-images.githubusercontent.com/4656308/110040624-1e3a8600-7d11-11eb-9440-63481a8c577c.png)

  Default doesn't apply on subtitle when selecting BY INDEX in the PICKER.

**Comment by quebecman** [comment]
Sorry my bad, I just noticed this is already in the picker, called by INDEX.  You can go ahead and close the THREAD.

**Comment by quebecman** [comment]
Hmmmm... Ok, after lots of testing, there is some bad behavior with the INDEX ID.  In other terms, when selecting BY INDEX, there is 1 thing that should be modified:

  -- Remove the DEFAULT option and or
  -- Remove the DEFAULT box.

Personnally, I would remove the DEFAULT BOX since it's get confusing but the DEFAULT BOX is easier.

Thanx. Regards.

**Comment by RandomEngy** [comment]
The "Default" checkbox is now hidden when using "by index" subtitle selection mode in v6.26 Beta.
