### ISSUE TITLE
Bug report:  When selecting system tray, VIDCODER duplicates itself

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#771]
When double clicking on VIDcoder, it creates a new instance instead of using the same one.

![image](https://user-images.githubusercontent.com/4656308/109980974-77cd9100-7cce-11eb-8719-31d76d8a808f.png)

 Sometimes, I can up to 1, 2, 3, 4, 5  or even 6 of theses opened up.

**Comment by RandomEngy** [comment]
This is fixed in 6.26 Beta. Launching again will use an existing instance of VidCoder, and restore it if there is one already running in the tray.
