### ISSUE TITLE
Suggestion for PICKER to APPLY to the QUEUE

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#772]
Same as the AUDIO ENCODING, would be nice to get the Apply to Queue when changing something in the PICKER instead of removing files from the QUEUE and re-adding them with the new settings.

![image](https://user-images.githubusercontent.com/4656308/109876762-24146680-7c40-11eb-94d8-5e9b6524a3de.png)

**Comment by RandomEngy** [comment]
There might be some weird corner cases with this. Say you've loaded in a disc and enqueued multiple titles. Does it remove all of them and re-run the picker to select the titles? Will it throw away manual selections people have made to change selected subtitles or rename the output file? Does it throw away custom chapter names? Does it throw away manually added .srt subtitles?

**Comment by quebecman** [comment]
Let say something like this.  When selected in BATCH QUEUE, there would be an option to APPLY NEW PICKER VALUES.

[cid:4b9c5da7-a54f-43fc-a867-1ef0e040f08f]
________________________________

**Comment by RandomEngy** [comment]
Yeah but you might have manual edits conflicting with the changes in the picker. Properly tracking all the state to warn the users when this will happen would be rather difficult, since there are so many settings.

If you wanted to give it a shot, go for it, but I don't think I'll be doing this any time soon.

**Comment by quebecman** [comment]
Ok, thanx. Nevermind then.  Will just remove and re-add files.

________________________________

**Comment by quebecman** [comment]
You can go ahead and close this thread.

Thanx.
Regards.
