### ISSUE TITLE
Suggestion: Chapter generator

### ISSUE THREAD

**Issue by MDA999** [RandomEngy/VidCoder#774]
I would love to see implemented, that you can browse the video frame by frame and simply select chapter marks to be created with the encode. I do not find any software that can do this for mkv.

**Comment by RandomEngy** [comment]
That would be possible. I assume you are looking to do this with a file input? Couldn't do it with a disc input, but then again those usually have chapters already.

**Comment by MDA999** [comment]
No, file input is available with MKVtoolnix. But there is no tool to select the exact frame directly, hit "chapter" and a chaptermark gets set, so that your encoded video will have now a chapter where you would've put it.

That's pretty useful when reencoding streams without preset chapters and you want a mark right after the intro, one in the middle and one at the end of an episode.

**Comment by RandomEngy** [comment]
I guess what I was checking was that it's a file that you're taking as input and encoding with VidCoder, right? If it's a DVD or Blu-ray there are no easy ways to have the source video show up inside VidCoder.

**Comment by MDA999** [comment]
Again - NO! I do NOT ask for a txt import of chapter marks.

I want to import a videofile into VidCoder for reencoding - but 99,9% of the videos I'm reencoding don't have chapter marks, but I WANT them to have some. And the fastest way would be to get VidCoder to search inside these vids with VidCoder to find the perfect place for a chapter mark, hit a button and get the encoded video to have a chapter mark exactly there.

I hate creating txt files for chapter marks! That's taking up so much time and here is my suggestion: Make it easy to mark chapters inside VidCoder by being able to browse the video input file for the perfect spot for a chapter mark, simply hit a button and get that chapter mark there with the reencoded video.

Forget DVDs, forget BDs. The majority of videos I'm reencoding doesn't come from these and have no chapter marks, but need them.

**Comment by RandomEngy** [comment]
Yeah I understood what you were asking. I was trying to clarify if you were taking a *video file* or a *DVD/Blu-ray* as input. It sounds like a file.

And please, thank me after it's done rather than assuming I'll do it.

It's a good idea; I'll put it on the backlog.

**Comment by MDA999** [comment]
Ah, I didn't understand that as english is not my native language. Still - Thank you.

Another thing - if I put in a file that already has chapter marks, I get the chapter marks displayed and can change the names of the chapters but not the timecode itself - if that could be done, it would be also acceptable. (Noticed that if putting in a video without chapter marks, I don't get this menu at all, which is sad.)

**Comment by RandomEngy** [comment]
I took a closer look at this tonight and it appears that the HandBrake API does not support setting chapters with arbitrary timecodes. You can only rename existing chapters. You could ask the HandBrake team to add this capability. If they do, I would be able to make a chapter editor UI.

**Comment by MDA999** [comment]
Thanks, I contacted them and made that suggestion.

**Comment by MDA999** [comment]
Sadly...

"Handbrake does not implement a chapter track editor, and probably never will (out of scope for the project)."

**Comment by RandomEngy** [comment]
Ahh, too bad.
