### ISSUE TITLE
Question: Does VIDCoder gets a NEW BUILD everytime HB release one?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#776]

**Comment by quebecman** [comment]
Well, was just wondering on wich NIGHTLY VERSION does VIDCODER runs on?

**Comment by RandomEngy** [comment]
No, VidCoder just picks the latest nightly one some of its Beta releases. The idea is that I want to make sure VidCoder still works after picking up a nightly build and pushing it to Beta users. And to reduce the number of automatic updates pushed to Beta users.

You can check which HandBrake nightly VidCoder is using in Help -> About VidCoder
