### ISSUE TITLE
Suggestion for exporting:  Unable to export in BATCH from the GUi all the Encode settings and PICKER

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#779]
Behavior description:

  - We can't export in BATCH from the GUi all the Encode settings. Only one by one and this gets really long when you have lots. 
  - More likely, i didn't found any way to export at all the PICKER settings.  I have to recreate them manually everytime.

This is not convenient everytime you download a new portable version and can't re-import PICKER and or ENCODING settings.

Thanx. Regards.

**Comment by RandomEngy** [comment]
If you have your settings in %appdata%\VidCoder-Beta\VidCoder.sqlite (Like where the installer puts them), the portable version will use that location. In that case you don't need to worry about importing or exporting settings. Or you can copy the VidCoder.sqlite file to wherever you need it.

**Comment by RandomEngy** [comment]
Yes. It writes it there if it doesn't find one in %appdata%. That's by design.

**Comment by quebecman** [comment]
You can go ahead if you want to close this thread.  Up to you if you want to add something to EXPORT all settings, that includes ENCODING SETTINGS and PICKER.

Thanx. Regards.
