### ISSUE TITLE
MKV problems

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#78]
Got another more major problem... MKVs are basically unplayable now. No chapter marks being stored and if you try to search in say, PotPlayer or VLC they just crash :(  :(  :(

I've checked similar files done only a week ago in the previous beta using the same Presets and Pickers and they are fine. Everything's really screwed up in 2.27!

**Comment by iamjaydear** [comment]
So I thought I'd just go back to 2.26... worst idea I've had for a long time! As you would know, I now have no presets and no pickers. I do have a file called VidCoder-v31.sqlite which I can read in a text editor. Can I get my stuff back out of that? I realise that betas are betas and there might be surprises, but... :-1:

**Comment by RandomEngy** [comment]
I'm working on it. The filter change is a rather large one, but I'll get everything out correctly. If you want a quick and dirty workaround you can open the .sqlite file in an editor like https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/ , then look in the settings table and change the version to 30. Then it will open with 2.26.

I'm also planning on adding a system that will back up your old .sqlite files before upgrading them so you have the chance to go back.

**Comment by iamjaydear** [comment]
As Ford Prefect would say, don't panic. Thanks for replying so quickly
(it's 3:30am here) and thanks for your coding effort. I'll do as you
suggested.

> On 21/04/2016 3:31:49 AM, RandomEngy (notifications@github.com) wrote:
> > I'm working on it. The filter change is a rather large one, but I'll
get everything out correctly. If you want a quick and dirty workaround
you can open the .sqlite file in an editor like
https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/ , then
look in the settings table and change the version to 30. Then it will
open with 2.26.
>
> I'm also planning on adding a system that will back up your old
.sqlite files before upgrading them so you have the chance to go back.

**Comment by RandomEngy** [comment]
I think this is fixed in 2.28. MKVs seem to play fine and have correct chapter markers.
