### ISSUE TITLE
Bug report v6.27:  Everytime you select a langage in the PICKER for the Audio, the application crashes.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#780]
![image](https://user-images.githubusercontent.com/4656308/110358866-d23a5a80-800a-11eb-9436-7481a2aba66c.png)

 This happens everytime.

**Comment by RandomEngy** [comment]
Thanks for the report. This should be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 6.28 Beta.
