### ISSUE TITLE
Suggestion for BATCH QUEUE:  To be able to stop active jobs in QUEUE before removing from the BATCH QUEUE.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#782]

**Comment by quebecman** [comment]
Just by right clicking the job to be able to stop some job from the BATCH QUEUE

**Comment by RandomEngy** [comment]
Are you talking about when you have multiple simultaneous encodes happening? You want to stop just one of them?

**Comment by quebecman** [comment]
Yes. To stop only one of thé job in thé batch queue instead of all thé batch.

Envoyé de mon iPhone

Le 12 mars 2021 à 22:48, David Rickard ***@***.******@***.***>> a écrit :


Are you talking about when you have multiple simultaneous encodes happening? You want to stop just one of them?

**Comment by RandomEngy** [comment]
Added this feature in 6.30 Beta.
