### ISSUE TITLE
Is this a BUG or NOT?  What means RESTORED FROM QUEUE

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#786]
Hello, 

 This thing drives me insane and I can't reprocuse it but I was wondering if this can be explained.  It drives me nuts because it changes my ENCODING DETAILS for some obscur reason.

If changes to below without any notice:

![image](https://user-images.githubusercontent.com/4656308/110995964-2e71e700-8349-11eb-94e0-77a540ef24d1.png)

Note that my ENCODER PRESETS are selected in the PICKER.

Thanx. Regards

**Comment by RandomEngy** [comment]
If you queue up a job, it could have any settings on it. When you restore, you might have changes that encoding preset. You're given a temporary "restored from queue" preset that goes away if you switch presets. That's to prevent unintentionally editing an encoding preset just by restoring a queue item.

**Comment by quebecman** [comment]
Sorry, but I am not following you and totally lost.  If preset is selected, why this thing happen.  It happens many time that I have encode with bad settings.  So I always have to make shure this is not selected.

**Comment by RandomEngy** [comment]
If you edit an queued job, it will create this temporary preset. This is is needed to avoid unintentionally altering an existing preset.

**Comment by quebecman** [comment]
A ok, I get it now.  Ouf, coffee time.

**Comment by quebecman** [comment]
Can be closed.  

Thanx. Regards.

**Comment by quebecman** [comment]
Code 18. Personnal knowledge
