### ISSUE TITLE
For my knowledge. With same settings, HUGE DIFFERENCE in the FPS. Can be up to 70% difference.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#787]
I have been using handbrake since always and I was always curious about the following:

  -- Is there any explanation why sometimes, when using the SAME ENCODING settings, sometimes I do get 255 fps with a CPU encoding and sometimes I get only 160 fps.

I do understand this probably depends on a lot of factors such as the quality of  the source, how grainy it is, audio, CPU temperature and other stuff like this, but why so much difference.  

I don't get it.  

Thanx. Regards

**Comment by RandomEngy** [comment]
Source complexity can change encoding speed. I've always noticed that encoding speeds up when it's reached the credits, because those are much less visually complex and are slow-moving.

**Comment by quebecman** [comment]
You can go ahead and close this thread.  Cleanup purposes.

**Comment by quebecman** [comment]
Code 18.  Personnal knowledge.
