### ISSUE TITLE
Bug Report v6.28:  Everytime you change the AUDIO encoding setting, the applications crashes

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#788]
Way to reproduce.  Change your audio, SAVE, and change to a new audio bitrate.  Will crash everytime.

![image](https://user-images.githubusercontent.com/4656308/111051913-a82ad300-8424-11eb-8180-c5b9c413d8c5.png)

**Comment by LittleDudeNZ** [comment]
Can also confirm this bug on my system.

**Comment by RandomEngy** [comment]
Thanks for the report. Will be fixed in the next Beta. In the meantime you can workaround this by making sure to edit this or the sample rate only when the preset has unsaved changes.

**Comment by quebecman** [comment]
Hmmmm... no worries but sometimes it happens even when not saving.

**Comment by RandomEngy** [comment]
Fixed in 6.29 Beta.
