### ISSUE TITLE
Suggestion BATCH queue:  Add a column with number for moving around files

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#789]
It would be nice to be able to move in the BATCH QUEUE for piority level purpose by example with numbers that are attributed to batch queue files.

  By example, I would like to move the file 63 to place number 4.

I do understand you can move with the mouse, but when you are at position 100, this takes a lot of time to move it to the begining.

Thanx. Regards.

**Comment by RandomEngy** [comment]
Have you tried right click -> Move to top?
I think if I implemented this it would be right click -> Move to position and allow you to type in a certain number. I think I would also need to add a number column to tell what slots the jobs are in. And I'd have to update them all whenever the queue was updated.

**Comment by quebecman** [comment]
This sounds silly but I have never noticed the Move to TOP was already there.  LOL.  For myself, it fits my needs.  I just want to put them in priority.

  -- If you want to implement this later, it maybe in your very low priority in your development.  This is your call shot.

BTW, nice going with the Number of Encode retries.

Thanx. Regards.

Thanx.
Regards.

**Comment by quebecman** [comment]
A bof request.

**Comment by quebecman** [comment]
Moved to Requested feature.
