### ISSUE TITLE
Crashes When Opening AVI File From Sony Vegas

### ISSUE THREAD

**Issue by UnitedDugout27** [RandomEngy/VidCoder#791]
I have noticed that anything past version 6.16 will crash when trying to open a "AVI (video for windows) NTSC DV" file that was created by Sony Vegas. 

Vidcoder will hang on the "Scanning" dialog box and a force close from task manager is the only way to close it. 

![image](https://user-images.githubusercontent.com/77062086/111158310-42e2f900-856e-11eb-93a0-45a3bb138f01.png)

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)
