### ISSUE TITLE
Weird behavior when changing the maximum simultaneous jobs

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#794]
I was just curious of why when you change the MAXIMUM SIMULTANEOUS JOBS from 1 to 2 to 3 or even higher it doesn't it apply in realtime?  In fact, you have to wait for one of the job to be completed.  This can take quite some time.

![image](https://user-images.githubusercontent.com/4656308/111675241-4aff9a80-87f3-11eb-96d1-0d27d69a591f.png)

I do understand if you change it from let say 3 jobs to 2 or to 1, it has to wait for the job to complete...

So in my part, the behavior is wrong here.

It's not a big of a assel... but time in encoding is everything.

Thanx.
Regards.

**Comment by RandomEngy** [comment]
It will now immediately start new jobs on changing the setting in 6.30 Beta.
