### ISSUE TITLE
Is hardware encode (GPU encoding) on the TO DO LIST?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#795]
Just curiuous since Hanbrake Nightly version has the GPU encoding.

Thanx.
Regards.

**Comment by RandomEngy** [comment]
VidCoder has had GPU encoding for quite a while now. Should show up in the video encoder list when your system supports it.

**Comment by quebecman** [comment]
Wow... ok, sorry, my bad.  Handbrake had this under the GLOBAL OPTION...  Didn't knew this was part of VIDCODER if your system was supporting it.

Thanx. Regards.

**Comment by quebecman** [comment]
Code 18.

**Comment by RandomEngy** [comment]
I saw that they had these options, but wasn't sure of the actual use of offering an option to disable them, so I haven't added the options to VidCoder. They're just always enabled.
