### ISSUE TITLE
Watch Folder

### ISSUE THREAD

**Issue by bdlegend** [RandomEngy/VidCoder#798]
Is there have any watch folder option where the file add in that folder vidcoder automatically starts encode.

**Comment by RandomEngy** [comment]
VidCoder doesn't have that feature yet.

**Comment by quebecman** [comment]
Well... A watch folder + picker for different settings.

**Comment by bdlegend** [comment]
> VidCoder doesn't have that feature yet.

Is it possible to add this feature ?

**Comment by RandomEngy** [comment]
Yeah. It's been on the backlog for a while. It's just an expensive feature and I've had many other things to do.

**Comment by RandomEngy** [comment]
Added a folder watcher in 8.4 Beta.
