### ISSUE TITLE
Behavior: Is there anyway to Clear log?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#807]
I have tons of log file. Is there anyway to clear them?  Clear finished doesn't work

![image](https://user-images.githubusercontent.com/4656308/112738520-eef6ed80-8f39-11eb-9801-625d06044bb9.png)

I am running version 6.30 beta.

**Comment by RandomEngy** [comment]
Run 6.31 Beta. Clear finished will work.
