### ISSUE TITLE
Beta 2.28 does not store X265 QSV profiles correctly. It refers to X264.

### ISSUE THREAD

**Issue by ZaphodX77** [RandomEngy/VidCoder#81]
From an export of this version's preset, Please see at the bottom where X264 is referred to in this X265 preset. Beta 2.28 still does not include an input box for QSV X265 preset information like QSV X264, but when it does, this will become an issue. And of course, being meddlesome, I may try to manually write in variables into the preset itself, and I don't know if they will take. Handbrake does have a QSV X265 variable input area. Thank you. Love your program. Now testing alternates to FAAC available in Vidcoder.
{
  "Version": 19,
  "Preset": {
    "Name": "X265 Q28",
    "IsBuiltIn": false,
    "IsModified": false,
    "IsQueue": false,
    "EncodingProfile": {
      "ContainerName": "av_mkv",
      "PreferredExtension": "Mp4",
      "IncludeChapterMarkers": false,
      "LargeFile": false,
      "Optimize": false,
      "IPod5GSupport": false,
      "Width": 0,
      "Height": 0,
      "MaxWidth": 0,
      "MaxHeight": 0,
      "CappedWidth": 0,
      "CappedHeight": 0,
      "ScaleMethod": "Lanczos",
      "CroppingType": "Automatic",
      "Cropping": {
        "Top": 0,
        "Bottom": 0,
        "Left": 0,
        "Right": 40
      },
      "Anamorphic": "Loose",
      "UseDisplayWidth": false,
      "DisplayWidth": 0,
      "KeepDisplayAspect": true,
      "PixelAspectX": 0,
      "PixelAspectY": 0,
      "Modulus": 2,
      "Rotation": "None",
      "FlipHorizontal": false,
      "FlipVertical": false,
      "Detelecine": "off",
      "CustomDetelecine": null,
      "DeinterlaceType": "Off",
      "DeinterlacePreset": null,
      "CustomDeinterlace": null,
      "CombDetect": null,
      "CustomCombDetect": null,
      "DenoiseType": "Off",
      "DenoisePreset": null,
      "DenoiseTune": null,
      "CustomDenoise": "",
      "Deblock": 0,
      "Grayscale": false,
      "UseAdvancedTab": false,
      "VideoEncoder": "qsv_h265",
      "VideoOptions": "",
      "VideoProfile": "main",
      "VideoPreset": null,
      "VideoLevel": "4.0",
      "VideoTunes": [],
      "QsvDecode": false,
      "VideoEncodeRateType": "ConstantQuality",
      "Quality": 28.0,
      "TargetSize": 0,
      "VideoBitrate": 0,
      "TwoPass": false,
      "TurboFirstPass": false,
      "Framerate": 0.0,
      "ConstantFramerate": true,
      "AudioEncodings": [
        {
          "InputNumber": 0,
          "Encoder": "av_aac",
          "PassthroughIfPossible": false,
          "EncodeRateType": "Bitrate",
          "Bitrate": 64,
          "Quality": 0.0,
          "Compression": -1.0,
          "Mixdown": "dpl2",
          "SampleRate": null,
          "SampleRateRaw": 0,
          "Gain": 2,
          "Drc": 0.0,
          "Name": null
        }
      ],
      "AudioCopyMask": [],
      "AudioEncoderFallback": null,
      "OutputFormat": "Mp4",
      "X264Options": null,
      "X264Tune": null,
      "X264Tunes": [],
      "X264Profile": null,
      "X264Preset": null,
      "QsvPreset": null,
      "H264Level": null,
      "CustomCropping": false,
      "PeakFramerate": false,
      "Deinterlace": "Off",
      "UseCustomDenoise": false,
      "Decomb": "Off",
      "CustomDecomb": null,
      "Denoise": null
    }
  }
}

**Comment by RandomEngy** [comment]
Hmm. Will have to look into why obsolete fields are getting put into the JSON. VidCoder ignores the "X264" fields and uses the VideoPreset, VideoTunes, etc fields instead. Will also take a look at the QSV x265 options field when I can get a computer that supports it.

**Comment by RandomEngy** [comment]
In 2.29 I've fixed the preset serialization so the obsolete properties no longer get serialized.
