### ISSUE TITLE
10bit pipeline and HDR metadata

### ISSUE THREAD

**Issue by eflymann** [RandomEngy/VidCoder#813]
Hi,

in handbrake version HandBrake-20210322-126013c87-x86_64-Win_GUI (night release) there was information that it keeps now hdr metedata and has 10bit pipeline, what about vidcoder? - really do not like HB gui

Thank you,
eF

**Comment by RandomEngy** [comment]
VidCoder 6.31 Beta uses HandBrake 20210324-222202. It should have that change.

**Comment by eflymann** [comment]
I can see in HB option: 
![image](https://user-images.githubusercontent.com/81652576/113133484-00811380-9220-11eb-8407-cf6a2dbbc4e1.png)
there is nothing like this in VidCod.

**Comment by RandomEngy** [comment]
Added option to keep video metadata in 6.32 Beta. Though HandBrake doesn't pass through HDR metadata.
