### ISSUE TITLE
Pixilated previews

### ISSUE THREAD

**Issue by ThomasCSR** [RandomEngy/VidCoder#814]
Why does the preview pictures pixilate? 
![Image2](https://user-images.githubusercontent.com/20925593/113509732-802c1c80-9557-11eb-83f6-9aff15d3fb69.jpg)

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)

**Comment by ThomasCSR** [comment]
You were right. Dame problem in HandBrake when source is a .ts file. No problems with mp4 source.
Thanks for your answar
