### ISSUE TITLE
Finished Variables

### ISSUE THREAD

**Issue by Jbgamer676** [RandomEngy/VidCoder#819]
First off, As a video coder, it works great...
Unfortunately though I've found a bug in the software....
In the Post-Encoding section, If you add a single video, the variables are passed no problem... But if you use the Enqueue folder or Enqueue multiple files option, the variables don't get passed at all.

**Comment by RandomEngy** [comment]
Did you try surrounding the {file} in quotes?

"{file}"

Works for me when I do that.

**Comment by Jbgamer676** [comment]
Yes... I was using "{source}" and if I add the files to the queue
individuality, it works fine... But if you use either of the enque options
nothing gets passed...

What is the difference between using "{source}" or "{file}"?

**Comment by RandomEngy** [comment]
Ahh I see. This is just a problem with the {source} variable when using batch queuing. I've got a fix for this; will be in the next Beta release.

**Comment by quebecman** [comment]
Please, would it be possible to only PICK a script with a browse button.  I don't get that thing with "{source}" or "{file}".

Thanx.
Regards.

**Comment by RandomEngy** [comment]
Different batch files are launched in different ways. It should always be possible to launch a script this way. For example to launch a batch file, run `cmd.exe` with parameters `/c "c:\myscript.bat"` then whatever parameters you want to pass to the script. If you'd like to add native support for different script files (batch, powershell, python, whatever), you're welcome to submit a pull request.

**Comment by RandomEngy** [comment]
Fixed in 6.32 Beta.
