### ISSUE TITLE
BUG Report 6.31: Audio in PICKER doesn't work

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#820]
Hello,

  Please note that I have tried the INDEX and the LANGUAGE option under the AUDIO in the PICKER and nothing works.  

In other terms, if you enter in the index a 2 instead of a 1, it won't pick 2 but still keep 1.  
Under the language, if you pick all language, it won't check both... only 1.

Thanx.
Regards

**Comment by RandomEngy** [comment]
Both "by index" and "all tracks for language" work for me when loading new sources. Can you post a screenshot of the picker settings and the resulting selected tracks?

**Comment by quebecman** [comment]
Unable to reproduce.
