### ISSUE TITLE
VIDCoder 6.3.1 Weird Behavior: Add a file twice creates a duplicate entry in the Queue 

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#823]
Hello,

 I found this to be a weird behavior but when a file is already present in the QUEUE and you add up the same video file, it just creates a duplicates.  Would it be possible to POP a message if you want to REPLACE and or just DON'T ADD since the file is already in the Queue?

Maybe in the Picker and or Global Option not to create duplicate files.

Thanx.
Regards.

**Comment by RandomEngy** [comment]
Yes, I've already added this functionality. It replaces the old item in the queue and the dialog has been updated to Replace/Rename/Cancel.
