### ISSUE TITLE
[ask] how to render with the same aspect ratio with origin files?

### ISSUE THREAD

**Issue by Dhanamerdeka** [RandomEngy/VidCoder#827]
how to do that?
sorry because i dumb...
but i need to know how to render video with the same size as the original video?
because i just want to convert H264 to H265

because not all of my video use default aspect ratio from setting
thanks...
sorry for my english

**Comment by RandomEngy** [comment]
The aspect ratio is preserved automatically when you choose sizing mode Automatic. If you want to keep the resolution the same as the input video, use these settings:

![image](https://user-images.githubusercontent.com/9450861/116018186-603bc600-a5f6-11eb-8b79-95b31f343951.png)
