### ISSUE TITLE
VIDCoder 6.31:  Bugfix Overwrite and or AutoRename duplicate entry with Picker.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#829]
Hello,

  My previous ticket was closed saying that this was fix.  When you add a second time the same file, you should have a message like below.

Steps to reproduce:

  -- Add a file in the queue;
  -- Add a second one with the same name, it will duplicate as shown in the image below.  There is no message of any sort.

![2021-04-25 22_57_09-VidCoder Beta - 3 2%](https://user-images.githubusercontent.com/4656308/116023178-a35b6080-a619-11eb-921b-204a705e6c4b.png)

Note:  If you have a JOB in the QUEUE and you modify it and re-add it to the queue, yes, you will have a popup like below but not before.

![image](https://user-images.githubusercontent.com/4656308/116023605-72c7f680-a61a-11eb-9998-082a11413ef0.png)

In other terms, I think there should be a BUTTON to CANCEL or AUTO-RENAME the add file.  If you don't pay attention, it will re-encode the file twice.

Thanx.
Regards.

**Comment by RandomEngy** [comment]
In your Picker, what do you have for "When file already exists?"

**Comment by quebecman** [comment]
I know this is there but OVERWRITE and or AUTOMATICALLY RENAME does the same thing.

![image](https://user-images.githubusercontent.com/4656308/116026800-5e3b2c80-a621-11eb-9ce7-878fced2f05a.png)

**Comment by RandomEngy** [comment]
Okay. I had implemented it correctly for single encodes but there was an issue with it applying for batch encodes. Should be fixed in 6.32 Beta.

**Comment by quebecman** [comment]
Exactly, thanx.  I was having problems to reproce it but I have just discovered it that it was in the batch queue.

Regards.

________________________________
