### ISSUE TITLE
add reset button in custom cropping section

### ISSUE THREAD

**Issue by bjmi** [RandomEngy/VidCoder#83]
I find it useful if I could quickly reset all four custom cropping values back to zero with one click. If in Encoding Settings > Picture > Cropping the option "Custom" is selected then the new "reset" button is enabled and I could change all values to 0.

**Comment by RandomEngy** [comment]
Have you tried clicking on "None" before clicking on "Custom"?

**Comment by bjmi** [comment]
Yeah, starting from "Custom" then selecting "None" and "Custom" again do the trick.
