### ISSUE TITLE
a wish with subtitles

### ISSUE THREAD

**Issue by pketola** [RandomEngy/VidCoder#831]
i have movies with separate subtitles with the same name: ex. movie.mkv and subtitle to that movie.srt. I would like to have automation to burn in the subtitles without a many step mouse clicking exercise. Particularly if there are multiple files with subtitles, there is big possibility to select wrong subtitle tto movie.

**Comment by RandomEngy** [comment]
I added this feature in 6.34 Beta. Go to the Picker window to turn it on.

**Comment by pketola** [comment]
it does not work. encoding crashes even without subtitles.
ERROR: Operation 'Ping' failed. Worker process exited unexpectedly with code -1073741819. This may be due to a HandBrake engine crash.
ERROR: Encode failed with code ErrorHandBrakeProcessCrashed

**Comment by RandomEngy** [comment]
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

Equivalent versions:
VidCoder Stable ↔ [HandBrake Stable](https://handbrake.fr/downloads.php)
VidCoder Beta ↔ [HandBrake Nightly](https://handbrake.fr/nightly.php)
