### ISSUE TITLE
Minor Bugfix v6.3.3:  The POPUP occurs everytime for BATCH QUEUE and SINGLE

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#832]
Hello,
 
 Please note if ASK is selected for SINGLE file, it will apply the same thing to the BATCH QUEUE.  In other terms, there will be a POPUP in the BATCH QUEUE.

This is minor,  there is an easy workaround.  Just select Overwrite in the SINGLE and it will bypas this.

Thanx.
Regards.

**Comment by quebecman** [comment]
Personally, I don't really understand the purpose of keeping a POPUP if already selected in the PICKER.

**Comment by RandomEngy** [comment]
It only applies the popup if you are adding a single item. That's not a batch operation. If you don't want the popup, you can select a different setting for the "single" mode.

**Comment by quebecman** [comment]
Sorry to say this but this is untrue.  Give it a try. I just drag and drop in the BATCH QUEUE and I have the popup even if Overwrite is selected.

This is what I am saying.  There is a small bug there.  The single applies to the batch.

https://img.xthor.tk/2021/05/3b8c2e_7PfJxomv5bymy2mjy2mgqtyjhjzi00ogy3lwfjmwutmgqxzmuyodkzzmvkxkeyxkfqcgdeqxvynjg4nzayota._v1_ux182_cr00182268_al_.jpg

**Comment by RandomEngy** [comment]
How many items did you add with the drag/drop? If it's just one item, it uses the "single item" setting by design.

**Comment by quebecman** [comment]
Ok, thanx... This is exactly what I was doing.  Only one file, even if dropped in the BACH QUEUE was considered as a singe file.

Thanx. 
Regards.

**Comment by quebecman** [comment]
Ok, thanx... This is exactly what I was doing.  Only one file, even if dropped in the BACH QUEUE was considered as a singe file.

Thanx. 
Regards.
