### ISSUE TITLE
A small renaming bug

### ISSUE THREAD

**Issue by h45251880** [RandomEngy/VidCoder#836]
For example
The file name is x_x_x
but coder Rename to x x x or x X x to output

**Comment by RandomEngy** [comment]
Can you be more precise about what the steps to reproduce are, what you expected to happen and what you saw happen?

**Comment by h45251880** [comment]
![Snipaste_2021-05-25_22-48-09](https://user-images.githubusercontent.com/34127128/119518726-5fd84b80-bdab-11eb-8e16-18e1c15fd341.png)

**Comment by h45251880** [comment]
> Can you be more precise about what the steps to reproduce are, what you expected to happen and what you saw happen?

it can't fully copy the source file name

**Comment by RandomEngy** [comment]
Then make sure your settings in the Picker look like this:

![image](https://user-images.githubusercontent.com/9450861/119528928-798b7b80-bd36-11eb-8210-645512a6bb81.png)

**Comment by h45251880** [comment]
> Then make sure your settings in the Picker look like this:
> 
> ![image](https://user-images.githubusercontent.com/9450861/119528928-798b7b80-bd36-11eb-8210-645512a6bb81.png)

Oops its my fault, sorry to disturb you
