### ISSUE TITLE
Suggestion: Add Forced Flag on Subtitle Picker

### ISSUE THREAD

**Issue by dan64** [RandomEngy/VidCoder#837]
Currently in the Subtitle Picker there is the possibility to specify if a subtitle is default, but it is missing the possibility to assign the Forced flag.  In effect there is the option to show only the Forced subtitle but this has a different meaning and usage.

It would be useful to add the Forced Flag on Subtitle Picker.

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://handbrake.fr/community.php) to add it.

**Comment by dan64** [comment]
In the log file, for the subtitles I can see the following data

 "Subtitle": {
    "Search": {
      "Burn": false,
      "Default": false,
      "Enable": false,
      "Forced": false
    },
    "SubtitleList": [
      {
        "Burn": false,
        "Default": false,
        "Forced": false,
        "ID": 1,
        "Offset": 0,
        "Track": 0,
        "Name": "Full"
      }

In this movie there is only a subtitle track called "Full", I'm wondering if it is possible change the "Forced" attribute from "false" to "true" before send the information to the HB encoder.

**Comment by RandomEngy** [comment]
The "Forced" property here actually means "Pick only Forced subtitles from the input track". It does not put any flags on the output track. The "Default" option will cause the subtitle to be displayed by default..
