### ISSUE TITLE
Drag&Drop launch?

### ISSUE THREAD

**Issue by r1cola** [RandomEngy/VidCoder#84]
so, i realize this may not be an "issue" per-Se, but there is some facility(not sure what it's called) for applications to be able to load in an associated file upon drag/drop.  However, when you try this on vidcoder it just starts the app like normal...

did something in the install go wrong?

**Comment by RandomEngy** [comment]
I haven't heard of this before. Can you give me an example of a program that does this? Are you dragging onto the taskbar icon or a desktop shortcut?

**Comment by r1cola** [comment]
example would be mspaint.exe

you drag a jpg onto its shortcut and it loads said jpg

**Comment by RandomEngy** [comment]
Ahh, it does that with the desktop shortcut but not for the taskbar icon. Will put this on the backlog.

**Comment by r1cola** [comment]
exactly, but its already running at that point :)

**Comment by RandomEngy** [comment]
Starting in Windows 7 you can have a non-running program in the task bar.

**Comment by r1cola** [comment]
interesting, however when I pin vidcoder to taskbar and drag media file to that icon, it just wants to pin that file TO vidcoder...

**Comment by RandomEngy** [comment]
Added in 2.29 Beta. It wasn't too hard; I updated VidCoder to treat the launch parameter like it does when you drag a file onto the window.

**Comment by r1cola** [comment]
thanks buddy :D
