### ISSUE TITLE
SRT subtitle in version 6.34 doesn't get inserted automatically like advertise

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#840]
SRT subtitle in version 6.34 doesn't get inserted automatically like advertise

  Note:

Video filename: Mozart.in.the.Jungle.S01E01.FRENCH.WEBRip.x264-CHiLL.mp4
SRT filename: Mozart.in.the.Jungle.S01E01.FRENCH.WEBRip.x264-CHiLL.srt

**Comment by RandomEngy** [comment]
Did you enable that functionality in the Picker window?

**Comment by quebecman** [comment]
LOL, my bad.  Didn't knew this was in the picker.   Unfortunately, there is missing the NAME of the SUBTITLE.  Would be nice to get the one that is already entered down in the subtitle.
![2021-05-28 15_15_44-Picker_ Series SD avec ST](https://user-images.githubusercontent.com/4656308/120032052-a4d8c980-bfc7-11eb-9263-b6c1a131ff21.png)

It works as advertize.

**Comment by quebecman** [comment]
Transfered over General discussion
