### ISSUE TITLE
CPU Throttling in version 6.34

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#847]
Hmmmm... CPU throtling doesn't seems to be working well in version 6.34.  In fact, version 6.33 and below was working really good.

  In version 6.33, when selecting 92%, the CPU was throtling like it was suppose too, meaning at 92%

In version 6.34, when selecting 75% of the CPU, the CPU throttle at 92%.  Else, 100% will be used.

Weird.
Thanx Regards.

**Comment by RandomEngy** [comment]
Can't reproduce this. How many cores do you have? Are you sure it was VidCoder that was using 92% after selecting throttling to 75%?

**Comment by quebecman** [comment]
I have a 12 cores / 32 threads CPU. AMD Ryzen 3900x.

**Comment by quebecman** [comment]
Unable to reproduce. No other ressource was using the CPU.  Will keep close look to this.
