### ISSUE TITLE
I need help enabling the advanced tab in VidCoder

### ISSUE THREAD

**Issue by Hiacios** [RandomEngy/VidCoder#85]
I just download the latest stable version of VidCoder and I don't know how to enable the advanced tab! Can someone help me with this?

**Comment by RandomEngy** [comment]
Are you using x264 as your encoder? If so you should be able to enable it by clicking "Advanced tab" under the Video tab.

**Comment by Hiacios** [comment]
No, I'm using x265 and I don't see the advanced tab anywhere. Here's a picture.
http://imgur.com/Ghcrz3I

**Comment by RandomEngy** [comment]
There is no advanced tab implemented for x265. You can enter encoder options manually in the "extra options" field.

**Comment by Hiacios** [comment]
Ok, thanks for answering my questions.
