### ISSUE TITLE
VidCoder and 60fps!

### ISSUE THREAD

**Issue by FMA1986** [RandomEngy/VidCoder#858]
When I convert a video,60fps not appear and converted but 25-30fps remaining. What issue have this VidCoder? Thanks!

**Comment by RandomEngy** [comment]
I don't understand the question. What are you trying to do? What framerate settings are you using?

**Comment by FMA1986** [comment]
It doesn't matter, I solved it. It has to be constant 60fps. Even if it's fake! Thanks anyway for the help.
