### ISSUE TITLE
VidCoderCLI Picker Argument is Ignored

### ISSUE THREAD

**Issue by Baimbekka** [RandomEngy/VidCoder#863]
**Describe the bug**
The picker argument for the CLI is only used for picking the title of the video.  AutoPickSubtitles does not take in the picker specified.  It gets the current one active in the UI.

**To Reproduce**
1. Have two pickers.  One for subtitle track 1 and one for track 2.
2. Have picker 1 active in the UI
3. Find a video with 2 tracks
4. Use the CLI to encode it with picker 2
5. See track 1 gets used anyway

**Expected behavior**
Create an override to AutoPickSubtitles that lets the ProcessingService.Process method pass in the picker.

This also should be fixed for AutoPickRange and AutoPickAudio.

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Should be fixed in 6.36 Beta.
