### ISSUE TITLE
Japanese Language problem ?

### ISSUE THREAD

**Issue by toru-takehisa** [RandomEngy/VidCoder#867]
Hello.

I installed VidCoder today. I was learning the basic functions, but I ran into a problem.

I am Japanese and my PC is also in Japanese environment. For that reason, Japanese is also selected for VidCoder. At this time, the "Add to Queue ▼" menu of VidCorder is showed as "キューへ追加". That is, ▼ is disapered. I'm not sure because of that, I can't see the drop-down menu for entering multiple jobs in the queue.

I would like to ask you some questions. Is it possible to change the language to English? Please tell me how to do it if possible. 2. Or  let me know if there is a way to enter multiple jobs in Japanese.

Thank you.

**Comment by RandomEngy** [comment]
What version are you using? It works for me in Japanese:

![image](https://user-images.githubusercontent.com/9450861/127719193-28826669-1954-4a06-925a-f36f9bf18c19.png)

You can change to English by clicking the Global options button
![image](https://user-images.githubusercontent.com/9450861/127719214-3e7a95cc-5d18-4c9b-aec2-f45902e45414.png)

Then select English for the language:
![image](https://user-images.githubusercontent.com/9450861/127719232-8b813f39-250b-4444-91f6-8ca017021c51.png)

**Comment by toru-takehisa** [comment]
In conclusion, it was a mistake to write that there seems to be a problem with the function. There was an error in my usage procedure.
However, the screenshots shown are slightly different. This was the same for both versions 5.21 / 6.35. It wasn't a big problem.
I also think I overlooked the choice of language. 　I apologize for the inconvenience.

Thank you for your prompt reply.

![キャプチャ1](https://user-images.githubusercontent.com/88195313/127724796-e43d5da8-6da0-4eae-aa63-3b236320c6f9.JPG)

**Comment by RandomEngy** [comment]
If the source you've loaded doesn't have multiple titles, then it doesn't offer the drop down menu. There's no point in trying to add multiple titles then.
