### ISSUE TITLE
Windows alt-tab app switcher disrupted when VidCoder encoding

### ISSUE THREAD

**Issue by RobMielcarski** [RandomEngy/VidCoder#870]
When VidCoder is encoding it causes the Windows alt-tab app switcher window to flash and flicker making it difficult to switch between Windows applications.

I'm running Windows 11 but the problem was also present on Windows 10.

**Comment by RandomEngy** [comment]
I think something may be wrong with your Windows install. VidCoder shouldn't be able to mess up the ability for Windows to do alt-tab switching.

**Comment by RobMielcarski** [comment]
Sorry, I was unclear. Alt-tab still works.  But the window flickers because (I think) VidCoder is updating it's status too frequently or in the wrong way.

Please try it. I think you'll immediately see it.

**Comment by RandomEngy** [comment]
I have tried it and I don't actually see any flicker. We do update the user interface and the window title when running, but that should not cause the switcher window to flash.

**Comment by RobMielcarski** [comment]
This is still an irritant for me. I had another look today with fresh eyes.

The VidCoder title bar displays "VidCoder Beta xx%" when encoding. Each time the xx% increments (about once a second) the Windows alt-tab switcher windows flickers. 

Would you consider removing the xx% and simply displaying a static "VidCoder Beta" all the time?

**Comment by RobMielcarski** [comment]
If you do not want to make this change, I found a work-around. 

Press alt, then tap other alt, then press tab. 

This opens the task switcher using the old style icons that do not flicker when VidCoder is encoding.

**Comment by RandomEngy** [comment]
I tried it again and I see what you mean. I think this is a bug in Windows itself. An app title bar update should not cause the alt-tab switcher to flicker like this.

I added an option in the Advanced section of Global Options to turn this off to work around it. It's in v10.0 Beta.

**Comment by RobMielcarski** [comment]
Wonderful. Thank you so much!

**Comment by RobMielcarski** [comment]
Works perfect. I use VidCoder pretty much every day so this change is really appreciated.

I also use the Compare feature you added for me every day. Maybe someday you could add x265 support? 

x265 is quite common these days.

**Comment by RandomEngy** [comment]
Not sure what you mean about x265. Does it not show up for you on the encoders list?

<img width="179" alt="image" src="https://github.com/RandomEngy/VidCoder/assets/9450861/520b8f98-37f9-4665-b35e-03b614c45c98">

**Comment by RobMielcarski** [comment]
X265 encoding is fine.

I was referring to the fact that the Compare against original feature you added for me in 6.16 does not work if the video is x265.

**Comment by RandomEngy** [comment]
Ahh right. You may need to wait on a Windows update for that one. I'm just playing the video with the media player that's built in to WPF.

**Comment by RobMielcarski** [comment]
Thanks. It's a great and I think still unique feature.
