### ISSUE TITLE
In the current Beta, problem with Subtitles and output file size

### ISSUE THREAD

**Issue by bcook75** [RandomEngy/VidCoder#875]
I have begun transcoding some .mp4 files that were encoded with the H264 protocol into H265. I have use both the latest full release (5.21) and the latest Beta (6.35). The source .mp4 file has 2, sometimes 3 subtitles (English only). Even when all are selected before beginning the operation, the subtitles are NOT included in the result file. I have checked that all the settings I know to check are the same in both the release and beta versions. The subtitles are all properly included in the result file using the release version.

I have also started to notice a significant difference in file sizes between the release and beta versions when transcoding the same input file, with the release version being as much as 50% smaller.

For both, the Video Codex is H265 (x265), framerate is "Same as source" and Variable. Both are set to Constant quality of 22. Encoder is set to "Very fast" in both. Video Filter in both has Deinterlace set to Decomb, Default and Default. All others are off. (I did just discover one difference. On the Sizing tab, both had Sizing Mode set to Automatic, but the release version had Max Width and Max Height set and Use Anamorphic checked. I've just set the same on the Beta, so we'll see.

**Comment by RandomEngy** [comment]
Ahh, didn't realize that HandBrake had released a new Stable version. Yeah, you'll need to test with VidCoder Beta until I get a new stable release out.
