### ISSUE TITLE
problem cutting when Imax and tonemapping

### ISSUE THREAD

**Issue by Marciuz90** [RandomEngy/VidCoder#878]
**Is your feature request related to a problem? Please describe.**
Hello, Handbrake with versions 1.4.0 and with 1.4.1 has solved the problem of cutting especially when it comes to Imax, in addition it has imposed a tonemapping support for BT2020 to BT709.

**Describe the solution you'd like**

**Comment by RandomEngy** [comment]
VidCoder 6.40 Beta supports the Colorspace filter.
