### ISSUE TITLE
Vidcoder 2.29.0.0 Beta x64 sluggish slow/lagging when changing profile settings

### ISSUE THREAD

**Issue by kairukun93** [RandomEngy/VidCoder#89]
I have been using vidcoder for 5 years, it has been one of the best user friendly video encoder, the main issue ins't really that bad, it's just that when you go profile Settings, it dog slow/sluggish like it takes 4 to 5 seconds to respond, like changing constant quality, it takes 3 to 5 to change it, because it's lagging, I already tried changing the programs CPU priorities, and nothing changes, still lagging, i mean don't get me wrong, the encoding part is working fine, sometimes it fails, and have to redo, I don't why it's doing that, but anyway i don't think logs will help this time! thank you!

**Comment by kairukun93** [comment]
Ok, its been 10 days, still no word from you guys?! still got the problem, It's really slow when opening Settings on the profile, can't really change anything, it's running so slow!

**Comment by RandomEngy** [comment]
It's just me that works on it in my spare time. It's on my list of stuff to look at.

**Comment by kairukun93** [comment]
Ok, thanks for letting me know!

**Comment by RandomEngy** [comment]
Fixed in 2.30 Beta. The issue was that we were serializing the presets to JSON before handing them to the background task to save, but the serialization was the expensive part. Changed to clone the objects then serialize on the background.
