### ISSUE TITLE
Start Encoding After Scan

### ISSUE THREAD

**Issue by kenanunkesti** [RandomEngy/VidCoder#902]
I've tried today and doesn't work even though I choose this option.

![image](https://user-images.githubusercontent.com/65110421/138065842-c587234a-76f0-4290-875b-7d49f4525f25.png)

**Comment by RandomEngy** [comment]
Ahh I see, I originally wrote that to apply when scanning a single video. I can update it to also apply after a batch scan.

**Comment by RandomEngy** [comment]
Updated in 6.43 to apply after a batch scan.

**Comment by kenanunkesti** [comment]
Thanks David 👍
