### ISSUE TITLE
Upgraded to 6.41, now has problems

### ISSUE THREAD

**Issue by SpeedLee69** [RandomEngy/VidCoder#904]
Prior to recently upgrading Vidcoder to 6.41, it would encode dvd's fairly fast, typically 20-40 minutes. Now it indicates 6 days!!!!  I've tried various discs, re booting the pc, plus trying various encoding settings all to no avail.  What is the solution?
![image](https://user-images.githubusercontent.com/92914159/138235562-ad293958-5890-42fe-83a3-f3fd39194a0e.png)

**Comment by kenanunkesti** [comment]
Unfortunately, I have the same slowness.
The settings are the same, the files are the same, the startup time is the same.

![image](https://user-images.githubusercontent.com/65110421/138363118-60b4de0b-8ad5-4e16-b6e3-d0fa4486d3cc.png)

**Comment by RandomEngy** [comment]
Does it happen with all files? Also, you can try with HandBrake and if there's still a difference, provide encode logs.

**Comment by kenanunkesti** [comment]
I'm using Vidcoder because I don't like Handbrake :)

**Comment by kenanunkesti** [comment]
Yes a little detail is slowing me up.
Accelerated.
Thanks.
