### ISSUE TITLE
Delete files (without confirmation, instantly)

### ISSUE THREAD

**Issue by kenanunkesti** [RandomEngy/VidCoder#905]
I don't always have time to manually delete successfully completed source files.
When I run out of disk space, the conversions are interrupted :(
It would be great if the program could do this on its own.
Thanks.

![image](https://user-images.githubusercontent.com/65110421/138405483-d411093c-5734-4de6-9463-8633234a36f1.png)

**Comment by RandomEngy** [comment]
This is implemented in v7.0 Beta. You can find the options in the Picker window under the Post-encoding section.
