### ISSUE TITLE
Post-encoding Send File To - Exception Handling

### ISSUE THREAD

**Issue by LeeThompson** [RandomEngy/VidCoder#907]
VidCoder 6.4.1

If you specify a process incorrectly in the "Send File To", it will cause VidCoder to crash.  
I haven't narrowed this down extensively but I was trying to use growl notify and I specified a bunch of stuff in the "send file to" area.   This caused VidCoder to crash with a error 2 exception when the job completed.   

It should catch and handle the exception gracefully.

(Worst case, maybe wrap around a try except)

**Comment by RandomEngy** [comment]
Fixed in 6.42.
