### ISSUE TITLE
Add multiple titles to queue -> preview images not working

### ISSUE THREAD

**Issue by 666Shadowlord666** [RandomEngy/VidCoder#911]
**Describe the bug**
I have a problem with VidCoder when I want to add multiple files to the queue. 
When I click on "Add multiple titles to queue", the preview images for each video are identical (but with different cropping), which is not correct.

The problem occurs in the latest stable 6.41 as well as in the latest beta 6.40, but not in the old VidCoder 5.21.

**To Reproduce**
1. Add videos (e.g DVD) to VidCoder.
2. Click "Add to queue" -> "Add multiple titles to queue"
3. Select video.

**Expected behavior**
Each selected video should show its own preview image.

**Screenshots*
![2021-10-31_19-06-28-176](https://user-images.githubusercontent.com/21986069/139596290-33063bbe-75f3-49c2-aaa4-9b8275de8011.gif)
*

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by RandomEngy** [comment]
Fixed in 6.42.
