### ISSUE TITLE
PROBLEME NACH NEUSTEM UPDATE

### ISSUE THREAD

**Issue by PelleGrafi** [RandomEngy/VidCoder#912]

**Comment by PelleGrafi** [comment]
Guten Abend
Bis heute konnte ich das Programm VidCoder problemlos nutzen. Meine privaten DVDs wurden problemlos auf den PC kopiert.
Heute Morgen habe ich das neuste Update durchgeführt und wollte anschliessend eine weitere DVD nach gewohntem Prozedere auf meinen PC überspielen. Ich konnte die DVD problemlos überspielen und das gewünschte Ziel angeben.
Nach dem Befehl ENCODIEREN geht nichts mehr; bei ETA gibt es eine Überspieldauer von 3d und 20h an. Das kann doch nicht sein.
In der Zwischenzeit habe ich das Programm deinstalliert und danach neu heruntergeladen. Doch das Problem ist das gleich geblieben. Bitte helfen Sie mir.
Freundliche Grüsse
Pellegrafi

**Comment by RandomEngy** [comment]
Might be the same as https://github.com/RandomEngy/VidCoder/issues/901 . Can you post an encode log? And try with HandBrake to see if it's an engine issue?
