### ISSUE TITLE
Selectable Resize filters for VidCoder

### ISSUE THREAD

**Issue by mwittmann1980** [RandomEngy/VidCoder#913]
Hello, I'm missing the option to choose my desired filter for resizing. For downsizing I'm only using Spline36 which is the sharpest resizer available that creates no ringing artifacts like Lanczos3. Unfortunately there's no possibility to change the resize filter in VidCoder.  I even don't know which resize filter VidCoder is using by default - there's no info about it.

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://handbrake.fr/community.php) to add it.
