### ISSUE TITLE
Maximized window is larger than display on secondary display when main display is scaled

### ISSUE THREAD

**Issue by ottosson** [RandomEngy/VidCoder#923]
**Describe the bug**
I have two monitors, my main (laptop) monitor set to resolution 3840x2160 with 250% scaling and an external monitor at 2560x1440 with 100% scaling. When I maximize the application window on my external monitor the right side of the window disappears (minimize/restore/close buttons are not accessible). If I set the scaling of my main monitor (the laptop monitor) to 150%, or lower, it will be maximized correctly but with 175% and higher the right side of the window disappear outside of the display... The weird thing is that the application is placed on the monitor NOT being scaled.

(The disgusting green background is to visualize how large the monitors are)
![image](https://user-images.githubusercontent.com/3355320/141512791-10881baf-83bb-4c89-9ce3-d09646c0f1d3.png)

**To Reproduce**
Not sure if it's necessary to have my exact setup to reproduce the bug.
Open application
Maximize window

**Expected behavior**
All of the window should be visible when maximized independent of monitor scaling

**Comment by ottosson** [comment]
I found a solution to this problem. Add an application manifest and set the DPI awareness mode. I don't know if it has any other implications on the application, but at a quick glance it seems to solve the issue.

https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process#setting-default-awareness-with-the-application-manifest

**Comment by RandomEngy** [comment]
VidCoder uses this code to find the position to put a maximized window:

```cs
case WM_GETMINMAXINFO:
	// We need to tell the system what our size should be when maximized. Otherwise it will cover the whole screen,
	// including the task bar.
	MINMAXINFO mmi = (MINMAXINFO)Marshal.PtrToStructure(lParam, typeof(MINMAXINFO));

	// Adjust the maximized size and position to fit the work area of the correct monitor
	IntPtr monitor = MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST);

	if (monitor != IntPtr.Zero)
	{
		MONITORINFO monitorInfo = new MONITORINFO();
		monitorInfo.cbSize = Marshal.SizeOf(typeof(MONITORINFO));
		GetMonitorInfo(monitor, ref monitorInfo);
		RECT rcWorkArea = monitorInfo.rcWork;
		RECT rcMonitorArea = monitorInfo.rcMonitor;
		mmi.ptMaxPosition.X = Math.Abs(rcWorkArea.Left - rcMonitorArea.Left);
		mmi.ptMaxPosition.Y = Math.Abs(rcWorkArea.Top - rcMonitorArea.Top);
		mmi.ptMaxSize.X = Math.Abs(rcWorkArea.Right - rcWorkArea.Left);
		mmi.ptMaxSize.Y = Math.Abs(rcWorkArea.Bottom - rcWorkArea.Top);
	}

	Marshal.StructureToPtr(mmi, lParam, true);

	break;
```

The problem is that when you make custom window chrome, like VidCoder did to implement dark mode, it will by default maximize you in a really weird way, by cutting off 7px on every side. So you need to hook to this WM_GETMINMAXINFO to adjust what the window size should be after it maximizes. Now to find that desired size I'm looking up the monitor that's closest to the window.

I'm guessing in your case, the monitor it decided to maximize to was different from the one returned by `MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST)` . I've been digging around but I can't find a solution to this. There are some obviously wrong approaches like finding the monitor from the mouse cursor (doesn't work with keyboard shortcuts) and everything else I've found also uses the same method to get the monitor from the window:

https://stackoverflow.com/questions/15003484/wpf-custom-window-and-maximized-size

Where is the window before you try to maximize it?

**Comment by ottosson** [comment]
I maximized the VidCoder window when it was on my secondary, non-scaled, monitor.

I've tried to build an application from scratch using the same approach, which is showing the same issue. When I added the manifest file it solved the issue both for my application and for VidCoder. I haven't done any extensive research or testing, so I don't know if it has any other implications using that approach. But adding a manifest file with `<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>` seems to work.

**Comment by RandomEngy** [comment]
I added that to the manifest in this pre-release build:

https://engy.us/misc/VidCoder-7.1-Beta-Portable.exe

Can you check and see if it's behaving properly for you?

**Comment by ottosson** [comment]
7.1-beta works as expected 👍. I verified by downloading the latest portable (6.43) from vidcoder.net which had the issue.

Btw. I'm not a user of VidCoder, but found this repo by reading your blog post [Implementing a Custom Window Title Bar in WPF](https://engy.us/blog/2020/01/01/implementing-a-custom-window-title-bar-in-wpf/) which I appreciated a lot. Thanks! Maybe dpiAwareness should be mentioned there for others to find as well? 😊

**Comment by RandomEngy** [comment]
Haha you seemed unusually technically adept for one of my VidCoder users. Thanks for letting me know about the oversight; I'll update the blog post.

The documentation on this is pretty confusing, simultaneously insisting that WPF is already DPI-aware, but then suggesting that you can also declare that WPF is DPI-aware without explaining what that really means or why you would want to do it.

**Comment by RandomEngy** [comment]
Okay, I've updated the blog post.

**Comment by ottosson** [comment]
Very nice, thanks a lot! 👍🏻
