### ISSUE TITLE
Picker doesn't pic subtitles

### ISSUE THREAD

**Issue by jglazer63** [RandomEngy/VidCoder#929]
### Problem Description

I get videos with 33 subtitles in them. I only want english.  I choose 

Track Selection: english
only if different language from audio
all tracks for this language

It still chooses no subtitles when I bring the video in.  I have to go in each individually and select the english subtitles

### What version of VidCoder are you running?

6.4.3

**Comment by RandomEngy** [comment]
What language is the audio track?

**Comment by jglazer63** [comment]
Just returning here to say you guys helped me to resolve this by setting up the picker preferences correct.  Thanks!
