### ISSUE TITLE
Can't encode a time range in 2.29.0.0 beta x64

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#93]
I'm using v2.29.0.0 beta x64. If I try to encode a portion of video by typing in start and stop times such as 0:01:00 - 0:01:16 the encode fails with this error "The instruction at 0x6f30647a referenced memory at 0x00000094. The memory could not be read. Click on OK to terminate the program". Pressing OK does not actually terminate the program. If I select a portion of video using the mouse in the time range bar it also fails and the error message is exactly the same. 

[Uploading errorlog.zip…]()

**Comment by RandomEngy** [comment]
Can you compare the behavior of the latest HandBrake nightly to VidCoder Beta 2.30? Want to see if this is a HandBrake engine issue.

**Comment by iamjaydear** [comment]
The Time Range feature in v2.30.0.0 is now not crashing :)  but I noticed another little bizarreness... if I have a Picker profile selected, VC ignores the time range selected and encodes the whole file. If I select Picker: None only the selected time range is encoded.

**Comment by RandomEngy** [comment]
What do you have set in your picker profile? I tried one and it seems to encode time ranges correctly.

**Comment by liracobopu** [comment]
VIdCoder 1.5.34.0 correctly encodes the specified Time Range for me, however VidCoder 2.30 Beta does not encode the specified Time Range correctly, being several seconds off. The Time Range bug is also present in HandBrake-20160616-5bddfcb_x86_64-Win_GUI.exe, which looks like is based on the same version of Handbrake as VidCoder 2.30 (20160611220333-44a359d-master.

So I guess it is a Handbrake bug.

**Comment by iamjaydear** [comment]
Nothing tricky in the picker profile.
![pickertv](https://cloud.githubusercontent.com/assets/16139156/16178966/bdc54308-369a-11e6-8728-21e24a11c47b.jpg)

**Comment by liracobopu** [comment]
@RandomEngy Encoding by time is now fixed in the latest nightlies.
https://github.com/HandBrake/HandBrake/issues/225

I hope there will be an updated beta soon!

**Comment by RandomEngy** [comment]
Unfortunately their latest nightly broke static previews, so I need to wait on that fix before updating.

**Comment by RandomEngy** [comment]
Updated the HandBrake core in VidCoder 2.31 Beta.
