### ISSUE TITLE
bug: Dragging more videos onto vidcoder causes "scanning" window to hang

### ISSUE THREAD

**Issue by smanross** [RandomEngy/VidCoder#931]
I'm not 100% sure what causes this, but it's possible that VidCoder was finishing the encoding on one file when the scanning window appeared to add the new files to the queue.

The interesting part is that my queue of 10+ videos (files that were in the queue previously) finished 2+ hours later but the "scanning" progress bar for the newly adding titles stayed there indefinitely and wouldn't close even if I pressed the "X" at top right, and ultimately had to forcibly close the application from task manager.

This is the first time I've had this happen in using the program for years, and I've added multiple titles in the past while encoding other files, and it never hung like this before.  However, I recently upgraded to the new version (6.42) -- and it could also just be a race condition - when one file finishes encoding and another one starts -- but while it's scanning the files to add to the queue.

This is not a showstopper...  Just an interesting issue (possibly hard to reproduce) - and likely a seldom seen race condition.  I hope this information helps you.  I can certainly just deal with this IF it happens again, as the solution is simple.

I love your program!

**Comment by RandomEngy** [comment]
I've reworked this to instead show some inline UI while the files are being scanned. As of Beta 8.5 it no longer blocks with the dialog. It may have fixed the issue.

**Comment by smanross** [comment]
thanks as always!!!  love the program...
