### ISSUE TITLE
Unable to type/paste in the custom Colorspace textbox and the Tune encoder setting sometimes displays None

### ISSUE THREAD

**Issue by Solo177** [RandomEngy/VidCoder#934]
### Problem Description

(1) The Custom textbox for the Colorspace video filter doesn't seem to accept any input.

(2) Frequently when switching between multiple custom presets, the Tune encoder setting will display None instead of the saved value.  This seems to be purely cosmetic, as starting an encode with it displaying None will still properly load the saved Tune. Even saving the preset (with no other changes) while it displays None will retain the previous value, and changing any other setting will cause the correct Tune value to instantly appear.  It doesn't always happen and seems to be more likely to happen when switching between presets with different Tune values.  It can also happen regardless of which preset tab is visible when switching.

Thanks for the awesome work. I'm especially fond of the 6.x audio/subtitle name UI layout.

### What version of VidCoder are you running?

6.43

**Comment by RandomEngy** [comment]
Thanks for the reports. I'll have issue #1 fixed in the next release.

As for #2, which "Tune" are you talking about? The one on the Video Encoding tab? I haven't been able to reproduce the issue you describe.

**Comment by Solo177** [comment]
Yeah, the Tune for Animation, Film, etc.  I made a tiny video to demonstrate what I meant.  Every preset under 1080A is set to Tune: Animation, but as you can see it will cosmetically display None sometimes, and change back when I modify other options.

[video](https://cdn.discordapp.com/attachments/289250850159984641/916735812203327538/vidcoder.mp4)

**Comment by RandomEngy** [comment]
Hmm. Can you send me your %appdata%\VidCoder\VidCoder.sqlite file? The "Tune" value does have special handling code behind it and maybe something about your presets is reproducing the issue.

**Comment by RandomEngy** [comment]
Actually, nevermind, I've got a repro now. It has to do with switching between presets with different containers (mkv/mp4)

**Comment by RandomEngy** [comment]
Figured it out. Will be fixed in the next release.

**Comment by RandomEngy** [comment]
Fixed in v6.44.
