### ISSUE TITLE
6.44 not auto-updating

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#935]
### Problem Description

I have VC set to auto-update on closing and I usually just start it and then exit when I get an update message. Check for update within VC just says 6.43 is up to date and auto-update is not working :(  

I was able to d/l it. I haven't installed it yet in case there's a problem in the system.

### What version of VidCoder are you running?

6.43

**Comment by RandomEngy** [comment]
My hosting provider moved the FTP server location. Just updated it. Thanks for the heads-up.

**Comment by iamjaydear** [comment]
My pleasure 👍
