### ISSUE TITLE
Better cropping

### ISSUE THREAD

**Issue by FCrane** [RandomEngy/VidCoder#936]
### Feature details

Hi!

When I use "Automatic" for Cropping, the program crops from all sides as far as black bars are detected. This generally is fine, but quite often, it e.g. crops 2 (or 4 or 8) pixels from a FullHD video (because the pixels are black). However, I'd like to stay FullHD-compatible, meaning that the automatic cropping should only crop vertically OR horizontally, not both! E.g. if the video is 2:35:1, it should crop 132 from the top and the bottom, but not crop anything from left or right! If the video is 4:3, the program should crop 240 from the left and the right but not crop anything from the top or the bottom. This way, one of the dimensions will always be FullHD-compatible, meaning the videos will always be 1920 wide OR 1080 high! This prevents unneccessary scaling in players on full hd displays. The same goes for UHD, of course. This could be implemented with a setting like: "Only crop dimension with larger black bars", for example.

The sensitivity of black bar detection should also be adjustable, because I notice that the program sometimes seems to crop too much. 

Also, what noticed is, that if the automatic cropping suggests e.g. "2 pixels from the right" and I switch to "Custom", suddenly other fields also contain different numbers than before! E.g. the "2 from the right" turn into "6" and the "0 from the left" turn into "2", or something like that. I don't know what the reason for this is, but it's quite annoying always having to check all values. When switching from "Automatic" to "Custom", all values should stay the same and not change.

Thanks!

**Comment by RandomEngy** [comment]
I could have a setting: Min cropping amount that would disallow cropping if below a certain number of pixels.

The values should stay the same after switching from Automatic to Custom, and that's what seems to be happening for me. Can you give a list of steps to follow to reproduce the bug?

**Comment by FCrane** [comment]
The Min cropping could work for most situations, I guess, so this would definitely help a lot! However, there are situations when it would be better to simply restrict cropping to the axis with larger detected black bars (e.g. sometimes the vertical cropping is just 16 or 22 pixels, so setting the min cropping to e.g. 10 is quite close and could sometimes produce incorrect results...) Of course it would be perfect if both could be implemented: a min crop value and the restriction to one axis ;-)

Regarding the values in the cropping edit boxes: I usually drag a file into the VidCoder main window, so it starts the automatic detection of the cropping values (I've set the "Number of picture previews to scan" to 25, btw). It then sets the found values. I always have the "Encoding Preset" window open and the "Sizing" tab selected, so I immediately see the result. If I want to correct the values, I switch from "Automatic" to "Custom" cropping and at the moment the edit boxes get enabled, VidCoder sometimes (maybe 3 out of 10 times) changes the values. Mostly from 0 to something very small, like 2, 4 or 6. However, rarely it sets really huge values (144, 200, etc.) for a full hd video. I think it only happens for the left and right cropping value, but I'm not sure, because 95% of my videos are cropped from the top and the bottom due to their format. Unfortunately, I can not give you steps to  reliably reproduce this, because it seems to happen randomly. However, If it happens for a video file, it doesn't happen consistently, meaning I if I repeat the procedure above, the values will sometimes not change. Very strange...

Thanks for your time and the great program!

**Comment by FCrane** [comment]
One more thing: auto cropping seems to "overcrop" to an even number. E.g. if the black bar on the top is 21 pixels, auto cropping selects 22 pixels, which results in loss of image information! I'd prefer undercropping, so that there may be a 1 pixel black line but no image information is lost... Maybe this can be implemented with an option (radio buttons for undercropping or overcropping to an even number)?

Thanks!

**Comment by RandomEngy** [comment]
I wouldn't be able to add that option. The auto-crop numbers I get back from the HandBrake API are already rounded to even numbers. You'd need to ask the HandBrake team about that.

**Comment by RandomEngy** [comment]
I added both features (Constrain crop to one axis and minimum crop amount) in 7.3 Beta.
