### ISSUE TITLE
Encoded Date

### ISSUE THREAD

**Issue by nitewulf** [RandomEngy/VidCoder#94]
I've noticed that after encoding a video that the encoded date when viewed with MediaInfo is about 20 years in the future.  I found out because I started uploading the videos to google photos and they all kept showing up as though they were taken "today".  I thought it was odd because I used your awesome feature to preserve the timestamps.  When I looked at the MediaInfo I noticed the date was way off.  Even the month and day.  In this example it says 2/6/2036.  I encoded these this month not back in February.

Please look into setting the encoded date to the actual date encoded.  And ideally what I'd love is an option to preserve the original encoded date.  Otherwise google photos will still think the videos were taken "today" and not put them properly in the timeline.  Or roll that into the option to preserve the Created and Modified date when converting.

I'm using version 1.5.34.0 x64

Thanks,
Scott

![wrong encoded date](https://cloud.githubusercontent.com/assets/8270448/15966025/c57eb0e0-2ee6-11e6-8944-45ebdb28676f.JPG)

**Comment by RandomEngy** [comment]
I'm not sure what the "Encoded date" comes from but I'd guess it works the same in HandBrake. You could confirm that and ask them about it, since I use the HandBrake engine. I can preserve the created/modified date since that's a standard Windows file setting, but I'm guessing this is some embedded metadata.

**Comment by nitewulf** [comment]
It's definentally embedded.  I came across:
http://forum.videohelp.com/threads/373362-Change-Time-Stamp-on-mp4-video

check out post #16.  I messed around with a HEX editor and its true, changing that QWORD value affects the Encoded date.  I did some tests with hand brake.  Looks like that was a bug in the .10.2 version.  Its been fixed since then.  I tested with your beta version and the Encoded dates are set properly to DateTime.Now.  

I intend to use the tool Budman1 made to correct the Encoded dates so google photos puts them properly in my timeline.  I'm not sure if that HEX editing applies to other containers as well like .mkv.  

I'm working on my own little tool to edit timestamps/meta data to get my photos and videos recognized properly when they were actually taken.  I'd be happy to share if I come up with a method of preserving the Encoded date.  Because that would be an awesome handy option to include in VidCoder.

**Comment by RandomEngy** [comment]
Cool. Though isn't it always correct to set the encoded time to "now" since you are actually encoding it at that time?

**Comment by nitewulf** [comment]
just like its correct to allow windows to use "now" for the created/modified timestamp because technically you are creating a new file? 

I'm finally getting around to re-encoding m2ts files to a reasonable size that I recorded of my kids years ago and uploading them to google photos to share with the family.  I kinda want them organized in the right year when they were taken.  Its true, it was encoded "now", but really we want to original files encoding timestamp so videos of my kids first steps from 2014 don't have a 2016 timestamp.

I've been at it all afternoon and have successfully calculated the correct HEX value for a given date, and used that to modify the right spot in the file to change the encoded date on a .mp4 file.  It seems that .mkv stores the date in a different spot.  Working on that next.
