### ISSUE TITLE
Renaming is not consistent

### ISSUE THREAD

**Issue by jglazer63** [RandomEngy/VidCoder#940]
### Problem Description

I have it set to encode the video to the same location.  When it does, it **sometimes** adds "(encoded)" to the video name, which is fine, but other times it dupes the name.  See this link for a screenshot:

https://imgur.com/f4TrgtG

Ideally, I would love an option to actually replace the old video file with the new one or at least move the old file somewhere and keep the new one in place.

### What version of VidCoder are you running?

6.44 Installer

**Comment by RandomEngy** [comment]
Hmm. I could update the behavior when configured to recycle/delete the source file on encode success. In that case we won't need to add (Encoded) at the end since the original is going away.

Would that help you?

**Comment by RandomEngy** [comment]
This change will be in the next Beta release.

**Comment by RandomEngy** [comment]
Added in 7.3 Beta.

**Comment by jglazer63** [comment]
Thanks!
