### ISSUE TITLE
Support for VCEEncC ?

### ISSUE THREAD

**Issue by FCrane** [RandomEngy/VidCoder#955]
### Feature details

Hi!

VCEEncC seems to be a superb GPU encoder!

https://github.com/rigaya/VCEEnc/releases

It produces much better results than AMD VCE so it would be great if VidCoder could use it!

Thanks!

**Comment by RandomEngy** [comment]
VidCoder exposes the functionality of HandBrake. To get that feature, you'd need to ask the [HandBrake team](https://handbrake.fr/community.php) to add it.
