### ISSUE TITLE
Just upgraded videcoder...

### ISSUE THREAD

**Issue by Bigjohn1980** [RandomEngy/VidCoder#957]
### What were you doing when VidCoder crashed?

just upgraded, tried to launch, and bam.
The log file contains a lot of this -  and I mean A LOT (pages)
x264 [error]: ratecontrol_end: stats file could not be written to

What does that mean, and where is it trying to write?

### Crash details

```text
appears i might need an older version - I'm still on win7 and will be until the end of time - the last GOOD windows.  The last GREAT windows was XP... :)
```

**Comment by RandomEngy** [comment]
Yeah there is no support for Windows 7 on the newer versions.
