### ISSUE TITLE
NVEnc confusion

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#958]
### Problem Description

I'm not achieving any noticeable speed increase when using NVEnc settings. The PC I'm using is a new ASUS TUF gaming laptop with a Ryzen 7 5800H cpu, Radeon graphics and nVidia GeForce RT3060 gpu. Using the H.264 (NVEnc) codec in VidCoder to convert from 1080i to 720p and constant framerate / same as source the encode speed is about 120 to 150fps. Using the software H.264 (x264) codec with the worker process enabled the speed is pretty much the same for a similar filesize. I've looked at HandBrake's website, but the information there is pretty flimsy. I've tried NVEnc with and without the worker process, but I think it is for software encoding only. I know I'm missing something basic but I really don't know just what. I think I'm right in assuming I should be seeing NVEnc speed well over 150fps. 

### What version of VidCoder are you running?

6.45 Installer

### Encode Log

```text
I can send a log privately if you'll point me there.
```

**Comment by RandomEngy** [comment]
Sometimes a resize operation or a filter can bottleneck the operation. Try removing all cropping/resize/filters and setting framerate same as source, variable framerate. You can try using this preset as a template (right click, save as source) https://engy.us/misc/Ultrafast.vjpreset

**Comment by iamjaydear** [comment]
Thanks for the preset. I guess it's the 1080 to 720 resizing (plus sometimes deinterlacing) slowing things, but that's what I need to do. From the results I'm getting it seems the quality from NVEnc is not able to be as good as software encoding. QSV is worse imo. I imagined that HB would software encode at least twice as fast on a much newer PC running Win10 x64 compared to the old one running Win8.1 x64. Anyway, I must say your queueing works very well, so I can set up a queue and rely on it finishing with good results. C'est la vie.

**Comment by RandomEngy** [comment]
Yeah, software encoding is always going to give better quality results for the same file size.
