### ISSUE TITLE
vidcoder 1.5.34 closing abnormal

### ISSUE THREAD

**Issue by lucabis** [RandomEngy/VidCoder#96]
VidCoder abnormal termination at any time , no mistakes , no information
thanks

**Comment by RandomEngy** [comment]
Not enough information to fix the issue.

**Comment by lucabis** [comment]
The problem is that I have no information .
No error , no message .
VidCoder , records the anomalies ?
Where to find them ?

**Comment by RandomEngy** [comment]
What were you doing when it crashed? Does it always crash then? What version crashed? Does HandBrake crash in the same spot?

**Comment by lucabis** [comment]
Using two external servers , for encoding . in the two servers have the same problem . It can happen after a few mimuti divere or after hours .
1.5.34 version , cpu intel xeon E3-1230v3 with 32gb ram
But no report appears , VidCoder closes is just

**Comment by RandomEngy** [comment]
So, while encoding? Does it happen with the VidCoder beta? Or with HandBrake?

**Comment by lucabis** [comment]
You while H265 encoding .
I have not tried the beta .
With handbrake , works
