### ISSUE TITLE
Vidcoder Phones Home?

### ISSUE THREAD

**Issue by eurobank** [RandomEngy/VidCoder#969]
### Problem Description

Why Vidcoder tries to phone home all the time, while updates check is disabled?

What exactly is sending and why? 

### What version of VidCoder are you running?

6.45 Windows

![2022-01-30 22_17_29-](https://user-images.githubusercontent.com/4467158/151716248-eb687fef-5474-4775-96fd-e89af4514598.png)

**Comment by RandomEngy** [comment]
My guess is that it's the Options dialog checking to see if there is a Beta version available. If there is a more recent Beta version it displays it in the Updates tab.

It should be retrieving https://engy.us/VidCoder/latest-beta.json , which sends no data and currently has this response payload:

```
{
    "LatestVersion":  "7.6",
    "DownloadUrl":  "https://github.com/RandomEngy/VidCoder/releases/download/v7.6-beta/VidCoder-7.6-Beta.exe",
    "ChangelogUrl":  "https://github.com/RandomEngy/VidCoder/releases/tag/v7.6-beta"
}
```

**Comment by eurobank** [comment]
Not so.

It tries to connect to

144.208.71.88

Thant belongs to Inmotion hosting. 

https://www.abuseipdb.com/check/144.208.71.88

Again,  why is this happening? I realy like to know.
