### ISSUE TITLE
Error occurred while scanning

### ISSUE THREAD

**Issue by dwall115** [RandomEngy/VidCoder#978]
### Problem Description

Since this last windows update my Vidcoder shows the error.  Regardless of DVD I attempt to scan, protected or not.  Running windows 11, version 21H2, build 22000.493.  Rolling back to 6.44 doesn't fix the issue.  Happy to help diagnose the issue  Just let me know what you need.
![Screenshot 2022-02-11 152959](https://user-images.githubusercontent.com/88781231/153679874-786a7dcf-0c59-45cb-b29a-31db2fb08823.png)
d

### What version of VidCoder are you running?

6.45 Installer

**Comment by dwall115** [comment]
I totally removed 6.45 and installed 7.10 with same results.
regards,
d

**Comment by RandomEngy** [comment]
You need to go to Windows -> Log and copy the details so I can see what happened.

**Comment by dwall115** [comment]
I should also add that Handbreak 1.4.2 with libdvdcss-2.dll 1.4.3 works fine.

**Comment by dwall115** [comment]
David

Thank you for the quick response.  

 

There are several hundred log files in the windows\log directory and Im unclear as to which you need.  If there is a wiki or specifics, ill be happy to read and respond.  I do not see an encode.log file (it never reaches that point as it fails on reading the disk).  I do appreciate your time and assistance.  Thank you

d

**Comment by dwall115** [comment]
Duh.  Sorry.  Here are the logs from the app directory

 

d

**Comment by dwall115** [comment]
David

 

I apparently didn’t have the libdvdcss-2.dll file in the correct directory.  It appears to be working now sorry for the trouble.

 

d

 

From: ***@***.*** ***@***.***> 
Sent: Sunday, February 13, 2022 3:21 PM
To: 'RandomEngy/VidCoder' ***@***.***>; 'RandomEngy/VidCoder' ***@***.***>
Cc: 'Author' ***@***.***>; ***@***.***
Subject: RE: [RandomEngy/VidCoder] Error occurred while scanning (Issue #978)

 

Duh.  Sorry.  Here are the logs from the app directory

 

d

**Comment by dwall115** [comment]
my own fault  I had libdvdcss-2.dll in the wrong directory.  all is well now.  Sorry for the false alarm.
d

**Comment by dwall115** [comment]
thank you
