### ISSUE TITLE
The popup window: "Error Scanning Video Files" is not scalable / resizable / scrollable

### ISSUE THREAD

**Issue by YupoWert** [RandomEngy/VidCoder#987]
### Problem Description

Scanning ~ 6000 files (out of a total of 150000+ in our family archive library) led to quite a large number of scanning errors which were reported within the "Error Scanning Video Files" popup window. 

The list exceeded the screen size. Unfortunately, it is not possible to resize or scroll that popup window.

I know why a lot failed, (that's my own separate problem) but I need to see the complete list correctly. 

I have tried to solve this by:
a) dragging the list further up the screen - Windows 10 won't permit it
b) minimise the taskbar to expose any resize controls on the bottom (they don't exist)

Here's a screen cap.
![image](https://user-images.githubusercontent.com/73061808/155499037-d72ee716-d5d6-47e0-8d0e-2d6ae5d44bc0.png)

Many thanks

### What version of VidCoder are you running?

7.12

### Encode Log

```text
no log - it's a visual GUI bug
```

**Comment by RandomEngy** [comment]
Thanks for the report. As a workaround you can press <kbd>Ctrl</kbd>+<kbd>C</kbd> then paste into notepad.

**Comment by YupoWert** [comment]
I never thought of that! Thanks!
Feel free to close this if you feel it's appropriate - otherwise I'll happily beta test any change
Regards

**Comment by RandomEngy** [comment]
Tracking under https://github.com/RandomEngy/VidCoder/issues/900
