### ISSUE TITLE
Additional Picker option within 'When file already exists (batch)' : SKIP

### ISSUE THREAD

**Issue by YupoWert** [RandomEngy/VidCoder#997]
### Feature details

Hi,
Could an additional response to the option 'When file already exists (batch)' of 'SKIP' (aka 'IGNORE' etc)  be added.

Background:
I have many 1000's of video clips from phones taken by family over the last 20 years. I am reprocessing these to x265, saving them to their original folder, giving them a new extension of M4V. This could take months of PC slowly processing them. Naturally, I'll have to restart PC during that time, restart Vidcoder, and re-add the files.  Some new files will undoubtedly get added, some after review would be deleted/renamed etc.
So IDEALLY, I'd just use explorer to re-Search for the MP4 originals (living in 100's of folders, across multiple drives), drag them all back in, and get Vidcoder to work out which ones have already got M4V versions in their destination folders, and skip them before processing.

Many thanks

**Comment by RandomEngy** [comment]
Added this option in v11.3 Beta.
